### ISSUE TITLE
Problem with repeat.for & interpolation & IE11 & Cyrillic alphabet, Chinese, Yiddish, Arabic

### ISSUE THREAD

**Issue by luboid** [aurelia/binding#102]
Hi,
here is sample:

http://plnkr.co/edit/a6b40k?p=preview

when plnkr is open into Win8-IE11 options text in second select is as is ${...}

**Comment by jdanyow** [comment]
Windows 8 or Windows 8.1?

Here's what I'm seeing on windows 8.1:
![screenshot](http://i.imgur.com/f239XhM.png)

**Comment by luboid** [comment]
Here is mine, you need to open second select 

![12](https://cloud.githubusercontent.com/assets/383517/7968371/117e32be-0a39-11e5-8285-6e1be4f59b0d.jpg)

![23](https://cloud.githubusercontent.com/assets/383517/7968428/7a944ce8-0a39-11e5-9ffb-d3602e76e390.jpg)

**Comment by jdanyow** [comment]
ah- ok I neglected to open the select- I'm seeing the same thing.  Will take a look.  Thanks!

**Comment by luboid** [comment]
I have such problem and with next pattern 

```html
  <div class="layout-row">
    <label for="sector">
      你在這裡
      <!--ביסט איר דא -->
      <!--кирлица-->
    </label>

    <select id="sector" name="sector" value.bind="parameter.CSTLSECTOR">
      <option>${$parent.$parent.defaultValueOptionText}</option>
      <option repeat.for="item of $parent.$parent.model.sector" value="${item.ID}">${$parent.$parent.$parent.optionText(item)}</option>
    </select>
  </div>
```

![1](https://cloud.githubusercontent.com/assets/383517/8077666/6c27e2b0-0f60-11e5-949f-c9fbc3bd1f7d.jpg)

if I append numbers to text it works

```html
  <div class="layout-row">
    <label for="sector">
      你在這裡 78
      <!--ביסט איר דא -->
      <!--кирлица-->
    </label>

    <select id="sector" name="sector" value.bind="parameter.CSTLSECTOR">
      <option>${$parent.$parent.defaultValueOptionText}</option>
      <option repeat.for="item of $parent.$parent.model.sector" value="${item.ID}">${$parent.$parent.$parent.optionText(item)}</option>
    </select>
  </div>
```

![1](https://cloud.githubusercontent.com/assets/383517/8077739/fdcfbc88-0f60-11e5-8434-92c145c3239d.jpg)

I tested it with Chinese, Yiddish,  Arabic and problem is the same

Is there any progress with this issue

**Comment by jdanyow** [comment]
For whatever reason, IE is breaking up the interpolation expression into multiple adjacent text nodes:

![debugger](http://i.imgur.com/NvMZ2Tj.png)

Planning on fixing this by using the `wholeText` property and then advancing the "cursor" to the next non-text node.

**Comment by luboid** [comment]
Thanks

**Comment by jdanyow** [comment]
@luboid - while you wait for the next release, you should be able to replace the `view-compiler.js` file in your `jspm_packages/github/aurelia/templating@0.12.1` folder with [this file](https://gist.github.com/jdanyow/477f7132c8257768055e#file-view-compiler-js).

**Comment by luboid** [comment]
Ok, thank you
