### ISSUE TITLE
Repeat.for add one empty option to select

### ISSUE THREAD

**Issue by luboid** [aurelia/binding#104]
Hi,

Here is test sample:
https://github.com/luboid/aurelia-repeat-for-test

IE11,Chrome 43 & Firefox 38 on Win 8

```html
<template>
  <select id="country3" name="country3">
    <option>select one of ...<option>
    <option repeat.for="ctry of model2.countries" value="${ctry.ID}">${ctry.IDTEXT}</option>
  </select>
</template>
```

```javascript
define(["require", "exports"], function (require, exports) {
    exports.App = function () {
        this.model2 = {
            countries: [
                { ID: '001', IDTEXT: 'Text 1' },
                { ID: '002', IDTEXT: 'Text 2' }
            ]
        };
    };
});
```

![1](https://cloud.githubusercontent.com/assets/383517/7991814/9b09435a-0b03-11e5-849b-360651ae414a.jpg)

**Comment by jdanyow** [comment]
The first option isn't closed:
`<option>select one of ...<option>`
should be:
`<option>select one of ...</option>`

**Comment by luboid** [comment]
sorry about this, thanks

**Comment by jdanyow** [comment]
No need to be sorry, sometimes all you need is a second pair of eyes.

There's work going on to improve the bundling, etc.  I wouldn't be surprised if Aurelia+SystemJS is actually smaller than durandal+knockout+requirejs.  

There are several things in the works to help learn Aurelia:  Pluralsight courses in the works, a full-fledged documentation app which will have live samples and full API docs, there's the Aurelia CLI which will make common tasks easier.  Don't be afraid to hit up the [gitter chat](https://gitter.im/Aurelia/Discuss) with any questions.  There are a ton of community members hanging around that will be able to give you a hand.  Also check out the [blog](blog.durandal.io) for articles on different aspects of the framework.

**Comment by NeelapareddyReshma** [comment]
For this in case if i want to select one dropdown for that i have to provide url link that one it want to redirect to next page how will it work? Can you please clarify this one

**Comment by NeelapareddyReshma** [comment]
For example in dropdown Text1 is there for that i need to provide href link then it want to navigate to next page. This is the my question.

**Comment by bigopon** [comment]
@NeelapareddyReshma Is this https://codesandbox.io/s/ypq2lqk5l9 what you want?

**Comment by NeelapareddyReshma** [comment]
This is a simple drop down right

**Comment by bigopon** [comment]
yes, it is

**Comment by NeelapareddyReshma** [comment]
In dropdown we have two options if we click on first option then it should move to other url. 2nd link should not be functional. I mean to say 2nd link should be deadend.

**Comment by bigopon** [comment]
@NeelapareddyReshma Please help move this to Discourse forum https://discourse.aurelia.io, it's much better for help request purposes.

**Comment by NeelapareddyReshma** [comment]
i want to get the code of this functionality in aurelia https://codesandbox.io/s/ypq2lqk5l9

**Comment by NeelapareddyReshma** [comment]
i saw what you were written in file first i will try with this code.

**Comment by NeelapareddyReshma** [comment]
it's working fine for me.Thanks for your help.

**Comment by bigopon** [comment]
@NeelapareddyReshma You're welcome. Discourse forum is the best place for you to get help, and help other as well. Please leverage it next time ❤️ https://discourse.aurelia.io

**Comment by NeelapareddyReshma** [comment]
sure

**Comment by NeelapareddyReshma** [comment]
Hi bigopon,

we have added the drop down code like the below, but we are not getting how to map the URL
here <voya-field> and <voya-option> are the custom tags.
in html
-------
<div class="max-width-container">
            <voya-field
                type="select"
                label="Select an account"
                hide-label
                class="select-type"

               style="width:100px;">
                <voya-option repeat.for="option of options.countries" model.bind="option" value.bind="selectedOption">
                ${option.IDTEXT}</voya-option>
        </voya-field>
      </div>
code in JS
----------
@observable()
  selectedOption;

    options = {
    countries: [
      { ID: '001', IDTEXT: 'Country 1' },
      { ID: '002', IDTEXT: 'Country 2' }
    ]
  };
selectedOptionChanged(option) {
    if (option && option.ID === '001') {
      location = '#/retirement/details/5120B4FE280E6F3C677E9F039F2B8EDEE299115519A4CCDAFEE3BFA9C483996F/showsub';
    }
  }

**Comment by NeelapareddyReshma** [comment]
HTML Code to access the values from JS:
=========================
`<div class="max-width-container">
            <voya-field  type="select"  label="Select an account" hide-label  class="select-type"    style="width:100px;">
                <voya-option repeat.for="option of options.countries" model.bind="option" value.bind="selectedOption">
                ${option.IDTEXT}</voya-option>
        </voya-field>
      </div>
`

**Comment by NeelapareddyReshma** [comment]
how to map above url to first dropdown
