### ISSUE TITLE
paper-button from Polymer 1.0 does not work.

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [aurelia/binding#105]
Hi,

I'm trying Polymer 1.0 with Aurelia. Here are fragments from my welcome.html and my welcome.ts.

`<input>` works fine and shows full name. But pressing the Submit button does not call `welcome()` in welcome.ts. 

If I use `<button>` rather than `<paper-button>`, `welcome()` is called.

Do I need something else? 

```
<template>
  <link rel="import" href="bower_components/iron-form/iron-form.html">
  <link rel="import" href="bower_components/paper-button/paper-button.html">
  <link rel="import" href="bower_components/paper-input/paper-input-container.html">
  
  <section>
    <h2>${heading}</h2>

    <form is="iron-form" role="form" id="form" submit.delegate="welcome()">
	  <paper-input-container>
		<label for="fn">Fist name</label>
	        <input is="iron-input" value.bind="firstName" class="form-control" id="fn" placeholder="first name">
	  </paper-input-container>
	  <paper-input-container>
		<label for="fn">Last name</label>
	        <input is="iron-input" value.bind="lastName" class="form-control" id="ln" placeholder="last name">
	  </paper-input-container>
      <label>Full Name</label>
      <p>${fullName | upper}</p>
      <paper-button onclick="submitForm()">Submit </paper-button>
    </form>
  </section>
  <script>
  function submitForm() {
	  document.getElementById('form').submit();
	  console.log('submitForm()')
	}
  </script>
</template>
```

**Comment by HIRANO-Satoshi** [comment]
Note that the doc of `iron-form` which I use in the above code says that I need the following code, so I added. 

https://elements.polymer-project.org/elements/iron-form

```
function submitForm() {
      document.getElementById('form').submit();
      console.log('submitForm()')
    }
```

`console.log('submitForm()')` is called when I press the Submit button.

**Comment by EisenbergEffect** [comment]
Your scripts won't be connected inside of template. You aren't going to want to do it that way. Instead, connect the button to a method on your view model. For that you can use `click.trigger="welcome()".

**Comment by HIRANO-Satoshi** [comment]
I see. It worked. Thanks. 

Here is the new version.

<template>
  <link rel="import" href="bower_components/iron-form/iron-form.html">
  <link rel="import" href="bower_components/paper-button/paper-button.html">
  <link rel="import" href="bower_components/paper-input/paper-input-container.html">
  
  <section>
    <h2>${heading}</h2>

    <form is="iron-form" role="form">
	  <paper-input-container>
		<label for="fn">Fist name</label>
	        <input is="iron-input" value.bind="firstName" class="form-control" id="fn" placeholder="first name">
	  </paper-input-container>
	  <paper-input-container>
		<label for="fn">Last name</label>
	        <input is="iron-input" value.bind="lastName" class="form-control" id="ln" placeholder="last name">
	  </paper-input-container>
      <label>Full Name</label>
      <p>${fullName | upper}</p>
      <paper-button click.trigger="welcome()">Submit </paper-button>
    </form>
  </section>
</template>

**Comment by nevercast** [comment]
A late comment on this, sorry about the grave digging.

You've elected to use click.trigger over click.delegate. Is there a design reason behind this that I should be aware of in future when using Polymer and perhaps other frameworks with Aurelia? Was it entirely a personal preference it will it function differently?

I ask because .delegate seems to be preferred in the aurelia documentation.

**Comment by HIRANO-Satoshi** [comment]
Josh

I have switched to MaterializeCSS. I forgot everthing about Polymer.

In the last June I tried Polymer and I found Polymer’s Bower was not compatible with Aurelia's jspm. I gave up.

Now I’m almost satisfied with Aurelia and MaterializeCSS.

Have a nice day!

HIRANO Satoshi

**Comment by nevercast** [comment]
@HIRANO-Satoshi 

I managed to get Polymer working with Aurelia by using a SystemJS -> Bower plugin, and having both Bower and JSPM modules installed. I will look at MaterializeCSS, it may better suit my needs.

Thank you.
Josh

**Comment by HIRANO-Satoshi** [comment]
Josh,

> I managed to get Polymer working with Aurelia by using a SystemJS -> Bower plugin, and having both Bower and JSPM modules installed. I will look at MaterializeCSS, it may better suit my needs.

Great news. Have your improvement merged to the master branch of the Aurelia?

Why do you think MaterializeCSS may be better for your needs?

If you use MaterializeCSS with Aurelia, look at the following sample. 

https://github.com/jdanyow/aurelia-breeze-northwind


You will find Materialize requires some magic words to be used with Aurelia. For example, 

https://github.com/jdanyow/aurelia-breeze-northwind/blob/master/src/orders/order.html

has the following code that fixes an issue with materialize.

 <label for="OrderDate" materialize>Order Date</label>
