### ISSUE TITLE
aurelia td are outside of table when using custom elements / composing elements

### ISSUE THREAD

**Issue by CarlosOnline** [aurelia/binding#108]
td shows up outside of table when using custom elements.
Can this be fixed.  Without this, custom elements can't be used to generate table cells and rows.

No responses on discuss sight.

    <template>
      <table class="this-table-put-tds-outside-table" style="width: 800px">
        <thead> <tr> <td>col1</td> <td>col2</td> </tr> </thead>
        <tbody>
        <tr repeat.for="row of rows">
          <compose view-model="./RowTest" model.bind="row"></compose>
        </tr>
        </tbody>
      </table>
    </template>

**Comment by chovy** [comment]
That is to be expected. `<compose>` isn't a valid child of `<tr>` -- I had this same problem with angular and it took me awhile to realize it was because I was using tables.

**Comment by CarlosOnline** [comment]
Can this be fixed?
The problem is created b/c of the aurelia html markup: template, and custom elements.  If aurelia could remove this markup then it would perfect.

    <div id="aureliaTable" style="border:5px solid blue; padding: 2px; margin: 2px;">
      <table>
        <row></row>
        <tr>
          <td>Hi</td>
          <td>There</td>
        </tr>
      </table>
    </div>

generates this

    <div id="aureliaTable" style="border:5px solid blue; padding: 2px; margin: 2px;">
      <row class="au-target">
        
        
            <cell class="au-target">
        <td class="cell" style="border: 1px sold blue;">
            Abc Def Ghi
        </td>
    </cell>
        
    </row><table>
        
        <tbody><tr>
          <td>Hi</td>
          <td>There</td>
        </tr>
      </tbody></table>
      </div>"

**Comment by chovy** [comment]
Angular had a way to avoid this using attribute-defined directives. I never got that far as I just worked around the problem. I don't think it can be done in Aurelia. But I don't know, not a dev.

You should really consider if a `table` is the best option for your case. Tables can be more trouble than they are worth at times.

**Comment by EisenbergEffect** [comment]
There aren't a lot of options here due to the way that the browser implements things. You can see if your scenario works with our Custom Attributes instead. Also, in the latest release, we have introduced the idea of "containerless" custom elements. These elements do not render their containing custom tag into the DOM, but just render their view. To convert your element into a containerless element, add the `@containerless` decorator. This may or may not work in tables though. I'm skeptical since it may be a low level issue with the HTML Parser that breaks the markup before we have a chance to parse it out. You can try it though.

**Comment by CarlosOnline** [comment]
1. When require is used in the containerless custom element the tr & td elements are not even rendered.

2. Removing the require renders the tr & td but still outside of table.

**Can aurelia replace the <row></row> before the browser parses the html?**

row.html

    <template>
        <require from='./cell'></require>
        <tr class="row" style="border: 1px solid green;">
            <td>custom row cell with require</td>
        </tr>
    </template>

generates:

      
        
        
            custom row cell with require
        
    <table style="border:5px solid red; padding: 2px; margin: 2px;">
        
        <tbody><tr>
          <td>Hi</td>
          <td>There</td>
        </tr>
      </tbody></table>

without require:

      
        <tr class="row" style="border: 1px solid green;">
            <td>custom row cell</td>
        </tr>
    <table style="border:5px solid red; padding: 2px; margin: 2px;">
        
        <tbody><tr>
          <td>Hi</td>
          <td>There</td>
        </tr>
      </tbody></table>

welcome.html
       <force render as markup>

        <table style="border:5px solid red; padding: 2px; margin: 2px;">
          <row></row>
          <tr>
            <td>Hi</td>
            <td>There</td>
          </tr>
        </table>

**Comment by jabbera** [comment]
I'm don't understand how the parser works, but being able to do something like this would help:

```<tr view-model="loader" model.bind="loader" repeat.for="loader of loaders">```

Even if we couldn't reference a template allow us to specify a VM on a TR would at least allow proper testability. Right now I'm stuck with one giant VM which is a pain to test:

```
<tr view-model="loader" model.bind="loader" repeat.for="loader of loaders">
            <td>${loader.name}</td>
            <td>${loader.status}</td>
            <td>${loader.lastErrorMessage}</td>
            <td>${loader.lastErrorTime}</td>            
 </tr>
```

**Comment by niieani** [comment]
I'm having the same problem, needing to make a custom element that's a row of a <table>.
As pointed out above, this does not work:
```html
<table>
  <tbody>
      <custom-row repeat.for="row of items" model.bind="row"></custom-row>
  </tbody>
</table>
```

Wrapping the custom-row is a `<tr>`.
I've tried making the `custom-row` `containerless()`, but still no luck, the element is rendered outside the table.

What's the official, proper way of implementing a custom row pattern?

**Comment by EisenbergEffect** [comment]
The first thing to realize is that, regardless of Aurelia, HTML will not let you make a custom element that replaces a tr or td. The HTML spec doesn't allow for it, so there's no way to make it work.

For this specific scenario, it would be possible to create a custom attribute that made the element it was on act like a custom element. It would be significant work to implement that probably. If we built it in...it might not be too hard. Would something like that work for all scenarios? I don't know.

Usage could be something like this:

```html
<table>
  <tbody>
      <tr as-element="custom-row" repeat.for="row of items" model.bind="row"></tr>
  </tbody>
</table>
```

This feature could be made to change any HTML element into a user-defined custom element.

**Comment by jabbera** [comment]
I ended up using divs as tables like so: http://programmers.stackexchange.com/questions/277778/why-are-people-making-tables-with-divs

Although something like as-element would be a huge win when the html spec won't allow what the natural dilution is.

**Comment by EisenbergEffect** [comment]
(Psst...I don't think I've used a real table in years. Not only are the browsers funny about the markup, but they severely degrade rendering performance because of the way they are designed and how browsers have to handle them.)

I *think* that implementing as-element might only take a few lines of code. Basically, just check for the attribute and change the tagName here; https://github.com/aurelia/templating/blob/master/src/view-compiler.js#L293 I don't know for sure though without doing some experiments.

**Comment by niieani** [comment]
Is there an issue tracking the implementation of `as-element`? Might be good to keep that in the backlog, or open for contributors.

**Comment by EisenbergEffect** [comment]
If you submit an issue for that, I can assign it to myself and probably implement it pretty easy based on my research. Create it and we'll do it.
