### ISSUE TITLE
Null no longer works in class.bind

### ISSUE THREAD

**Issue by Souldrinker** [aurelia/binding#109]
Not sure if this should be considered a bug or a breaking change in the latest releases of the binding library, but since I updated to the latest version the ClassObserver.setValue method crashed telling me split is not available on undefined.

After an hour or so of debugging I found out that I can no longer use null values in class.bind bindings. For exemple in my VM I had a property defined as sortCss = null (that I in some cases set to something else) which now crashed. When I changed it to sortCss = "" my application works again.

Not really an issue now when I know I have to set it to an empty string (or leave it undefined?), but...

**Comment by jdanyow** [comment]
I'd categorize this as a bug.  Will get this fixed asap.
