### ISSUE TITLE
 how to bind custom elements for two or more times using view-model?

### ISSUE THREAD

**Issue by changgvash** [aurelia/binding#111]
how to bind custom elements for two or more times using view-model?

app.html
```
<div repeat.for="data of datas">
	<compose
	     model.bind="data"
	     view-model="source">
	</compose>
</div>
```
source.html
```
<require from='/custom-element'></require>
<custom-element value.bind="value"></custom-element>
```

custom-element.html
```
${value.name}
${value.age}
```
i am able to bind custom-element in view for first data not for second onwards...

**Comment by jdanyow** [comment]
please don't blast the gitter and create an issue at the same time :wink:
