### ISSUE TITLE
Binding Mode/s filename

### ISSUE THREAD

**Issue by zewa666** [aurelia/binding#113]
I've realized that the bindingMode enum-like construct is named bindingMode, yet the file is named binding-modes. Note the plural form. Maybe by time we should standardize this and bring it back to singular naming.

**Comment by EisenbergEffect** [comment]
Good catch. @jdanyow At your earliest convenience, could you make this fix?

**Comment by jdanyow** [comment]
It's also declared as a `const`- should it be `var` instead?  Declaring as "const" doesn't make the object immutable.
