### ISSUE TITLE
Checkboxes bound to object are not updating in the UI

### ISSUE THREAD

**Issue by wshayes** [aurelia/binding#115]
Plunker demonstrating the bug(?)  http://embed.plnkr.co/rOL3Wj/preview (embed view works on Chrome - edit view doesn't show the checkboxes at all for me)

Binding to checkboxes inside of a repeat.for using model.bind and checked.bind, but the checkboxes aren't getting checked though from the console, the checked.bound object is getting updated? 

I had checkboxes not showing checks before when I forgot to return from a method, but I don't see what is going wrong now. Any suggestions on debugging this or is it a bug?

**Comment by jdanyow** [comment]
It works for me after removing the `click.delegate="$parent.$parent.search()`.  Modifying the search method to return true also worked.

**Comment by wshayes** [comment]
Thank you very much - missed the notification email on this.  So click.delegate responses need to be true or false and not a promise - makes sense.
