### ISSUE TITLE
Suggestion: Would like to see better support for non-visual custom elements and "containment".

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/binding#119]
This suggestion comes from my experiences in using XAML. It may or may not be the direction Aurelia wishes to move in/

Let's say I have a non-visual custom element "my-container" and another custom element "my-item" Let's say I write the following conceptual HTML (in another module called myModule):

```html
<my-container>
   <my-item attrib1="blah"/>
   <my-item attrib2="blah2"/>
</my-container>
```
Firstly, `<my-item>` will not know about any concept of containment within `<my-container>`. When `<my-item>.bind( )` is called, the bindingContext will be "myModule".

it would therefore be nice to be able to define an "addChildItem" method or similar within the MyContainer view-model class so that child view-models can be registered into it, if MyContainer is acting in a "container-like" fashion.

The corollary to this is that each MyItem view-model does not get told, via the bind( ) method or otherwise, that it is "contained" within a MyContainer. Instead it appears you have to muck around with refs and a bindable property to connect the models, similar to this:

```html
<my-container view-model.ref="cont1">
    <my-item container.one-time="cont1"/>
</my-container>
```

(I also find the xxx.one-time syntax extremely ugly, BTW).

For the latter issue I think it would not be unreasonable to extend the bind( ) method to take two parameters: the bindingContext (the current "parent"), as well as a containmentContext, being the closest surrounding ViewModel object surrounding the inner custom element.

The above suggestions would permit "modules" or "custom elements" to more easily define things like "resource objects" within a given view/view-model.

**Comment by EisenbergEffect** [comment]
The next release of aurelia allows a "container" to collect an array of children using the `@children('selector')` decorator or to gain a reference to a child with `@child('selector')`.

**Comment by jdanyow** [comment]
@kevmeister68 if you don't like `one-time` you can alias it to anything you want by doing this:

**main.js**
```js
import {SyntaxInterpreter} from 'aurelia-templating-binding';
SyntaxInterpreter.prototype['once'] = SyntaxInterpreter.prototype['one-time'];
SyntaxInterpreter.prototype['from'] = SyntaxInterpreter.prototype['one-way'];
```

here's a working example:  http://plnkr.co/edit/9abfaI?p=preview
