### ISSUE TITLE
Password input doesn't bind on autofill

### ISSUE THREAD

**Issue by ktomala** [aurelia/binding#120]
When the browser does autofill of password with login manager, the value of the variable is not updated. 

When you have a code like this:
```
<template>
            <form role="login" submit.delegate="try_login()">
              <input type="email" name="email" placeholder="Email" required class="form-control input-lg" value.bind="login" />
              <input type="password" class="form-control input-lg" id="password" placeholder="Password" required value.bind="password" autocomplete="off" />
              <button type="submit" name="go" class="btn btn-lg btn-orange btn-block">${ logintext }</button>
            </form>
</template>
```
and JS code for this view:
```
import {inject} from 'aurelia-framework';
import {HttpClient} from 'aurelia-http-client';
import {Router, Redirect} from 'aurelia-router';

@inject(HttpClient, Router)
export class Login {
	
	constructor (http, router) {
		this.appState = appState;
		this.http = http;
		this.router = router;
		this.login = null;
		this.password = null;
                this.logintext = 'Login';
	}
	
	try_login () {
                console.log(this.login);
                console.log(this.password);
       }
}
```
when the browsers' password manager autofills the form, the value of `this.login` is updated correctly, but the value of `this.password` is `null`. When the password field is filled in manually by typing, the binding works.

It seems that autocomplete="off" attribute doesn't work when browsers' password manager is involved as stated here: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

One possible workaround I have devised is to update value manually when clicking submit button inside a `try_login()` function like this:
```
		let passwd = document.getElementById('password').value;
		if (this.password != passwd) {
			this.password = passwd;
		}
```
but I believe Aurelia should support updating this value out-of-the-box (if it's possible).

**Comment by jdanyow** [comment]
Maybe we should use `DirtyCheckProperty` instead of `ValueAttributeObserver` for inputs of type "password" since most of the solutions for this issue on StackOverflow involve polling the input value on an interval.

https://github.com/aurelia/binding/blob/master/src/observer-locator.js#L117

**Comment by EisenbergEffect** [comment]
@jdanyow Did you have any further thoughts on this? Should we switch to the dirty checking in this case?

**Comment by jdanyow** [comment]
Reviewed this one yesterday- had trouble setting up a case where the browser would autofill, possibly because of the localhost url.  Will do some more testing.

**Comment by jdanyow** [comment]
This is working for me:
https://gist.run/?id=ca0423c27cdd1184953f
