### ISSUE TITLE
Call binding does not supply function reference on element

### ISSUE THREAD

**Issue by acidbluebriggs** [aurelia/binding#122]
When using a ‘call binding command’ the first time a custom element is created the call binding works fine. This element is then removed from the DOM and another is created (using an 'if binding' on a bound property). When this element is created, the call binding does not get set and remains null.

An example can be found here: http://plnkr.co/edit/0jwm1H

To test: 
1) Click on the ‘Create’ button.
2) The button has been removed and the custom element now displays with its "Save" button.
3) Click the ‘Save' button. 
4) The bound function has been invoked and the display updates to show the "Create" button again with the custom element having been removed due to the 'if binding'.
5) Click on the ‘Create’ button.
6) The button has been removed and the custom element now displays with its "Save" button.
7) Click the 'Save' button. The function call binding fails as it is null.

The expected result is that the call binding has set the function reference on "Save" but the value is now null, as the console will show.

**Comment by jdanyow** [comment]
Thanks for the nice repro!

Updated plunkr (looks like their backend is now case-sensitive so had to rename Entry.html/.js to entry.html/.js):

http://plnkr.co/edit/4B5poNiviDA1aq0nRb8x?p=preview
