### ISSUE TITLE
Can't load in a node environment

### ISSUE THREAD

**Issue by stoffeastrom** [aurelia/binding#128]
Assumes `document` is present in several places which isn't the case in a node environment.
For example this line https://github.com/aurelia/binding/blob/master/src/svg.js#L212 crashes when trying to load the module.

**Comment by stoffeastrom** [comment]
This line also crashes https://github.com/aurelia/binding/blob/master/src/class-list.js#L190

**Comment by jdanyow** [comment]
Thanks @stoffeastrom - have you guys decided on the method for detecting "running in node"?  I'd like to use whatever the best-practice is when fixing these.

**Comment by EisenbergEffect** [comment]
@jdanyow In the metadata library, there is now a check against the global variable. So we have `Metadata.global`. We could extend this check to also set a metadata values such as `Metadata.isServer` and `Metadata.isClient`. What do you think?

**Comment by jdanyow** [comment]
:+1: sounds good- would we put this code in binding's [environment.js](https://github.com/aurelia/binding/blob/master/src/environment.js) or would binding take a dep on metadata?

**Comment by EisenbergEffect** [comment]
I think we would add the dependency on metadata anywhere we needed to access the global object or check client/server mode.

**Comment by stoffeastrom** [comment]
Sounds like a plan. Metadata could also be enhanced with some kind of feature detection property. So instead of testing things on document, HTMLElement and whatnot the metadata library exposes feature detection properties that the other libraries could use. I'm not sure about the `isServer` `isClient`. They are good but I think "feature detection" properties are better. In the long run maybe you would want to configure this kind of stuff running in server mode....?!? Meaning that the metadata library could be configured so different scenarios could be run. For the browser that would mean that the bootstrapper would configure it before starting the app. Does that make any sense?

**Comment by EisenbergEffect** [comment]
Ah yes. I think you are right about the `isServer` and `isClient` piece. That should be configurable. But, I think we could place those in the Metadata library and have the framework set `isClient = true` by default. But you could set it yourself, for example. I do think this will be important as we hash out more of the isomorphic story.

I like the idea of feature detection as part of the metadata library. I'm quite sure what the best way to do that is just yet though. We'll need to think about that a bit more.

**Comment by stoffeastrom** [comment]
This has been implemented with the new `PAL` :smile:.
