### ISSUE TITLE
automatically create object structure

### ISSUE THREAD

**Issue by devmondo** [aurelia/binding#129]
hi, i have the following scenario where i have user object

```let user ={}```

when i bind in html like this

```<input value.bind="user.personal.name">```

i get undefined in the textbox, but if i make user like this  ``` let user={personal:{}}```
 ```undefined ```  in textbox goes away, i can understand this behavior if we are using something like c# because it is a statically typed languge but javascript is dynamic and left this constrain from us.

please consider this, thanks in advanced.

**Comment by jdanyow** [comment]
gitter discussion:  :point_up: [July 7, 2015 4:46 PM](https://gitter.im/Aurelia/Discuss?at=559c3a9352cc8c664f51093e)

The request is to make the binding system automatically "define" undefined path expressions.

Binding behavior maybe?

**Comment by EisenbergEffect** [comment]
@devmondo Do you mean that you get the word "undefined" appearing in the text box? If so, I think we should look into fixing that in the core.

**Comment by devmondo** [comment]
@EisenbergEffect  yeah exactly, it is  really troublesome with huge object structure, thanks :)

**Comment by jdanyow** [comment]
@devmondo are you still able to reproduce this?  This example works for me using the current bits:

```javascript
export class App {
  user = {};
  
  constructor() {
    setInterval(() => this.debug = JSON.stringify(this.user), 500);
  }
}
```

```html
<template>
  <p>user = ${debug}</p>
  
  <input type="text" value.bind="user.personal.name">
</template>
```

**Comment by devmondo** [comment]
@jdanyow it is working :) so you guys worked on it to make sure it is not false alarm?

**Comment by jdanyow** [comment]
Nice- yeah I was just going through the binding repo issues to see what was outstanding.

**Comment by devmondo** [comment]
i dont know if it is me or not, but if i do this 
```
 this.user.personal.numbers=[1,2,3];
```
i get inner error: TypeError: Cannot set property 'cool' of undefined
unless i do this 
```
 this.user.personal={};
```

**Comment by EisenbergEffect** [comment]
My guess is that your "personal" reference is undefined. We don't actually change your objects (I don't think), but the binding system can safely evaluate undefined paths. For your own code in JS, you will need to handle setting up all the references.

**Comment by jdanyow** [comment]
@EisenbergEffect / @devmondo here's a plunkr that shows what happens:

http://plnkr.co/edit/HnNmfzVqnQhsOkQCWpXn?p=preview

once you type in the textbox you'll see the feature that @devmondo  was asking for (magic creation of object structure).  Personally I think this is weird and would not expect it to work this way but hey- it works ;)

Here's the code I think is responsible:  https://github.com/aurelia/binding/blob/master/src/ast.js#L240-L243

**Comment by EisenbergEffect** [comment]
Ah yes....it does work. I remember that.

**Comment by devmondo** [comment]
@jdanyow @EisenbergEffect  i know it is weird, but sometimes it is really needed :)
