### ISSUE TITLE
Html not updating for Objects (valueConverter)

### ISSUE THREAD

**Issue by Webviech** [aurelia/binding#133]
Hi,

I am currently trying to filter an array with a value converter. This is going quite well, when passing just a string or a boolean to the value converter. When I try to pass an object, the value converter is excecuted on start. But if a value changes inside the object, nothing happens.

Here is my code:

module.js
```javascript
export class ModuleName {
  items = [
    {name: 'Item 1', flag: true},
    {name: 'Item 2', flag: false}
  ];
  filterObject = {
    flag: false
  };
}
```

value-converter/filter.js
```javascript
export class FilterValueConverter {
  toView(array, filterObject) {
    return array.filter((item) => {
      for (let key in filterObject) {
        if (item[key] !== filterObject[key]) {
          return false;
        }
      }
      return true;
    });
  }
}
```

module.html
```html
<input type="checkbox" checked.bind="filterObject.flag" />
<div repeat.for="item of items | filter:filterObject">
  ${item.name}
</div>
```

When clicking the checkbox, the value converter should filter again. But nothing happens.

I think it should work like this, but maybe I am doing something wrong?

P.S.: Hope you can understand my english ;) and this is the correct place to post this issue.

**Comment by shanonvl** [comment]
@Webviech you have to load the value converter before using it.  You can do that in two ways that I know of:

1.  If you're going to use it all over the place, make it a global resource.   Using the skeleton navigation example, you can configure it in the [animation-main.js](https://github.com/aurelia/skeleton-navigation/blob/master/src/animation-main.js):
```javascript
  ...
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-animator-css');

  // load the global resource 
  aurelia.globalizeResources('./value-converter/filter')
  ... 
```
2.  `<require>` it directly in your `module.html` ( using this method will only enable the converter for the current module )

```html
<!-- put this @ the top of the <template> -->
<require from="./value-converter/filter"></require>

...

<input type="checkbox" checked.bind="filterObject.flag" />
<div repeat.for="item of items | filter:filterObject">
  ${item.name}
</div>
```

**Comment by jdanyow** [comment]
When Aurelia encounters this binding expression: `repeat.for="item of items | filter:filterObject"` it sets up an array observer for the view model's `items` property.  If items are added/removed from the array (via push/pop/splice/etc).  Aurelia also sets up a property observer for the view model's `items` property which tracks scenarios where the `items` property is assigned a new array instance or null, etc.

None of these observers track property changes to the objects in the array, which is why you're not seeing the repeat binding re-evaluate when you change the flag property.

We'll be able to handle these kinds of scenarios with binding-behaviors in a future release of aurelia-binding.

**Comment by shanonvl** [comment]
-- removed my comment because it wasn't valid -- thanks @jdanyow ...

**Comment by Webviech** [comment]
@jdanyow Thanks for your answer. Actually I don't want to change an object in the item array. I want to change a property in the filterObject. Aurelia observes the change for the property in the object, but not for the object itself.

I just found a workaround:

Mehod in the class which is excecuted on change (checkbox):
```javascript
  applyFilter() {
    let filterObject = this.filterObject;
    this.filterObject = {};
    this.filterObject = filterObject;
  }
```

```html
<input type="checkbox" checked.bind="filterObject.flag" change.trigger="applyFilter()" />
```

Not pretty, but it works :)
Or is there a better solution?

**Comment by jdanyow** [comment]
Ah- I see- yes, here's a sneaky workaround...

use the `filterObject.flag` as a converter parameter (your converter doesn't need to use it).  Aurelia will start observing this expression and update the repeat when it changes:

```html
<input type="checkbox" checked.bind="filterObject.flag" />
<div repeat.for="item of items | filter:filterObject:filterObject.flag">
  ${item.name}
</div>
```

**Comment by Apcio** [comment]
I have the same problem with ValueConverter. I download JSON data from web and insert it to the object. ValueConverter run only once at page load.

View:
```
<pre innerHTML.bind="Data.Raw | toJSON"></pre>
```

Object:
```
this.Data = {
         "URL": {"url" : "url" },
         "Raw": {
            "Generated": null,
            "Consumed": null,
            "Imprted": null,
            "Exported": null
         },
         "Parsed": [ ]
      };
```

ValueConverter:
```
export class toJSONValueConverter
{
   toView(object)
   {
      if(typeof object !== "object") return object;
      return JSON.stringify(object, null, 2);
   }
}
```

RawData getter:
```
get rawData()
   {
      return this.Data.Raw;
   }
```

**Comment by gronostajo** [comment]
> We'll be able to handle these kinds of scenarios with binding-behaviors in a future release of aurelia-binding.

I can't figure out how to get it to work with binding behaviors, could you guys give me any pointers on this? I'm in a similar situation as described above, I have an object like this 

    count = { "min": <val>, "max": <val> }

and I want to update text every time `min` or `max` changes. It doesn't work with `CountConstraintsValueConverter`:

    <p>Count: ${metadata.constraints.count | countConstraints}</p>

I'd rather avoid workarounds if it can be achieved with a proper method.

**Comment by shanonvl** [comment]
@gronostajo, per [@jdanyow's suggestion](https://github.com/aurelia/binding/issues/133#issuecomment-124076319), have you tried the following as a workaround?
```
<p>Count: ${metadata.constraints.count | countConstraints:metadata.constraints.count.max:metadata.constraints.count.min}</p>
```
While I can see this as a problem for a large number of properties, I think it would work for your case here...
