### ISSUE TITLE
@computedFrom throws error when set method is implemented

### ISSUE THREAD

**Issue by Webviech** [aurelia/binding#136]
Hi Dev-Team,

if the decorator "@computedFrom" is used for a get method, I get an error when implementing a set method.

Error message:
ERROR [app-router] Router navigation failed, and no previous location could be restored.

Example view:
```javascript
import {computedFrom} from 'aurelia-framework';

export class Test {
  _fullName = 'John Doe';

  @computedFrom('_fullName')
  get fullName() {
    // some logic
    return this._fullName;
  }

  set fullName(name) {
    // some logic
    this._fullName = name;
  }
}
```

**Comment by jdanyow** [comment]
We can probably remove this restriction:  https://github.com/aurelia/binding/blob/master/src/computed-observation.js#L71

You could use the [aurelia-computed](http://www.danyow.net/introducing-aurelia-computed/) plugin instead, as a workaround.

**Comment by EisenbergEffect** [comment]
Yep, I was thinking about it and I don't think there would be an issue with removing it.

**Comment by akircher** [comment]
+1.  This is also a good example of the router swallowing a descriptive error and reporting a general one instead.  It took me a long time to figure out this error was actually from my use of `@computedFrom`

**Comment by EisenbergEffect** [comment]
I think we have the error issue worked out in the next release, coming in a couple of days. I'll also get this fix in for that too.
