### ISSUE TITLE
Binding to an Array in a repeat.for does not bind in a two-way direction

### ISSUE THREAD

**Issue by grantcarthew** [aurelia/binding#137]
I read through the current open issues and can't see anything on this. I may have missed something or be making a silly mistake.

If I create a member property on the welcome.js view model like so;

``` dataArray = [ '111' , '222' , '333' ]; ```

Then use a repeat.for in the welcome.html view;

```
<div repeat.for='da of dataArray'>
     <input type='text' value.bind='da'>
</div>
```

The view is updated when attached, but any changes to the input box will not be reflected back to the dataArray. Binding with ``` value.two-way ``` makes no difference.

Here are the versions of Aurelia I'm testing with;
```
  "jspm": {
    "dependencies": {
      "aurelia-animator-css": "github:aurelia/animator-css@^0.13.0",
      "aurelia-bootstrapper": "github:aurelia/bootstrapper@^0.14.0",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@^0.9.0",
      "aurelia-framework": "github:aurelia/framework@^0.13.0",
      "aurelia-http-client": "github:aurelia/http-client@^0.10.0",
      "aurelia-router": "github:aurelia/router@^0.10.0",
      "bootstrap": "github:twbs/bootstrap@^3.3.4",
      "core-js": "npm:core-js@^0.9.18",
      "css": "github:systemjs/plugin-css@^0.1.11",
      "font-awesome": "npm:font-awesome@^4.3.0"
    },
```
aurelia-binding is at 0.8.0

**Comment by jdanyow** [comment]
Interesting scenario- assigning a new value to the loop variable in a `repeat.for` will not have any impact on the array.  

Consider a for-of loop in javascript:
```javascript
for (da of dataArray) {
  da = 'something else';
}
```
Assigning `da` something else doesn't change the values in `dataArray`.  The same thing is happening in the `repeat.for` binding scenario.

Here's how you could modify your code to achieve the desired result:

```javascript
export class App {
  dataArray = ['111', '222', '333'];
  
  // Following code is used to display the contents of the array for debugging purposes: 
  debugString = ''; 
  constructor() {
    setInterval(() => this.debugString = JSON.stringify(this.dataArray), 500);
  }
}
```
```html
<template>
  <p>${debugString}</p>
  <div repeat.for="i of dataArray.length">
    <input type="text" value.bind="$parent.dataArray[i]">
  </div>
</template>
```

**Comment by EisenbergEffect** [comment]
@jdanyow Nice work. Can you add this to a list of "How Tos" in the binding repo for our future docs. I think this is a good "recipe" type piece we would want to share in the future.

**Comment by jdanyow** [comment]
sure

**Comment by grantcarthew** [comment]
@jdanyow Thanks Jeremy, nice one.

**Comment by djedi** [comment]
But what if you were observing the array in the data. It wouldn't update the template because `dataArray.length` doesn't change. See https://gist.run/?id=1f8eb3ee7a8e3772ab22ade6c719e30b

**Comment by djedi** [comment]
I've tried a combination of the two approaches and still no luck - but I'm not sure why https://gist.run/?id=fc06317dc6b9a8e099f7eecb25eb6d34

**Comment by wallaceturner** [comment]
can someone tell me where the `repeat.for` docs are? 
its not under http://aurelia.io/docs/binding - or at least i can't find it there

**Comment by EisenbergEffect** [comment]
See if this helps: http://aurelia.io/docs/templating/basics#repeaters

**Comment by EisenbergEffect** [comment]
Here's another resource: http://aurelia.io/docs/fundamentals/cheat-sheet#templating-view-resources

**Comment by wallaceturner** [comment]
yes thanks i found that just after i posted it.

however in this section it does not mention the issue that this bug details - that is there is no example with repeat-for and inputs where two way binding is expected to just work


e.g. instead of 
```
<tbody>
                  <tr repeat.for="i of arr.length">
                    <td>
                      <input type="text" class="form-control" value.bind="$parent.arr[i]">
                    </td>
                  </tr>
</tbody>
```
you must use
```
<tbody>
                  <tr repeat.for="i of arr.length">
                    <td>
                      <input type="text" class="form-control" value.bind="$parent.arr[i]">
                    </td>
                  </tr>
                </tbody>
```

**Comment by EisenbergEffect** [comment]
Any interest in submitting a PR to address the over-sight?

**Comment by wallaceturner** [comment]
sure - you want it to go in the cheat sheet or the binding basics?

**Comment by EisenbergEffect** [comment]
Let's put it in the repeaters section of the templating basics doc. Sounds good? https://github.com/aurelia/templating/blob/master/doc/article/en-US/templating-basics.md#repeaters

**Comment by jalmansa88** [comment]
Hello,

The documentation is not completed. Check:

```
Two-way binding with arrays requires a special syntax due to the nature of the for-of loop in javascript. Do not use repeat.for="item of dataArray";doing so will result in one-way binding only - values typed into an input will not be bound back. Instead use the following syntax:

Range
We can also iterate over a numerical range:

${10-i}
```
The "following syntax" is missing.

I tried using 
`repeat.for = 'i of arr.length` and does not work neither. The array is not updated in view.
