### ISSUE TITLE
how tos

### ISSUE THREAD

**Issue by jdanyow** [aurelia/binding#138]
This issue contains a list of "how tos" that we will include in the official docs application.
- [how to two-way bind to elements in an array](https://github.com/aurelia/binding/issues/137#issuecomment-124073551)
- [how to bind select element values to non-string data](https://github.com/aurelia/binding/issues/141)

**Comment by netaisllc** [comment]
Here is another topic, the solution or answer to which is nearly impossible to find.  It concerns eventing via **.trigger** and **.delegate** (which is confusing enough to mortals as it is) but my topic is _not_ the typical question (when to use one technique over the other).

In Jquery (gasp), it is trivial to create a sort of "micro-aggregator" for DOM events at an arbitrary level in the DOM tree.  An example being a collection of DIVs, all children of a single parent DIV. Setting **.on** on the parent element easily and effectively trapped all clicks on the children, and one would determine the actual clicked child using vanilla DOM, the good old event.target.

Aurelia pretends to do this, but in my work it subtly doesn't.   

Given the example above, using **click.trigger** on the parent can miss clicks on children depending on the _layout_ of the elements.  Ouch. On the other hand, **click.delegate** properly exposes the event as occurring on the child, but gives no facility to detect events at the parent (container) level which is what we wanted.  Arg.

Dear God, is Jquerys approach easier/better at this?  The very words sour on my tongue. So my suggestion is to document how to do such in Aurelia.

Or possibly I have missed something obvious?

**Comment by EisenbergEffect** [comment]
@jdanyow Pinging you on binding documentation ;)

**Comment by EisenbergEffect** [comment]
@jdanyow You mentioned you thought you would have the binding docs ready last week, so I just wanted to check in with you to see how that is coming.

**Comment by jdanyow** [comment]
will wrap them up this week- sorry the holiday weekend snuck up on me and I probably shouldn't have waited to mess around with that gource video but I couldn't resist.

**Comment by Alexander-Taran** [comment]
can be closed

**Comment by ConnectedReasoning** [comment]
am I wrong in saying react does this built in?

**Comment by Alexander-Taran** [comment]
@ConnectedReasoning "this" being exactly what?
