### ISSUE TITLE
Binding to a simple array of numbers or strings does not behave as expected

### ISSUE THREAD

**Issue by jbgarr** [aurelia/binding#139]
I've run into an issue when binding to a simple array of numbers or strings that I can't quite understand. If the items in the array are repeated over using the `repeat.for="item of itemsInArray"` syntax and then each item's value is bound to an input, making changes to the item's value does not cause the underlying item in the view-model's array to be updated.
Here is what I would assume *should* work:
```
<div repeat.for='item of itemsArray' >
    <label>Item:</label>
    <input type="text" value.bind="item" class="form-control">
</div>
```
Here is the only way that I could find that does work:
```
<div repeat.for='item of itemsArray' >
    <label>Item:</label>
    <input type="text" value.bind="$parent.itemsArray[$index]" class="form-control">
</div>
```

This situation works fine if the each item in the array is an object though.

In order to better explain the situation I've created a [plnkr](http://plnkr.co/edit/Jyw1XIpFy50uFm2pQvql).

**Comment by jbgarr** [comment]
I just found a similar issue that was already closed! https://github.com/aurelia/binding/issues/137 Seems to cover exactly the same situation. Sorry about that!

**Comment by jdanyow** [comment]
no worries- glad you found what you're looking for

**Comment by bebor** [comment]
i came about the same issue, but even more, what if the item in `itemsArray` is not just a number, but an object
itemsArray = [{ property: 'test'}]
