### ISSUE TITLE
<a> tag not followed when a parent has a click binding

### ISSUE THREAD

**Issue by MetalKid** [aurelia/binding#140]
I added a click.trigger event to a <tr> that allows a row to be "selected":

<tr repeat.for="employee of employees" class="${employee.isSelected ? 'yellow' : ''}" click.trigger="$parent.select(employee)">

I then had an Actions column that allowed a user to go to the edit screen via an <a> tag with:

<a route-href="route: employee-edit; params.bind: { id: employee.employeeID }"><i class="fa fa-edit fa-lg" title="Edit"></i></a>

When you click the <a> tag, the <tr> click event ends up handling it instead and won't let it bubble up.  Thus, the only way around it is to add your own click event on that <a> tag.  Is there any way around this that allows a normal <a> tag click to get handled by itself in this scenario?

**Comment by EisenbergEffect** [comment]
Some of your code is missing from above, so I'm not entirely sure of the use case. However, you can allow the event to continue to bubble by returning true from your triggered method. If I understand you correctly, that should solve your problem.

**Comment by MetalKid** [comment]
Ah, didn't realize you could do that.  Thanks! :)
