### ISSUE TITLE
$index used in delegate not updating when used with $parent.array[$index] strategy

### ISSUE THREAD

**Issue by davismj** [aurelia/binding#145]
I have a `repeat.for="item of items"` block that contains a `value.bind="$parent.array[$index]"` binding as well as a `click.delegate="handler($index)` binding. If I have say 5 items, remove the first one, and then invoke the click handler on the last item, the argument passed to the function is still 5. If I remove the value binding, however, the click handler works as expected.

**Comment by davismj** [comment]
One work around is to replace `replace.for="item of items"' with 'replace.for="index of items.length", and replace any bindings to `item` with bindings to `$parent.items[index]`.

**Comment by jdanyow** [comment]
possibly related to https://github.com/aurelia/templating-resources/issues/109

**Comment by martingust** [comment]
@davismj I'm trying to reproduce this but I must be missing something. Here is what I've got

**View**
```
<button click.delegate="removeFirst()">Remove First</button>
    <ul>
      <li repeat.for="item of items">
        <input value.bind="$parent.items[$index]" click.delegate="$parent.handler($index)" />
      </li>
    </ul>
```

**ViewModel**
```
items = ['foo', 'qux', 'bar'];

handler(index){
    console.log(index);
}

removeFirst(){
    this.items.splice(0, 1);
}
```

When I remove first item and then click inside of the second input to invoke `handler()` I get expected `1` in the console.

**Comment by jdanyow** [comment]
@davismj / @martingust  can this one be closed?  sounds like it's fixed

**Comment by davismj** [comment]
I couldn't reproduce.
