### ISSUE TITLE
observing computed properties via their dependencies

### ISSUE THREAD

**Issue by jdanyow** [aurelia/binding#15]
@Alxandr and I were brainstorming how to get around using dirty-checking when binding computed properties (properties that have a getter function).

One idea we were throwing around was to provide a way declare the computed property's dependencies.  This way aurelia could observe the computed property's dependencies and recompute the property value only when the dependencies change.  If this isn't something that should be put in Aurelia directly an adapter could provide this logic (https://github.com/aurelia/binding/pull/10).

Thoughts?

----------------------------------

**First attempt (no worky):**
```js
var person = { firstName: 'Don', lastName: 'Draper' };

Object.defineProperty(person, 'fullName', {
  enumerable: true,
  configurable: true,
  get: function() { return this.firstName + ' ' + this.lastName; },
  dependencies: ['firstName', 'lastName']  // wondering if getOwnPropertyDescriptor will return this...
});


var descriptor = Object.getOwnPropertyDescriptor(person, 'fullName');
descriptor.dependencies  // undefined :(  bummer....
```

**Second Attempt (works but not ES6 style/if-stmt in getter is bad idea)** 
```js
var person = { firstName: 'Don', lastName: 'Draper' };

Object.defineProperty(person, 'fullName', {
  enumerable: true,
  configurable: true,
  get: function(returnDependencies) {
    if (returnDependencies)
      return ['firstName', 'lastName'];    
    return this.firstName + ' ' + this.lastName; 
  }
});


var descriptor = Object.getOwnPropertyDescriptor(person, 'fullName');
descriptor.get(true);
```

**Third Attempt (works but ugly/even worse)**
```js
var person = { firstName: 'Don', lastName: 'Draper' };
function fullName() {
  return this.firstName + ' ' + this.lastName; 
}

fullName.dependencies = ['firstName', 'lastName'];

Object.defineProperty(person, 'fullName', {
  enumerable: true,
  configurable: true,
  get: fullName
});

var descriptor = Object.getOwnPropertyDescriptor(person, 'fullName');

descriptor.get.dependencies;
// ["firstName", "lastName"]
```

**Last Attempt**
```js
function declarePropertyDependencies(ctor, propertyName, dependencies) {
  var descriptor = Object.getOwnPropertyDescriptor(ctor.prototype, propertyName);
  descriptor.get.dependencies = dependencies;
}

export class Person {
  constructor() {
    this.firstName = 'Don';
    this.lastName = 'Draper'; 
  }

  get fullName() {
    return this.firstName + ' ' + this.lastName;
  }
}

declarePropertyDependencies(Person, 'fullName', ['firstName', 'lastName']);
```

**Variation of last attempt, enabling multiple props to be configured in one call**
```js
function markComputedProperties(object, props) {
  var keys = Object.keys(props);
  for (var i = 0, l = keys.length; i < l; ++i) {
    var descriptor = Object.getOwnPropertyDescriptor(object.prototype, key);
    descriptor.get.dependencies = props[key];
  }
}

export class Person {
  constructor() {
    this.firstName = 'Don';
    this.lastName = 'Draper'; 
  }

  get fullName() {
    return this.firstName + ' ' + this.lastName;
  }
}

markComputedProperties(Person, {
  fullName: ['firstName', 'lastName']
});
```

**Comment by EisenbergEffect** [comment]
I think we could do this through the existing metadata api.

**Comment by EisenbergEffect** [comment]
Actually, if we can find attach something to the getter function itself, then that might be the best way. It would need to be something the binding system can use to determine how to know when a custom getter/setter was changing.

**Comment by EisenbergEffect** [comment]
@jdanyow  Might be worth looking into merging in your dependent property code. What do you think?

**Comment by Alxandr** [comment]
The last examples are attaching it to the getter itself.

**Comment by jdanyow** [comment]
@EisenbergEffect sure

**Comment by jdanyow** [comment]
@EisenbergEffect logistics question:  would you expect to see this treated as a system supplied ObjectObservationAdapter or would you you rather the logic to determine whether to use a ComputedPropertyObserver was hard-coded into the ObserverLocator.
