### ISSUE TITLE
bug: console error when using nested custom elements

### ISSUE THREAD

**Issue by andrevlins** [aurelia/binding#150]
I'm getting the error bellow when using custom elements inside another.

```javascript
Uncaught TypeError: callbacks[i] is not a functionhandleChanges @ aurelia-binding.js:3465
```

I did a repro fork on skeleton to show.
https://github.com/andrevlins/skeleton-navigation

In this case I use a layout custom element with some input custom elements inside.

If I remove the layout custom element the error goes away.

**Comment by andrevlins** [comment]
additional info: if I change `<input type="text" value.bind="$parent.foo2" />` to `<input type="text" value.bind="$parent.foo" />` the error goes away too.

If I have more than one `var` binded the error happens.

**Comment by EisenbergEffect** [comment]
@jdanyow When you get a chance, can you look into this?

**Comment by jdanyow** [comment]
Nice find- thanks for the repro.  Subtle bug.  Here's what's happening:

The code to publish a property change looks like this:
```javascript
for (i = 0, ii = callbacks.length; i < ii; i++) {
  callbacks[i](newValue, oldValue);
}
```
https://github.com/aurelia/binding/blob/master/src/property-observation.js#L177


Or sometimes like this:
```javascript
while(i--) {
  callbacks[i](splices);
}
```
https://github.com/aurelia/binding/blob/master/src/collection-observation.js#L82

---

When an `unsubscribe` happens while invoking the callbacks, depending on the implementation the index out of bounds error can occur or a callback can be invoked multiple times while others aren't invoked at all.

I think the fix is to copy the callback array's contents and iterate over the copy like this:

invoke-callbacks.js
```
var temp = [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];

export function invokeCallbacks(callbacks, ...args) {
  let i = length = callbacks.length;
  while(i--) {
    temp[i] = callbacks[i];
  }
  for (i = 0; i < length; i++) {
    temp[i](...args);
    temp[i] = null;
  }
}
```

Still working on the tests for this (see above branch ^^^).  @EisenbergEffect do you see any problems with this approach?  I'm planning on refactoring to not use the spread operator because it results in an array allocation:

transpiled invoke-callbacks.js
```javascript
  var temp = [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null];

  function invokeCallbacks(callbacks) {
    for (var _len = arguments.length, args = Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) {
      args[_key - 1] = arguments[_key];
    }

    var i = length = callbacks.length;
    while (i--) {
      temp[i] = callbacks[i];
    }
    for (i = 0; i < length; i++) {
      temp[i].apply(temp, args);
      temp[i] = null;
    }
  }
```

**Comment by EisenbergEffect** [comment]
@jdanyow The only problem is that it is a temporary solution. As soon as the benchmarks are done one of the first things we are going to do is remove all these arrays and replace them with field accessors. I would love to get on to the actual perf work which I think could also help to address this issue.

**Comment by jdanyow** [comment]
Thought you might say that- do you want a PR for this or do you want to tackle it when we make the "first, second, third, rest" change?

**Comment by EisenbergEffect** [comment]
I'd rather wait to tackle it along with the performance work.

**Comment by andrevlins** [comment]
how to do a quick workaround until then? is it possible?

**Comment by jdanyow** [comment]
@andrevlins in your repro the issue occurs in `OoObjectObserver.handleChanges`.  You can patch it like this:

main.js
```javascript
import {ObserverLocator} from 'aurelia-framework';

export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-animator-css');

  if (Object.observe) {
    let obj = {foo:'bar'};
    aurelia.container.get(ObserverLocator).getObserver(obj, 'foo');
    console.log(obj.__observer__.__proto__.handleChanges = handleChanges);
  }
  aurelia.start().then(a => a.setRoot());
}

var temp = [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];

export function invokeCallbacks(callbacks, newValue, oldValue) {
  var length, i = length = callbacks.length
  while(i--) {
    temp[i] = callbacks[i];
  }
  for (i = 0; i < length; i++) {
    temp[i](newValue, oldValue);
    temp[i] = null;
  }
}

function handleChanges(changes) {
  var properties = {}, i, ii, change, propertyName, oldValue, newValue, callbacks;

  for(i = 0, ii = changes.length; i < ii; i++){
    change = changes[i];
    properties[change.name] = change;
  }

  for(name in properties){
    callbacks = this.callbacks[name];
    if (!callbacks) {
      continue;
    }
    change = properties[name];
    newValue = change.object[name];
    oldValue = change.oldValue;

    invokeCallbacks(callbacks, newValue, oldValue);
  }
}
```

**Comment by andrevlins** [comment]
I'll try, thank you.

**Comment by EisenbergEffect** [comment]
@jdanyow Nice. You are thinking carefully about the cost of various choices in hot path code I see :)
