### ISSUE TITLE
Suggestion: Observe paths

### ISSUE THREAD

**Issue by jods4** [aurelia/binding#158]
Aurelia should expose a simple way to observe a path, e.g. `user.firstName`.

If I am not mistaken, `ObserverLocator` only helps you observe a property directly on your object.

`@computedFrom` really needs it: #149 

`aurelia-validation` built its own solution to the same problem (maybe some reuse is possible here?):
https://github.com/aurelia/validation/blob/master/src/validation/path-observer.js

And it seems to me that the binding system _has_ to be doing that somewhere already.

And my own code needs it as well... ;)

**Comment by EisenbergEffect** [comment]
Yes, we should expose that. We have been hesitant to do it just yet because we are about to do a major overhaul to the biding system in order to improve performance and memory. After we do that, we'll expose some nicer APIs for consumers such as this. @jdanyow Let's use this issue to track the user-facing APIs for the binding system that we want to add after the perf work is done.

**Comment by DavidBLynch** [comment]
+1

**Comment by jdanyow** [comment]
related to https://github.com/aurelia/binding/issues/149

**Comment by jdanyow** [comment]
The upcoming release has our new bindingSystem API which exposes `observePropertyChanges(obj, propertyName, callback)` and `observeCollectionChanges(collection, callback)`.  We could add `observeExpression(expression: string, callback)`.

Thoughts?

**Comment by jods4** [comment]
(1) Naming seems a bit long and maybe inconsistent. Why `Changes` -- or why not `observeExpressionChanges` then? I think you can go with just `observeProperty` and `observeCollection`.

(2) What is the execution context for `observeExpression`? If a call `observeExpression('item.price * item.quantity', value => console.log(value))`, where is `item` supposed to be? How does Aurelia know?

(3) Does `observePropertyChanges` support paths, e.g. `address.city.zip` or `orders[3].quantity`? I think it's a must-have API. For instance, it is required internally in Aurelia by `@computedFrom` attribute and aurelia-validation.

If it already supports paths, it is probably a misnommer and the API should be renamed. `observeProperty` kinda implies that it only observes a single property.

I suggest `observeValue`, `observeScalar` or just `observe`. Not `observePath` for a reason that will become more obvious in (4).

(4) The fact that `observeCollection` takes a collection directly is limiting. In the same way `observeProperty` taking a single property is limiting.

I think that it should accept a collection _or a path to a collection_. Say I want to observe this collection: `observeCollection(context, 'selectedItem.tags', callback)`. I would be notified when the `tags` change (addition, removal) but also when the `selectedItem` changes and I get a brand new `tags` array.

BTW I assume arrays are "smart", i.e. `observeValue(context, 'items.length', cb)` would work?

**Comment by jdanyow** [comment]
good feedback- this is just a starting point- the API will definitely evolve based on the community feedback.  Here's some more info:

1. naming: wrestled with this myself.  Problem is there's a lot of confusion around property observation vs collection mutation observation.  Would like to avoid this if we can.  

2. binding context: good call, it's missing in the pseudo code

3. observePropertyChanges does not support paths

4. So there are tradeoffs, having a single "observe" method that accepted expressions was considered.  We could still add that.  There's a cost to parsing expressions, there's a cost to eagerly observing array mutation along with property changes.  

What do you think?  Should we favor an API that takes just about anything for args and eagerly observes the result or should we keep things very explicit, like they are now?  Maybe we could have mix, with a very eager default behavior and some options to dial things back?

**Comment by jods4** [comment]
I think it make sense to keep at least 2 different APIs and probably even 3 for efficiency purposes.

Observing a collection or a single value is not the same for two reasons:
1. The callback is different. In one case you are passed the new value (and possibly the old one). I have not looked at the new API documentation but I assume that for collections you get a list of addition and removal (array of values + change + index) or a "reset" flag when the collection has completely changed.
So different signature -> different API. It is good design and it is even more important for the Typescript experience.
2. Consider `observeValue(x, 'tags', cb)` and `observeCollection(x, 'tags', cb)`. Exact same call, but different behaviour. In the first you want to know when the `tags` array is swapped for another array (or null). In the second you want to listen to mutations of the `tags` array.

The gray area is for expressions. With a context they are very similar to the `observeValue` function. But because the parsing involved is more complicated, I would tend to have a "simple" path parser in `observeValue` and a more complex expression parser in `observeExpression`. Now maybe it's not worth having a path parser at all and they could use the same API, I am not 100% sure about this one.

So I think a good API start would be:
`observeValue(object, path, cb)`
`observeCollection(object, path, cb)`
`observeExpression(object, expr, cb)`

Another concern is whether passing a callback is the good thing to do. I am thinking that adopting RxJS might be better. Here's why:
0. The result of `observe` _is_ an observable sequence, which is what Rx models.
1. The syntax is a bit nicer and similar to (now) well-known Promise:
`let disposable = observeValue(x, 'name').subscribe(console.log)`
2. This object model is composable. I won't repeat why composition is a good thing vs callbacks, this has been beaten to death in Promises.
3. This syntax leaves room for future optional parameters, such as `options`.
4. This gives a lot of operations for free to people willing to include RxJS in their project. E.g. debounce, throttle, filter, combine with other RX streams, etc.

Doing so might require the `rx-core` if you don't want to re-implement all the bare bones of a RX observable, which is 15Ko minified.

**Comment by EisenbergEffect** [comment]
We aren't going to adopt RxJS in the core. That can be handled by the plugin and @jdanyow has already done some work there. Our internals need to be as light as possible and as small as we can get them, without 3rd party dependencies. The only deps we allow in the core are polyfills.

I think we can improve the naming. @jdanyow I think we could have:

* `observeProperty`/`unobserveProperty`
* `observeCollection`/`unobserveCollection`
* `observeExpression` (how to unobserved this one?)
* `createBindingExpression`
* `registerBindingAdapter`

...possibly other things as we see fit

Jeremy, while looking into this, also consider addressing the initialize function. I don't think we can allow orphaning of old services upon container initialization because, especially after adding `registerBindingAdapter` we could wind up in a situation where a plugin's configuration of the binding system was "lost" on an orphaned instance.

**Comment by EisenbergEffect** [comment]
(sorry about the close, accidentally clicked the wrong button)

**Comment by jods4** [comment]
@EisenbergEffect returning a dispose function, or a disposable object, seems like a better design than having `unobserve*` functions.

If you don't want to take `rx-core` into Aurelia (note that `rx-core` is a minimalist subset that was created with the sole purpose of being embedded by frameworks that _don't_ want to have Rx as a dependency, but for which exposing some Observables that might be consumed by Rx makes sense) you could implement your own return type in a Rx-compatible way. Given that `observe` results would not throw or close, what you need to actually implement is _very_ thin.

This is something that you won't be able to change easily after v1, so I think you should not dismiss the idea too quickly. Returning an object with `{ subscribe(); dispose(); }` is a nice API, makes the API easier to extend in the future, feels familiar with other frameworks, enables composition (impossible with callbacks), and gives tons of free features to people willing to embed Rx in their app.

**Comment by EisenbergEffect** [comment]
@jods4 It is a core tenant of this project that we do not allow any 3rd party libraries in the core which are not polyfills for web standards. Our current api could easily be wrapped with an RxAdapter if someone were to need it. That could even be provided as part of @jdanyow 's async plugin. We don't want to be creating and returning these objects unnecessarily because we just got through doing a bunch of perf optimizations which showed us just how costly doing that is.

**Comment by jods4** [comment]
@EisenbergEffect Do you mean that returning a function that disposes the observation has proven too costly in benchmarks compared to being able to dispose the subscription by passing in the same arguments again?

That's very unfortunate. Is there no way to optimize this, e.g. minimize the captured state / object creation? 
Is it that costly even when you consider the fact that the caller must keep those arguments somewhere if you don't capture them? It is a pitfall in optimization that pushing work outside a framework doesn't optimize the global workload, only what happens in the framework -- and it's even worse because of repeated bloat in the caller code.

I guess an alternative design would be to return a dispose token (i.e. number) à la `setTimeout` / `clearTimeout`. It could index into whatever internal structure you use to keep track of the subscriptions and be able to dispose it from that. There would be no allocation required.

**Comment by EisenbergEffect** [comment]
We have been through these conversations internally....and it does make a difference. We are talking about a change that would affect every databinding expression in the entire UI. So, that adds up and has big affects on memory. You could "wrap" our api with something that provides the api you want. It won't affect our internal optimizations. But, we don't want to couple our internals to mechanisms that would create unnecessary allocations.

Or maybe....hmmm.


@jdanyow We don't actually use this api internally anywhere do we? So, I guess we could make it a bit different for dev use without affecting our internal perf, right? If that is true, what is the minimum we could do to get something a bit "friendlier" and compatible with Rx? If we make any changes here, we should also consider making the event aggregator's pub/sub API match. Thoughts?

**Comment by jods4** [comment]
I understand your concerns. The binding system is used _a lot_ in an application, so it has to perform well. This is very important.

I guess that having a low-level API for when perf is at a premium (e.g. the binding engine) and "better" API for when it's not critical is a good approach. As you said, those "better" wrapper might even be an optional plugin. I see your point and I agree with this design.

The tricky part is mostly to expose that in a clean and intuitive way. Starting with: which API should be center stage? The "better" or the "faster"?

**Comment by EisenbergEffect** [comment]
Since the fast API (I believe...@jdanyow can correct me if I'm wrong) is already used directly by use internally, I think we could do some of this with `bindingSystem`. It is, after all, a wrapper of the internal services designed to create a friendlier API. So, maybe we just need to take it a step farther. I would like Jeremy's input on that.

@jods4 Without including any 3rd party library, what is the minimal you think we could to a nice api, and either support Rx or be "friendly" or "easy" to integrate with it. Keep in mind I'm also trying to reduce our source code size :)

**Comment by jods4** [comment]
@EisenbergEffect I can have a look at that, but I need to know what the internal/fast API looks like.

**Comment by EisenbergEffect** [comment]
Just look here: https://github.com/aurelia/binding/blob/master/src/binding-system.js
You will see what the `bindingSystem` class is doing under the hood.

**Comment by jdanyow** [comment]
@jods4 hit me up with a PM on gitter if you have any questions about the internal API that binding-system.js is wrapping.  Basically the internal API uses no callbacks, no closures, and no object or array allocations other than the "observer" and "binding" instances.  Thanks for pitching in on the "public" API.

**Comment by jods4** [comment]
OK, this is untested but for brainstorming purposes, what about that. 
Note that size-wise this is a very thin layer. Perf-wise for the fake-Rx version there are two allocations and some captures happening for each subscription, probably more with the real-Rx implementation. The first allocation may sometimes be amortized since the same "Observable" may be reused with different subscriptions.

```javascript
// Idea #1
// --------------------------------------------------------------------------------------
// Returns a dispose function: () => void
function observeProperty(obj, propName, cb) {
	observePropertyChanges(obj, propName, cb);
	return unobservePropertyChanges.bind(null, obj, propName, cb);
}

// Idea #2
// --------------------------------------------------------------------------------------
// API that returns a RxJS Observable if Rx is loaded
// or a similar API when RxJS is not there

// Shipped in base aurelia bundle:
function observeProperty(obj, propName) {
	return {
		subscribe: (cb) => {
			observePropertyChanges(obj, propName, cb);
			return { dispose: unobservePropertyChanges.bind(null, obj, propName, cb) };
		}
	};
}

// Shipped as an optional module, overwrites base version:
bindingSystem.observeProperty = function(obj, propName) {	
	return Rx.Observable.create(function(observer) {
		let callback = value => observer.onNext(value);
		observePropertyChanges(obj, propName, callback);
		return unobservePropertyChanges.bind(null, obj, propName, callback);
	});	
}

// Usage of idea #2
// --------------------------------------------------------------------------------------
var subscription = observeProperty(obj, "firstName")
					.subscribe(value => console.log(value));
// When you're done:
subscription.dispose();

// More fun:
var sub = observeProperty(obj, "firstName")
			.filter(name => name !== "")
			.throttle(300 /* ms */)
			.subscribe(value => console.log(value));
```

**Comment by EisenbergEffect** [comment]
@jods4 Are the two apis compatible. In other words, if Rx is not present, is the api above basically the same as what Rx would provide, or at least a strict subset. The thing I don't want is completely different APIs based on whether or not you have Rx installed. In other words, someone who write an Aurelia plugin, without Rx, should be able to use this api and it should continue to work if someone with Rx installs their plugin. Does that make sense?

**Comment by jods4** [comment]
@EisenbergEffect That's the idea. The first version returns an object with the following shape:
```
{
  subscribe: (callback) => { dispose: () => void }
}
```
Which is a subset of the Rx api.

**Comment by EisenbergEffect** [comment]
@jods4 @jdanyow Ok, I think this sounds pretty good then. My main concerns were:

* Not affecting the performance of the core
* Making sure our APIs were compatible and wouldn't break by the addition of Rx

So, I'm satisfied there. We should also make the same change to the event aggregator api. There was a request for something similar, so this would make all our pub/sub stuff consistent.

@jods4 Do you have time to submit a PR today? I want to make the new release this evening and would like to have this in.

**Comment by jods4** [comment]
Thinking about all this stuff some more:

(1) About what API should be publicly put forward: only the easy one. 
Most applications won't use this much. Convenience is more important than performance.
If a case requiring maximum speed arises, one should fallback to the low-level, highly optimized `ObserverLocator` directly.

(2) We don't need `observeExpression`.
It encourages bad practice. People should put their logic into computed properties (getter only) and observe that.

(3) Don't forget that we badly need path observation.
This is a _very_ important use case. Both `observeValue` and `observeCollection` should accept a path. This should then be used to fix #149 and simplify aurelia-validation, which has its own path observation system.

@EisenbergEffect sorry it's getting late here and I don't have time to create a PR.

**Comment by EisenbergEffect** [comment]
I think `observeExpression` is the same thing as enabling path observation on the other APIs, isn't it?
@jdanyow Do you have time to do this today? If not, I may be able to do it later. Just let me know.

**Comment by jods4** [comment]
Observing a path is a subset of observing an expression, which is easier to handle.
But then if you already have the expression observator maybe you can just use it, yes. (I think you shouldn't, though)

- You don't need a full parser, just dots and indexers.
- Keeping the dependency data structure and unsubscribing to things as they change is also a lot easier. consider observing `a.x * b.y`. When `b` changes you need to unsubscribe to the old `b.y` and subscribe to the new `b.y`. It forces you to keep the expression tree for dependencies. Or you can rely on a path observation engine and simply observe `a.x` and `b.y`, which means observing paths is a stepping stone to observing expressions and has to be built first anyway.
- You can include special semantics more easily. I think it makes sense for an observation engine to return `undefined` when any part of the path is `null` or `undefined`. Including such nullability semantics into a generic expression engine is more difficult.
- As I said, I don't think exposing an expression engine is a good idea. People should not be encouraged to write code in strings.

**Comment by EisenbergEffect** [comment]
All of that infrastructure already exists though, in the binding engine.

**Comment by jods4** [comment]
@jdanyow @EisenbergEffect 
Quick question: is there any global reference kept when creating a subscription? 
Precisely, if I do `bindingEngine.propertyObserver(x, 'name').subscribe(console.log)` and never dispose the subscription, is this going to create a memory leak after `x` is freed?

My expectation is that one should be able to do that.
I would think that the chain of references is `x` -> subscribers (maybe via a WeakMap) -> listener callback. 
Am I right or do subscriptions _always_ have to be disposed? (which would be a bummer)

**Comment by jdanyow** [comment]
Failing to dispose of a subscription will create a memory leak.

Internally the binding engine uses `Object.observe`.  If you don't dispose of the subscription the observer will never call `Object.unobserve` which means the browser will continue to observe `x`, holding a reference `x` and the callback it's supposed to invoke when `x` changes.

**Comment by jods4** [comment]
@jdanyow 
For the `Object.observe` implementation, reading the [specs](http://arv.github.io/ecmascript-object-observe/) I don't think that it will leak. The specs doesn't explicitely say whether it would leak or not, but the core piece that makes everything work is the `Notifier` instance that is stored into the `[[Notifier]]` internal property of an object. So references are observed object -> `[[Notifier]]` -> callbacks.

So my questions are:
- Why do you say not calling `Object.unobserve` would leak?
- What about other observation mechanisms such as setters made by Aurelia, will they leak?

Change notifications are, at they core, just events. I think you would agree that any platform where each event has to be unsubscribed from in order not to leak would suck (and I know of no such platform).

**Comment by EisenbergEffect** [comment]
Pretty much every platform has this issue. Usually, the greatest source of memory leaks in every app I've ever looked at has to do with failing to unsubscribe from eventsRemember, eventing mechanism holds a reference to a callback...which could have values captured by its closure. This means that as long as the event is subscribed, the source holds a strong reference to the closure and all its captured state. This may or may not cause you an issue, depending on the lifetime of the objects. Aurelia's O.o fallback stores subscriptions with the object itself, so in theory it should all get cleaned up. However, as applications grow, there can be references between objects that the developer creates which are less obvious. I would just follow it as a best practice to "clean up" something when it is done.

**Comment by jods4** [comment]
I get from @EisenbergEffect answer that using Aurelia to observe objects does create a strong reference to the observed object and that nothing would leak in the common case where the observee doesn't outlive the observer. In that sense it works like events.

Digression:
I agree that every platform that I know works more or less the same. The "issue" is specifically when the _source_ outlives the _listener_, which is a leak (typically if you subscribe to global / static events). It is important for a dev to be aware of this.

Yet I think there is a large place for "subscribe and forget" events. It is perfectly fine if you know the event source doesn't escape the listener's scope, which in a ViewModel should be 90% of the time if you program cleanly. (Writing a framework such as Aurelia is surely different in that regard.)

When the event source lifetime is not linked to the observer, I usually fall back on one of two techniques: (a) unsubscribe if the lifetime is clear, e.g. when a UI component is unloaded; or (b) weak events when lifetimes are not clear, e.g. when there are several references from independent owners (although not easy to use, WPF has weak events; Flex had them too).

I think that in application code unsubscribing from every single event creates tons of code and variables and closures. When it's not required it just clutters the code and hurts perf. Consider this mind exercise: a Promise's callback is in fact a one-shot event and keeps a reference to your closure, etc. How would your code look if you had to "unsubscribe" from every Promise you used!

**Comment by EisenbergEffect** [comment]
Absolutely. I agree with you here. I created some weak event tech for WPF back in the day to assist with some of those scenarios.

When it comes to our binding system, we have to create the absolute lightest weight implementation possible and that means not creating any unnecessary structures, which are typically needed to handle auto-cleanup. Specifically, with the browser, one would need to use a WeakSet or something to do it...but that isn't implemented everywhere, and there's no WeakReference speced. So, even achieving this in a generic way is very hard...and may not be possible at all to do within the perf constraints we need for the binding system.

Hopefully, developers don't need to do too much manual subscription themselves. Most of this should be taken care of by the binding system which ensures things get cleaned up. As  you mention the real problem is when the source outlives the listener. It's these cases developers do need to manage themselves at the moment.

**Comment by jods4** [comment]
@EisenbergEffect FYI here are some example user cases where I manually observe stuff today with Aurelia:

(1) A business rule says that when property `x` changes, then `y` should reset. Given that `x` can be directly changed by UI bindings I usually do: `observe(data, "x").subscribe(() => data.y = 0)` when loading `data`.
A cleaner way would be to put that logic in a setter, but there are obstacles. If you have `set x(value) { this._x = value; this.y = 0; }`. Then you have to be careful avoiding dirty checking by adding `@computed("_x")` on the property. Also if `data` was a JSON payload, you would need to set its prototype or reassign it to a class instance to get this working. 
So that's not as good as it should.

(2) I work around the limitations of aurelia-validation dependencies. The validation can't take path dependencies at the moment, so I kinda had to implement them myself. That's painful and I hope it'll be changed soon. Same thing for `@computed` on properties BTW.

(3) I write custom elements or custom attributes that accept collections and I need to react to a change in the bound array. That should be handled by Aurelia itself but it currently is not. I wanted to open an issue but I will add a comment in #183 instead.
