### ISSUE TITLE
Parametrize events to bind

### ISSUE THREAD

**Issue by heruan** [aurelia/binding#159]
If I understand correctly when binding a VM property to a `input`'s `value` attribute, the `EventManager` listens to `change` and `input` events. Can I specify for some `input` elements to listen only to the `change` event? So the VM property won't be updated while the user types, e.g. `<input type="text" value.bind="[change]property">`.

**Comment by EisenbergEffect** [comment]
We are tracking a feature called "binding behaviors" which will be implemented soon. That will enable the specification of the event to trigger for changes.

**Comment by heruan** [comment]
Awesome! I'll check for that :+1:
