### ISSUE TITLE
OoObjectObserver TypeError in handleChanges

### ISSUE THREAD

**Issue by SPARTAN563** [aurelia/binding#161]
A performance optimization made in `OoObjectObserver.handleChanges` [here](https://github.com/aurelia/binding/blob/master/src/property-observation.js#L177) makes it fragile to a changing model. Specifically, if an earlier observer callback changes the list of available callbacks (through the use of `if.bind` for example) then you can end up failing to trigger later ones.

### Use Case
Any situation in which an `if.bind` is used to wrap other bindings poses this risk of triggering this if those child bindings themselves are descendants of a dependency in `if.bind`. My particular use case involves conditionally showing configuration controls when the specific configuration key is present - mirroring the way our server and API process this information.

### Versions
Currently running a (heavily modified) version of the Skeleton Navigation Example on v0.17 libraries - however the bug still appears to be present in the latest code after a cursory inspection (not tested).

### How to Reproduce

```js
export class Demo {
    container = { value: '' };

    toggle() {
        if(this.container) delete this.container;
        else this.container = { value: '' };
    }
}
```

```html
<template>
    <a href="#" click.delegate="toggle()">Break Me</a>

    <div if.bind="container">
        <input type="text" value.bind="container.value"/>
    </div>
</template>
```

Clicking the **Break Me** button should hide the text input control, instead the control remains and an error is thrown. (If this functions as expected, let me know, it may require more bindings to be present to trigger it).

### Suggested Fix
I would suggest grabbing a copy of the `this.callbacks` array and iterating over that in lieu of the true `this.callbacks` (which can be modified). I fear that this could impose a performance penalty though, so while it would be nice for a quick fix I'm not sure it would work as a long-term solution.
Long term, a better approach would be to ensure that bindings are not removed from the callbacks array until the propagation loop has completed - however that is likely to require more significant architectural changes.

**Comment by EisenbergEffect** [comment]
@jdanyow Do we need to address this? or will our upcoming chnages to the internals of observers solve this problem automatically?

**Comment by jdanyow** [comment]
I think we decided that when we make the changes to the observers we'll need to keep this issue in mind.

@SPARTAN563 this issue has instructions on how to monkey patch the OoObjectObserver:  https://github.com/aurelia/binding/issues/150

The patch passes the unit test suite because it originally came from here:
https://github.com/jdanyow/binding/commit/dfe184ba94ac6cf0effbe6f51afb37430cc1ab97

**Comment by SPARTAN563** [comment]
Thanks guys, I've ended up using proxies in the underlying model to bypass the issue - good to know that the issue will be solved in future.
