### ISSUE TITLE
using ES2015 Symbols in paths break in IE11

### ISSUE THREAD

**Issue by reinholdk** [aurelia/binding#164]
I'm using a custom symbol (created using Symbol()) in my model to separate UI related status properties from actual data. This breaks on IE11 in ObserverLocator.getObserver where propertyName is an instance of Symbol.
The method returns undefined in that case because the JavaScript 'in' operator returns true for any custom Symbol:
```javascript
// from ObserverLocator.getObserver
...
if (observersLookup && propertyName in observersLookup) { 
   return observersLookup[propertyName];
}
```
The scenario works well in Chrome.
It looks like an issue with the Symbol polyfill for IE. You can check the expected behavior using the following examples:
```javascript
Symbol.iterator in []; // returns true
Symbol.iterator in {}; // returns false
Symbol('x') in {}; // returns true but obviously should return false
```

**Comment by jdanyow** [comment]
hi @reinholdk - would you mind putting together a minimal reproduction in the aurelia plunker?  This one has the latest Aurelia build:  http://plnkr.co/edit/tgcNkp?p=preview

I want to make sure I understand the issue fully.

Thanks!

**Comment by reinholdk** [comment]
OK, here is a basic example:
http://plnkr.co/edit/ghs4NU0F2om25Q50mKXH?p=preview
Unfortunately, the aurelia plunker does not run in IE. So you may need to copy app.js, test.js and app.html into a local project in order to reproduce.
In IE you'll get an TypeError in aurelia-bindings.js immediately after loading the app:
   Unable to get property 'subscribe' of undefined or null reference
MS Edge, FF and Chrome run just fine.

Hope that helps
-- Reinhold

**Comment by jdanyow** [comment]
@reinholdk thanks

updated plunker that runs in IE:  http://plnkr.co/edit/2aC3Qv?p=preview

**Comment by jdanyow** [comment]
requires native support for symbols
