### ISSUE TITLE
.call functions should allow you to give your own context object

### ISSUE THREAD

**Issue by Alxandr** [aurelia/binding#166]
Currently, when you do stuff like `<my-foo bar.call="afunction()">`, the arguments available for to use in the `.call` expression is the ones that exist on the scope, and the magical `$event`. In most cases, `$event` makes sense, given that you mostly use this with events, however, this does not hold true for all events.

Take the following example:

```javascript
@customElement('show-data')
public class ShowDataElement {
  @bindable getData;
  bind(ctx) {
    console.log(this.getData({$foo: 'bar'}));
  }
}
```

`getData` is clearly not an event. What I want is to be able to do the following in the HTML

```html
<show-data get-data.call="myFunc($foo)"></show-data>
```

In this case, `foo` would be set to `'bar'`, because that is what was given by the `ShowDataElement`. Today, this *can* be achieved using the following html: `get-data.call="myFunc($event.$foo)"`, however, this is counter-intuitive, and IMHO somewhat limiting. Especially if you want to define a lot of custom values, you end up having to repeat `$event` a lot of times in the html. Not to mention the fact, that as said, `get-data` is clearly not an event, so it makes no sense for it to have any event arguments. It's just a function reference I've passed into my custom element.

Implementing this should also be really easy, because this logic already exist in Aurelia. Currently, what happens when you call `getData`, is that it takes the parameter and adds it to a context object with the name of `$event`, then extract the parameters (using the binding logic) from that context object. Instead, functions that want to actually use `$event`, could just pass `{$event}`, and use that as a context object, whereas it would allow us to pass anything else we would like.

**Comment by EisenbergEffect** [comment]
@jdanyow This is another reason to consider the core binding concept of the alternate binding context we talked about. Let's keep this in mind as we make the binding changes. The same mechanism we use to solve the $parent issue could handle this as well potentially.

**Comment by jdanyow** [comment]
@Alxandr  I'm happy to report that this week's release now has this feature.

https://github.com/aurelia/binding/blob/master/src/call-expression.js#L30

Let me know if you run into any issues using it
