### ISSUE TITLE
CheckedObserver.prototype.unsubscribe throws @3987

### ISSUE THREAD

**Issue by devployment** [aurelia/binding#168]
Following along @EisenbergEffect demo from NDC Oslo ```aurelia-binding.js``` throws as ```callbacks``` is null before splicing. It happens if I tick the checkbox the 2nd time to show the recursive element again.

I think the source file is is the following 

https://github.com/aurelia/binding/blob/9a3162815cc4c0ae592ba7666409189d65e8d516/src/element-observation.js#L241

```
Uncaught TypeError: Cannot read property 'splice' of null              aurelia-binding.js:3987
unsubscribe @ aurelia-binding.js:3987
updateRight @ aurelia-binding.js:822
(anonymous function) @ aurelia-binding.js:809
handleChanges @ aurelia-binding.js:3460
```

**Comment by EisenbergEffect** [comment]
@jdanyow Just tagging you on this.

**Comment by jdanyow** [comment]
Tested the recursive welcome.html that @EisenbergEffect demonstrated at 48 minutes into [this presentation](https://vimeo.com/131641012) with the binding/templating/etc code in **master**...  pleased to report that the error @devployment was seeing will be fixed in the next release.

```html
  <input type="checkbox" ref="isRecursive">
  <compose view-model="./welcome" if.bind="isRecursive.checked"></compose>
```
