### ISSUE TITLE
Changing bound value to null causes crash

### ISSUE THREAD

**Issue by Hexagenic** [aurelia/binding#172]
Hi, I think I've found a bug in the binding unsubscription code.  When having bindings like 
```html
<span>${a.b}</span>
```

And ```a``` goes from some value to null, and then some value. Aurelia tries to remove observers from null,  and I get an indexOf on null error on aurelia-binding.js:3404

I'm not very familiar with this codebase, but I found a quick solution was to add a check for null

```javascript
var callbacks = this.callbacks[propertyName];
if (!callbacks) {
  return;
}
var index = callbacks.indexOf(callback);
```

**Comment by jdanyow** [comment]
this is fixed in the upcoming release- there's a workaround here:  https://github.com/aurelia/binding/issues/150
