### ISSUE TITLE
Using show bind with template tag doesn't work

### ISSUE THREAD

**Issue by devteamexpress** [aurelia/binding#174]
i'm trying to wrap two html statements with a template tag and use the template tag as such

    <template show.bind = "order.Tip == 0">
       <dt>Tip</dt>
        <dd>$${order.Tip}</dd>
    </template>

It toggles the class, but the template tag stays in the dom and is hidden by the browser default stylesheet.

**Comment by EisenbergEffect** [comment]
You can only use a custom attribute with a template tag if it is a "template controller" such as `if` or `repeat`. These attributes are literally designed to control the instantiation of templates. The `show` attribute merely swaps classes on the element to show/hide it. So, if you place it on a template, it will have no effect.
