### ISSUE TITLE
binding attribute order on element affects outcome

### ISSUE THREAD

**Issue by coderasm** [aurelia/binding#175]
If I place value.bind before change.trigger on an element, inside the change.trigger handler I see the updated value of the property attached to value.bind. If I place change.trigger before before value.bind on an element, inside the change.trigger handler I see the old value of the property attached to value.bind.

I see updated property value attached to value.bind inside change.trigger
```
<select class="form-control" value.bind="buyerId" change.trigger="loadBuybackVehiclesFromVM()" id="dealer">
     <option repeat.for="dealer of dealers" value.bind="dealer.id">${dealer.name}</option>
</select>
```

I see old property value attached to value.bind inside change.trigger
```
<select class="form-control" change.trigger="loadBuybackVehiclesFromVM()" value.bind="buyerId" id="dealer">
     <option repeat.for="dealer of dealers" value.bind="dealer.id">${dealer.name}</option>
</select>
```

**Comment by EisenbergEffect** [comment]
Quite simply, this is because event handlers are fired one after the other.

**Comment by MaartenThomassen** [comment]
Shouldnt there be a default, fixed, sequence of calling the handlers in
order of "priority" or similar?

Whatas the reasonimg behind the current implementation? Personally I find
behaviour based on the location of attributes a bit strange.
