### ISSUE TITLE
Is it the correct behaviour ?

### ISSUE THREAD

**Issue by JimmiV** [aurelia/binding#176]
I created [this](http://plnkr.co/edit/4nETg3)
If you click save the fist time you receive the expected message, but if I click new and then save the newItem is undefined; only if I select a value from the combo it became assigned.

In my real app the newItem is a breeze entity but the result is the same: the first time I can save it, the second time the FK associated to the combos are not binded correctly.

**Comment by jdanyow** [comment]
Thanks for creating the plunker Emiliano.  I think the problem is you have a select element whose value is bound to an object that doesn't exist in the select element's list of options.

Here's an updated version, showing what I mean:  
http://plnkr.co/edit/LS2TeA?p=preview

**Comment by JimmiV** [comment]
I have not explained well, sorry.

confezioni are my masterdata, coming from a table code-description
newItem is the new entity that reference confezioni; it will be added an entityManager (with Breeze) and saved somewhere.

The first time newItem is binded as expected, the second no.

**Comment by jdanyow** [comment]
Ultimately you cannot bind a select element's value to an object that is not in the select element's options.  Doing so leads to unexpected behavior.  

In your case when the app starts the select element shows that that `Conf.1` is selected.  This conflicts with your code which says `<select value.bind="newItem" ...`.  

`newItem` is not `Conf.1`, what you're seeing is the value binding is encountering a situation where you've given it a value that isn't "selectable".  In this case the binding doesn't do anything and the select element's default behavior takes over which is to display the first item in the set of options.

Does this make sense?

**Comment by JimmiV** [comment]
And this make sense looking at it from the model to the view.

But when you click Save, without do anything else, newItem IS Conf.1: it has an id and a des and this is what I want.
The second time, after New was clicked, if I save newItem is undefined until I change the selected value.

In my real app, when I add the first row to a table the FK are assigned to the properties of the empty entity with the fisrt value of the Select. The second did'nt have the same behaviour.
The only way I saw to workaround this, is to force the user to select a value from the select adding a first empty value.

**Comment by EisenbergEffect** [comment]
Not an issue.
