### ISSUE TITLE
observerLocator.getObserver() doesn't return an unsubscribe function anymore

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/binding#186]
After I updated to the latest aurelia libraries, I noticed that `getObserver(obj, prop).subscribe()` no longer returns an unsubscribe function. It now returns `undefined` and I believe this is a breaking change. What is the correct way to unsubscribe from the observer?

**Comment by jdanyow** [comment]
we haven't blogged about this yet but here's what you're looking for:
http://stackoverflow.com/a/28437456/725866
http://stackoverflow.com/a/30286225/725866

also this:  https://github.com/aurelia/binding/blob/master/src/binding-engine.js#L59

**Comment by JeroenVinke** [comment]
Thanks!
