### ISSUE TITLE
One-way binding on select causes binding error

### ISSUE THREAD

**Issue by salminio** [aurelia/binding#189]
I have a situation where I want to select the default value in a list but don't want the value to be reflected after. I know it's not the norm and I can work around it but figured I would point it out anyway in case others have a need for it.

It throws an error:
`Uncaught TypeError: Cannot read property 'length' of undefined`
`  call @ aurelia-binding.js:3831`
`  synchronizeValue @ aurelia-binding.js:3826`
`  (anonymous function) @ aurelia-binding.js:3865`

http://plnkr.co/edit/RAE9GB

**Comment by jdanyow** [comment]
fixed in latest build:  http://plnkr.co/edit/QiEcOR?p=preview
