### ISSUE TITLE
Can't set custom element value in attached()

### ISSUE THREAD

**Issue by bsrdjan** [aurelia/binding#191]
I want to set the initial custom element value, two-way binded, in `attached` callback. After the correct value assigned to `this.value` in `attached()`, the `valueChanged` is called with `undefined`. Changes later on work. When one-way binded, works fine, but need two-way.

Here the View and View-Model:

```html
<div class="row">
    <ci value.one-way="cimodel" ci.ref="cielement"></ci>
</div>
<div class="row">
    <p>ci: ${cimodel}</p>
    <button click.delegate="modelABC()">modelABC</button>
    <button click.delegate="modelXYZ()">modelXYZ</button>
    <button click.delegate="viewABC()">viewABC</button>
    <button click.delegate="viewXYZ()">viewXYZ</button>
</div>
```

```javascript
export class Welcome {

  modelXYZ() {
    this.cimodel = 'XYZ';
  }
  modelABC() {
    this.cimodel = 'ABC';
  }
  viewXYZ() {
    this.cielement.extChange( 'xyz' );
  }
  viewABC() {
    this.cielement.extChange( 'abc' );
  }
}
```

Here the custom element View and View-Model:

```html
<template>
    <input input.delegate="validateInput($event)"/>
</template>
```

```javascript
import {bindable, inject} from 'aurelia-framework';

@inject(Element)
export class Ci {

  @bindable value;

  constructor(element) {
    this.$el=element;
  }

  bind() {
    this.input = this.$el.querySelector('input');
  }

  attached() {
    if ((this.value === null) || (this.value === undefined)) {
      console.log('setting initial value');
      this.value = 'Initial'
    }
  }

  extChange(newValue) {
    this.value = newValue;
  }

  validateInput(event) {
    let newValue = event.srcElement.value;
    console.log(`validate: ${newValue}`, this.$el.value);

    this.value = newValue;
  }

  valueChanged(newValue) {
    console.log(`new: ${this.value}`, `newValue: ${newValue}`);

    this.input.value = this.value;
  }
}
```
Tested on 0.18.1 skeleton and here the console log, for two-way:
```shell
setting initial value
ci.js:35 new: undefined newValue: undefined
```

**Comment by stoffeastrom** [comment]
Is it good enough to set in when declaring the property

`@bindable value = "initial";`

**Comment by bsrdjan** [comment]
Not good enough, the initial value determined in runtime.

**Comment by nomack84** [comment]
@bsrdjan I'm not completely sure, but I think you don't need the `input.delegate` handler at all. Why don't you simply use two-way binding on the input and check in the `inputChanged` the fields value validity? 
I think that Aurelia binding system does something like what `input` does...

**Comment by nomack84** [comment]
Something like this:

```html
<template>
    <input value.bind="ci" />
</template>
```

```javascript
ciChanged(newValue) {
    // validation logic here
}
```

**Comment by nomack84** [comment]
and if the initial value is determined at runtime, the `constructor` is your friend

**Comment by bsrdjan** [comment]
I have a feeling there could be a simpler way but didn't find one yet. The binding is defined in the View and there is already declared value.bind="cimodel".  In custom element template I cant fiy the binding to "ci", as custom element reusable in different models. Not sure I got the point, the same with the constructor, but believe the simpler solution possible 😊

**Comment by bsrdjan** [comment]
Here the shorter and hopefully simpler description of the issue. When the custom element value two-way binded to non-existing model variable (undefined), it is not possible to change the value in `bind()` or `attached()` methods. Assigning any value to `this.value`, within these methods, calls the `valueChanged()` call `undefined` new value, thus no change happens. Not sure if bug or feature ?

**Comment by jdanyow** [comment]
@bsrdjan please set this up in the [aurelia-plunker](http://bit.ly/aurelia-plunker) and we'll investigate further.

thanks!
