### ISSUE TITLE
API design: bindingEngine

### ISSUE THREAD

**Issue by jods4** [aurelia/binding#194]
This is a bit of follow-up on #158

(1) It was closed without a clear comment, so my guess is that paths can be observed with `expressionObserver`.

Given that this is a superset of `propertyObserver`, do we need to keep both? Why can't we reduce the API surface to just `observer(context, expression)` and `collectionObserver(collection)`? If this is an optimization trick, `observer` could detect that it got a single property and use an optimized codepath. Also, per the discussion in #158 these API are meant to be easy to use, not provide the absolute performance (for this there is `ObserverLocator`).

(2) Another point that bothers me is that we don't have an expression observer for collections. Say: `collectionObserver(context, 'selectedCustomer.orders')`. Currently if I want to observe a list of items and the collection itself may change (e.g. another `selectedCustomer`) than I have to do all the dirty observation / unsubscribe work myself. This is kind of similar to the discussion in #183. I think Aurelia needs a primitive for that. Things like that are trivial in Knockout.

(3) We probably need a syntax to say we want to be notified when array elements change. Kinda like `collectionObserver` but from a string. Here's one example, consider this property on a ViewModel:
```typescript
@computedFrom("selectedCustomer.orders[]")
get ordersCount() { return this.selectedCustomer.orders.length; }
```
This expression changes whenever `selectedCustomer` or `orders` changes, OR when elements are added or removed from `orders`. Of course, this was kind of a bad example because you could observe `selectedCustomer.orders.length` directly and even put this in the View.

But let's consider a more complex example:
```typescript
@computedFrom("selectedCustomer.orders[].price")
get total() { return this.selectedCustomer.orders.reduce((total, o) => total + o.price); }
```
Yes, I even made up a more complicated syntax where you can observe properties on every element of the array, including when elements are added or removed.
Such a scenario would just work in KO.

Doing this today is cumbersome. You need to observe the path `selectedCustomer.orders` yourself, then observe the current array (unobserve when it changes, etc.). Then for each element observe `price`. And when any of this change, redo the computation and store it into a field `total` that you can bind to from the view. This is _a lot_ of plumbing and subscriptions management for something that ought to be simple. 

What do you think?

**Comment by EisenbergEffect** [comment]
@jdanyow First can you comment on whether or not you think we can merge any of the APIs? If we do that, and we have something we like, then we could add additional features in the future...the sorts of things that @jods4 is asking for. My main concern now is that we have a stable API and that we aren't going to have to break it for a long time (adding new things is perfectly fine).

**Comment by jdanyow** [comment]
I don't have time to put any further effort into this one *before the beta*.  There's nothing stopping us from iterating on what we have in an external plugin and rolling it into the binding repo once we come up with something better.  

Does that sound reasonable to you guys?  

@jods4 if you have the bandwidth to explore any of this I will help you any way that I can.

**Comment by jods4** [comment]
@jdanyow I think part of this stuff is important enough to get into the core and not external plugins. For instance, I think that there needs to be a way to declare complex dependencies for computed properties or validation. 

Consider the `total` example above. How do you think this should work in Aurelia? What are the alternatives?

I would like to contribute here and surely will try, but my "bandwidth" is also very limited at the moment :(

**Comment by jdanyow** [comment]
@jods4 Consider the overhead to observe the `total` property in your example.  Do you think precise observation using a series of property observers and array an observer is more efficient than dirty-checking in this specific use-case? What about in situations where the selectedCustomer has a lot of orders?  When thinking about this, take into consideration memory utilization and "time to bind".  In some cases dirty-checking is a good fit performance-wise for certain observation scenarios.

**Comment by jods4** [comment]
@jdanyow that's a good point. Observing `total` is not trivial and involves approx. 3+N observers, N being the size of the shopping cart.

My thoughts:
- 3+N is not extreme either, you would need quite a lot of orders for it to become a problem. In fact, KO does exactly that and I used it in many situations without noticeable problems (desktop only, though).
- dirty checking avoids this but you trade for evaluating the total several times a second. If N is large that's not cheap either and it puts a permanent strain on the system, perf and batteries will suffer as well.
- Assuming N is really large and it becomes a problem, I think I would turn to alternative strategies. Most probably using a coded signal for triggering a `total` update.

It is true that dirty checking trades setup time + memory for CPU and update time. Maybe I'm not being rational but I avoid dirty checking as much as possible. I am afraid that it doesn't scale well. Your property might be costly to compute and if you start having tons of them (think large app) I can't imagine this doing well.

**Comment by EisenbergEffect** [comment]
It seems like this specific scenario would be best optimized by something like signals, which are coming in the next release. This allows you to "signal" that a particular binding or set of bindings should refresh.

**Comment by jods4** [comment]
Good to know that other tools are coming! 
Signals are something I had in mind for quite some time now.

Yet I wouldn't totally dismiss the issue at hand here. `total` is only an example and not an end in itself. There are plenty of situations where stuff like that "just worked" well with Knockout. Raising signals explicitly is a good tool to have in one's arsenal, yet kind of a step back at the same time.

Generally speaking the more option, the better. Especially when perf. trade-offs are involved.
