### ISSUE TITLE
Suggestion: optimized observable arrays

### ISSUE THREAD

**Issue by jods4** [aurelia/binding#195]
Knockout had this and it was awesome and useful: http://github.com/SteveSanderson/knockout-projections.

Basically: some operations on arrays are very common (e.g. filtering `.filter()` or projecting `.map()`).
Consider how you would display a filtered list in Aurelia today:
```typescript
@computedFrom(["search", "items[]"])
get filteredItems() { return this.items.filter(x => x.name === this.search); }
```
This works (except for the array observation, see #194) but any time one item is added, the whole array is filtered and copied again, and then the DOM is entirely rebuilt.

KO.projections has "intelligent" array operations. When an item is added to `items` a change notification is received by the filtered array. It then looks at the new element and checks if it satisfies the predicate. If no, nothing is done. If yes, it is added to the filtered collection and a change notification is raised.

This means that for stuff like projections or filtering, adding/removing an element is O(1) instead of O(N).

**Comment by jdanyow** [comment]
>but any time one item is added, the whole array is filtered and copied again, and then the DOM is entirely rebuilt.

I don't think this is a true statement.  Aurelia's binding system attempts to add/move/update the minimum repeated elements when an array is mutated.  It uses the Levenshtein distance algorithm to optimize/minimize the set of "splices" that are applied to the DOM.  Check out the code in the repeat element and the calcSplices method in the `array-change-records.js` file.

**Comment by jods4** [comment]
I think actually KO was doing something similar and the statement is you quoted is only partially true.

The part that may not happen is _"the DOM is entirely rebuilt"._

The rest still holds. 

If you have a relatively large array in memory, and a computed property that filters the array. Maybe something like this:
```
@computedFrom('orders')
get largeOrders() {
  return this.orders.filter(order => order.price > 300);
}
```

Any time you add an item `this.orders.push(new Order())` the following things happen:
- The `largeOrders` value is recomputed, which implies iterating the whole array and copying all items that match the predicate into a new array.
- Aurelia needs to compare the new resulting array to the old one, computing the minimum diff, which is not cheap.

Use cases manipulating large arrays benefit greatly from stuff like KO-Projections, because when you add a new order:
- only this new order is passed through the predicate.
- if it doesn't match nothing more happens, if it does:
- the new order is inserted in the alreay existing filtered array
- Aurelia would immediately know that the diff is a single insert.

That's still considerably more efficient.

**Comment by jdanyow** [comment]
One thing you'll be able to do with the release that dropped this week is create your own collection type that has the logic you've described and plug a strategy into the repeat binding command to teach it how to use your new collection type.  That would make an awesome plugin- `aurelia-projections` or something.

Want to take a shot a build something like that?  I would be happy to help anywhere I can.

**Comment by jods4** [comment]
The fact that this is possible is very cool and shows how extensible and well-designed Aurelia is. :+1: 

I have no time to take a shot at this at the moment, but I am very happy that the possibility exists and I might do that in the future.

**Comment by ISkomorokh** [comment]
Has anything changed since last comment?
