### ISSUE TITLE
params.bind in route-href ignores parameter

### ISSUE THREAD

**Issue by bolddp** [aurelia/binding#199]
I have a viewmodel object like this:

```javascript
this.quiz = {
    Id: '10C32120-527A-44C5-9392-C910AC93A8BC',
    Questions : [
        {
            Id: '70188D42-F3C3-4203-AC01-C722D630261D',
            Text: 'First question'
        },
        {
            Id: '117A7CB2-2BBD-4903-A10D-88A5B9E9CEBC',
            Text: 'Second question'
        },
        {
            Id: '60ADBF6F-C9E0-4C0C-B0EE-3B642B5DE8E3',
            Text: 'Third question'
        },
    ]
};
```

And try to bind it in an unordered list:

```html
<ul class="list-group">
    <li repeat.for="question of quiz.Questions" class="list-group-item">
        <a route-href="route: questionoverview; params.bind: { quizid: quiz.Id, questionid: question.Id }">
            <h4 class="list-group-item-heading">${question.Text}</h4>
        </a>
    </li>
</ul>
```

But the resulting anchor tag completely ignores the quizid param:

*http://localhost:64243/#/questionoverview?questionid=117A7CB2-2BBD-4903-A10D-88A5B9E9CEBC*

If I change it to a fixed value like this:
```html
<a route-href="route: questionoverview; params.bind: { quizid: 'fixed', questionid: question.Id }">
```

it's working properly (even though the params are in reverse order):

*http://localhost:64243/#/questionoverview?questionid=70188D42-F3C3-4203-AC01-C722D630261D&quizid=fixed*

**Comment by jdanyow** [comment]
the reason this didn't work in the previous release is you needed `$parent.quiz.id` to reach out of the repeat scope and access the quiz.  In the current release your code should work as-is.
