### ISSUE TITLE
Problem with click.delegate="method()"

### ISSUE THREAD

**Issue by VladCherniavsky** [aurelia/binding#208]
When I try to call function by clicking on "<a" tag element I get an error:"run is not a function", but whenI'm clicking on button - all work fine
```javascript
            <div class="row  au-stagger">
                <div class="col-sm-" repeat.for="user of userList">
                   <a href="#" click.delegate="run()"> <div class="card" >
                        
                        <div class="avatar">
                            <img src.bind="user.userImage" crossorigin ref="image" />
                        </div>
                        <div class="content">
                            <p class="name">${user.username}</p>
                            
                        </div>
                    </div></a>
                </div>
            </div> <button click.delegate="run()"> Save</button>

**Comment by EisenbergEffect** [comment]
This is likely because `run` is on the parent model. In the current version you would need to access that with `$parent.run()` instead. However, in the next release the code, as you have it, will work.

**Comment by nomack84** [comment]
@EisenbergEffect so in the beta finally the $parent won't be needed inside the repeat.for directive? That's awesome.

**Comment by EisenbergEffect** [comment]
Yes :) We just got all the pieces merged into master today.
