### ISSUE TITLE
How to unsubsribe() from observerLocator.getObserver().subscribe()

### ISSUE THREAD

**Issue by sylvain-hamel** [aurelia/binding#211]
The [docs page](http://aurelia.io/docs.html) says

> Note: Keep in mind that by forcing refreshes, Aurelia has to rebuild the complete VM. As for 
> performance reasons a simple observer on the router.currentInstruction might be sufficient for 
> scenarios where you'd simply like to exchange some data.

Before the mid October release, the code to do that was:

```
  activate(params) {
    this.unsubscribe = this.observerLocator
        .getObserver(this.router, 'currentInstruction')
        .subscribe((i) => { // DO YOUR THING });
  }

  deactivate() {
    this.unsubscribe()
  }
```

Now, `subscribe` no longer returns a function to unsubscribe. I found this to be the new way to do it:

```
  constructor(...) {
    // use bind because we pass the function to subscribe()
    // and we need `this` to be bound properly
    this.currentInstructionChanged = this.currentInstructionChanged.bind(this);
  }

  activate(params) {
    // watch for changes to the `q=18267` in route
    this.currentInstructionObserver= this.observerLocator
        .getObserver(this.router, 'currentInstruction')
        .subscribe(this.currentInstructionChanged);
  }

  deactivate() {
    this.observerLocator.getObserver(this.router, 'currentInstruction').unsubscribe(this.currentInstructionChanged);
  }

  currentInstructionChanged(currentInstruction){
      // DO YOUR THING
  }

```

Is this the new and correct way to subscribe/unsubscribe or is this an unintended API change?

**Comment by EisenbergEffect** [comment]
The ObserverLocator is a very low level mechanism for observing properties on objects. We made some changes to the API in order to improve performance and memory consumption. The way you are using the API now is correct. However, you might prefer to use the BindingEngine class instead since it provides a higher level API for subscriptions.

**Comment by sylvain-hamel** [comment]
@EisenbergEffect thanks! Here the updated code using bindingEngine.


```
  import {bindingEngine} from 'aurelia-binding';
  ...

  activate(params) {
    this.currentInstructionSubscription = bindingEngine
      .propertyObserver(this.router, 'currentInstruction')
      .subscribe((i)=>{ // DO YOUR THING  });
  }

  deactivate() {
    this.currentInstructionSubscription.dispose();
  }
```

**Tip:** Don't try to get `BindingEngine` injected. That won't work you have to use the global `bindingEngine` instance.

**Comment by EisenbergEffect** [comment]
Yes...although...in the next release you will need to get BindingEngine injected. In the current release, we made a singleton object. However, very shortly thereafter, we thought better of that and switched it to a class. So, you will need to update this code when we release the beta. There should be a reminder in the release notes when the time comes.

**Comment by sylvain-hamel** [comment]
@EisenbergEffect that will be a good change. Thanks
