### ISSUE TITLE
Insert element and/or set class no more than once inside repeat.for

### ISSUE THREAD

**Issue by glen-84** [aurelia/binding#212]
I have an array of objects which include dates, and I need to "mark" the row just above or below the current date.

Here are some of the options:

1. Calculate the correct position/offset each time that the data changes, and bind to that offset inside the `repeat.for`. This should work, but we want to use a value converter to filter the data, which means that we wouldn't be able to keep track of what is being rendered (AFAIK?).

2. Run code after the `repeat.for` completes and manually mark the row. (I don't think that there is an event for this? [see [here](https://github.com/aurelia/binding/issues/132)]).

3. Somehow track state within the `repeat.for` to limit the marking to a single row.

What would be the best way to do this?

**Comment by stoffeastrom** [comment]
@glen-84 

1. Can a flag be supplied when getting the data that marks the current date?
2. If not can you filter the array and for the current date add a flag?

Then you could add a tag that represent the row marker if that flag is set. This way you don't have to read position/offset the whole time which could be slow depending on your `repeat.for`

Does that make sense? I hope I understood your question.

**Comment by glen-84** [comment]
@stoffeastrom,

You made me think, and I realized that I can add the flag inside of a value converter, so I should be able to do something like this:

```html
<tr repeat.for="match of matches | filter:matchFilter | markNearestDate">
```

The term "value converter" is a bit of a stretch here, but this should work.

Thanks!

(I'll leave this open for a few days, just in case there are cleaner alternatives. I still think that #132 could be useful in certain scenarios.)

**Comment by EisenbergEffect** [comment]
Not sure I clearly understand...but if you want to visually highlight a row based on data, I would probably use a class binding. You could also create a custom attribute that was bound to the date and compared that to the current date, then affected the element based on that.

**Comment by glen-84** [comment]
A class binding (if it is what I think it is), wouldn't work, because I only want it to apply once (to the first row with a date greater than now).

A custom attribute may work, but it's a bit messy because I need to do two things – mark the row with a class, and insert an element into one of its TDs. I don't know if both could be done inside the custom attribute on the row.

**Comment by glen-84** [comment]
@EisenbergEffect,

Could you please re-open this? I'm not happy with the initial solution (which was a bit of a hack).

Let me show a more concrete (and simple) example:

Given the following data:

```
data = [1, 2, 3, 4];
```

I display it in my template:

```
<ul>
    <li repeat.for="item of data">${item}</li>
</ul>
```

Now I want to "mark" the first element that is greater than 2 (`> 2`). "Marking" here means (a) Adding a class to the list item, and (b) Inserting an element into the list item.

If I do this:

```
<ul>
    <li repeat.for="item of data" class="${item > 2 ? 'marker' : ''}">
        ${item}
        <div if.bind="item > 2">marker</div>
    </li>
</ul>
```

... it'll mark all items greather than 2 (3, 4), but I only want the first one (3) marked.

How can I do this?

**Comment by EisenbergEffect** [comment]
Well, in your scenario, you would simply say item === 3. So, that is simple. For a date, why not just use a simple expression that says item > date && item < date?

**Comment by glen-84** [comment]
> Well, in your scenario, you would simply say item === 3. So, that is simple.

I was trying to simplify the issue, but my example wasn't ideal. Just imagine that there were two 3s in the list, and you only wanted to mark the first.

> For a date, why not just use a simple expression that says item > date && item < date?

You mean like a range? That will mark multiple items, especially if they have *exactly* the same date.

```js
let data = [
    { title: "Hello1", date: "2015-11-11 22:00" },
    { title: "Hello2", date: "2015-11-11 22:00" },
    { title: "Hello3", date: "2015-11-11 23:00" },
    { title: "Hello4", date: "2015-11-11 23:00" }
];
```

The current date is "2015-11-11 22:30". The row with "Hello3" should be marked, since it is the first row with a date greater than the current date. There is no way to single-out that specific row using a range or similar mechanism.

I need to be able to set a flag somewhere to indicate that the row has been marked, and then reset that flag each time the list is re-rendered.

**Comment by stoffeastrom** [comment]
Well, I guess you are responsible of fetching the data?

If the flag can't be supplied why not go through the data yourself and add it?

```
let marked = false;
for(let i = 0, ii = data.length; i < ii; ++i) {
  if(data[i].date > currentDate && !marked) {
    data[i].showMarker = true;
    marked = true;
  } else {
    data[i].showMarker = false;
  }
}
```

```
<ul>
    <li repeat.for="item of data">
        ${item}
        <div if.bind="ite.showMarker">marker</div>
    </li>
</ul>
```

Does this work for you?

**Comment by EisenbergEffect** [comment]
@stoffeastrom Exactly. That was my next suggestion. You beat me to it :)

**Comment by glen-84** [comment]
@stoffeastrom @EisenbergEffect,

Not once you pass the data to a value converter, which might hide some of the items. This needs to be done during the rendering process.

For example, if you have this value converter: `repeat.for="item of data | filter:dataFilter"`, it may hide (filter-out) the item that had the marker, so it would need to be set again based on the remaining items.

**Comment by EisenbergEffect** [comment]
You should avoid a value converter in this case then and filter the data yourself. If you control the data, this is an easy problem to solve.

**Comment by glen-84** [comment]
That doesn't seem like a great solution.

1. I can't solve the problem for data I don't "control" (apparently).
2. I can't use VCs at all. If I wanted to do sorting, paging, etc. with VCs I can't.

:disappointed:

**Comment by stoffeastrom** [comment]
@glen-84 

You can do this.

Use similar code to mark the row as I suggested above. As long as you don't remove items from the array you can do sorting, paging that won't affect the marked row, right?

**Comment by glen-84** [comment]
@stoffeastrom I have a text filter that removes items.

Doing the "marking" inside a custom VC was my initial solution, but it was a hack and I don't think that it solved the problem of the current date changing as time passes (i.e. moving the marker every second/minute).

**Comment by EisenbergEffect** [comment]
Have you read @jdanyow 's post on binding behaviors? You could use the signal behavior in conjunction with a custom function to determine if the current item should be marked. You can re-signal every X minutes or seconds. Read about it here: http://www.danyow.net/aurelia-binding-behaviors/

**Comment by glen-84** [comment]
@EisenbergEffect,

Yes, I did read that yesterday. I was trying to figure out if I could use it in some way, but I haven't thought of anything yet. Thanks.

I did come up with one solution (not using binding behaviours), but I'm not sure yet whether or not it's a good idea.

Basically, it looks something like this:

```html
<ul>
    <li repeat.for="item of data" class="${markItem(item, $index, time) ? 'marker' : ''}">
        ${item}
    </li>
</ul>
```

```js
  itemMarked = false;

  markItem(item, index, time) {
    if (index === 0) {
      // Reset flag at the beginning of each iteration.
      this.itemMarked = false;
    }

    if (!this.itemMarked && new Date(item.date) > time) {
      this.itemMarked = true;
      return true;
    }

    return false;
  }
```

Because it's bound to `time` (the changing current date), it gets called as time passes.

I'm not sure if this is too "weird" or not. Also it needs changes, because I have to call the method twice (once for a CSS class, and once to insert an element), so I need to keep track of that (or use two separate methods).

If you think of a cleaner/better way of doing this with or without binding behaviours, please let me know.

Thanks for your help.
