### ISSUE TITLE
Discussion: Object.observe is dropped

### ISSUE THREAD

**Issue by jods4** [aurelia/binding#213]
I'm sure you watch web standards probably even more closely than I do, but just in case.

It seems that `Object.observe` is dead:
https://esdiscuss.org/topic/an-update-on-object-observe
The information is also relayed on caniuse or bugzilla. Chrome has intent to remove apparently.

Not sure what the consequences for Aurelia are. The most obvious one is that O.o-based observers should be removed from the code base.

**Comment by EisenbergEffect** [comment]
Yep, we got it. This will basically just mean us removing some code. Not real negative affects here. Might even be able to make some new optimizations :)

**Comment by jods4** [comment]
Exactly. I was wondering to what extend some design decisions that were made to mimick O.o API surface could be revisited.

Like: would support for read detection be an interesting idea? E.g. to compute dependencies from opaque functions, expressions or properties. Everywhere seems not feasible, but maybe decorate some fields with `@autoWatch` (not a good name obviously) and then use a `@computedAuto` on properties? 

Just brainstorming here, not actually asking for features.
