### ISSUE TITLE
if.bind does not work after upgrade to framework 0.18

### ISSUE THREAD

**Issue by avizcaino** [aurelia/binding#215]
Hi,

I upgraded my aurelia project with the last release version and I'm having binding issues (for now, only in templates). In some cases, the if.bind is not working and changing it to show.bind solves the problem. But in other cases is not working at all... I checked the changes of the new release and found that binding engine has been improved.

Anyone else is having the same problem? If so, any clue on how to solve it?

Thanks!!

**Comment by EisenbergEffect** [comment]
We are going to need much more information in order to help you. Can your provide a simplest possible reproduction of the problem, preferrably something we can easily drop into the skeleton-navigation project to see the issue.

**Comment by jdanyow** [comment]
here's a plunker that uses the latest aurelia components:  http://plnkr.co/edit/DhmmYA?p=preview

If you can reproduce your issue using the plunker that would be extremely helpful

**Comment by avizcaino** [comment]
I'm trying to reproduce the exact example but it's a bit tricky since involves route navigation and updates in the binded objects... I tested an example in plunker but it seems is working fine so I guess is  a more elaborated problem...

**Comment by jdanyow** [comment]
ok, we released a bunch of fixes last night:  :point_up: [November 11, 2015 10:52 PM](https://gitter.im/Aurelia/Discuss?at=56440ce355ea302e50abbec4)
Perhaps one of those will help with your issue?

**Comment by avizcaino** [comment]
it seems the problem is related with #223 issue, but I updated with the last patches and the problem is persisting. I've been struggling with the problem and it seems that some routing is involved since the trigger of the problem is a compose inside a template of another route.

I have a table with routes to another view when a register is clicked. This second view changes the value of the binded properties (which is what i need) and also has a compose. When going back (route.navigateBack), the binded properties are reset in the first view (with its original values) but that compose of the second view is attached again (don't know why) and is the one that seems that is changing the values of the binded properties...

**Comment by avizcaino** [comment]
Ok, so I found the problem... It wasn't a binding issue but more of a memory-leak issue. I'll try to explain.

 I have the following view-structure:
```
table-view
detail-view
|_ custom-element (detail)
      |_ compose (header)
      |_ compose (table)
```
I can navigate from table-view to detail-view and back via routing. The problem is, when going back from detail to table, first it goes to the table-view activate and then to the activate of both composes in custom-element-detail are triggered. That was the problem since I was doing some operations with the model in the activates and I was assuming that the model was never empty. Since the activates are triggered in the first view, the models are empty and the app is crashing. I've solved the problem by performing the operations in the attached (since I'm controlling the attachment with if.bind checking the models are not empty).

It makes sense that the activates of composes in previous views are triggered when navigating back? I don't know if the problem is just ours or is something is already happening in aurelia and we are triggering unintencionally :S. Any clues?

I guess this issue can be moved to another repo, but don't know which ;)

Thanks for the help!!

**Comment by EisenbergEffect** [comment]
Basically, the `activate` for a view-model used with `compose` will get fired whenever the initial compose happens, the view-model changes or the model changes. When you navigate back, this causes the previous view to get created and bound. The act of binding that view triggers the `compose` to do its work, resulting in a call to `activate`.
