### ISSUE TITLE
Chained value converters can cause infinite loop (freeze)

### ISSUE THREAD

**Issue by spi-ap** [aurelia/binding#216]
Testing the PreBeta release I stumbled upon this. It totally freezes my chrome tab.
Just chained a filter and a sort value converter.

This should reproduce it: http://plnkr.co/edit/fFMsS1?p=preview

P.S.: Sorry if this is the wrong repo, I am not that deep into the internals yet.

**Comment by jdanyow** [comment]
Still looking into this.  Has to do with the sort value converter mutating the array with each toView call.  If you update the toView function to return `array.slice(0).reverse();` instead of `array.reverse();` you won't get stuck in the loop.

**Comment by jdanyow** [comment]
minimal repro:
```js
export class App {
  filter = '';
  items = ['a', 'b', 'c'];
}

export class FilterValueConverter {
  toView(array, filter) {
    if (filter.length) {
      return array.filter(x => x.startsWith(filter));
    }
    return array;
  }
}

export class ReverseValueConverter {
  toView(array) {
    return array.reverse();
  }
}
```
```html
<template>
  <label>Filter: <input ref="input"></label>
  <ul>
    <li repeat.for="item of items | filter:input.value | reverse">${item}</li>
  </ul>
</template>
```

**Comment by spi-ap** [comment]
Thanks a lot for the fast response!

I think there is still a performance penalty in here.
The infinite loop is fixed, but I had the impression that it is way slower than before the PreBeta.  I added the slice(0) just for test and it is indeed faster (not as fast I would have hoped though). This is in my app, I have no plunk for that (yet).

Any ideas?

**Comment by jdanyow** [comment]
how many items are in your array?  Can you elaborate on what the perf issue is?  I believe in your example you had a `throttle` or `debounce` binding behavior on your filter input- is that what is making it seem slower?  Because the array filtering is delayed?

**Comment by spi-ap** [comment]
Thanks to the explanations about the array mutations and the usage of slice(0) I think I can live with my current implementation. The difference in my app was only the aurelia packages, the debounce was there before (own implementation, still is. Didn't convert to aurelia debounce there yet).

The performance difference between aurelia-mid-october and pre-beta were around 3 seconds for ~350 array items without any code changes. As in 3 instead of 0.x seconds. With slice(0) I would have to measure if there is even a real difference.. it "feels" slower.
