### ISSUE TITLE
Suggestion: a means to re-use the implementation of a custom-attrib on a custom-element.

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/binding#218]
Aurelia presently has custom elements and it has custom-attributes, that can be applied to any HTML element. But custom-attributes are currently or effectively "fixed" in terms of their names.

Often you want "composeability" when building a custom element, including potentially adding special attributes to a custom element that might special behaviours.

Whilst not a great example, you might have a custom-attribute which takes its value (assuming a string) and breaks it up into an array of substrings based on a separator.

In a sense, therefore, it is an extension of "bindable" to declare an attribute and to have a custom-attribute "view model" associated with it. Something perhaps like:

@bindable( { name: "myProperty", attribute: "names", customAttribute: NameCollectionAttribute } );

The implication is that myProperty ends up of type NameCollectionAtttribute, and is used within *this* custom element using the name "names".

**Comment by EisenbergEffect** [comment]
Is this close to what you want? https://github.com/aurelia/templating/issues/96

**Comment by kevmeister68** [comment]
I think it's fair to say that letting a bindable have a type-converter is a specific case of letting a bindable property behave as an object.

I mean, when you choose to go to the trouble of writing a *custom attribute* using Aurelia, what is the purpose of that construct? Clearly you want more than a piece of data attached to a HTML element, you want a backing object (a ViewModel) that has presumably some associated behaviour.

So how do you get those features of a custom attribute onto one of the attributes of a custom element? This was really what my suggestion was about, and data conversion was the example that came to mind.

I don't have a specific use-case I can give you unfortunately, since it was a generic idea that popped up after reading docs on custom elements and custom attributes.

**Comment by EisenbergEffect** [comment]
I'd like to leave this open for future consideration. I don't think it's going to make it in v1, but there's always 1.1, 1.2, etc. We can evaluate priorities as community use cases arise.

You may want to look into surrogate behaviors. I'm not sure if we have this in the docs yet ;( But we do mention it in a few blog posts. It lets you place custom attributes in your view, on the template element itself. These custom attributes get transferred to the actual custom element tag at runtime, but their binding context is still against the element's own view model. I think it would let you accomplish something similar to what you are describing.

**Comment by EisenbergEffect** [comment]
We enable this through surrogate behaviors.
