### ISSUE TITLE
Suggestion: Ability to bind to the View Model object, not a property of it.

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/binding#219]
Occasionally you need to specify a bind expression that references the entirety of the view-model itself, and not one of its properties.

At present you need to workaround by either having a "self" kind of property and referring to that (initialised in the View Model constructor), or doing a similar thing with view-model.ref.

Be nice to simply have a well defined name like $this or $self or $viewmodel to take care of this binding circumstance.

**Comment by jdanyow** [comment]
This week's release has the ability to bind to `$this`!
