### ISSUE TITLE
Suggestion: Ability for binding expressions to be parsed literally as JSON, into an object.

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/binding#220]
I'm not sure how this would work in a "chained" fashion, but the original idea comes from basically being able to do something like this:

<my-custom-element some-object.bind="{ prop1: value1, prop2, value2, prop3: value3 }">

It is kind of like a corollary do being able to do this literally and declaratively for a simple string attribute:

<my-custom-element some-property="fred">

It is not unusual to use Aurelia custom elements to wrap fairly complex UI widgets (jQuery-UI, kendo, etc), and at least one area the above syntax might be helpful is in configuration.

I realise there is potentially some overlap between this and my suggestion to have re-usable, composable custom definable on a custom element.

**Comment by jdanyow** [comment]
this is possible, check out this plunker:  http://plnkr.co/edit/eNafhyusJ6Uz6BNCIHWT?p=preview

```js
// some data to use in our object literal
export class App {
  foo = 'bar';
  one = 1;
  date = new Date();
}

// used in the view to demonstrate that binding expressions can contain
// object literals:
export class StringifyValueConverter {
  toView(obj) {
    return JSON.stringify(obj, null, 2);
  }
}
```

```html
<template>
  <!-- an object literal expression is bound to the div's "test" property:  -->
  <div ref="myDiv" test.bind="{ x: foo, y: one, z: date }"></div>
  
  <!-- display the div's "test" property -->
  <pre><code>${myDiv.test| stringify}</code></pre>
</template>
```
