### ISSUE TITLE
Uncaught TypeError: Cannot read property 'overrideContext' of null in Listener

### ISSUE THREAD

**Issue by reinholdk** [aurelia/binding#221]
Hi,

this occurs after upgrading to pre-beta release.

When the delegate synchronously unbinds the source element, e.g. in a context menu that should disappear when the menu item is clicked a TypeError occurs in listener-expression.js line 40

delete this.source.overrideContext.$event;

I can workaround by closing the menu asynchronously but you may want to fix this.

Regards
-- Reinhold

**Comment by EisenbergEffect** [comment]
@jdanyow Do you have time to take a look at this?
