### ISSUE TITLE
Nesting if.bind breaks enclosed binding

### ISSUE THREAD

**Issue by asemahle** [aurelia/binding#223]
There seems to be a problem with nesting `if.bind`. Consider the following view snippet:
```html
<div if.bind="foo">
    <div if.bind="bar">
        ${baz}
    </div>
</div>
```
Currently, if `foo` is set to a falsy value, then the binding on `baz` will break.

[Here is a Plunker](http://plnkr.co/edit/qJgAdl?p=preview) that demonstrates the problem.

Maybe this is related to aurelia/binding#215?

**Comment by EisenbergEffect** [comment]
@jdanyow Do you have time to look at this?

**Comment by jdanyow** [comment]
yep
