### ISSUE TITLE
Bindable variables do not bind unless variable name is lowercase

### ISSUE THREAD

**Issue by asemahle** [aurelia/binding#224]
Bindable variables do not bind unless the variable name is lowercase. Consider the following model (`custom-element.js`):
```javascript
import {bindable} from "aurelia-framework";

export class CustomElement{
  @bindable someVariableName: any = null;
}
```
Currently binding a value to `someVariableName` from a view does not work. No error is raised, the variable simply is not bound to value. Though, if the variable name is all lowercase (`@bindable somevariablename: any = null;`) then binding works as expected.

I suspect this is because attribute names are automatically converted to lower case by the browser (at least in chrome) meaning that this:
```html
<custom-element someVariableName.bind="Value"></custom-element>
```
gets converted to this:
```html
<custom-element somevariablename.bind="Value"></custom-element>
```
Though I think binding to camelCased variables worked in a previous version of Aurelia.

[Here is a Plunker](http://plnkr.co/edit/su0bEY?p=preview) demonstrating the behaviour.

**Comment by EisenbergEffect** [comment]
Yes, it's because of the browser. However, if you have camel-cased variables, Aurelia will turn those into hyphenated attributes.
