### ISSUE TITLE
Resharper syntax validation for HTML attributes with dot?

### ISSUE THREAD

**Issue by diegohb** [aurelia/binding#225]
Using code like example below, I get the red squigglies in VS2013 and VS2015. I'm not sure if it's Resharper 10 or VS but I was wondering if there was a way to ignore or teach it to learn that syntax? 

Also curious if that is valid HTML5 or an aurelia-specific implementation ?

Thanks!

**Comment by EisenbergEffect** [comment]
I would recommend installing the Web Essentials for VS 2015. I believe that a number of months ago Mads actually implemented intellisense for the Aurelia binding syntax.

**Comment by diegohb** [comment]
Thanks! you're fast... i was just editing this comment to the following..  I actually do have WebEssentials installed.. 


'''
Curious about the attributes like "bind.for" - Is it valid HTML5 or an aurelia-specific implementation?

Resharper is not validating some of the html and none of the attributes with dots. Also, none of the Javascript is validating even though I changed the javascript level from Automatic to ECMAScript6 in the Inspections settings.

Any guidance, plugins, or known list of unsupported IDE and/or Resharper features ?

Thanks!
'''

**Comment by diegohb** [comment]
Looks like you're correct... https://webessentials.uservoice.com/forums/140520-general/suggestions/7154356-add-aurelia-support

I'll post back if I can figure out how to have Resharper and WebEssentials play nice.

**Comment by EisenbergEffect** [comment]
Yes, it's valid html, svg and xml. It's just not something that is used very often. So, we adopted that convention to represent our binding language.

Regarding the best VS setup, I would ask in our gitter channel and see what responses you get there.

**Comment by ristaloff** [comment]
This has been fixed in Resharper version 10.0.2.
Resharper issue: https://youtrack.jetbrains.com/issue/RSRP-445006

**Comment by ristaloff** [comment]
This has just been fixed and will probably be available in Resharper 10.1.
https://youtrack.jetbrains.com/issue/RSRP-445006
