### ISSUE TITLE
repeat.for error for expr type [object.array]

### ISSUE THREAD

**Issue by xiwc** [aurelia/binding#228]
### eg: 
```
<a class="item" repeat.for="item of projects.projectInfoList" if.bind="!item.isSelected" href="#/project/${item.projectId}" jquery.popup="content.bind:item.projectName; variation:inverted; position:right center; on.bind:item.onTrigger">
```

**Comment by xiwc** [comment]
Error console log:
![image](https://cloud.githubusercontent.com/assets/8816203/11149024/4e175e60-8a5b-11e5-872f-3a26cbf56537.png)

**Comment by EisenbergEffect** [comment]
Are you running the absolute latest versions? We had a bunch of patch fixes on repeat and if over the last day or so. Please run `jspm update` and double check it to see if it's fixed.

**Comment by xiwc** [comment]
### My config:

    "aurelia-binding": "github:aurelia/binding@0.11.3",
    "aurelia-bootstrapper": "github:aurelia/bootstrapper@0.19.0",
    "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.12.1",
    "aurelia-event-aggregator": "github:aurelia/event-aggregator@0.10.0",
    "aurelia-framework": "github:aurelia/framework@0.18.0",
    "aurelia-history": "github:aurelia/history@0.9.0",
    "aurelia-history-browser": "github:aurelia/history-browser@0.10.0",
    "aurelia-i18next": "github:aurelia/i18n@0.3.0",
    "aurelia-loader": "github:aurelia/loader@0.11.0",
    "aurelia-loader-default": "github:aurelia/loader-default@0.12.0",
    "aurelia-logging": "github:aurelia/logging@0.9.0",
    "aurelia-metadata": "github:aurelia/metadata@0.10.1",
    "aurelia-pal": "github:aurelia/pal@0.3.0",
    "aurelia-pal-browser": "github:aurelia/pal-browser@0.3.0",
    "aurelia-path": "github:aurelia/path@0.11.0",
    "aurelia-route-recognizer": "github:aurelia/route-recognizer@0.9.0",
    "aurelia-router": "github:aurelia/router@0.14.0",
    "aurelia-task-queue": "github:aurelia/task-queue@0.9.0",
    "aurelia-templating": "github:aurelia/templating@0.17.4",
    "aurelia-templating-binding": "github:aurelia/templating-binding@0.17.0",
    "aurelia-templating-resources": "github:aurelia/templating-resources@0.17.3",
    "aurelia-templating-router": "github:aurelia/templating-router@0.18.0",

**Comment by EisenbergEffect** [comment]
@jdanyow @martingust Any time to take a look at this?

**Comment by martingust** [comment]
@xiwc What is `projects.projectInfoList`?

**Comment by xiwc** [comment]
object.array type var

**Comment by martingust** [comment]
@xiwc I'm not able to reproduce. Please see this plunk: http://plnkr.co/edit/dUHCcJdPOoMgnnv4X0xB?p=preview

Are you doing anything differently?

**Comment by xiwc** [comment]
I validated in `aurelia.skeleton `, i worked fine.
![image](https://cloud.githubusercontent.com/assets/8816203/11173776/8a53f6a8-8c55-11e5-9df4-029b006720ac.png)
![image](https://cloud.githubusercontent.com/assets/8816203/11173782/969c27f0-8c55-11e5-85de-e14869ca2de9.png)
![image](https://cloud.githubusercontent.com/assets/8816203/11173789/a69e998a-8c55-11e5-9690-55b46c9095c4.png)

**Comment by xiwc** [comment]
But,  my own project.
![image](https://cloud.githubusercontent.com/assets/8816203/11173824/08bb50d6-8c56-11e5-8416-98075ef579a6.png)
![image](https://cloud.githubusercontent.com/assets/8816203/11173827/1a6ef8fa-8c56-11e5-8671-935f63e9b455.png)

**Comment by xiwc** [comment]
3ks, I will check my code again, 
if still not work, i will wait for next version aurelia then check again.

**Comment by jdanyow** [comment]
I'm not able to reproduce in beta-1:  http://plnkr.co/edit/V3RtBn?p=preview

@xiwc if you're still hitting this issue please re-open with a repro using the [aurelia plunker](http://bit.ly/aurelia-plunker)
