### ISSUE TITLE
ObserverLocator assumes OoPropertyObserver when getObserver is called for an undefined property

### ISSUE THREAD

**Issue by jdanyow** [aurelia/binding#23]
When getObserver is called for an undefined property an instance of OoPropertyObserver is returned.

When the property later becomes defined and is not a primitive property (has a getter/setter), the incorrect observer type has already been returned to the templating system so property change events cannot be observed.

I'm thinking we should return an instance of a new class: `UndefinedPropertyObserver`.  This new class would listen for the property to become defined using Object.observe.  When this happens it would do the following:

1. call ObserverLocator.getObserver to retrieve the correct "actual" observer.
2. delegate the subscribe, getValue and setValue methods to the "actual" observer.
3. funnel any existing callbacks into the "actual" observer via it's subscribe method.

*note:*   `UndefinedPropertyObserver`'s setValue method would need to have special handling to ensure the appropriate observer is created and change events are published.

**Edit**
specifically talking about cases where Object.getOwnPropertyDescriptor returns `undefined`.  (As opposed to cases where it returns `{value: undefined, writable: true, enumerable: true, configurable: true}`)

**Comment by EisenbergEffect** [comment]
How should we handle this if Object.observe is not present?

**Comment by jdanyow** [comment]
I think that would continue to fall through to `SetterObserver`
