### ISSUE TITLE
Strange issue with ternary operator

### ISSUE THREAD

**Issue by glen-84** [aurelia/binding#231]
If I do:

```html
<ul repeat.for="item of items" class="${log('hello')}">
```

The function `log` is invoked once per item. But if I do:

```html
<ul repeat.for="item of items" class="${log('hello') ? 'yes' : 'no'}">
```

The function is invoked twice per item.

Is this a bug or am I doing something that I'm not supposed to be doing. :P

**Comment by jdanyow** [comment]
neither- the binding system sometimes needs to evaluation expressions twice. In this case it evaluates the condition part of the expression to determine which parts of whole the expression to observe, later it evaluates the whole expression when assigning the elements class property.

Use `class="${log('hello') ? 'yes' : 'no' & oneTime}">` or `class.one-time="log('hello') ? 'yes' : 'no'">` to avoid this.

**Comment by glen-84** [comment]
Umm. Okay. Thanks.
