### ISSUE TITLE
Binding doesn't work for colspan.bind in Edge

### ISSUE THREAD

**Issue by jeremy-holt** [aurelia/binding#235]
```
 <td colspan.bind="item.finishedDryingDate ? 0 : 15"></td>
```
works fine in Chrome and FF, however it breaks in Edge.

It seems to be making `colspan` camel case to `colSpan`.

This happens at line 3312 in aurelia-binding (compiled version) where `this.propertyName = colSpan`

```
    DirtyCheckProperty.prototype.setValue = function setValue(newValue) {
      this.obj[this.propertyName] = newValue;
    };
```

**Comment by jdanyow** [comment]
`colSpan` (camel case) is correct:

**chrome**
![colspan](http://i.imgur.com/8DfNgdj.png)

**edge**
![colspan](http://i.imgur.com/JerKjo4.png)

Maybe Edge has an issue where it's not obeying the `colSpan` value when it's assigned dynamically?

**Comment by jeremy-holt** [comment]
Perhaps it could throw a more informative error?

**Comment by jdanyow** [comment]
I can't reproduce this.  Here's a working colSpan binding demo.  Works in chrome and edge:  http://plnkr.co/edit/gZ86zV?p=preview

Please re-open if you're still hitting this issue.
