### ISSUE TITLE
ref of the custom element in included view, undefined in the main view

### ISSUE THREAD

**Issue by bsrdjan** [aurelia/binding#236]
The main View is including the view with the custom element:
```html
<template>
  <require from="./header.html"></require>
  <header></header>
</template>
```

```html
<!-- header.html -->
<template>
  <custel custel.ref="ref1"></custel>
</template>
```
The model of the main View is not getting the ref1 reference, is undefined. I tried
`<custel custel.ref="$this.ref1"></custel>` (use Beta), did not help. Could it be a bug ?

**Comment by bsrdjan** [comment]
The view ia correctly included, the <header></header> is missing only in my message.

**Comment by jdanyow** [comment]
It's not a bug.  Refs in the header custom element template (header.html) will be created on the header custom element's view-model (header.js), not on the outer view model.

**Comment by bsrdjan** [comment]
There is no header.js,  the header.html does not have own model and all other custom elements from the header.html are properly binded to the outer view model. Could this addition in header help <template bindable="outer"> ?

**Comment by jdanyow** [comment]
If i'm not mistaken, html-only custom elements such as your header.html element get a view-model instance that's created on the fly, which is what the ref is being assigned to.  If you switch to this:

```html
<template>
  <require from="./header.html"></require>
  <header></header>
</template>
```
to this:
```html
<template>
  <compose view="./header.html"></compose>
</template>
```


Basically a ref can't be pushed through a custom-element boundary.

**Comment by bsrdjan** [comment]
yes, it is visible, not in `attached()`, but later. thanks!
