### ISSUE TITLE
BindingEngine injected as undefined

### ISSUE THREAD

**Issue by andrevlins** [aurelia/binding#238]
In the code bellow `bindingEngine` is **undefined**.

I'm doing something wrong or it's a bug?

I'm using latest aurelia bits.

```javascript
import {inject} from ‘aurelia-framework’;
import {BindingEngine} from ‘aurelia-binding’;

@inject(BindingEngine)
export class MyClass {
   constructor(bindingEngine) {
            this.observer = bindingEngine.propertyObserver(this.foo, ‘x’);
   }
}
```

**Comment by jdanyow** [comment]
hmm strange- seems to be working on the plunker:  http://plnkr.co/edit/T1WjaU?p=preview

What does `jspm inspect --forks` say?

**Comment by andrevlins** [comment]
@jdanyow I figured out the problem... it's not related to `inject` and it's not a bug, sorry.

The question is that I'm using `compose` with a class created by a factory and that factory creates the instance of `MyClass` so, the DI is not used.

How to make a factory, or better, how to load a module dynamically in a way that DI injected constructor is respected? should I use `aurelia-default-loader`?

**Comment by andrevlins** [comment]
I solved the problem with the factory bellow, but I want to know if there's a way to do this in a way that I can create more `xInput type` without `InputFactory` need to import that new `type`.

```javascript
import {inject, Aurelia} from 'aurelia-framework';
import {MemoInput} from 'res2/fields/memo/memo-input';
import {QpdInput} from 'res2/fields/qpd/qpd-input';
import {PioInput} from 'res2/fields/pio/pio-input';
import {CidInput} from 'res2/fields/cid/cid-input';

@inject(Aurelia)
export class InputFactory {
	constructor(aurelia) {
		this.container = aurelia.container;
		this.container.autoRegisterAll([MemoInput, QpdInput, PioInput, CidInput]);
	}

	create(fieldType) {
		switch (fieldType.toLowerCase()) {
			case 'memo':
				return this.container.get(MemoInput);
			case 'qpd':
				return this.container.get(QpdInput);
			case 'pio':
				return this.container.get(PioInput);
			case 'cid':
				return this.container.get(CidInput);
			default:
				throw new Error('cannot found input for filedType: ' + fieldType + '.');
		}
	}
}
```

**Comment by jdanyow** [comment]
Would `container.registerTransient('memo', MemoInput)` work for your use case?

Then you could do `container.get('memo')` or `@inject('memo')`.

**Comment by andrevlins** [comment]
:+1: 

thanks!

**Comment by maodean** [comment]
import $ from 'jquery';
import moment from 'moment';
import {bindable, inject, BindingEngine} from 'aurelia-framework';
import {HttpClient} from 'aurelia-fetch-client';

@inject(HttpClient, BindingEngine)
export class Rules {
    
    constructor(bindingEngine) {
        this.rules = {      
        ObsRanges: [
            { id: 1, low:1.0, high:1.99 },
            { id: 2, lowd:8.0, high:8.99 },
            { id: 3, low:3.0, high:3.99 },
            { id: 4, low:9.0, high:9.99 },
            { id: 5, low:5.0, high:5.99 }]
        };  

        let subscription = bindingEngine.propertyObserver(this.rules, 'ObsRanges').subscribe((newValue, oldValue) => this.objectValueChanged(newValue, oldValue));
    }

    objectValueChanged(newValue, oldValue) {
        console.log(`observeMe value changed from: ${oldValue} to:${newValue}`);
    }
}

Sorry, new to Aurelia. why I get following error:


RROR [app-router] Error: Error invoking Rules. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: bindingEngine.propertyObserver is not a function
Inner Error Stack:
TypeError: bindingEngine.propertyObserver is not a function
    at new BetRules (http://localhost:9000/scripts/app-bundle.js:129:40)
    at Object.invoke (http://localhost:9000/scripts/vendor-bundle.js:12057:14)
    at InvocationHandler.invoke (http://localhost:9000/scripts/vendor-bundle.js:12022:168)
    at Container.invoke (http://localhost:9000/scripts/vendor-bundle.js:12286:25)
    at StrategyResolver.get (http://localhost:9000/scripts/vendor-bundle.js:11739:37)
    at Container.get (http://localhost:9000/scripts/vendor-bundle.js:12225:23)
    at http://localhost:9000/scripts/vendor-bundle.js:23128:73
    at tryCatcher (http://localhost:9000/scripts/vendor-bundle.js:3411:23)
    at Promise._settlePromiseFromHandler (http://localhost:9000/scripts/vendor-bundle.js:2627:31)
    at Promise._settlePromise (http://localhost:9000/scripts/vendor-bundle.js:2684:18)
    at Promise._settlePromise0 (http://localhost:9000/scripts/vendor-bundle.js:2729:10)
    at Promise._settlePromises (http://localhost:9000/scripts/vendor-bundle.js:2808:18)
    at http://localhost:9000/scripts/vendor-bundle.js:153:25
End Inner Error Stack
