### ISSUE TITLE
repeat.fors over Maps don't update on element change

### ISSUE THREAD

**Issue by duke9509** [aurelia/binding#239]
Repro:
http://plnkr.co/edit/MqKNE4QdjMO5lAkJCoqN?p=preview

If you have a `Map` over which you do a `repeat.for`, changes to the contents of the `Map` do not appear in the repeat.

The repeat can be forced to refresh by wrapping it in a container with an `if.bind` and toggling the condition off and on (with a 0ms timeout).

**Comment by martingust** [comment]
Fixed in https://github.com/aurelia/templating-resources/commit/7f245ce3b490fa82cae20103281b665a07cf3eb2.
