### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by valichek** [aurelia/binding#240]
After updating to beta-1 I got in Chrome
```
Uncaught TypeError: Cannot read property 'dispose' of undefined
unbind @ t.js:102
unbind @ aurelia-templating.js:2767
unbind @ aurelia-templating.js:883
unbind @ if.js:68
unbind @ aurelia-templating.js:2767
unbind @ aurelia-templating.js:883
unbind @ aurelia-templating.js:2763
unbind @ aurelia-templating.js:883
(anonymous function) @ if.js:40
flushMicroTaskQueue @ aurelia-task-queue.js:110
(anonymous function) @ aurelia-task-queue.js:60
```

In Firefox I have `TypeError: this.subscription is undefined`

The error occurs when changing `merchantState.selector`
```html
// somewhere in app-subcomponent.html
<span if.bind="merchantState.selector != 'single'" data-toggle="dropdown" href="#" class="dropdown-toggle" style="cursor: pointer;">
     <span if.bind="merchantState.merchant">${merchantState.merchant.user.companyname</span>
     <span show.bind="!merchantState.merchant" t="merchant-selector.undefined"></span>
</span>
```
I change `merchantState.selector` during navigation in auth step, and app-subcomponent is removed at that moment with if.bind="..." from the DOM.

**Comment by valichek** [comment]
@zewa666 Looks like from i18n?

**Comment by zewa666** [comment]
yeah could be @valichek. May I ask you to create a fiddle so I can debug that code easier?

**Comment by valichek** [comment]
@zewa666 would be nice to have some configured plunkr/fiddle template with i18n, it is not easy just to extract code from my app because of complexity.

**Comment by valichek** [comment]
Just got some idea to override the problem. That html works with no  error.
```html
<span if.bind="merchantState.selector != 'single'" data-toggle="dropdown" href="#" class="dropdown-toggle" style="cursor: pointer;">
     <span if.bind="merchantState.merchant">${merchantState.merchant.user.companyname}</span>
     <template show.bind="!merchantState.merchant">
         <span t="merchant-selector.undefined"></span>
     </template>
</span>
```

**Comment by zewa666** [comment]
oh ok so its more a timing issue since it seems that show is removing the element before t can work with it. Could you try to change the order of the attributes, so `t` before `show`?

**Comment by valichek** [comment]
@zewa666 tried
```html
<span t="merchant-selector.undefined" show.bind="!merchantState.merchant"></span>
```
but error is still there

**Comment by zewa666** [comment]
ok thanks for checking, will take a look asap
