### ISSUE TITLE
Error: Parser Error: Multiple expressions are not allowed error

### ISSUE THREAD

**Issue by damianof** [aurelia/binding#243]
I have this binding 

change.trigger="$parent.sourceEnabledChanged(source) 

and getting this error, after upgrading to aurelia 1.0.0 beta 1: 

ERROR [app-router] Error: Parser Error: Multiple expressions are not allowed. at the end of the expression [$parent.sourceScrapeChanged(source);](…)

**Comment by jdanyow** [comment]
make sure there's no trailing semicolon in your binding expression.  It should look like this:

```html
<foo change.trigger="$parent.sourceEnabledChanged(source)"></foo>
```

If you'd like, you can remove `$parent.` from he expression, it's no longer required in the latest version of Aurelia.

**Comment by damianof** [comment]
It seems the ; is the problem.
