### ISSUE TITLE
Map<any,any> definition missing from aurelia-binding.d.ts

### ISSUE THREAD

**Issue by MaartenThomassen** [aurelia/binding#244]
I recently upgraded to the aurelia beta 1 pacakges and migrated my typscript definiations from the ones found here: https://github.com/cmichaelgraham/aurelia-typescript (which we where using up untill yesterday) to the ones provided by aurelia itself in the NPM packages.

Most of the upgrade went off without any problems, however, in the file aurelia-binding.d.ts on lines 

```329: getMapObserver(map: Map<any, any>): InternalCollectionObserver;```

and

``351: collectionObserver(collection: Array<any> | Map<any, any>): CollectionObserver;```

The type Map<any, any> is used. However, Visual Studio is telling it "Cannont find name 'Map'. I browsed the aurelia repositories (the binding and the ones it depends on) and I can't find the Map type anywhere. Am I missing something?

I'm using typescript 1.6.3.0.

Regards,
Maarten

**Comment by fopsdev** [comment]
Hi Maarten

Maybe this SO post can help you:
http://stackoverflow.com/questions/30019542/es6-map-in-typescript

as i understood it ts uses an es6.d.ts internally but ouput type needs to be ES6

**Comment by MaartenThomassen** [comment]
Thanks for the post fopsdev. So its a typescript issue then, wierd the .d.ts contains the definition then if the type doesn't exist in typescript.

For now i added ``` export interface Map<T1,T2>{}``` to aurelia's .d.ts file myself so that it compiles propertly. I don't need the type in my own code anyway, but i thought there might be a better solution, perhaps adding a Map definition to the Aurelia .d.ts definitions for the time being?

**Comment by MaartenThomassen** [comment]
This is still bugging us in development btw. Adding the export to the typing file only helps myself. As soon as a team member pulls the repo and executes ```jspm install``` to restore the pacakges on his/her side, the added export isnt present anymore. 

Would it be an option for me to add it to the .d.ts file manually and make a pull request, or are the .d.ts files generated by a tool you use?

**Comment by EisenbergEffect** [comment]
The binding library has manually created d.ts files now, rather than generated. So, you can make a PR to the d.ts to fix the issue and we can get it out in the next release.

**Comment by StrahilKazlachev** [comment]
Isn't this matter of typescript configuration? I use the lib.es6.d.ts and I don't have that problem.

**Comment by MaartenThomassen** [comment]
I'm working with Visual Studio which also references this file, so it should work then, but I'll check it to be sure. Thanks!

**Comment by MaartenThomassen** [comment]
It does work when i have set my Typescript project to compile to ES6, however, we've set our project to compile to ES5 and configured jspm to use Typescript (instead of Babel/Traceur).

So the solution here would be to set typescript project to ES6 and transpile output back to ES5 then?

**Comment by MaartenThomassen** [comment]
Sorry for the tripple post. I double checked my config and just now noticed we're using es6-promise from DefinitelyTyped for promise definition for ES5 (which i noticed by setting Typescript version to compile to ES6 after which Visual Studio complained to me about double definitions of Promise, which led me to look a bit deeper), there is also an es6-shim definitions file there which defines not only the Promise type but also the Map type.

I've solved this by grabbing the es6-shim package from NuGet and included it in my project. Thanks for the assist.

**Comment by StrahilKazlachev** [comment]
My concern is that the Map interface is present if the target is ES6 and problem can be solved by including additional .d.ts file with the Map definition. But you can not remove the definition from the aurelia-binding.d.ts if necessary.

**Comment by MaartenThomassen** [comment]
@StrahilKazlachev you are right, adding it to Aurelia is not a good idea. I fixed my issue as described above, so if anyone else has this problem i hope they'll find this topic.
