### ISSUE TITLE
Can't set bound object null

### ISSUE THREAD

**Issue by davismj** [aurelia/binding#248]
I have a basic master/detail view: A master list where you can select a user to open the user details, and a detail panel where you can edit the user details.

However, once bound, setting the user to null is immediately reverted by Aurelia. Here's the code:

```javascript
export default class UserViewModel {
  users;
  user;

  constructor() {
    this.user = null;
    this.users = [{ name: 'user1' }];
  }

  select(user) {
    this.user = user;
  }

  deselect() {
    this.user = null;
  }
}
```

```html
 <div>
    <table>
      <tr repeat.for="user of users" click.delegate="select(user)">
        <td>${user.name}</td>
      </tr>
    </table>
  </div>
  <div>
    <form reset.delegate="deselect()">
        <input type="text" value.bind="user.name" />
        <button type="reset">Cancel</button>
    </form>
  </div>
```

However, if I remove the line `<input type="text" value.bind="user.name" />` user gets correctly set to and from null.

**Comment by jdanyow** [comment]
Keep an eye on [this issue](https://github.com/aurelia/binding/issues/205) for updates.
