### ISSUE TITLE
computedFrom doesn't observe lists

### ISSUE THREAD

**Issue by davismj** [aurelia/binding#249]
In other words.

``` javascript
@computedFrom('filter', 'list')
get filteredList() {
  // filter the list
}
```

``` javascript
list.splice(index, 1); // filteredList doesn't recompute
```

**Comment by andrevlins** [comment]
there are any workaround this?

**Comment by jdanyow** [comment]
one workaround would be to write `this.list = this.list.slice(0).splice(index, 1)` instead of `this.list.splice(index, 1)`,

**Comment by davismj** [comment]
@andrevlins So this is actually a bad design practice. Observing lists via splice is working, and modifying a list with another variable through value converters is working. Thus if you want a computed list you should bind the list and add a value convert to filter it.

However, I think we're agreed that this should eventually work, too, @jdanyow?

**Comment by jdanyow** [comment]
@davismj I agree, the best way to do this would be with a value converter.

There are other enhancement requests for `@computedFrom` so I think we should leave this open and revisit when we refactor that component.

**Comment by jdanyow** [comment]
related to #149

**Comment by AlbertoMonteiro** [comment]
Using computed from with checked.bind to a list also doest not work

**app.ts**
```typescript
import { computedFrom } from 'aurelia-framework';

export class App {
	selectedOptions = [];
	options = [1, 2, 3, 4];

	@computedFrom("selectedOptions")
	get selectedItemsSeparetedWithComma(): string {
		return `${this.primeiroNome} ${this.sobreNome}`;
	}
}
```
**app.html**
```html
<template>
  <ul>
    <li repeat.for="item of options">
      <label><input type="checkbox" model.bind="item" checked.bind="$parent.selectedOptions" >${item}</label>
    </li>
  </ul>
  <div>${selectedItemsSeparetedWithComma}</div>
</template>
```
**selectedItemsSeparetedWithComma** is never fired when **selectedOptions** change.

**Comment by davismj** [comment]
Using @computedFrom with any array mutation will not work.

**Comment by AlbertoMonteiro** [comment]
@davismj how can I make it work?

**Comment by davismj** [comment]
I recommend creating a value converter. Try looking at [this article by Jeremy Danyow ](http://eisenbergeffect.bluespire.com/binding-with-value-converters-in-aurelia/) for more information on value converters.

**Comment by AlbertoMonteiro** [comment]
@davismj thanks!

**Comment by atsu85** [comment]
@jdanyow, any progress with `@computedFrom('someArray')` and array mutations? I stumbled upon issue with `someArray.push(someElem)`.

**Comment by atsu85** [comment]
@jdanyow, I might be totally wrong as I'm not familiar with binging logic, but could my gut feeling be correct, that this problem might be related to [this line](https://github.com/aurelia/binding/blob/master/src/computed-observation.js#L62) that uses `ExpressionObserver`, but not `CollectionObserver`

**Comment by jdanyow** [comment]
@atsu85 - the binding system observes property changes- if you put `<input value.bind="foo.bar.baz">` in an html template or in `@computedFrom('foo.bar.baz')`, the binding system will observe the `foo` property for changes, `foo`'s `bar` property for changes and `bar`'s `baz` property for changes. It doesn't check "is the value an array? yes? also observe the array for mutation".

Perhaps we could do that in the `@computedFrom` use-case or maybe we need an explicit instruction to do so- something like: `@computedFrom('foo.bar.baz', { collection: true, expression: 'cart.items' })`

**Comment by StrahilKazlachev** [comment]
@jdanyow I'm for an explicit option. We should be able to differentiate between property change and changes to the value.

**Comment by atsu85** [comment]
@jdanyow, 
> Perhaps we could do that in the @computedFrom use-case or maybe we need an explicit instruction to do so- something like: @computedFrom('foo.bar.baz', { collection: true, expression: 'cart.items' })

I understand, that if I'd need to use `@computedFrom("bindableArray.bar.baz")` instead of `@computedFrom("bindableArray")`, then there might be a need to explicitly instruct that CollectionObserver should be used, but when one of the computed properties is actually a array, then I'd expect that `computedFrom` decorator detects that `bindableArray` is array and it then additionally uses `CollectionObserver`, so it could also detect array modifications (such as `.push(newElem)`) in addition to replacing array instance (that is implemented right now).

Here is an example of my use-case:
```html
<template>
  ${computedGetter.value}
<template>
```
with
```ES6
  @computedFrom("bindableArray", "bindableId")
  get computedGetter() {
    // return item from `this.bindableArray` by `this.bindableId`
  }
```

**Comment by davismj** [comment]
@atsu85 As mentioned above, I haven't seen a case where this couldn't be solved with a value converter, which is much more efficient. So instead you might have:

```html
<template>
  ${bindableArray | filter: bindableId}
</template>
```

```javascript
export class FilterValueConverter {
  toView(array, id) {
    // return item from `array` by `id`
  }
}
```

I've even written a small library that does this for you here: http://foursails.github.io/bouncer/

**Comment by davismj** [comment]
@jdanyow As the person who originally opened this issue, I recommend we close it, as I don't see this as a valuable enhancement. What do you think?

**Comment by atsu85** [comment]
@davismj, my example was a lot simplified from real use-case. I also need the result of `computedGetter` in other methods of the class.

**Comment by Thanood** [comment]
Is it intended that the value converter (`jsonValueConverter`) in this gist does *not* update when I change the array?
https://gist.run/?id=82c48de63159f1b1d39c2658ab748bf7

**Comment by carusology** [comment]
Even if the official solution is "use a value converter", an error message would be much more valuable than the current approach of "try it in futility for an hour, google it and find this issue." Can `@computedFrom` do a typeof check to see if the observed property is an array, and throw an error if so?

**Comment by dkent600** [comment]
Value converters don't work at all for this use case.  I don't understand why it was so strongly recommended nor why those who should be more in the know didn't object when it was.

**Comment by zakjan** [comment]
Observing array length with `@computedFrom("array.length")` works, is it officially supported?

**Comment by davismj** [comment]
Yep! That is a completely viable strategy. See https://github.com/aurelia/binding/blob/master/src/observer-locator.js#L159
