### ISSUE TITLE
Issue with binding on custom element

### ISSUE THREAD

**Issue by iamcdonald** [aurelia/binding#254]
I have set up a simplified structure similar to the one I've been experiencing problems with [here](http://plnkr.co/edit/tB2sIRuMagOCYiJQ3zGA?p=preview) on plunker.

The crux of the problem is that the 'loader' custom element isLoading.bind doesn't seem to be getting bound at all. Thus isLoading within the custom element isn't ever set, never mind showing true or false as it changes (I would expect to see 'Loading...' in the html and then 3 seconds later see it disappear).

Any pointers would be much appreciated.

Thanks.

**Comment by jdanyow** [comment]
The DOM lower-cases all element and attribute names.  Aurelia has a convention that hyphenates custom element names and bindable property names that have mixed casing.  This means you'll need to use `is-loading.bind...` when you want to bind to your `isLoading` bindable property.

If you change hobbies.html to use `is-loading.bind="person.hobbies.isLoading"` it will start working.
