### ISSUE TITLE
composed views are not updated when underlaying data changes

### ISSUE THREAD

**Issue by mbroadst** [aurelia/binding#259]
relevant example: http://plnkr.co/edit/fOK3A8HpafsLwOU37M1K

The console will show you when the "slang" representation of age changes and what it should be for each of the duck brothers. The initial data is rendered, but subsequent changes to underlaying data do not result in re-rendering of the composed component. Is this a bug?

**Comment by mbroadst** [comment]
@EisenbergEffect if you actually wait one more second I have a few other examples of this breaking with different types of "composed" elements

**Comment by mbroadst** [comment]
@EisenbergEffect okay I've updated the plunker to include another form that I've been using where I pass a function to `template`. You'll note in the updated plunker: http://plnkr.co/edit/fOK3A8HpafsLwOU37M1K, that neither field which is being "composed" is actually being updated.

**Comment by mbroadst** [comment]
@EisenbergEffect, @jdanyow any idea what is going on here? (maybe I can help with some direction) This has basically stopped me dead in my tracks, is there a way to opt-out of the view caching here, which I assume is what's preventing the update of information.

**Comment by EisenbergEffect** [comment]
There is no "view cache" used unless you ask for it. I have not had a chance to look into this yet. I'll try to have a look this week.

**Comment by mbroadst** [comment]
@EisenbergEffect hm okay, I recalled refactorings a few months back about introducing more aggressive caching and had mistakenly assumed it was what was going on here. I'll try to see if I can elicit more information about what's going on.

**Comment by mbroadst** [comment]
So I spoke with @jdanyow on the gitter channel yesterday and he helped clear up a little bit why the data wasn't updating in either of these cases: aurelia doesn't proactively bind to all members of an object, but rather on an as-referenced basis. Hence, if I pass in `row.age` to the function it works as expected.

Is there any way to opt in to proactive property changes? For instance, in the example I've given `compose` elements do in fact change when the model that you bind to them changes in some way (this is a form of proactive change notification for the whole object is it not?). Composition works fine for me in most cases, but sometimes I want to have a column definition that does a _very_ simple operation that doesn't seem to deserve a whole template file or View + ViewModel, e.g. convert some incoming data to a percentage and add a `%` at the end of it. In this cases it would be incredibly useful to be able to use a function and just pass the whole object in (I might need two or more data points in the object to calculate percentage) without having to pass in particular members of the object (or know which ones are needed beforehand).

I hope I'm being clear here, please let me know if I can help clarify anything!

**Comment by mbroadst** [comment]
ping

**Comment by jdanyow** [comment]
Aurelia has no "watch whole object for changes" feature, it would be difficult to implement efficiently especially now that `Object.observe` is going away.

**Comment by mbroadst** [comment]
@jdanyow perhaps a better way to go about this is to rather ask you if you have any advice for how to solve this particular issue of wanting to provide a bound function to my grid's template. 

If I use a `<compose>` element, assign the `row` to `model.bind`, and then use some property of that model in the composed view's template, then the view changes properly when that property changes.  There doesn't seem to be a shorthand version of doing this. For instance, if I want one particular column to show a row property with an added "%" after it, I need to create a whole new file with either just a View or View+ViewModel pair.  It seems like the plumbing is here, I'm just not sure how to tap into it generically.

**Comment by mbroadst** [comment]
I know this is sort of getting out of the `binding` territory here, but is it possible to provide a raw string for the view for a `<compose>` element? I tried this quickly and it didn't seem to work, but I might be missing some magic.

If that were possible, that would seem to solve my immediate use case as I could instead just provide the templated view directly (optionally using a number of bound properties of the source object) rather than trying to use a plain javascript function. In code this would look like (modifying the `grid.html` in the plunker above, adding an optional `view` property to the column definition):

```
<compose if.bind="!!column.view" view="${column.view}" view-model.bind="$parent.row"></compose>
```

and the grid options definition changing to something like:
```
  gridOptions = {
    columns: [
      { name: 'name' },
      { name: 'age', template: 'age-template' },
      { name: 'height', view: '<template>${(height > 10) ? 'tall' : 'short'}</template>' },
      { name: 'weight' }
    ]
  }
```

I'm sort of running out of ideas of how else to accomplish this goal with aurelia, so some sort of guidance would be greatly appreciated.

**Comment by EisenbergEffect** [comment]
You cannot provide a raw string, but you can provide a ViewStrategy instance....and you can use an instance of InlineViewStrategy to provide the string you want.

**Comment by EisenbergEffect** [comment]
The reason for this is that it has no way to determine if a string is a relative path to a view or the source for the view. So, strings mean paths. But you can bind the compose view to an instance of ViewStrategy which can create the view in any way it chooses. Under the hood, all component views are handled by ViewStrategy implementations. Usually, the ConventionalViewStrategy is used. But you can use others or create your own. For this case, you want the InlineViewStrategy.

**Comment by EisenbergEffect** [comment]
http://aurelia.io/docs.html#/aurelia/templating/1.0.0-beta.1.0.2/doc/api/class/InlineViewStrategy

Note: only the markup parameter of the constructor is required. I think our docs aren't properly displaying optional params ;( We will work to get that fixed.

**Comment by mbroadst** [comment]
@EisenbergEffect now to the golden question: given that I provide an `InlineViewStrategy` wrapping the string provided to `view` (in this case), will it correctly process the content and bind all relevant properties accessed within the template?

**Comment by EisenbergEffect** [comment]
I'm not following the question. The inline view will be just as if you had created a view in an .html file and referenced that with the view property.

**Comment by mbroadst** [comment]
@EisenbergEffect let me see if I can sum up quickly my problem here in a more concise format:

In the plunker linked above, I have a `grid` component I create and bind to it some `gridOptions` which contain column definitions. In the most basic case this works very well for displaying a single bound value of each row of some source data.

I also have cases where I wan to be able to easily (and.. accessibly?) very slightly modify that data: so maybe I want to simply add a '%' to the end of the data, maybe I want to do a quick calculation (`$(row.a + row.b) %`), which lead me to supporting passing in a function. The goal here is that I could use a composed view, or just a template, but a separate file for such a simple view seems overkill.
In the plunker above this looks like this:

```
      { name: 'height', template: function(row) {
          return (row.height > 10) ? 'tall' : 'short';
        }
      },
```

The problem being, of course, that since I don't actually pass a specific property of the row into that function it never updates (because aurelia can't proactively monitor the `row` object for all changes). If, instead, I pass in `row.height` to that function it would update accordingly, but we've lost the flexibility of the original intent.

This all lead me to thinking about composed views, which seem to do something similar: you only bind the model in, but magically value changes are processed for any properties accessed in the view of whatever you're composing.

Now, what I think I'm reading from your proposal above, is that I could still maintain some flexibility (I could embed the view as a string in my `gridOptions`, and therefore not need separate files for simple operations) by wrapping the passed in template string with a ViewStrategy - but in that case, would it do all the magic to track property updates for properties used in that view?

**Comment by mbroadst** [comment]
On the other hand, I understand that the way I'm currently doing this isn't exactly the most declarative way, especially since it seems like most of the work I'm trying to do is in the view itself.  Are there any better examples of a generic data grid? I know there is `aurelia-bs-grid`, but even that has to work through some incredibly trickery to work the way it does (basically overriding most of aurelia's general behavior with @processContent)

**Comment by EisenbergEffect** [comment]
It will track all bindings. If the inline view declares binding expressions, those will work like any other view.

**Comment by EisenbergEffect** [comment]
@mbroadst The kendo ui grid for aurelia might be a good example. But, you should realize, data-grids are complicated components. It's about the most complicated component you could create.

**Comment by mbroadst** [comment]
@EisenbergEffect can you provide a link to that? Or do you just mean this wrapper for the existing kendo grid: https://gist.github.com/charlespockert/1ef96e44f3f15ab60f5e

**Comment by EisenbergEffect** [comment]
http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/grid/basic-use

**Comment by mbroadst** [comment]
@EisenbergEffect great. Thanks to both you and @jdanyow for your patience on this thread, I'll close this now pending more relevant related questions.

**Comment by mbroadst** [comment]
@EisenbergEffect incredible tip on the InlineViewStrategy! Looks like I can begin to make something much more declarative with that:  http://plnkr.co/edit/LSmSiL

**Comment by EisenbergEffect** [comment]
Great to hear!

**Comment by kristianmandrup** [comment]
Hi @mbroadst I'm really keen to learn how to build fully dynamic views based on dynamic data models. I couldn't make your plunker demo run however I found your au-grid component which I'm trying to grog. Wish there was more documentation or better examples on these aspects!
Feels like pretty deep down the rabbit whole. 
Would love to pick your brain on how to best leverage this for building a UI generator with drag and drop. Thanks :)
