### ISSUE TITLE
Value converter and two-way binding - unexpected behavior

### ISSUE THREAD

**Issue by StrahilKazlachev** [aurelia/binding#261]
I have a field `userInput: string` bound to an input. And a clear button that sets the `userInput` to `''`. If a value converter is added I get the following:
* after the view is loaded and no changes are made, the clear button works as expected - `toView` is called with the new value `''`, then `fromView` is called.
* after the view is loaded and the user enters a new value, `userInput` is correctly updated. But now if the clear button is pressed `userInput` is not set to `''`, you need to press it a second time to set the value to `''`. I changed the value converter to just return the value in both `toView` and `fromView`. What I see is that the first time the clear button is pressed `toView` is not called and `fromView` is called with the last value written in the input.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you take a look at this?
@StrahilKazlachev Can you provide a simple reproduction that we can use to see the behavior?

**Comment by StrahilKazlachev** [comment]
I tried, and couldn't, it seems I'm one patch release behind in the project. Updating now.

**Comment by StrahilKazlachev** [comment]
Here is a [repro](https://github.com/StrahilKazlachev/skeleton-navigation) - welcome page. But it looks like I'm doing some things that "confuse" the binding engine. Like `<template if.one-time="!config.readonly">` where `config` is `undefined` and the beginning and I assign it a value in the `bind` callback.

**Comment by StrahilKazlachev** [comment]
@jdanyow It seems I forgot to "mention" anyone, sorry if you've already seen it.

**Comment by jdanyow** [comment]
@StrahilKazlachev I wasn't able to reproduce this issue using the code you provided. What does `jspm inspect --forks` say?

**Comment by StrahilKazlachev** [comment]
@jdanyow I tried now in FF and it worked, but in chrome(47) I still get that behavior.
