### ISSUE TITLE
iOS click.delegate not functioning without cursor: pointer

### ISSUE THREAD

**Issue by stsje** [aurelia/binding#263]
Seems to be a problem with `click.delegate` on iOS, if the element doesn't have the styling `cursor: pointer`.

plnkr show the issue, tested using the iPad simulator (ignore the repeats, they have nothing to do with the issue):
http://plnkr.co/edit/Lpirev?p=preview

I've found what I think is a similar issue on stackoverflow. They say the event won't bubble all the way to body, if the cursor isn't pointer. They also mention other workarounds (such as using trigger for our case).
http://stackoverflow.com/questions/10165141/jquery-on-and-delegate-doesnt-work-on-ipad

Is it even something Aurelia will do anything about? I expect many to run into this very same problem, and be completly puzzled by it, but doesn't have anything to do with Aurelia directly.

**Comment by stsje** [comment]
Maybe adding a small note about it in the docs could help?

**Comment by lukechilds** [comment]
I just spent hours pulling my hair out over this. It says in the answer to the above SO post that attaching the listener to the first child of body should work. Could that be a possible workaround?

**Comment by Alexander-Taran** [comment]
yep.. apple way or the highway..

**Comment by imran-khan77** [comment]
Daaaamn! it was just this :-o
Great thanks !
