### ISSUE TITLE
One-way binding broken after 1.0.0-beta.1.0.3 update

### ISSUE THREAD

**Issue by michaelmalonenz** [aurelia/binding#264]
After updating to yesterday's release, we found an issue regarding one-way binding.  Specifically, if using a getter to compute the value from another object, if the value is undefined (which it must be to show the placeholder) then the literal string `undefined` is shown in the input.  If the binding is changed to two-way (and a setter added, obviously) then the problem disappears.

I have reproduced the problem here:
https://github.com/michaelmalonenz/skeleton-navigation/tree/one-way-binding-bug

**Comment by EisenbergEffect** [comment]
@jdanyow Seems like a small regression.

**Comment by jdanyow** [comment]
ah yes- will get this fixed.  [This logic](https://github.com/aurelia/binding/blob/master/src/element-observation.js#L100-L101) that was added for https://github.com/aurelia/binding/issues/152 needs to be added to the static accessor stuff.
