### ISSUE TITLE
Suggestion: API for traversing binding context

### ISSUE THREAD

**Issue by genadis** [aurelia/binding#266]
Hi,

I believe that a set of APIs for traversing the binding context, something like jQuery style for traversing the DOM could be a very useful feature for Aurelia.

For example API for finding specific binding context parent based on Class type? Something like $.closest() of jQuery.

I've implemented something basic that i find useful:
```
export function getClosestContext(overrideContext: Object, contextClass: Function) {
  let bindingContext = null;
  let context = overrideContext;
  do {
    if (context.bindingContext instanceof contextClass) {
      bindingContext = context.bindingContext;
      break;
    }
    context = context.parentOverrideContext;
  } while (context);

  return bindingContext;
}
```

Which i use in `bind` context of my VM:
```
// Some child custom element
  bind(bindingContext: Object, overrideContext: Object) {
    this.usefulParent = getClosestContext(overrideContext, SomeParentClass);
  }
```

I find it more useful instead of passing the context through each custom element of the DOM.
If I decide to change the structure of the DOM, I don't need to worry about passing the parent context binding.

**Comment by jdanyow** [comment]
@genadis you can use DI to access ancestor VMs:

```js
@inject(Optional.of(SomeParentViewModelClass)) // will inject nearest ancestor if one exists
export class MyViewModel {
  constructor(parentVM) {
    ...
  }
  ...
```

**Comment by genadis** [comment]
@jdanyow Thank you.
Regarding the specific example: What if I have number of custom parent elements of the same VM type,
will using the DI retrieve the Object of the first containing parent?

The suggestion is more general, consider other more complex cases as well.
We can always use DOM methods + jQuery and retrieve the VM from the view, but it ads more complexity.

**Comment by jdanyow** [comment]
check out this question and answer on stackoverflow for more info on the DI approach:  http://stackoverflow.com/questions/32777303/custom-elements-binding-context-what-is-it-exactly-how-to-access-parent-vm

**Comment by genadis** [comment]
@jdanyow Thank you for the link, exactly what I needed, just added checkParent set to true.

Last comment here before I close this as it's more relevant to DI.
I better understand now the DI approach.

I've reviewed the code, but couldn't find option to add ID to Objects. It seems the resolving is done by Class names (constructor function), but from the other hand looks flexible to allow other methods.

Consider the case of having multiple Objects of same Class and wanting to resolve one of them by ID/metadata.
Couldn't find documentation for such use case, and would be happy if you point me to the right direction.

Thanks!

**Comment by jdanyow** [comment]
@genadis sure- you can register anything with any key.  The key doesn't need to be a constructor function/class. It could be a string, a number, an object instance, anything...  For example:

```js
let a = new Something();
let b = new Something();
container.registerInstance('some key', a);
container.registerInstance('another key', b);
```
then:
```js
@inject('some key', 'another key')
export class Foo {
  constructor(a, b) {
    ...
  }
  ...
}
```
