### ISSUE TITLE
Promise bindings / Lazy bindings

### ISSUE THREAD

**Issue by niieani** [aurelia/binding#268]
One common thing that I seem to be repeating in my code over and over again is creating workarounds for values that might or might not be there at the time a binding is attached. This is of course relatively easy with Aurelia, since I can send a `signal` once a Promise is resolved to reevaluate the binding, yet still, the binding definition remains quote long and writing around the problem slows down development.
It would be awesome if we could bind to promises, returning a default (pre-set) value until the promise is resolved, and then reevaluating the binding automatically. 

At first I was awaiting all the Promises in the `activate()` or `attached()` methods of the ViewModel by returning a Promise from them, but this has the effect of blocking all loading until they are resolved. Lazy loading values into the view - "as they resolve" - makes much more sense to me.

Currently, in order to create "lazy" bindings, we need to:

View:
```html
${obj.resolvedValue ? obj.resolvedValue : 'loading...' & signal: 'obj-' + obj.id + '-resolved'}
```

ViewModel:
```js
attached() {
  // this.obj.value is a Promise //
  this.obj.value.then(value => { 
    this.obj.resolvedValue = value; 
    this.signaler.signal('obj-' + obj.id + '-resolved');
  })
}
```

If we had it natively, I'd imagine we could simply do something like:
View:
```html
${obj.value & lazy: 'loading...'}
```

A lot of current use cases for `signal`s would go away and the View code will be clearer and ViewModel less cluttered. 
I'd be happy to contribute that feature, but I'm not sure where to start (any pointers?). Would a custom binding behavior work for this?

**Comment by jdanyow** [comment]
@niieani I'm unclear why the signal is needed?  The binding system will detect when the `resolvedValue` property becomes defined.

Take a look at the readme for [this plugin](https://github.com/jdanyow/aurelia-async). Is it anything that would work for your use-case?

**Comment by niieani** [comment]
@jdanyow I don't remember why exactly now, but I think it was because when the property is doubly nested (`obj.resolvedObject.prop`) I get errors from the binding system about it `not being able to read prop of undefined`, so my binding needed signals and it turned into this monster:
```js
obj.resolvedObject && obj.resolvedObject.property ? obj.resolvedObject.property : 'loading...' & signal: 'some-signal'
```

`aurelia-async` looks like it could be a solution for my use cases! I'll try it out. I see the code is simple enough to start hacking with too.
