### ISSUE TITLE
bindingExpression updates the target unnecessarily for equal date values

### ISSUE THREAD

**Issue by sylvain-hamel** [aurelia/binding#269]
`bindingExpression` compares old and new values using `===` and therefore will update the target if the source value changes from `new Date(1776, 7, 4)` to `new Date(1776, 7, 4)`.

See https://github.com/sylvain-hamel/binding/commit/d9e16e28adc413abe16756b388b15e36f4839457 for the unit tests that reproduce the issue.

After discussing with @jdanyow I'm opening this issue to keep track of this limitation.   Changing `bindingExpression` could be costly, using a custom binding behavior is a workaround if someone needs to avoid the unnecessary update to the target:

```
<my-element max-date="date1 & dateComparison", min-date="date2 & dateComparison">
```

**Comment by jdanyow** [comment]
Discussed this with @sylvain-hamel last week in a private gitter chat. The binding engine's behavior is technically correct, notifying changes when a property's date instance changes, however this might is not optimal when the new date instance has the same date value as the original date instance. 

It could be argued that it's not the binding instance's responsibility to sort this out, we definitely don't want to add additional logic to this already hot path. Perhaps the component or logic that is assigning a new date instance to a property whose value is a date instance with the same date value should be updated to do a date comparison prior to assigning.

A workaround that would avoid adding overhead to non-date-related bindings would be a binding behavior.  Something like:

export class DateComparisonBindingBehavior {
  bind(binding, source) {
    binding.dateComparedUpdateSource = binding.updateSource;
    binding.updateSource = function(newValue) {
      let currentValue = this.sourceExpression.evaluate(this.source, this.lookupFunctions);
      if (!currentValue || !newValue || +currentValue !== +newValue) {
        this.dateComparedUpdateSource(newValue);
      }
    }
  }

  unbind(binding) {
    binding.updateSource = binding.dateComparedUpdateSource;
    binding.dateComparedUpdateSource = null;
  }
}
