### ISSUE TITLE
Document "best practices" for defining array properties used in data-binding expressions

### ISSUE THREAD

**Issue by mvpspl619** [aurelia/binding#27]
https://github.com/aurelia/binding/blob/master/src/dirty-checking.js#L79 This code always returns false when checking for arrays(properties who's getter returns an array in view-model).

This makes Aurelia to constantly update the DOM as if in an infinite loop. 

Isn't there a necessity to deep compare ?

**Comment by EisenbergEffect** [comment]
So, you've got a computed property that returns a new instance of an array each time? Is that the use case?

**Comment by yelvert** [comment]
@EisenbergEffect I think I ran up against a similar issue laid out in aurelia/templating-resources#14 with deep checking.

**Comment by mvpspl619** [comment]
For ex:

get yo() {
    return [1,2,3]
}

-----Original Message-----

**Comment by mvpspl619** [comment]
See this for example. https://github.com/aurelia/framework/issues/29

Dirty checking is the reason for that.

**Comment by EisenbergEffect** [comment]
So, when the value is an array, and it's not the same instance.....then we need to compare the members using a simple comparison to see if each index is equal. If it's all the same, then it's not dirty (even though it's a different array instance). Is that correct?

**Comment by yelvert** [comment]
Objects as well, I would think.

**Comment by EisenbergEffect** [comment]
Why? We can observe objects. Ultimately....if you are using getters you are choosing a less optimized path. The goal is to have dirty checking only as a fallback. If you return the same array or object instance we can actually observe those automatically, so no need to dirty check those. If you return a different array, that makes the process more expensive.

Does that make sense?

**Comment by yelvert** [comment]
I suppose it would be fine to setup my own watchers inside the behavior and just not use the changeHandler in withProperty, but it would be nice if it was baked into the changeHandler. I can see it being used often, and could prevent a lot of copy/paste. Might I suggest adding a withShallowProperty or something similar to Behavior, so that either way can be used explicitly, or maybe a different binding method model.bind-shallow, though I think the behavior route would be a little cleaner.

**Comment by EisenbergEffect** [comment]
I'm not entirely following you. BUT...Aurelia is pretty extensible, so you might be able to add it yourself as a plugin. For example, we have already have someone build a plugin to Aurelia's binding system that enables computeds without dirty checking. You can declare your dependencies and it will only raise a change notification when the dependencies change. That was built completely as a plugin to the binding system. No hacking required. So, maybe you can build something for your use case? If you can do that, then it's easier for us to discuss whether or not it should be in the core.

**Comment by yelvert** [comment]
Ill take a stab tonight, see what I can come up with.

**Comment by mvpspl619** [comment]
Rob,

I think doing a simple comparison for arrays should be enough in this case.

-----Original Message-----

**Comment by jdanyow** [comment]
@yelvert here's the plugin @EisenbergEffect was referring to:  https://github.com/jdanyow/aurelia-computed

depends on [this](https://github.com/aurelia/binding/pull/21) which isn't released yet but will be soon.

**Comment by jaimerivera** [comment]
Could Aurelia parse the getter functions of the view model and automatically detect the dependencies.  In theory the function could be parsed and as long as all the dependent properties are in the form of "this.xyz" and "xyz" is a property then what the plugin does could be done automatically.  In essence generate the "declarePropertyDependencies()" call on the fly.  Definitely not trivial but I think do-able.

**Comment by WeeHorse** [comment]
I have a simple repeater that fails by not finding any VM functions. Is this related?
The template:
 <ul>
    <li repeat.for="subj of subjects" click.delegate="loadOneText(subj)">${subj}</li>
</ul>

Or (this fails too):
<a repeat.for="subj of subjects" click.delegate="loadOneText(subj)">${subj}</a>

But this does not fail (no repeater):
<a click.delegate="loadOneText(subject)">${subject}</a>

In the VM this.subjects is an array of objects, like [{subject:'some text', text:'long text'}, {…}] while this.subject is a string, like 'some text'

The error:
Uncaught Error: loadOneText is not a function
ensureFunctionFromMap @ ast.js:57
evaluate @ ast.js:560
(anonymous function) @ listener-expression.js:67
execute._createClass.value @ event-manager.js:61

**Comment by EisenbergEffect** [comment]
It's true `loadOneText` is not a function in the current scope. You probably meant `$parent.loadOneText` This is something that will be improved. We are tracking it separately. It's not related to this issue.

**Comment by jdanyow** [comment]
The Aurelia docs need to provide "best practices" for defining array properties for the purposes of data-binding.  An array property intended for data-binding should not return a new array instance each time it is accessed.  Returning new instances containing the same items would not make efficient use of Aurelia's templating/binding system.

**Comment by jdanyow** [comment]
updated docs
