### ISSUE TITLE
Binding should expose an `observable` decorator

### ISSUE THREAD

**Issue by PWKad** [aurelia/binding#270]
Should be a subset of the `bindable` functionality that can be used on any class instance field -

```language-javascript
import {observable} from 'aurelia-binding';

export class MyViewModel {
  user;
  constructor() {
    this.user = new User();
  }
}

class User {
  @observable name = '';
  nameChanged(newValue) {
    console.log(newValue);
  }
}
```

**Comment by jdanyow** [comment]
I like this idea! 

I *think* [this will do the trick](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=function%20observable(target%2C%20propertyName%2C%20descriptor)%20%7B%0A%20%20%2F%2F%20grab%20the%20inner%20property%20name%20and%20the%20callback%20function%20name.%0A%20%20let%20innerPropertyName%20%3D%20%60_%24%7BpropertyName%7D%60%3B%0A%20%20let%20callbackName%20%3D%20%60%24%7BpropertyName%7DChanged%60%3B%0A%20%20%0A%20%20%2F%2F%20set%20the%20initial%20value%20of%20the%20property.%0A%20%20target%5BinnerPropertyName%5D%20%3D%20descriptor.initializer()%3B%0A%20%20%0A%20%20%2F%2F%20we're%20adding%20a%20getter%20and%20setter%20which%20means%20the%20property%20descriptor%0A%20%20%2F%2F%20cannot%20have%20a%20%22value%22%20or%20%22writable%22%20attribute%0A%20%20delete%20descriptor.writable%3B%0A%20%20delete%20descriptor.initializer%3B%0A%20%20%0A%20%20%2F%2F%20add%20the%20getter%20and%20setter%20to%20the%20property%20descriptor.%0A%20%20descriptor.get%20%3D%20function()%20%7B%20return%20this%5BinnerPropertyName%5D%3B%20%7D%3B%0A%20%20descriptor.set%20%3D%20function(newValue)%20%7B%0A%20%20%20%20%20%20let%20oldValue%20%3D%20this%5BinnerPropertyName%5D%3B%0A%20%20%20%20%20%20this%5BinnerPropertyName%5D%20%3D%20newValue%3B%0A%20%20%20%20%20%20if%20(this%5BcallbackName%5D)%20%7B%0A%20%20%20%20%20%20%20%20this%5BcallbackName%5D(newValue%2C%20oldValue)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%3B%0A%20%20%0A%20%20%2F%2F%20make%20sure%20Aurelia%20doesn't%20use%20dirty-checking%20by%20declaring%20the%20property's%0A%20%20%2F%2F%20dependencies.%20This%20is%20the%20equivalent%20of%20%22%40computedFrom(...)%22.%0A%20%20descriptor.get.dependencies%20%3D%20%5BinnerPropertyName%5D%3B%0A%7D%0A%0Aclass%20Test%20%7B%0A%20%20%40observable%20foo%20%3D%20'bar'%3B%0A%20%20%0A%20%20fooChanged(newValue%2C%20oldValue)%20%7B%0A%20%20%20%20console.log(%60foo%20changed!%20newValue%3D%24%7BnewValue%7D%3B%20oldValue%3D%24%7BoldValue%7D%60)%3B%0A%20%20%7D%0A%7D%0A%0A%0Alet%20test%20%3D%20new%20Test()%3B%0Alet%20test2%20%3D%20new%20Test()%3B%0Atest.foo%20%3D%20'baz'%3B%0Atest2.foo%20%3D%20'hello%20world'%3B%0Atest2.foo%20%3D%20'goodbye%20world'%3B)

```js
function observable(target, propertyName, descriptor) {
  // use a convention to compute the inner property name and the callback 
  // function name.
  let innerPropertyName = `_${propertyName}`;
  let callbackName = `${propertyName}Changed`;
  
  // set the initial value of the property.
  target[innerPropertyName] = descriptor.initializer();
  
  // we're adding a getter and setter which means the property descriptor
  // cannot have a "value" or "writable" attribute
  delete descriptor.writable;
  delete descriptor.initializer;
  
  // add the getter and setter to the property descriptor.
  descriptor.get = function() { return this[innerPropertyName]; };
  descriptor.set = function(newValue) {
      let oldValue = this[innerPropertyName];
      this[innerPropertyName] = newValue;
      if (this[callbackName]) {
        this[callbackName](newValue, oldValue);
      }
    };
  
  // make sure Aurelia doesn't use dirty-checking by declaring the property's
  // dependencies. This is the equivalent of "@computedFrom(...)".
  descriptor.get.dependencies = [innerPropertyName];
}
```

**Comment by StrahilKazlachev** [comment]
What about an option to explicitly specify the **changed** handler?

**Comment by jdanyow** [comment]
That would be cool- also- this decorator doesn't seem to work in TypeScript.

**Comment by PWKad** [comment]
@jdanyow do you think it would work somehow to break [this](https://github.com/aurelia/templating/blob/master/src/bindable-property.js#L120) out somehow to work from multiple decorators?  That way both `@bindable` and `@observable` could use the same code to implemented the `changeHandler`?

**Comment by EisenbergEffect** [comment]
@PWKad That's a tricky question. There are parts of that code that are very behavior-specific, such as the options check, for example.

**Comment by PWKad** [comment]
@jdanyow I just got around to testing what you put in and it seems to work perfect on a class instance field.  If I add some tests to binding to support this as a class decorator and a class instance field decorator think we can get this in the next release?

**Comment by jdanyow** [comment]
Sounds good to me- some outstanding questions/concerns: 
1. does it work in typescript
2. what repo does it go in?
3. maybe the name isn't quite right.  Maybe something like `@notifyChanged` or `@notifies` is more accurate?
4. option to specify the handler function name

@EisenbergEffect thoughts?

**Comment by jdanyow** [comment]
I think this will preserve the default value, even in typescript:
```js
function observable(target, propertyName, descriptor) {
  // use a convention to compute the inner property name and the callback 
  // function name.
  let innerPropertyName = `_${propertyName}`;
  let callbackName = `${propertyName}Changed`;

  // typescript or babel?
  let babel = arguments.length === 3;
 
  if (babel) {
    // babel passes in the property descriptor with a method to get the initial value.
    // set the initial value of the property.
    target[innerPropertyName] = descriptor.initializer();
  } else {
    // typescript doesn't pass in the property descriptor.
    descriptor = {};
  }

  // we're adding a getter and setter which means the property descriptor
  // cannot have a "value" or "writable" attribute
  delete descriptor.writable;
  delete descriptor.initializer;

  // add the getter and setter to the property descriptor.
  descriptor.get = function() { return this[innerPropertyName]; };
  descriptor.set = function(newValue) {
      let oldValue = this[innerPropertyName];
      this[innerPropertyName] = newValue;
      if (this[callbackName]) {
        this[callbackName](newValue, oldValue);
      }
    };

  // make sure Aurelia doesn't use dirty-checking by declaring the property's
  // dependencies. This is the equivalent of "@computedFrom(...)".
  descriptor.get.dependencies = [innerPropertyName];

  if (!babel) {
    Object.defineProperty(target, propertyName, descriptor);
  }
}
```

**Comment by Scapal** [comment]
This is a modified version accepting a changeHandler to be specified, both `@observable   value = 10;`and `@observable({changeHandler: ‘myHandler’}) value=10;`are working.
```javascript
 function observable(targetOrConfig, key, descriptor) {
	console.trace('observable');
	let deco = function(target, key2, descriptor2) {
		// use a convention to compute the inner property name and the callback 
		// function name.
		let innerPropertyName = `_${key2}`;
		let callbackName = (targetOrConfig && targetOrConfig.changeHandler) || `${key2}Changed`;

		// set the initial value of the property.
		target[innerPropertyName] = descriptor2.initializer();

		// we're adding a getter and setter which means the property descriptor
		// cannot have a "value" or "writable" attribute
		delete descriptor2.writable;
		delete descriptor2.initializer;

		// add the getter and setter to the property descriptor.
		descriptor2.get = function() { return this[innerPropertyName]; };
		descriptor2.set = function(newValue) {
			let oldValue = this[innerPropertyName];
			this[innerPropertyName] = newValue;
			if (this[callbackName]) {
				this[callbackName](newValue, oldValue);
			}
		};

		// make sure Aurelia doesn't use dirty-checking by declaring the property's
		// dependencies. This is the equivalent of "@computedFrom(...)".
		descriptor2.get.dependencies = [innerPropertyName];
	}

	if(key) {
		let target = targetOrConfig;
		targetOrConfig = null;
		return deco(target, key, descriptor);
	}

	return deco;
}
```

**Comment by EisenbergEffect** [comment]
@jdanyow Should we put this in the box? In the binding repo or elsewhwere? Of note on this implementation is that the callback timing will be different than other scenarios.

**Comment by jdanyow** [comment]
yes, I think so.  Do you think the name `@observable` is appropriate or should it be something else? `@notifies` or `@notifyChanged` maybe?

@Scapal would you be interested in submitting a PR to the binding repo for this (with tests, etc)? (if not, no worries- we're just always looking for new contributers :rocket:)

**Comment by EisenbergEffect** [comment]
I'm not sure what the best name is. I don't particularly like "notifies" or "notifyChanged" though...but I'm not sure if "observable" is the best name either...though I like that the best, mostly because of how it reads when combined with the property  name.

**Comment by PWKad** [comment]
Yes @jdanyow and @Scapal have done a great job today of getting a working concept in place.

Personal opinion - @observable seems to be most common but does *slightly* conflict with other concepts.  @notifies or anything similar doesn't feel right.

Here's a user story to back it up, maybe this helps (or maybe it makes me look crazy) - 

As a property of a class,
When my value changes,
I want to conventionally call a changed handler method (or a supplied override).

`@observable`
`@watcher`
`@watch`
`@subscribe`

**Comment by Scapal** [comment]
I'll make some tests.
Concerning the naming, `@subscribe`should be more related to observe more complex scenario and external data. I almost always inject a datastore component in my views and I'd like to have a simple decorator to subscribe to a change inside those datastore.

For the moment I use this code below. Is there a better way to do it?

**Comment by Scapal** [comment]
Does this sound enough for a unit test?
```javascript
import {observable} from '../../src/utils/observable-decorator.js';

describe('observable decorator', () => {
	it('changeHandler valueChanged should be called when changing the decorated property', () => {
		class Test  {
			@observable value = '';
			valueChanged () {
				this.test = this.value;
			}
		};

		var test = new Test();

		expect(test.test).not.toBeDefined();
		test.value = 'hello';
		expect(test.test).toBeDefined();
		expect(test.test).toEqual('hello');

		test.value = 'world';
		expect(test.test).toEqual('world');
	});

	it('changeHandler should be called when changing the decorated property', () => {
		class Test  {
			@observable({changeHandler: 'customHandler'}) value = '';
			valueChanged () {
				this.test = 'fail';
			}
			customHandler () {
				this.test = this.value + ' world';
			}
		};

		var test = new Test();

		expect(test.test).not.toBeDefined();
		test.value = 'hello';
		expect(test.test).toBeDefined();
		expect(test.test).toEqual('hello world');
	});	
});
```

**Comment by jdanyow** [comment]
@Scapal looking good- will need a test for scenarios where the handler method name is passed in via config and a test for situations where the handler doesn't exist.

**Comment by Scapal** [comment]
@EisenbergEffect 
> Of note on this implementation is that the callback timing will be different than other scenarios.

Another approach would be to use a plugin using `Container.setHandlerCreatedCallback`, setting a custom handler that would `subscribe`and `unsubscribe` a `properyObserver`on `handler.invoke()` and the overridden `deactivate`.
 Would that be a better way?

**Comment by EisenbergEffect** [comment]
I'm not sure that putting something like that on the Container would make sense, but you could put it directly on the observable function itself with a default implementation, so it always works as above...but it would be possible for the BindingEngine, once instantiated to possible override that. @jdanyow What do you think?

**Comment by Scapal** [comment]
I see a lot of patterns needing to override `activate` and `deactivate` for decorator support. Wouldn't it be easier to integrate a basic mechanism making it easy for decorators to add some code execution there?
A decorator for `aurelia-event-aggregator` like `@subscribe-event` would also be nice for example. `aurelia-flux`is already doing it that way.

The basic pattern is to implement a custom metadata property (using Symbols to avoid conflicts) where you store all the info from your decorators, and place a hook on the container (using `setHandlerCreatedCallback`), override the `invoke` and the `target.deactivate` to iterate over those metadata and implement the event subscriptions, observers...

Making this more straightforward or at least have a 'best practice' for such cases would be nice. The ability for a plugin to register for `activate` and `deactivate`easily and receive a dedicated Metadata root point could be all what is needed.

Does is sound like a good design pattern?

**Comment by Scapal** [comment]
The following code, which is my first attempt for the `@observable` feature, does that, only without using `setHandlerCreatedCallback`, directly from the decorator, so it only works if used after the optional `attached`and `detached` definition. Here the decorator is on the change handler function, not the property.
Using `setHandlerCreatedCallback` and custom metadata would allow me to overcome this problem, but maybe it is a bit heavy to put that on the container. 

```javascript
export function onPropertyChange(...properties) {
	return function(target, key, descriptor) {
		let targetAttached = target.attached;
		let targetDetached = target.detached;

		target.attached = function() {
			properties.forEach( (propertyName) => {
				let subscriptionHandle = 'observe_' + propertyName + '_' + key;

				this[subscriptionHandle] =
					this.bindingEngine.propertyObserver(this, propertyName)
						.subscribe( () =>  this[key]() );					
			});

			if(targetAttached !== undefined)
				return targetAttached.bind(this)();
		}

		target.detached = function() {
			properties.forEach( (propertyName) => {
				let subscriptionHandle = 'observe_' + propertyName + '_' + key;

				this[subscriptionHandle].dispose();		
			});

			if(targetDetached !== undefined)
				return targetDetached.bind(this)();			
		}

		return descriptor;
	}
}
```

**Comment by PWKad** [comment]
@Scapal Any luck?  Anything you need feedback on at the moment?

**Comment by PWKad** [comment]
@jdanyow @EisenbergEffect Any feedback for @Scapal ?  I love this so much I literally can't wait  :)

**Comment by EisenbergEffect** [comment]
We don't want any attached/detached hacks. So, let's not have that particular implementation. I think this implementation is probably fine: https://github.com/aurelia/binding/issues/270#issuecomment-183449523

I'd like to see a PR. Probably the best place is the binding library. @jdanyow What do you think?

**Comment by jdanyow** [comment]
@EisenbergEffect binding repo sound good to me.  I agree this implementation looks the best out of all the options:  https://github.com/aurelia/binding/issues/270#issuecomment-183449523

@Scapal would be willing to create the PR in the binding repo?

**Comment by Scapal** [comment]
@jdanyow Yes, I'm putting it all together. There was still an error when no initializer was provided.

**Comment by jdanyow** [comment]
PR was merged- thanks again @Scapal
