### ISSUE TITLE
.call() binding should allow passing arguments

### ISSUE THREAD

**Issue by michaelmalonenz** [aurelia/binding#271]
At the moment, it's possible to pass arguments using the .call binding through somewhat odd means (and feels like it might be accidental), but it would be really useful to have it as an accepted / documented part of the framework.

Currently, if the binding specifies an $event object (`<checkbox-widget ontoggle.call="selected($event)"></checkbox-widget>`) then the checkbox-widget custom element could pass an argument back:

```javascript
...
 if (this.ontoggle) {
    this.ontoggle(this.checked);
 }
...
```

We can take advantage of this, but in the source code, this particular functionality is [questioned](https://github.com/aurelia/binding/blob/master/src/call-expression.js#L31) and having it called $event seems wrong unless we're genuinely passing an event.  

I guess the intention behind this originally was to allow raising custom events, and using a real event object, but I've never wanted to raise full events, but we are using the functionality, so would be sad to see it disappear (as seen in the comment above), so if nothing else, this is a plea to not delete it.

**Comment by jdanyow** [comment]
This is supported, `$event` is the "old way".  The new way is to use `<checkbox-widget ontoggle.call="selected(foo, bar, baz)">` and `this.ontoggle({ foo: 1, bar: 2, baz: 3 });`

**Comment by EisenbergEffect** [comment]
@jdanyow Would you be willing to update the cheat sheet to remove the docs on the old way and document the new way? It can be found in the framework repo, in the doc folder.

**Comment by michaelmalonenz** [comment]
doesn't that mean that `foo`, `bar`, and `baz` need to be defined in the binding override context?  I was meaning for passing values only defined in the checkbox back.

**Comment by jdanyow** [comment]
@EisenbergEffect sure

---

@michaelmalonenz here's an example using the element from your original post:

```html
<checkbox-widget ontoggle.call="selected(checked)"></checkbox-widget>
```

checkbox-widget.js
```js
  ...
  if (this.ontoggle) {
    this.ontoggle({ checked: this.checked });
  }
  ...
```

---

Another example, to make it more clear:

```html
<checkbox-widget ontoggle.call="selected(LOOK__sOme__ArGumEnt__)"></checkbox-widget>
```

checkbox-widget.js
```js
  ...
  if (this.ontoggle) {
    this.ontoggle({ LOOK__sOme__ArGumEnt__: this.checked });
  }
  ...
```

**Comment by peisenmann** [comment]
:+1 This works for me, but I would have never known that this was possible. I think the above example would be great to have on the docs.

**Comment by stoffeastrom** [comment]
@jdanyow I really hope it's still possible to mix in view specific variables?

```
<checkbox-widget ontoggle.call="selected(LOOK__sOme__ArGumEnt, LOOK_SOME_OTHER_VIEW_SPECIFIC_ARG )"></checkbox-widget>
```

**Comment by jdanyow** [comment]
@stoffeastrom definitely!

`call` / `delegate` / `trigger` support any method invocation expression... multiple args, no args, whatever. The expression is evaluated when the event fires (in `delegate`/`trigger` scenarios) or when the behavior invokes the method (in `call`) scenarios.

Here's a concrete example:
```js
export class App {
  foo = 'foo';
}
```
```html
<input ref="myInput">
<div mousemove.delegate="helloWorld.doSomething(foo, myInput.value, $event)"></div>
```

When the mousemove event fires, the delegate binding will add the actual DOM event to a property on the scope named `$event`. Then it will evaluate the  `helloWorld.doSomething(foo, myInput.value, $event)` expression, just like it would if you were using it in a string interpolation expression like this `${helloWorld.doSomething(foo, myInput.value, $event)}`.

What's special about the `call` binding is the custom element/attribute is you get to define what properties get added to the scope and thus available for data-binding.  For example let's say you had a custom element with a `click` bindable property:

my-element.js
```js
export class MyElement {
  @bindable click;
  ...
  notifyClick(e) {
    // this makes "x" and "y" available for binding purposes:
    let args = { x: e.clientX, y: e.clientY };
    this.click(args);
  }
  ...
}
```
app.js
```js
export class App {
  something = 'hello world';
}
```
app.html
```html
<my-element click.call="handleClick(x, y, something)"></my-element>
```html

**Comment by stoffeastrom** [comment]
:+1:

**Comment by cirelli94** [comment]
Nowadays it still not in the [cheat sheet](https://aurelia.io/docs/fundamentals/cheat-sheet#custom-elements), or I'm wrong?

**Comment by EisenbergEffect** [comment]
@cirelli94 I went looking and didn't find that detail either. It must has slipped through the cracks. Would you be interested in submitting a PR to our documention? It would be a great contribution and would help the community. Here's the source file for the cheat sheet: https://github.com/aurelia/framework/blob/master/doc/article/en-US/cheat-sheet.md If you wanted to go for extra credit, you could also add a section to the end of this document: https://github.com/aurelia/binding/blob/master/doc/article/en-US/binding-delegate-vs-trigger.md It would really help us out!
