### ISSUE TITLE
Bindable attributes may lose values set during bind()

### ISSUE THREAD

**Issue by sylvain-hamel** [aurelia/binding#272]
@jdanyow [this commit]( https://github.com/aurelia/binding/commit/917e61d6216207a35d532c48fcc72407ccc44f0c) has caused an intermittent behavior.

Given this custom element:
```
export class MyElement{
    @bindable attribute1;
    @bindable attribute2;
    bind(){
        if(!this.attribute1){
            this.attribute1 = this.attribute2;
        }
    }
}
```

Used like this:
```
<my-element attribute2="foo"> <!-- leave attribute1 unset -->
```
If there are more than 100 bindings in the page (`minimumImmediate`) then the binding connection is differed. When it is later connected, it overwrites the value assigned to `attribute1` during `bind()` with `undefined`.

**Comment by sylvain-hamel** [comment]
I patched my `aurelia.js` this way in the mean time:

```
Binding.prototype.bind = function bind(source) {
  ...
  if (mode === bindingMode.oneWay) {

    // PATCH
    // enqueueBindingConnect(this);
    sourceExpression.connect(this, source);
  } else if (mode === bindingMode.twoWay) {
    sourceExpression.connect(this, source);
    this.targetObserver.subscribe(targetContext, this);
  }
  ...
```

**Comment by jdanyow** [comment]
@sylvain-hamel why is there a binding instance being connected to the `attribute1` property?

**Comment by sylvain-hamel** [comment]
@jdanyow I'm sorry I made a mistake when I wrote the markup in my original post. In my real case, attribute1 is always set but does not always have a value. The markup would be closer to this:

```
<my-element attribute2="ob1.foo" attribute1="obj1.bar"> <!-- bar's value is undefined -->
```

If you can't reproduce it from this, I can write a test case. I wanted to submit this issue  with a  Plunkr but I could not find an up-to-date plunkr to fork.

**Comment by jdanyow** [comment]
`attribute1` is bound to the `obj.bar` expression.  This means the binding system is responsible for keeping them `attribute1` in sync with `obj.bar`.  By manually assigning `attribute1` you are interfering with this logic. Use a one-time or two-way binding and things will work as you expect.  You could also set the default binding mode for this `attribute1` to make this a little easier.
