### ISSUE TITLE
Select list - get id within delegate call

### ISSUE THREAD

**Issue by bischofb** [aurelia/binding#275]
Is there a way for a generic/shared delegate function that is attached to a select list to know the id of which item was selected? I currently have it working by using change.delegate = "optionChanged($event)". Then, in optionChanged() function I get the value.bind attribute from the $event.srcElement to determine which field it is bound to and then use that to get the value from the this[] collection. Lots of hoops to jump through! Is there an easier way?

**Comment by EisenbergEffect** [comment]
You can pass anything into your method. So, if you have a local view-model property that you want, you can just pass that. You could also use `ref` to give a local name to the HTML element itself and then pass that in if it's the actual element you want.

**Comment by bischofb** [comment]
Hmmm, that seems painfully obvious now. :-(  Thanks!
