### ISSUE TITLE
Binding error in value converter causes view not to load and does not report error.

### ISSUE THREAD

**Issue by kdawg1406** [aurelia/binding#278]
ANY error in value converter will result in the view not loading and no errors appear in the console.  Effectively swallowing the error.  Developer debug experience is poor since even a typo will result in an error that can't be located.

To Repro:

Take any binding that has a converter that has one parameter, just pass: BOGUS as below, the view won’t load.

${myModelProperty | myConverter:BOGUS }

Thanks,

Karl

**Comment by EisenbergEffect** [comment]
@jdanyow Important note about this that it's not the BOGUS symbol in the expression that is causing the problem. It's the fact that the myConverter converter attempts to use a parameter which is undefined, resulting in an error inside the toView method of the converter. We probably need some way to ensure that any errors that occur inside converters are logged.

**Comment by jdanyow** [comment]
I'm seeing an error in the console here: http://plnkr.co/edit/oHcQSk?p=preview

Will test with the router.

**Comment by kdawg1406** [comment]
Strange.

This was my scenario that caused the problem, the 1st parameter BOGUS.  Now
it's not.

<template>
  <H1>HI</H1>
  ${message | error:BOGUS}
</template>

**Comment by kdawg1406** [comment]
Jeremy,

Throwing in the converter was not my scenario, probably a good test to see that the router does not quit working.

Karl

**Comment by jdanyow** [comment]
Ah- I see what you mean- given a binding expression like this `${message | myConverter:myArgument}`, there are no errors in the console when `myArgument` is not defined (eg the view-model has no `myArgument` property).

We've got an open issue for this here:  https://github.com/aurelia/binding/issues/30

**Comment by EisenbergEffect** [comment]
I think it's two things. One is the bogus parameter not being detected and the thing that really cause stuff to "break" was probably that the converter expected a value and tried to work with that in a way that an exception was thrown.
