### ISSUE TITLE
Binding fails for undefined variables

### ISSUE THREAD

**Issue by Vaccano** [aurelia/binding#280]
I have a `select` that looks like this:

    <select class="form-control" value.bind="selectedRoute" change.trigger="routeChanged()" >
         <option class="dropdown-toggle" repeat.for="route of LocalCourierRoutes" model.two-way="route">${route.LocalCourierRouteNumber}</option>
    </select>

The releveant script looks like this:

    selectedRoute;

    routeChanged() {
        this.originStore.Route = this.selectedRoute;
    }

When`routeChanged` is called,  `this.selectedRoute` is undefined. (The core problem I was researching.)

To try to debug this, I changed my definition of `selectedRoute` to this:

    selecteRoute = null;

With this change, when `routeChanged` is called, `this.selectedRoute` is correctly defined.

So somehow, changing `selectedRoute` to be defined fixed my binding issue.

**Comment by Vaccano** [comment]
Think the core of this may include variables that are not initialized.

If I change the above to have `selectedRoute` be declared like this: `selectedRoute = {};` instead of just `selectedRoute;` then the binding starts working (similar to if I use the property).

I am guessing that the property somehow initializes the underlying variable...  (Just a guess).

**Comment by Vaccano** [comment]
As a side note, changing this:

    selectedRoute;

to be a property, like this:

    _selectedRoute;
    get selectedRoute() {
        return this._selectedRoute;
    }

    set selectedRoute(newSelectedRoute) {
        this._selectedRoute = newSelectedRoute;
    }

had the same effect as initializing it (like shown in my first post).

**Comment by jdanyow** [comment]
@Vaccano could you please put together a plunker demonstrating this issue?
http://bit.ly/aurelia-plunker

**Comment by Vaccano** [comment]
I would be willing to try.  I have not used plunker before.  

I went to the link you provided and the live preview stays at "Loading...."

I looked at the F12 console and it says:

> GET https://cdn.rawgit.com/jdanyow/aurelia-plunker/v0.10.0/jspm_packages/npm/aurelia-logging-console@1.0.0-beta.1.js 404 (Not Found)
> Unhandled promise rejection Error: XHR error (404 Not Found) loading https://cdn.rawgit.com/jdanyow/aurelia-plunker/v0.10.0/jspm_packages/npm/aurelia-logging-console@1.0.0-beta.1.js

My company network is really weird about HTTPS so it could be me, but when I go to *https://cdn.rawgit.com/jdanyow/aurelia-plunker/v0.10.0/jspm_packages/npm/aurelia-logging-console@1.0.0-beta.1.js* I get:

404 Not Found

I dunno what you expected, but it ain't here.

Is this just me?  (If so I will see if I can do the plunker at home.)

**Comment by jdanyow** [comment]
refresh it- sometimes it's slow

**Comment by Vaccano** [comment]
@jdanyow I tried to get it to fail using plunker.  I could not.  I thought maybe it would be related to being in a <template>, but I could not get that working. (http://plnkr.co/edit/DIeN4PVvTTOzr5Rd4Qfs?p=preview)

I am guessing that this is related to me using Typescript and "frakewalis plugin-typescript".

It is not a big deal for me to just initialize all my variables.  (It is a good practice anyway.)

**Comment by jdanyow** [comment]
ok, closing- please re-open if you have a repro
