### ISSUE TITLE
Request. Add datatype to binding signature.

### ISSUE THREAD

**Issue by EvernightX** [aurelia/binding#282]
It would be useful if when defining a bindable you could specify a datatype. Something like
bindable({
  name:'max',
  attribute:'max',
  changeHandler:'maxChanged',
  defaultBindingMode: bindingMode.oneWay,
  defaultValue: 5,
 **dataType: number**
})

And have Aurelia attempt to cast the incoming value to that type if necessary. This would help with scenarios like:

```
<custom-element max="10"></custom-element>
```
Where max should be a number but will end up being a string.  

Another possible solution would be a way to do the casting inside maxChanged in such away that maxChanged won't get called an additional time when assigning the casted value back to the bindable.

**Comment by jdanyow** [comment]
this is on the backlog: https://github.com/aurelia/templating/issues/96

**Comment by EvernightX** [comment]
OK. Glad to know it may happen at some point.
