### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by JimmiV** [aurelia/binding#284]
Documentation
Binding Behaviors
Signal example doesn't work with Edge.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you check that out in the docs and see if its an issue with the example or something in Aurelia itself?

**Comment by jdanyow** [comment]
works for me: http://screencast.com/t/H0taY6dW

**Comment by JimmiV** [comment]
Can't open your link with edge or chrome ... but I trust you :-)
