### ISSUE TITLE
iOS safari connect-queue error

### ISSUE THREAD

**Issue by jonnyynnoj** [aurelia/binding#285]
Getting the following error in iOS safari:

```
undefined is not an object (evaluating '_aureliaPal.PLATFORM.performance.now' )
```

Some quick console.logs show that `PLATFORM.performance` is undefined.

**Comment by jdanyow** [comment]
What version of iOS?

http://caniuse.com/#search=performance

**Comment by jonnyynnoj** [comment]
8.4, sorry should have said. Is this something we're supposed to polyfill ourselves?

**Comment by jdanyow** [comment]
apologies, yes you'll need a polyfill- it's mentioned [here](http://blog.durandal.io/2015/12/17/more-aurelia-performance-bug-fixes-docs-and-typescript-awesome/) but not in the docs yet.

**Comment by EisenbergEffect** [comment]
Closing as not an issue.

**Comment by EisenbergEffect** [comment]
Oops re-opening so we can document this better...

**Comment by EisenbergEffect** [comment]
@jdanyow I think our docs are still not up to date. What are all the polyfills that are needed for legacy browser support?

The docs currently state:

* MutationObserver
* RAF

Is a performance polyfill also needed?

**Comment by jdanyow** [comment]
closing:  performance polyfill is now part of pal-browser
