### ISSUE TITLE
TypeScript compiling error TS7006

### ISSUE THREAD

**Issue by hoangcuongvn** [aurelia/binding#286]
When noImplicitAny is set to true I see the TS7006 error which points to the method:
export function mergeSplice(splices, index, removed, addedCount): any;

error TS7006: Build: Parameter 'splices' implicitly has an 'any' type. 
error TS7006: Build: Parameter 'index' implicitly has an 'any' type.
error TS7006: Build: Parameter 'removed' implicitly has an 'any' type.
error TS7006: Build: Parameter 'addedCount' implicitly has an 'any' type.

**Comment by jdanyow** [comment]
@hoangcuongvn thanks for reporting this- care to take make a PR with the fix?  The change would be here: https://github.com/aurelia/binding/blob/master/src/aurelia-binding.d.ts#L404
