### ISSUE TITLE
bindableArrayChanged function of custom element not called for bindableArray property

### ISSUE THREAD

**Issue by genadis** [aurelia/binding#288]
Please see the following plunker to demonstrate:

https://plnkr.co/edit/6lrE7K1NITssUeSzoUoj?p=preview

bound array property behaves differently than bound simple properties (string/number).
For simple property the `Changed` function is called but for array it is not.

**Comment by jdanyow** [comment]
Hi @genadis, this is a common misunderstanding, let me attempt to explain.

There's a difference between a property change (eg `foo.bar = ['baz']`) and array mutation (eg `foo.bar.push('baz')`). In the former, the bar property's value change to a different array instance.  In the latter, the bar property remains the same array instance. The changed callback is only invoked for property changes, not for array mutation.

**Comment by genadis** [comment]
Got it, thank you for the explanation.
I'll keep using `ObserverLocator` for array/map mutation tracking.
