### ISSUE TITLE
Manually added observers are lost after bound object is recreated

### ISSUE THREAD

**Issue by timbell** [aurelia/binding#292]
Plunker demonstrating the issue: http://plnkr.co/edit/YkYv8b?p=preview

Is there something I can do to have the manually added observer recreated automatically on object recreation?

**Comment by jdanyow** [comment]
yep: http://plnkr.co/edit/Po4gjN?p=preview

only changes are in `test.js`

**Comment by timbell** [comment]
Brilliant, thanks for the help. (Still a bit new to this - I'd forgotten about the xyzChanged callbacks.)
