### ISSUE TITLE
Binding custom attribute parameter to an array does not seem to observe changes

### ISSUE THREAD

**Issue by philiphendry** [aurelia/binding#297]
I've created a [plunkr](http://embed.plnkr.co/gALLyX/) to demonstrate the issue. The general gist of it is I'm trying to define a view model property as an array then bind it to a custom attribute which should observe for changes but never seems to get triggered except the initial time. 

So the view model defines the array:

```
   mydata = ["first", "second", "third"];
```

which the view binds to the attribute:

```
   <div myattr="param.bind = mydata"></div>
```

and which the attribute observes:

```
   export class myattrAttribute {
       @bindable param;

       paramChanged(newValue) {
            // this never fires for an array
       }
   }

**Comment by genadis** [comment]
I believe issue  #288 is related. 
@jdanyow gave great explanation

**Comment by jdanyow** [comment]
thanks @genadis

**Comment by philiphendry** [comment]
Thanks guys
