### ISSUE TITLE
innerHTML / Binding not working

### ISSUE THREAD

**Issue by hmarcelodn** [aurelia/binding#298]
Hi guys,

I have an element like the one below

**innerHTML.bind="filler(col, item)"**

I need to be able to bind the raw HTML returned attributes. In my example I need to bind value attr. Example

		this.renders["check"] = function(col, item){
			return '<input type="input" value.bind="${hola}"/>';
		};
How can I accomplish that?

Thanks.

**Comment by Mordred** [comment]
Try `innerhtml.bind` instead of `innerHTML.bind`

**Comment by hmarcelodn** [comment]
It did not work.

		this.renders["check"] = function(col, item){
			return '<input type="input" value.bind="${200 + 1}"/>';
		};

I changed to that simple example. It did not work.

**Comment by jdanyow** [comment]
The innerhtml binding doesn't compile templates- docs here: http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.1.1/doc/article/cheat-sheet

More info on using the view-compiler here:
https://github.com/aurelia/templating/issues/35

In general you want to avoid using aurelia this way- there are often better approaches using html templating than construction your markup from strings.

**Comment by AStoker** [comment]
This might be a separate issue. If so, let me know.
I'm using the `innerHTML.bind` on an svg for a custom element. This works in all browsers by IE.
``` html
<template>
    <svg innerHTML.bind="svgParts"></svg>
</template>
```
`svgParts` is a string that represents the insides of an svg. Works on everything by IE.

**Comment by jdanyow** [comment]
@AStoker please do open a separate issue- additional details about the version(s) of IE and a [running example](http://bit.ly/aurelia-plunker) would be appreciated!

**Comment by hmarcelodn** [comment]
@AStoker I tried to use Aurelia sintax inside an Aurelia loop context and it was not working. Is that your case? I had to change my approach to get what I wanted. Guys here says it doesnt compile Aurelia sintax inside strings. I will looking forward to your running example. Thanks!

**Comment by AStoker** [comment]
@hmarcelodn, no, that's not my case. I'll open a new story with an example. Edge and IE both have horrible support for SVG stuff, and my guess is the way they're loading up the html content just isn't supported by the browser.
