### ISSUE TITLE
background-image broken in latest versions

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/binding#301]
Something changed in the latest version of Aurelia, breaking the `background-image` style.

```
<div style="background-image: url(http://demos.telerik.com/kendo-ui/content/web/Customers/${CustomerID}.jpg);"></div>
```

gets resolved to

![image](https://cloud.githubusercontent.com/assets/2189477/12764020/cf2e9b04-c9f7-11e5-8273-6f94f419f182.png)

which gives a 404 to "localhost:3000/http"

I have reproduced it here: https://github.com/JeroenVinke/background-image-bug/tree/master/src

I reverted to the previous versions and it worked with those

**Comment by stoffeastrom** [comment]
Could it be [this](https://github.com/z-brooks/binding/commit/a0101c0477954a52b16d8aa33f9d9c9d9b222829#diff-0e7b75111aff8a0702dcf38efb8c5278R82)? I'm not a regexp guy so not sure ;)

**Comment by EisenbergEffect** [comment]
Actually, you shouldn't use `style` with interpolation bindings. It isn't supported cross-browser. Try changing it to `css` instead. Let me know if that works.

**Comment by jdanyow** [comment]
The regex is splitting on the `:` in the url.  cc @z-brooks

**Comment by z-brooks** [comment]
I see. I think that should fix it. New regex only splits if `:` is not followed by `/`.

**Comment by Gheoan** [comment]
In my opinion, a regex is not enough, we need a parser.

**Comment by JeroenVinke** [comment]
@EisenbergEffect 

The `css` attribute is not an option unfortunately due to [this issue](https://github.com/aurelia/templating/issues/229). Thanks @z-brooks and @jdanyow  for the quick response (and the proposed fix).

**Comment by leye0** [comment]
With the regex it fails on any url with a port.

![image](https://cloud.githubusercontent.com/assets/3464994/17784828/ff0d9b32-654b-11e6-8a19-ca8dc3cdea07.png)
