### ISSUE TITLE
Splice then push causes view not to show on bound array

### ISSUE THREAD

**Issue by michaelmalonenz** [aurelia/binding#302]
So, this one is a little bit complicated to explain, but essentially, the view of a child viewmodel stops displaying under certain conditions.

I have reproduced the issue here:
https://github.com/michaelmalonenz/skeleton-navigation/tree/playground

In order to reproduce, once the view is loaded, drag the last item (in any column, but the middle is most accessible) to the second-to-last position and see it disappear.  After that, drag the last item to the second-to-last position _twice_ to see it disappear.  This makes me think there is an off-by-one error somewhere.

The reason why I think it is a binding bug, is because of the code here:
https://github.com/michaelmalonenz/skeleton-navigation/blob/playground/src/board/board.js#L51-L54

Uncommenting Lines 52 & 53 and then commenting L54 makes the problem much more difficult to reproduce (but it still can be done with persistence).

**Comment by EisenbergEffect** [comment]
@jdanyow @martingust Can you guys take a look?

**Comment by jdanyow** [comment]
@michaelmalonenz I think you need to cancel the drop.  If you let dragula mutate the DOM you'll leave the repeat/viewslot in a bad state.

More info [here](http://www.danyow.net/drag-and-drop-with-aurelia/).

Essentially [this](https://github.com/jdanyow/aurelia-solitaire/blob/master/src/drag-and-drop.js#L41) is needed [here](https://github.com/michaelmalonenz/skeleton-navigation/blob/playground/src/board/draganddrop.js#L43).

**Comment by michaelmalonenz** [comment]
@jdanyow if I cancel the drop, I get partial elements being left in the DOM, which messes up its ability to order the elements.  I will have a go at reproducing without dragula involved at all.

**Comment by michaelmalonenz** [comment]
@jdanyow You're quite right, removing dragula from the equation makes the problem go away.  Dragula still mutates the DOM on `cancel()` (i.e. attempts to put the dragged object back to where it was) but it isn't paying attention to the comment nodes like `<!--<view>-->`.  

If I put the element back where it was originally myself, will the repeat/viewslot be in a good state?  It appears to work, even if I am doing [terrible](https://github.com/michaelmalonenz/skeleton-navigation/blob/playground/src/board/draganddrop.js#L38-L41) [things](https://github.com/michaelmalonenz/skeleton-navigation/blob/playground/src/board/draganddrop.js#L48-L49) to get there.
