### ISSUE TITLE
Binding to 'length' property of filtered array causes parser error

### ISSUE THREAD

**Issue by larserikfinholt** [aurelia/binding#306]
Hi! Unsure if a bug, or maybe just unsupported syntax. Given:
```html
<tr repeat.for="c of contractors">
       <td>${c.name}</td>
       <td>${($parent.bookings|byContractorId:c.id).length}</td>
</tr>
```

I get the following error: 

> Unhandled promise rejection Error: Parser Error: Missing expected ) at column 18 in [($parent.bookings|byContractorId:c.id).length]

**Comment by fopsdev** [comment]
if you are on a current version you can remove $parent. not sure if this has anything to do with the issue but it is worth a try.

**Comment by jdanyow** [comment]
once a binding expression transitions to a converter expression you'll only be able to use converters and binding behaviors in the expression.  A converter expression cannot be wrapped in a javascript expression.

Try:

```html
<td>${bookings | byContractorId:c.id | length}</td>
```

```js
export class LengthValueConverter {
  toView(value) {
    return value.length;
  }
}
```
