### ISSUE TITLE
Template binding doesn't work when the bound variable name is mixed case

### ISSUE THREAD

**Issue by derkork** [aurelia/binding#307]
I have a template defined like this:

    <template bindable="testStep">

    <div class="form-group">
        <label for="name">Name</label>
        <input class="form-control" type="text" id="name" value.bind="testStep.name">
    </div>

    <div class="form-group">
        <label for="executor">Executor</label>
        <input class="form-control" type="text" id="executor" value.bind="testStep.executor">
    </div>
    </template>

Now I use this template in another template:

    <require from="./test-step-form.html"></require>
    <test-step-form testStep.bind="testStep"></test-step-form>

Result: the testStep variable is not bound to the inner template. When I rename the bindable variable in the inner template to  `teststep` (all lower case) 

    <template bindable="teststep">

    <div class="form-group">
        <label for="name">Name</label>
        <input class="form-control" type="text" id="name" value.bind="teststep.name">
    </div>

    <div class="form-group">
        <label for="executor">Executor</label>
        <input class="form-control" type="text" id="executor" value.bind="teststep.executor">
    </div>
    </template>

and use it like this:

    <require from="./test-step-form.html"></require>
    <test-step-form` teststep.bind="testStep"></test-step-form>

then the binding works. Browser is Chrome 48.

**Comment by jdanyow** [comment]
Any custom element class names or custom element bindable properties that have mixed case are converted to kebab-case because the DOM is case-insensitive:

 `selected-value.bind="property"`

 **not**

 `selectedValue.bind="property"`

**Comment by derkork** [comment]
I see. Thank you very much for the explanation :)
