### ISSUE TITLE
Export Listener class

### ISSUE THREAD

**Issue by heruan** [aurelia/binding#308]
The `Listener` class defined in [listener-expression.js](https://github.com/aurelia/binding/blob/master/src/listener-expression.js#L25) is not exported from the package (at least in the `.d.ts` file).

Since `Listener` is the type of the first argument for the `bind()` methods of a custom Binding Behavior, in a TypeScript project would be useful to type the argument, but the class is not exported.

Would it be possibile to export it (and maybe `ListenerExpression` and other classes which may be useful for building new bindings)?

**Comment by jdanyow** [comment]
Hi @heruan- use `Binding`: https://github.com/aurelia/binding/blob/master/src/aurelia-binding.d.ts#L212

its the interface that the different binding instance classes implement (Listener, Name, Binding, Call, etc).

**Comment by heruan** [comment]
Thank you!
