### ISSUE TITLE
Feature request: new Date() in binding expression

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/binding#312]
```
<template>
  ${new Date()}
</template>
```

throws

![image](https://cloud.githubusercontent.com/assets/2189477/12866247/2075c8ac-ccc8-11e5-9b0a-07147fda4f2e.png)

plunker: http://plnkr.co/edit/ruuN4a?p=preview

Now we have to create a property (with `new Date()` as value) in the view-model, and we have to bind to that. It would be great if we could use `new Date()` in a binding expression.

**Comment by jdanyow** [comment]
checked into this, what's happening is the parser doesn't support `new` and is incorrectly parsing the expression as a Chain containing an AccessScope (`new`) and a CallScope (`Date()`).

![expression](http://i.imgur.com/skva5bc.png)

Aurelia has never supported globals in binding expressions (eg `Math.round` etc).  This enhancement request is along the same lines. @EisenbergEffect - what are your thoughts on this one?

**Comment by EisenbergEffect** [comment]
I'd rather not support extending the expression syntax to support new or globals. I think we get into some security issues there and I really want our binding language to be more "glue" than "code".
