### ISSUE TITLE
select bind does not work with the current skeleton

### ISSUE THREAD

**Issue by clerik** [aurelia/binding#313]
Using the current skeleton, when binding a select (`<select value.bind="someProperty">`) I received the following error: `ReferenceError: SelectValueObserver is not defined`

I searched for SelectValueObserver all over the sources from the skeleton but only find one usage and no declaration.

Here's the full trace:

> DEBUG [aurelia] Loading plugin file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/aurelia-templating-binding@1.0.0-beta.1.1.0.
> aurelia...sole.js (line 38)
> DEBUG [aurelia] Configured plugin file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/aurelia-templating-binding@1.0.0-beta.1.1.0.
> aurelia...sole.js (line 38)
> DEBUG [aurelia] Loading plugin file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/aurelia-templating-resources@1.0.0-beta.1.1.0.
> aurelia...sole.js (line 38)
> DEBUG [aurelia] Configured plugin file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/aurelia-templating-resources@1.0.0-beta.1.1.0.
> aurelia...sole.js (line 38)
> DEBUG [aurelia] Loading plugin file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/aurelia-history-browser@1.0.0-beta.1.1.1.
> aurelia...sole.js (line 38)
> DEBUG [aurelia] Configured plugin file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/aurelia-history-browser@1.0.0-beta.1.1.1.
> aurelia...sole.js (line 38)
> DEBUG [aurelia] Loading plugin file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/aurelia-templating-router@1.0.0-beta.1.1.0.
> aurelia...sole.js (line 38)
> DEBUG [aurelia] Configured plugin file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/aurelia-templating-router@1.0.0-beta.1.1.0.
> aurelia...sole.js (line 38)
> DEBUG [aurelia] Loading plugin file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/aurelia-event-aggregator@1.0.0-beta.1.1.0.
> aurelia...sole.js (line 38)
> DEBUG [aurelia] Configured plugin file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/aurelia-event-aggregator@1.0.0-beta.1.1.0.
> aurelia...sole.js (line 38)
> INFO [aurelia] Aurelia Started
> aurelia...sole.js (line 46)
> DEBUG [templating] importing resources for file:///C:/DATA/Projects/rules/ui/src/app.html ["semantic-ui/semantic.min.css"]
> aurelia...sole.js (line 38)
> DEBUG [templating] importing resources for file:///C:/DATA/Projects/rules/ui/src/welcome.html []
> aurelia...sole.js (line 38)
> **Unhandled promise rejection
> ReferenceError: SelectValueObserver is not defined**
> createPropertyObserver@file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/aurelia-binding()1.0.0-b...ding.js (line 4040)
> getObserver@file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/aurelia-binding()1.0.0-b...ding.js (line 3974)
> bind@file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/aurelia-binding()1.0.0-b...ding.js (line 4252)
> bind@file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/aurelia-templating()1.0.0-b...ting.js (line 837)
> bind@file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/aurelia-templating()1.0.0-b...ting.js (line 2766)
> automate@file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/aurelia-templating()1.0.0-b...ting.js (line 2712)
> swap/<@file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/aurelia-templating-router()1.0.0-b...view.js (line 116)
> r/</g@file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/core-js()2.0.3/c....min.js (line 1921)
> r/<@file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/core-js()2.0.3/c....min.js (line 1926)
> e@file:///C:/DATA/Projects/rules/ui/jspm_packages/npm/core-js()2.0.3/c....min.js (line 2169)
> 	
> 
> shim.min.js (line 1940)

**Comment by jdanyow** [comment]
there was a bug in a recent release that broke select element binding (the SelectValueObserver wasn't included in the build).  This has since been fixed.
