### ISSUE TITLE
@bindable causes issue on child classes extended by "extends" inheritance

### ISSUE THREAD

**Issue by genadis** [aurelia/binding#316]
I've updated my project to latest aurelia release and started getting errors:
"Unhandled promise rejection TypeError: Cannot read property 'getValue' of undefined"
"Unhandled promise rejection TypeError: Cannot read property 'setValue' of undefined"

My use case is:
```
export class A {
   @bindable foo = true;

    // make use of foo property
}
```
```
export class B extends A {
}
```
Class A/B are custom elements I dynamically compose.
As soon as I add:
```
export class B extends A {
    @bindable foo = true;   // Add the bindable property to the parent class as well.
}
```
The problem goes away.

Again it started to happen after update.

Thanks!

**Comment by EisenbergEffect** [comment]
Inheritance of bindables was never supported. If it worked...it was temporarily and accidentally and probably not correctly. I'm closing this issue since we are tracking this already elsewhere as a future feature.

**Comment by genadis** [comment]
Thank you for quick response.
I think it's good idea to document it (or is it already, and I missed it?), since it took me while to track it down.
The error look like:
![errpr](https://cloud.githubusercontent.com/assets/6747147/13060383/a70eedda-d439-11e5-80bc-4999f0882d45.png)

**Comment by EisenbergEffect** [comment]
Would you be willing to submit a PR to our cheat sheet? It's located in the doc folder of the framework repo.

**Comment by genadis** [comment]
Sure

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.91&pv=5.0&source=email_footer_2] On Mon, Feb 15, 2016 at 11:19 PM, Rob Eisenberg < notifications@github.com [notifications@github.com] > wrote:
Would you be willing to submit a PR to our cheat sheet? It's located in the doc
folder of the framework repo.

—
Reply to this email directly or view it on GitHub
[https://github.com/aurelia/binding/issues/316#issuecomment-184400698] .[https://github.com/notifications/beacon/AGb0C1SR43ItopQTxz4iwGBonmmrvh9Bks5pkjhFgaJpZM4Hap20.gif]

**Comment by jwx** [comment]
Any progress or news on the future feature that will support this?

**Comment by EisenbergEffect** [comment]
We have a PR we are going to be reviewing soon.

**Comment by jwx** [comment]
Excellent. Hopefully this will fix http://stackoverflow.com/questions/41475364/aurelia-bug-with-bindable-in-combination-with-class-decorator .

**Comment by jwx** [comment]
@EisenbergEffect Any news on this? (I couldn't find a fitting PR.)

**Comment by EisenbergEffect** [comment]
The PR relates to inheritance: https://github.com/aurelia/templating/pull/507
