### ISSUE TITLE
Why EventManager contract is limited in d.ts?

### ISSUE THREAD

**Issue by fshchudlo** [aurelia/binding#317]
It's not a bug, just question and possible enhancement.
I want to write custom attribute for elements in list. This custom attribute attaches event handlers to elements and it's reasonable to use event delegation. 
Source code exploration gives me `EventManager.addEventListener` method. I've tried to use this method and it works correctly for both attaching and detaching handlers.
But I see that `aurelia-binding.d.ts` file doesn't declare this method and I don't understand why. Is it unsafe to use?

**Comment by jdanyow** [comment]
Good call- `EventManager.addEventListener` should be added to binding's public API.  This method is definitely safe to use.  Would you be interested in submitting a PR that adds this to the `aurelia-binding.d.ts` file in the `src` folder?

**Comment by fshchudlo** [comment]
@jdanyow Did this

**Comment by jdanyow** [comment]
@fshchudlo much appreciated.

@EisenbergEffect CLA check

**Comment by EisenbergEffect** [comment]
@jdanyow CLA is confirmed. Thank you @fshchudlo for joining in the fun of contributing!

**Comment by fshchudlo** [comment]
@EisenbergEffect Thanks to you for great framework )
