### ISSUE TITLE
Problem with self-closed tags custom elements 

### ISSUE THREAD

**Issue by fshchudlo** [aurelia/binding#318]
When I use custom element with self-closing tag then all sibling elements are disappeared
Super simple custom element:
```javascript
import {inlineView, containerless} from 'aurelia-framework';
@inlineView('<template>${rowNumber}</template>')
@containerless()
export class RowNumberCustomElement
{
        rowNumber: number;
        bind(bindingContext: any, overrideContext: any)
        {
            this.rowNumber = overrideContext.$index + 1;
        }
}
```
If I use it like this:

```html
<div repeat.for="item of items">
    <row-number/>
    <span>${$index}</span>
</div>
```
it renders "1 2 3" instead of "10 21 32".
If i use `<row-number></row-number>` and even `<row-number/></row-number>` (with additional slash) everything renders correctly. When I add `<content/>` to element template it also renders correctly.

**Comment by jsobell** [comment]
Self closing tags are not the same as empty tags, and they don't create the inner element in the DOM. That's why all the documentation says to use the opening and closing tags.
I don't think this is an issue.

**Comment by fshchudlo** [comment]
I agree with you that self closing tags and empty tags are not the same.
But now self-closing tag can be used (no errors), it creates inner elements, and it renders siblings as childs (if I use `<content/>` tag).
The fact that additional slash in `<row-number/></row-number>` fixes this situation means that binding engine just can't process this situation correctly.
I think that at least error must be thrown in this situation

**Comment by jsobell** [comment]
The binding engine is not given the DOM of the template until the browser has loaded and parsed it, and given that the trailing slash is invalid, the browser probably removed it, hence the template worked.
Errors are not thrown for self-closing script tags either, and they are simply ignored, and I think this falls into the same category.

**Comment by EisenbergEffect** [comment]
@fshchudlo The browser only supports self-closing tags for a very specific set of known elements. You cannot create custom self-closing tags.
