### ISSUE TITLE
ERROR [app-router] RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by tommasop** [aurelia/binding#324]
I'm using the master version of skeleton-es2016.

I'm trying to import paper.js in an Aurelia model:

`jspm install npm:paper`

canvas.js
```
import paper from 'paper';

export class Canvas {
  heading = 'Canvas check';
}
```

canvas.html
```
<template>
  <section class="au-animate">
    <h2>${heading}</h2>
    <canvas ref="testCanvas"></canvas>
  </section>
</template>
```

When I navigate on the Canvas page I receive the:

`ERROR [app-router] RangeError: Maximum call stack size exceeded`

This is the stack:

```
error	@	aurelia-logging-console.js:62
log	@	aurelia-logging.js:36
error	@	aurelia-logging.js:69
processResult	@	aurelia-router.js:1629
(anonymous function)	@	aurelia-router.js:1582
g	@	shim.min.js:1921
(anonymous function)	@	shim.min.js:1926
e	@	shim.min.js:2169
Mutation (async)		
g	@	shim.min.js:2180
asap	@	shim.min.js:2194
r	@	shim.min.js:1910
m	@	shim.min.js:1987
(anonymous function)	@	shim.min.js:300
a	@	system.src.js:4597
s.onreadystatechange	@	system.src.js:4597
XMLHttpRequest.send (async)		
I	@	system.src.js:4597
(anonymous function)	@	system.src.js:4597
Promise	@	shim.min.js:1999
(anonymous function)	@	system.src.js:4597
(anonymous function)	@	system.src.js:4597
(anonymous function)	@	system.src.js:4597
(anonymous function)	@	system.src.js:4597
(anonymous function)	@	system.src.js:4597
(anonymous function)	@	system.src.js:4597
(anonymous function)	@	system.src.js:4597
(anonymous function)	@	system.src.js:4597
g	@	shim.min.js:1921
(anonymous function)	@	shim.min.js:1926
e	@	shim.min.js:2169
Mutation (async)		
g	@	shim.min.js:2180
asap	@	shim.min.js:2194
r	@	shim.min.js:1910
m	@	shim.min.js:1987
(anonymous function)	@	shim.min.js:300
a	@	system.src.js:4597
s.onreadystatechange	@	system.src.js:4597
XMLHttpRequest.send (async)		
I	@	system.src.js:4597
(anonymous function)	@	system.src.js:4597
Promise	@	shim.min.js:1999
(anonymous function)	@	system.src.js:4597
(anonymous function)	@	system.src.js:4597
(anonymous function)	@	system.src.js:4597
(anonymous function)	@	system.src.js:4597
(anonymous function)	@	system.src.js:4597
(anonymous function)	@	system.src.js:4597
(anonymous function)	@	system.src.js:4597
(anonymous function)	@	system.src.js:4597
g	@	shim.min.js:1921
(anonymous function)	@	shim.min.js:1926
e	@	shim.min.js:2169
```

**Comment by EisenbergEffect** [comment]
If you remove the import of "paper" does the problem go away?
This doesn't sound like an Aurelia issue...but maybe a system.js issue.

**Comment by tommasop** [comment]
I can confirm that if I remove the import the issue goes away.



Il giorno 25 feb 2016 16:33, alle ore 16:33, Rob Eisenberg <notifications@github.com> ha scritto:

**Comment by EisenbergEffect** [comment]
It looks like an issue unrelated to Aurelia. Are you sure that is the correct way to import it?

**Comment by tommasop** [comment]
Thanks Rob for your patience.

Just as a reference for others this is the right way to import paper.js:

`jspm install npm:paper`

in model:

`import paper from 'paper/dist/paper-full'`

**Comment by EisenbergEffect** [comment]
Ah. Glad you got that sorted. One think you might consider doing is submitting a PR to the paper project's package.json file to add a jspm section with the correct main location for client-side development. There's info on how to do that on jspm.io if you are interested in making that library better for future devs.

**Comment by tommasop** [comment]
Great! I’ll surely do, I have the same problems with other canvas related libraries.

Thanks again.  

IN OBSCURO MIRANDA RELUCENT
