### ISSUE TITLE
class.bind currently overrides any existing class definitions on the element

### ISSUE THREAD

**Issue by shyamseshadri** [aurelia/binding#33]
If i have

```html
<div class="todo-card" class.bind="todo.completed ? 'completed' : ''"></div>
```
I expect that the div either becomes
```html
<div class="todo-card completed">
```
or
```html
<div class="todo-card">
```
Currently it becomes
```html
<div class="completed">
```
or
```html
<div class="">
```
I'm not sure this would be the expected behavior. I would not want to do 
```html
<div class="todo-card ${todo.completed ? 'completed': ''}"> 
```
in a lot of cases

**Comment by paullryan** [comment]
@shyamseshadri something seems to have go wrong with your formatting as nothing is showing after your statements for code (e.g. "if I have" is followed by blank).

**Comment by EisenbergEffect** [comment]
`class.bind` is expected to overwrite the existing classes. If you do not want to do this, you will want to use interpolation instead. Something like this `class="some-class another-class ${boundClass}"`

**Comment by olanod** [comment]
I'd like to reopen this, there should be a way to do this class interpolation thing without overwriting current classes but without using the example of @EisenbergEffect.  
I have an use case where I want to add a dynamic class to a custom element. `<my-element class="${myClass}"></my-element>` but the element in its inner logic toggles a class from Js which I don't(and shouldn't) control in this scope.  
I don't know there should be a special syntax for this or a different behavior but I think it should be possible.

**Comment by olanod** [comment]
Not sure if it's important but also note that `class.bind="..."` and `class="${...}"` overwriting deletes the `au-target` class also.

**Comment by EisenbergEffect** [comment]
With respect to `au-target` it's no longer important to the framework by the time that the binding expression is applied.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you an @olanod continue discussion here on his use case?

**Comment by olanod** [comment]
So as I previously mentioned. I want to set a class conditionally
```
<my-element class="${condition?'active':''}"></my-element>
```
but this will replace the classes the element already has. In my case the classes I want to keep are added dynamically from inside the custom element(or from anywhere anytime?).
E.g.
In the custom element logic in the `bind` method I add a class with `element.classList.add('fuu')`, it gets added to the host element but then sometime in the future some event changes the `condition` and the element gets the `'active'` class but it also deletes any previous classes it could have.

**Comment by shaunluttin** [comment]
How was this issue resolved?

**Comment by atsu85** [comment]
I haven't seen that issue, but you could use string interpolation instead of .bind
