### ISSUE TITLE
observerLocator subscribe does not return an object

### ISSUE THREAD

**Issue by Freshcutdevelopment** [aurelia/binding#330]
In all the documentation that I've seen on the ObserverLocator the subscribe method should return a disposable subscription object. 

I've tested this on the latest version of Chrome with the latest version of the skeleton-es2016 project by adding it to the welcome.js view-model and found that this actually returns an undefined object rather than the expected disposable subscription object. I'm not sure whether I'm looking at old documentation for this or if this functionality is no longer supported. What I would expect to see is the subscription object being set at the end of the constructor. I could then set it on the view-model and dispose of it later.

`   var subscription = observerLocator
            .getObserver(this, 'bar')
            .subscribe(this.onChange);`

The subscription object is undefined at the end of the constructor. 

[welcome.zip](https://github.com/aurelia/binding/files/152793/welcome.zip)

**Comment by EisenbergEffect** [comment]
You are definitely looking at some old blog posts. We recommend that consumers use the BindingEngine api for these sorts of things. You can see the api docs here: http://aurelia.io/docs.html#/aurelia/binding/1.0.0-beta.1.1.3/doc/api/class/BindingEngine  You'll want to use the `propertyObserver` method which will provide you an object you can subscribe to. http://aurelia.io/docs.html#/aurelia/binding/1.0.0-beta.1.1.3/doc/api/interface/PropertyObserver  That returns a disposable to dispose the subscription: http://aurelia.io/docs.html#/aurelia/binding/1.0.0-beta.1.1.3/doc/api/interface/Disposable

**Comment by Freshcutdevelopment** [comment]
Ah that makes sense. Thank you for clarifying!

**Comment by Anoop1001** [comment]
@EisenbergEffect, The links provided are no more valid. Could you please update the link? Getting 404 not found.

**Comment by Alexander-Taran** [comment]
@Anoop1001 
could you help with that and look for them here http://aurelia.io/docs/api
and post back.
