### ISSUE TITLE
Question: How to capture return value from parent component event handler in the child

### ISSUE THREAD

**Issue by ppn2** [aurelia/binding#331]
When a child component raises an event, of course the parent can listen to it. Now if that parent event handler returns a value, how can the child component capture it?

**Comment by EisenbergEffect** [comment]
It's important to realize that, in the DOM, event handlers don't return values. For the scenario you are describing, you probably want to use the `call` binding in combination with a `ref` binding to connect the parent and child. @jdanyow can provide some more information if needed.

**Comment by ppn2** [comment]
Thanks @EisenbergEffect. It is true DOM events don't return value. As you might have already realized I am dealing with custom events here.
@jdanyow I would appreciate a small example.
