### ISSUE TITLE
refactor connect-queue to avoid symbol usage

### ISSUE THREAD

**Issue by jdanyow** [aurelia/binding#332]
aurelia-polyfills doesn't have Symbol support.

This line:  https://github.com/aurelia/binding/blob/master/src/connect-queue.js#L12

Transpiles to: https://github.com/aurelia/binding/blob/master/dist/amd/aurelia-binding.js#L156

Causing errors in IE 11.

**Comment by Alan-AcutePath** [comment]
Any time frame to get this fixed? Just saw this error after upgrading

**Comment by EisenbergEffect** [comment]
It will be fixed today. We are combing the library now for any other places where the compiler may have generated code that used unexpected polyfills.

**Comment by Alan-AcutePath** [comment]
cool, thx.

**Comment by alvarezmario** [comment]
@jdanyow @EisenbergEffect what would happen if in our code we are using the `for..of` construct? Do we need to add `core-js`? Thanks

**Comment by EisenbergEffect** [comment]
First, I would try to find a Symbol polyfill and add that to see if that fixed the issue.

**Comment by alvarezmario** [comment]
So yeah, we need that. Thanks Rob

**Comment by jdanyow** [comment]
fixed in https://github.com/aurelia/binding/commit/7caea5d47e185d27cc3e9c696e934fb70113c183
