### ISSUE TITLE
Reflecting properties to attributes

### ISSUE THREAD

**Issue by levan1993** [aurelia/binding#333]
https://www.polymer-project.org/1.0/docs/devguide/properties.html#attribute-reflection

Is there something similar in aurelia?

**Comment by EisenbergEffect** [comment]
At the moment, there is not, but I think we could add this in the future. I'll add it to my todo list and update that here.

**Comment by EisenbergEffect** [comment]
Issue moved to [aurelia/templating #283](https://github.com/aurelia/templating/issues/283) via [**ZenHub.io**](https://www.zenhub.io/)
