### ISSUE TITLE
IE11 throws: 'Symbol' is undefined

### ISSUE THREAD

**Issue by crbranch** [aurelia/binding#334]
Simply building the Typescript skeleton (`skeleton-typescript` within `skeleton-navigation-1.0.0-beta.1.1.5.zip`) and making no code changes, I get an exception in IE11.  Firefox, Chrome, Edge work fine.  (Edge is slow, but that's a separate known issue that's fixable by adding bluebird.js).  The exception occurs inside the `flush` function:

    _iterator = _isArray ? _iterator : _iterator[Symbol.iterator]();;	'Symbol' is undefined

Is there a polyfill I'm missing?

![ie11](https://cloud.githubusercontent.com/assets/17033045/13512720/6ae68e6a-e16a-11e5-8e37-2fa60d014f16.png)

**Comment by doktordirk** [comment]
they just replaced the for .. of loops today. tried jspm update?

**Comment by EisenbergEffect** [comment]
Please run `jspm update` The code above no longer uses symbols. We apologize, this was compiler generated code that uses a polyfill we weren't using in our source. It has been fixed.

**Comment by crbranch** [comment]
Confirmed: `jspm update` resolves the problem.  Thank you!

**Comment by EisenbergEffect** [comment]
Excellent. Sorry for the inconvenience.

**Comment by crbranch** [comment]
Not a problem.  I'm just happy it wasn't my fault :-)
