### ISSUE TITLE
Obtain context when observing property changes

### ISSUE THREAD

**Issue by stefan505** [aurelia/binding#339]
I'm trying to find the correct way to subscribe to multiple VM property changes (multi observer scenario), with a callback that is able to tell me for which property it fired. I was hoping to use the `context` such as:

```
let subscription = this.observerLocator
    .getObserver(this, 'email')
    .subscribe('email', this.onChange);
```

and then

```
onChange(context, newValue, oldValue) {
 // Expect context to be 'email'
}
```

It seems the callback is actually wiring up only the first two params as `newValue` and `oldValue`, with `context` omitted. I'm I doing it wrong, or is there a bug?

**Comment by jdanyow** [comment]
subscribe has a couple of signatures- you can either pass a callback which will be invoked with `(newValue, oldValue)` OR you can pass a context and a callable.  Context can be anything and the callable needs to be an object with a `call` method which accepts `(context, newValue, oldValue)`.  Here's an example:

https://gist.run/?id=4893117f81d8f1ee1090

**Comment by stefan505** [comment]
Thank @jdanyow, got it working as per the Gist.
