### ISSUE TITLE
Binding a 0 value to a td colspan throws an error in IE11

### ISSUE THREAD

**Issue by MaluTom** [aurelia/binding#343]
If I have a 
`<td colspan="${columnSize}">Blablabla</td>`

And I set this.columnSize=0 in the view model, I get an error in the aurelia task queue for IE11. Seems to work fine in google chrome.

**Comment by EisenbergEffect** [comment]
Please run `jspm update`. We've recently had some IE11 fixes. Let us know.

**Comment by MaluTom** [comment]
Yikes - now I'm getting an unrelated error:
`ERROR [event-aggregator] TypeError: Object expected`
`"TypeError: Object expected
   at Anonymous function (Unknown script code:57:38)
   at publish (Unknown script code:54:15)
   at publishTransportChangeEvent (Unknown script code:80:25)
   at selectDevice (Unknown script code:102:29)
   at evaluate (Unknown script code:1398:9)
   at evaluate (Unknown script code:1056:7)
   at callSource (Unknown script code:4844:7)
   at Anonymous function (Unknown script code:20:7)"`

**Comment by EisenbergEffect** [comment]
Can you create a simple sample app that reproduces this error for us?

**Comment by MaluTom** [comment]
Seems to be triggered with the following line of code:
`this.myMap=new Map();
this.myMap.set("key",{'value1':'bla','value2':'bla2'});
...
this.eventAggregator.publish('Event',this.myMap.values());`

**Comment by EisenbergEffect** [comment]
That's quite strange. @jdanyow Do you have an IE11 instance available you can use to check this out on?

**Comment by MaluTom** [comment]
Happy to put together a demo app if you can point me to somewhere I can easily host it on

**Comment by EisenbergEffect** [comment]
If you create a github repo, you can host it as a github pages site. You could also create a plunkr or use gist.run. @jdanyow Can help you use the new gist.run service he's been working on.

**Comment by jdanyow** [comment]
Tested in the latest skeleton.  The only way I could get IE11 to throw an error was to use an invalid value (zero): `colspan.bind="0"` or `colspan="${0}"`.  This is a good error, not a bug. @MaluTom if you can fork the skeleton-navigation repo, set up the scenario and send me a link I'd be happy to take a look.

![error](http://i.imgur.com/wKtTQL9.png)

**Comment by MaluTom** [comment]
Thanks @jdanyow - if you can't reproduce my error with the eventAggregator must be that my jspm dependencies may not have updated properly. I'll clear out all my dependencies and try again.

On the above error with colspan="{0} - should not all browsers throw the same error and not just IE? It works in chrome fine.

**Comment by jdanyow** [comment]
@MaluTom I agree- all browsers should have the same behavior with respect to colspan.  That aside, if you ensure zero is not used, everything should work.  MDN says zero is an invalid colspan value in HTML5:

![colspan](http://i.imgur.com/BHlmo67.png)
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td

**Comment by jdanyow** [comment]
@MaluTom please re-open this if you're still hitting issues with colspan binding beyond the IE issue described above
