### ISSUE TITLE
Aurelia should support element attributes that act like disabled on input

### ISSUE THREAD

**Issue by AshleyGrant** [aurelia/binding#348]
Say I have created the `<ashley />` custom element. Wherever I place this element in my markup, it will show my name. The thing is, sometimes I'm feeling bold. When I'm feeling bold, I want to add the `bold` attribute to my custom element (`<ashley bold></ashley>`). When my custom element has this attribute, the `bold` property in the element's VM will be set to true. When the attribute is not there, the `bold` property is set to false.

In the title, I say that Aurelia should make these attributes behave like the `disabled` attribute on the `input` element. This isn't entirely true. The `disabled` attribute must be removed from the element to be unset. Sure, in JavaScript we can do `element.disabled = false;`, but `<input disabled="false" />` is functionally the same as `<input disabled />`. For Aurelia custom elements, I believe that boolean attributes should also accept a truthy/falsey value. This would allow the attribute to still participate in databinding. Whatever value is set would be coerced to true/false.

This is tied to #347 and might possibly be considered the same issue and could thus be merged with it. I have separated them for now though.

**Comment by EisenbergEffect** [comment]
Closing as duplicate.
