### ISSUE TITLE
Polymer's custom element styling breaks inside `repeat.for`

### ISSUE THREAD

**Issue by codeaid** [aurelia/binding#350]
I started using Aurelia `1.0.0-beta.1.1.4` together with Polymer 1.3.1 and Paper elements 1.0.7.

I implemented the `paper-drawer-panel` in my `app.html` as was shown in Polymer's example. Here's a trimmed down version of the HTML:

```html
<template bindable="router">
    <style is="custom-style">
        paper-item {
            --paper-item: {
                color: red;
                font-size: 40px;
            };
        }
    </style>

    <paper-drawer-panel>
        <paper-header-panel drawer>
            <paper-menu>
                <a repeat.for="row of router.navigation" href.bind="row.href">
                    <paper-item raised role="menuitem" active.bind="row.isActive">
                        ${row.title}
                        <paper-ripple></paper-ripple>
                    </paper-item>
                </a>
            </paper-menu>
        </paper-header-panel>
</template>
```

The style override is defined per Polymer examples and I spent ages trying to understand why it wasn't being applied to the `paper-item` elements. After some debugging I discovered that it works if I remove the `repeat.for="row of router.navigation"` attribute (and replace `${row.title}` with some text as otherwise it's blank. 

Here's the updated code where styles apply as expected:

```html
<a href.bind="row.href">
    <paper-item raised role="menuitem" active.bind="row.isActive">
        Testing
        <paper-ripple></paper-ripple>
    </paper-item>
</a>
```

It looks like a similar issue to #262 but I'm not sure why it's happening or how to fix it so please let me know if you need more information to replicate the issue.

**Comment by codeaid** [comment]
Some additional info that might be useful:

**bower.json**
```json
{
  "name": "example",
  "private": true,
  "dependencies": {
    "polymer": "Polymer/polymer#^1.3.1",
    "paper-elements": "PolymerElements/paper-elements#^1.0.7",
    "iron-elements": "PolymerElements/iron-elements#^1.0.8",
    "webcomponentsjs": "webcomponents/webcomponentsjs#^0.7.21"
  }
}
```

**config.js**
http://pastebin.com/L3iF6KZ7

**Full app.html**
http://pastebin.com/uGQvsnxs

**Comment by EisenbergEffect** [comment]
I think this likely relates to how Polymer is handling the element internally and there isn't likely anything we can do about it ourselves. Perhaps try reporting it to them as an issue?

**Comment by hleao** [comment]
For future reference, I had a similar issue and it was solved by configuring polymer to render local DOM using shadow DOM (the default value is 'shady'). 
```html
<script>
    window.Polymer = {
      dom: 'shadow'
    };
</script>
```
