### ISSUE TITLE
Aurelia binding fails after changing property type

### ISSUE THREAD

**Issue by Dygerati** [aurelia/binding#351]
So, this is likely an odd use case, so I'm unsure if it would be considered a bug. I have a view-model with a property that may be a string or an array. My view supports both. 

However, if the property is changed through the double-binding action of the view then I convert any potential string to an array. After converting a string to an array the binding behavior becomes erratic, and will not work correctly until I leave the view and return. This could probably be resolved by manually refreshing the view/bindings, but this function doesn't seem to be implemented (https://github.com/aurelia/router/issues/201).

**Comment by jdanyow** [comment]
@Dygerati we need more info to troubleshoot this.  Please put together a reproduction of what you're seeing using the aurelia gist: https://gist.run/?id=7542e061bc940cde506b

**Comment by jdanyow** [comment]
@Dygerati just checking in- let me know if you need a hand setting this up

**Comment by Dygerati** [comment]
Thanks - right now I'm working around this by simply converting my test data to use only arrays. I'll see about creating a gist in the next few days if I can prioritize the issue. I'm not sure if you want to keep this open in the meantime?

**Comment by jdanyow** [comment]
ok sounds good- will close for now, feel free to re-open if you put together a sample
