### ISSUE TITLE
Missing type declarations for ValueConverter constructor

### ISSUE THREAD

**Issue by thomas-darling** [aurelia/binding#352]
I'm doing essentially the same as what is being done here, in `TBindingBehavior`:
https://github.com/aurelia/i18n/blob/master/src/t.js

However, TypeScript complains because the constructor is missing in the type declaration for the `ValueConverter` class.

If I manually add it, it all works perfectly - not sure exactly which types are expected though :-)

```typescript
export class ValueConverter implements Expression {
    constructor(expression: any, name: any, args: any, allArgs: any);
    ...
```

**Comment by jdanyow** [comment]
The ctor of the various expression implementations are not part of the public API although they're unlikely to change so we could look into adding them to the d.ts in the future.
