### ISSUE TITLE
getArrayObserver, 2 push triggers unexpected results

### ISSUE THREAD

**Issue by vegarringdal** [aurelia/binding#354]
Hi

This might just be me again misunderstanding how its supposed to work.
I have this array observer on a collection in my grid element  binded to parent collection Im working on.

```
let arrayObserver = this.observerLocator.getArrayObserver(this.collection)
      arrayObserver.subscribe(function (changes) {
        debugger;
      }.bind(this));
      this.subscriptionsArray = arrayObserver

```

Then I I call function to push in 2 more: (over look the 

```
  push(data){
    this.collection.push(data[0]);
    this.collection.push(data[1]);
}
```

Now the unexpected comes.
My observer gets called...
```
addedCount:2
index:0
removed:Array[0]
```

I then though, ok, great I they have added added 2 from index 0.
I can just add those to my cloned array inside the custom element.
But it gets called again, and with same data....
So is it just me thinking this is not right?
Ofc good chance Im doing something wrong... again...

**Comment by jdanyow** [comment]
Sounds like you might have called subscribe multiple times with the same array.  Here's a gist that shows it's working properly:

https://gist.run/?id=41d5fb436a1d630ce8a6

**Comment by vegarringdal** [comment]
Restared gulp watch and now it works normal.
Sorry.
