### ISSUE TITLE
Question, pausing the observer subscription, is that possible ?

### ISSUE THREAD

**Issue by vegarringdal** [aurelia/binding#355]
Is there a way I can pause the observer subscription while I do some changes?

In my custom element I add propertyObserver per attibute on a object.
This is the "currentEntity" if my grid, and all html element use this for data, and I use it for getting data to apply to correct row form the binded html elements in parent component.

But when user selects a row, I need to set data for current entity, but before I do this I would like to pause the subscription while I do the chnages and activate it again, this way I dont get called on my internal observer on changes my grid does.

**Comment by jdanyow** [comment]
There is no way to pause a subscription other than unsubscribing and re-subscribing or adding some code to your handler like this:
```js
if (this.isPaused) {
  return;
}
```

**Comment by vegarringdal** [comment]
ok, just wanted to ask, for now Im using like you code above, and setTimeout so I skip the property obvservers calls
I tried to unsubscribe() then subscribe(xX) again, but it still got triggered.
Maybe I did something wrong again...
I will try again, thx for the fast reply.
