### ISSUE TITLE
View Fails to Update When Object Property Changed in ViewModel

### ISSUE THREAD

**Issue by Dygerati** [aurelia/binding#356]
I've created a simple gist to illustrate the issue:
https://gist.run/?id=8d03b3b8f8deef92e3a9

The summary of my issue involves trying to display contents from a simple object in a view. I wanted to use Aurelia's `repeat` operator in the view, and also use the Map() syntax to do so (ex. `repeat.for="[key, value] of object"`). For this reason I'm converting the object to a Map via a valueConverter module.

This works to display the data as the view initializes, but if the object is updated in the ViewModel, then it is NOT updated in the view.

At this point if I navigate to a different view and return, it will then display the added elements. As far as I can tell there is not a way to update the view without navigating to another one and returning.

Is this a bug? Am I just doing something horrible? Any workarounds?

**Comment by EisenbergEffect** [comment]
The simple explanation is that the bindings are observing the Map, which doesn't actually change. They aren't observing the underlying object at all.

@jdanyow May be able to recommend an alternate approach for you.

**Comment by Dygerati** [comment]
Understood. So the main question would be; how do I loop through an object in a View and preserve the live binding? If I use something like a `objectKeysValueConverter`  I believe I'll just run into the same issue. 

The only thing I can think of is to use a CollectionObserver in the ViewModel to create the map, and then use that map directly in the View. Although I'm still pretty inexperienced with Aurelia and unsure if that will work.

**Comment by alvarezmario** [comment]
@Dygerati perhaps this would be of help: http://ilikekillnerds.com/2015/08/iterating-objects-using-repeat-for-in-aurelia/

**Comment by alvarezmario** [comment]
@Dygerati iterating over objects has some issues: https://github.com/aurelia/templating-resources/issues/41

**Comment by Dygerati** [comment]
@alvarezmario Thanks, although that article recommends using something like the `objectKeysValueConverter` strategy I mentioned, which won't update the view when the underlying object is changed (same issue).

**Comment by alvarezmario** [comment]
@Dygerati yeah, exactly what is mentioned on the issue I linked above

**Comment by jdanyow** [comment]
@Dygerati here's an option for you.  It will only work if all your object's props are defined ahead of time:
https://gist.run/?id=b9071aaa4447426a0570

The only other way would be to use dirty-checking because there's no other way to tell when a property is added/removed from an object without Object.observe.

**Comment by Dygerati** [comment]
@jdanyow Really appreciate it; unfortunately my use case involves adding properties, so it won't quite work. I have implemented a workaround using Map()'s, so I'll just have to stick with that until proxies or something similar make the difference.

**Comment by alvarezmario** [comment]
@Dygerati I had to implement something like that and what I did was use `Map`s, which are a good option for that case when you have to add/remove keys from the object
