### ISSUE TITLE
accesskey global attribute missing

### ISSUE THREAD

**Issue by tommasop** [aurelia/binding#358]
I'm trying to bind an `accesskey` attribute in an Aurelia view:

```
<a href="${sub_option.link}" accesskey="${sub_option.rapidkey}">${sub_option.title}</a>
```

While href attribute is created correctly the accesskey attribute simply disappear.

It seems like is not being binded at all.

**Comment by jdanyow** [comment]
looks like we need to map `accesskey` to `accessKey`:  https://developer.mozilla.org/en-US/docs/Web/API/Element/accessKey
