### ISSUE TITLE
(regression) computedFrom is only applied the first time the ViewModel is bound

### ISSUE THREAD

**Issue by niieani** [aurelia/binding#359]
I've prepared a Gist demo, however since there isn't a version after the `computedFrom` refactor, I'll just present what used to work and now is broken:

https://gist.run?id=ce252a8c24716e5d3620

To see what I mean switch between "computed" and "else". In the previous Aurelia version (the one running the Gist) this works well, as `random` is only computed once, every time when the route is bound. However if you run the same code using the latest version of Aurelia, when you switch to "computed" then back to "else" then back to "computed", the binding will become dirty-checked and a new Random value will be seeded every few hundred ms.

Might this be related to the recent `computedFrom` refactor by @jdanyow?

**Comment by jdanyow** [comment]
thanks @niieani - good catch!
