### ISSUE TITLE
get.dependencies array wraping into ComputedExpression after bootstraping

### ISSUE THREAD

**Issue by dilvish4ever** [aurelia/binding#360]
I'm have some problems with dirty-checking of properties created by Object.defineProperty (defined in property decorator). I added dependencies array to getter, as described in http://stackoverflow.com/questions/32028553/aurelia-computed-properties-with-es5, but property still dirty-checking. In Chrome tools dependencies is not an array, but ComputedExpression. How to aviod dirty-checking in case of defining getters via decorators?
```javascript
export function example(someValue:string): any {
    return function(target, key) {
        var getter = function() {
            console.debug(someValue);
        }
        //transforms to ComputedExpression after page loaded :(
        getter.dependencies = [key];

        Object.defineProperty(target, key+"getter", {
            get: getter,
            enumerable: true,
            configurable: true,
        });
    }
}
```

**Comment by jdanyow** [comment]
fixed in upcoming release
https://github.com/aurelia/binding/issues/359
