### ISSUE TITLE
Adding a `bind` callback causes changeHandler callbacks to not be called.

### ISSUE THREAD

**Issue by Vaccano** [aurelia/binding#363]
Say I have a `@bindable` defined like this:

    @bindable({ defaultBindingMode: bindingMode.twoWay, changeHandler: 'boxChanged' }) box;

    boxChanged() {
      alert('box changed called.  '+
          'Uncomment "bind" found in box-vm.js, line 15 to see this not be called.')
    }

If I add the following to the view-model then `boxChanged` will no longer be called:

    bind(bindingContext: Object, overrideContext: Object) {  }   

**Observed**  
`@bindable`'s `changeHandler` is not called when there is a `bind` callback on the same view-model.

**Expected**  
`@bindable`'s `changeHandler` callback would be unaffected by the presence or absence of other callbacks (including `bind`)

**Repro**  
Here is the [gist run ](https://gist.run/?id=8c16d89bce2fb81f97ce) for this issue.
To run the related code, press the `Add Box` button.

This will cause the `boxChanged` method to fire and show the alert.

To make the error occur, uncomment the bind method found in box-vm.js, line 15.

**Comment by jdanyow** [comment]
When a component initially becomes data-bound each of its [property]Changed methods are invoked *unless the component has a `bind` method, in which case the bind method will be called once all the bindable properties have been assigned.*  Afterwards the [property]Changed methods will be called as-usual.

https://github.com/aurelia/templating/issues/257

**Comment by Vaccano** [comment]
@jdanyow I did notice that the bind method had what I needed in it.  Not quite a clean as I wanted from a typescript point of view (because I have to do an `any` cast to get it out).

But if this is the "way" then I works for me.  

(Sorry for the duplicate...)

**Comment by jdanyow** [comment]
no worries- fyi- inside of `bind` you can call `this.myBindableProperty` to access the bound values.  `bind`  is called *after* all the bindable properties have been data-bound.

**Comment by Vaccano** [comment]
@jdanyow Does this work for `custom-attributes` as well as `custom-elements`?  (I need to make a call in my custom attribute once all the parameters are databound.)
