### ISSUE TITLE
babel5 and core-js in config.js

### ISSUE THREAD

**Issue by mbroadst** [aurelia/binding#369]
Hey guys,
Just wondering if there is a reason that the `config.js` still has references to babel5 and core-js: https://github.com/aurelia/binding/blob/master/config.js#L23. 

I'm trying to clean up a few of my own modules after the babel6 update, and wanted to make sure I wasn't leaving any cruft around.

**Comment by EisenbergEffect** [comment]
No reason. We need to get that cleaned out.

**Comment by Vheissu** [comment]
Looks like the Babel5 and core-js stuff was cleaned, this can be closed @EisenbergEffect

**Comment by mbroadst** [comment]
@Vheissu was it? I still see entries for both in `package.json` and `config.js`

**Comment by EisenbergEffect** [comment]
Unfortunately, jspm 16 isn't compatible with Babel 6. I'm kind of looking to see if we can remove jspm from our core repos altogether in the future. We can keep this open until we resolve it.

**Comment by Gheoan** [comment]
In-browser transpilation is not needed as `karma` is already transpiling using `babel` 6.

**Comment by EisenbergEffect** [comment]
Removed all v5 config.
