### ISSUE TITLE
computedFrom doesn't support paths -  based on #149

### ISSUE THREAD

**Issue by ClareBear85** [aurelia/binding#370]
I updated to aurelia-binding@1.0.0-beta.1.3.1, so that I could do the following: computedFrom - including path. 

```
                    .ensure('baseContent.ValidFromDate', (config) => { config.computedFrom(['baseContent.ValidFromTime', 'baseContent.ValidToDate', 'baseContent.ValidToTime']) })
                        .if(() => {
                            return this.baseContent.ValidFromDate !== null && this.baseContent.ValidFromTime !== null && this.baseContent.ValidToDate !== null && this.baseContent.ValidToTime !== null })
                            .passes( () => { return this.datetimeformat.format(this.baseContent.ValidFromDate, this.baseContent.ValidFromTime) < this.datetimeformat.format(this.baseContent.ValidToDate, this.baseContent.ValidToTime) })
                            .withMessage('< Valid To')
```

![image](https://cloud.githubusercontent.com/assets/7114660/14313249/5c6e1798-fbe8-11e5-865d-5a933754f747.png)

However this doesn't fall into the if statement if 'baseContent.ValidFromTime', 'baseContent.ValidToDate', 'baseContent.ValidToTime' have changed. What am I missing?

**Comment by jdanyow** [comment]
Issue moved to [aurelia/validation #234](https://github.com/aurelia/validation/issues/234) via [**ZenHub.io**](https://www.zenhub.io/)
