### ISSUE TITLE
Binding to a boolean property

### ISSUE THREAD

**Issue by ppn2** [aurelia/binding#371]
Is there any way to tell aurelia that the bound property in the ViewModel is boolean and convert the value to boolean before assigning to the variable?

For Example (This is type script code)

Parent View
```
<my-comp is-active="true"></my-comp>
```
my-comp view model
```
export class MyComp {
  @bindable
  isActive: boolean; 
}
```
Right now aurelia will assign it a string "true" value instead of boolean true. (Of course it does not know I am looking for a boolean). That begs the question, is there any way to tell aurelia to convert the value to boolean before assigning to property.

I tried different approach to achieve this by specifying a getter and setter. something like this.
```
    private _isActive: boolean = false;
    @bindable
    public get isActive(): boolean | string {
        return this._isActive;
    }
    public set isActive(value: boolean | string) {
        this._isActive = this.toBool(value);
    }
    private toBool(value: boolean | string): boolean {
        return (/^true$/i).test(<string>value)
    }
```
But it seems once you decorate a property as bindable, Aurelia rewrites it or (do something which I am not aware) and the logic in the setter never kicks in. I am not sure if this is the way it is suppose to be. If it is, is there any way to tell Aurelia to not change the property definition?

**Comment by z-brooks** [comment]
: https://github.com/aurelia/binding/issues/347

You can bind it `is-active.bind="true"`, or something similar to your code:

```es6
@bindable isActive;
_isActive;

isActiveChanged( nv )
{
    this._isActive = this.toBool(nv);
}
```

**Comment by EisenbergEffect** [comment]
There's a feature being tracked to implement this already.

**Comment by EisenbergEffect** [comment]
https://github.com/aurelia/binding/issues/347

**Comment by ppn2** [comment]
Thanks @z-brooks for the workaround. However I would love to have a more robust solution as pointed out by @EisenbergEffect.

Moreover, I had another question, related to getter and setter on bindable properties. Is there any way honour the logic inside them. I know I can always fall back to the change event.

**Comment by EisenbergEffect** [comment]
Not currently. Bindables have a very specific set of internal needs related to surfacing of the interface in HTML.
