### ISSUE TITLE
Reference/Save value converter result

### ISSUE THREAD

**Issue by z-brooks** [aurelia/binding#373]
@xharmagne and @michaelprescott expressed interest in such a feature.
https://gitter.im/Aurelia/Discuss?at=570472f48eec5313252e7189
https://gitter.im/Aurelia/Discuss?at=5704739ff7d63d897f23a4e0

I had a similar requirement so I modified the files to allow saving value converter results.
```html
<element xyz.bind="foo | someVC >> someVar">
```

Is this something worth adding?

code: https://github.com/aurelia/binding/compare/master...z-brooks:value-pipe

**Comment by jdanyow** [comment]
Here's an issue where we discussed how to support this scenario:
https://github.com/aurelia/templating-resources/issues/171#issuecomment-166157329

**Comment by jdanyow** [comment]
@z-brooks what do you think- is the `let` element or attribute a good solution or do you favor extending the binding syntax?  I think I like the `let` approach better.

**Comment by z-brooks** [comment]
@jdanyow I could get on board with the `let` element. Easier to read/understand than what I've done and also seems more flexible. Something like this might be possible (?): 
```html
<let filtered.bind="someArray | filter & signal:'refilter'" 
       sorted.bind="filtered | sort & signal:'refilter':'resort'">
</let>
```
Not really possible with my solution.

**Comment by jdanyow** [comment]
nice! yes that ^^^ would be possible

ok to close this?

**Comment by z-brooks** [comment]
yep. :+1:
