### ISSUE TITLE
Allow binding behaviors in observer subscription

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia/binding#374]
I'm not sure if this is a supported use case at the moment, but I'd like to be able to throttle or debounce a subscription on an ExpressionObserver using the BindingEngine. At the moment, I don't think that this use case is supported.

Currently, we can do something like this:

        this.messageSubscription = this.bindingEngine.propertyObserver(this, 'message')
            .subscribe((change) => {
                this.cacheService.save(change);
            });

However, I'd like to be able to do something like this:

        this.messageSubscription = this.bindingEngine.propertyObserver(this, 'message')
            .subscribe((change) => {
                this.cacheService.saveSquawk(change);
            }, BindingBehaviors.throttle(800));

...or something along those lines. It seems like it might be generally useful, but there also might be other ways to handle this that I'm not yet aware of.

**Comment by jdanyow** [comment]
Unfortunately the throttle/debounce binding behaviors would be hard to reuse here.  Their implementation is optimized for the binding engine, eliminating closures, etc.  The reactive extensions for js seem to be a popular choice for this kind of thing: http://reactivex.io/  Not sure if that's too heavy handed.
