### ISSUE TITLE
On property change, if.bind attached to a computed property appears to be evaluating after contents are re-rendered.

### ISSUE THREAD

**Issue by BenDTU** [aurelia/binding#375]
I've currently got a situation where I'm rendering a grid with separate 'columns' and 'rows' properties, with the row rendering being wrapped with an if.bind that points to a computed property which determines whether the rows can currently be rendered (Based on both 'columns' and 'rows').

Upon changing the 'columns', I'm finding Aurelia will try and evaluate the contents of the if.bind before it accesses the computed property to see whether the rows should be rendered, leading to errors being thrown in functions being evaluated with the new 'columns' and old 'rows'.

I've also tried creating a computed secondary 'rows' which returns nothing if the above condition wasn't satisfied, with identical results - the old value of 'rows' was evaluated against the new 'columns'.

Hope that's clear - is this an actual issue?

**Comment by jdanyow** [comment]
If you want to put together a repro we can take a look: https://gist.github.com/jdanyow/7542e061bc940cde506b

**Comment by BenDTU** [comment]
Thanks very much. I've been able to replicate the bug at https://gist.run/?id=68e9e556b62b720a9fb6fd4138da3a9b

When you click 'switch between tables', you'll notice that the databound content is displayed quickly before disappearing, as well as a Javascript error being thrown due to the data it's trying to work with no longer matching what was expected.

**Comment by jdanyow** [comment]
This isn't a bug, the error happens in your example's `evaluationFunction` because it expects the data to have a `name` property which isn't always the case depending on the sequencing of your switchdata function in combination with dirtychecking the tableAndDataMatches computed property

**Comment by BenDTU** [comment]
Thanks for checking that out - I'm trying to add a computedFrom to my example there, but it doesn't appear to be working as expected from within GistHub. Is there something up there?
