### ISSUE TITLE
Valueconverters don't react to update in repeat

### ISSUE THREAD

**Issue by MFJust** [aurelia/binding#379]
I have two arrays in my class
```javascript
users = [ {
	id: 1,
	name: 'User1'
}, {
	id: 2,
	name: 'User2'
} ]
cases = [ {
	casenumber: '1234',
	user: 1
}, {
	casenumber: '1235',
	user: 2
} ]
```

And use a valueconverter to only show the cases per user, which are assigned to the user.
```html
<ul repeat.for="user of users">${user.name}
     <li repeat.for="dcase of cases | filterOnProperty:'user':user.id">${dcase.casenumber}</li>
</ul>
 ```

```javascript
export class FilterOnPropertyValueConverter {
	toView( array: {}, property: string, exp ) {

		if ( array === undefined || array === null || property === undefined || exp === undefined ) {
			return array;
		}
		return array.filter( ( item ) => item[ property ] == exp );
	}
}
```

When I update the cases to the following
```javascript
cases = [ {
	casenumber: '1234',
	user: 2
}, {
	casenumber: '1235',
	user: 2
} ]
```
Nothing changes, till I reload the page.

**Comment by EisenbergEffect** [comment]
How are you updating the cases?

**Comment by jdanyow** [comment]
I think he's changing the value of the `user` property on one of the case objects from 1 to 2.  This doesn't trigger re-evaluation of the expression because the binding system isn't deep observing the contents of the array and re-evaluating the filter expression when something changes.
