### ISSUE TITLE
computedFrom using Set doesn't watch for changes to Set

### ISSUE THREAD

**Issue by cehoffman** [aurelia/binding#383]
Basic idea is I'm trying to use `@computedFrom` on a property that contains a set and I expected it would watch that set for changes. But it doesn't. I guess I can understand that the basic implementation is only watching if the value a property is replaced, but it seems a natural extension based on how changes to sets are propagated in the view on repeat.for that this would work. Perhaps the binding could look at the current value and change what is watched if it is a more complex type like Map, Set, and Array?

I have a sample gist showing this.

https://gist.run/?id=16c4ad2dcb10368292ba0dd69dccbcd1

**Comment by jdanyow** [comment]
Would this work for you: https://gist.run/?id=5bdb56a888a2269a9bec7af373655ee6

There's also a gist here that might be helpful:  https://github.com/aurelia/templating-binding/issues/86

**Comment by kellyethridge** [comment]
@jdanyow Your solution works in Chrome but not in Firefox. The state argument is always undefined. Is that expected?

**Comment by cehoffman** [comment]
@jdanyow yeah that does work. Thanks for looking at the problem from a different angle.
