### ISSUE TITLE
Question regarding @bindable

### ISSUE THREAD

**Issue by vegarringdal** [aurelia/binding#385]
The html
```
<custom-element
          style="position:absolute;top:70px;bottom:0px;right: 25px;left:25px"
          row-height="50"
          header-height="50"
          resizable-headers="true"
          current-entity.bind=myCurrentEntity
          collection.bind=myCollection
          grid-context.bind=myGrid
></custom-element>
```

Atm I can do this
```
@processContent(false)
export class CustomElement{
  @bindable gridContext;
  @bindable collection;
  @bindable currentEntity;
  @bindable rowHeight;
  @bindable headerHeight;
  @bindable resizableHeaders;
}
```

But is i possible for me to set a few of them onto a class/object instead of having them in "this" context. without having doing something style tag way?
```options="row-height:50;header-height=50;resizable-headers:true" ```

Just do it with the @bindable
```
@processContent(false)
export class CustomElement{
  @bindable gridContext;
  @bindable collection;
  @bindable currentEntity;
  @bindable configClass.rowHeight;
  @bindable configClass.headerHeight;
  @bindable configClass.resizableHeaders;
}
```

**Comment by EisenbergEffect** [comment]
The code you are showing at the bottom isn't valid JavaScript. You could manage this with a custom attribute that communicated with the custom element to set up a different structure though. You might find this blog post helpful: https://blog.ashleygrant.com/2016/04/23/accessing-an-aurelia-custom-elements-viewmodel-from-acustom-attribute-on-that-element/

**Comment by vegarringdal** [comment]
Yes Ive seen it.
Just tried to show what I wanted it into some other place then "this" wondering if there was a way to pass something into @bindable, a class or something without creating a custom attribute for each one.
:-)

**Comment by vegarringdal** [comment]
Read Ashleys blog a few times more, think I know how to do it now.
Option.of will help me do what I want to do.
```
import {inject, dynamicOptions, Optional} from 'aurelia-framework';  
import {SayHello} from "./say-hello-one";

@dynamicOptions
@inject(Optional.of(SayHello))

```

Learn something new every day, but its fun :-)
Thanks for pointing me in the correct direction.
