### ISSUE TITLE
`@computedFrom('router.navigation')` does not work as expected

### ISSUE THREAD

**Issue by alexanderteinum** [aurelia/binding#388]
```javascript
 @computedFrom('router.navigation')
 get navItems() {
    return this.router.navigation.map(row => {
        return {
            ...row,
            icon: 'jigsaw',
        };
    });
}
```

…results in `[]` for some reason that I don’t understand.

My use case is that I want to transform `router.navigation` before passing it to the view in order to apply dynamic logic. By transforming I mean passing it through `filter()` and `map()` for instance. Although not shown in the example above, I have logic that is dynamic that e.g. determines if a nav item should be shown or not – e.g. depending on whether a flag is set that determines if it is a development environment.

I would assume that it would be a bad idea to mutate `router.navigation` to hold state. I would also assume that it would be a bad idea to set it up with dynamic data – it would only be possible to do it once.

I don’t want to observe `router.navigation` and keep the state as class variables. If I do that all around my code, then there is a lot of state to maintain.

**Comment by jdanyow** [comment]
The router supports custom "state" for routes via the `state` property.  You would have to change this:
```js
  configureRouter(config, router) {
    config.title = 'Aurelia';
    config.map([
      { route: ['', 'welcome'], name: 'welcome',      moduleId: 'welcome',      nav: true, title: 'Welcome' },
      { route: 'users',         name: 'users',        moduleId: 'users',        nav: true, title: 'Github Users' },
      { route: 'child-router',  name: 'child-router', moduleId: 'child-router', nav: true, title: 'Child Router' }
    ]);

    this.router = router;
  }
```

To something like this (scroll to the right -->):

```js
  configureRouter(config, router) {
    config.title = 'Aurelia';
    config.map([
      { route: ['', 'welcome'], name: 'welcome',      moduleId: 'welcome',      nav: true, title: 'Welcome', state: { icon: 'jigsaw', visible: true } },
      { route: 'users',         name: 'users',        moduleId: 'users',        nav: true, title: 'Github Users', state: { icon: 'globe', visible: false} },
      { route: 'child-router',  name: 'child-router', moduleId: 'child-router', nav: true, title: 'Child Router', state: { icon: 'floppy', visible: false} }
    ]);

    this.router = router;
  }
```


`@computedFrom` isn't helping because `@computedFrom('router.navigation')` causes the binding system to observe the `router` property for changes (eg a different value was assigned to `viewmodel.router`) and observe `navigation` for property changes (eg a different value is assigned to `router.navigation`).  The binding system is not evaluating the expression, looking for arrays, and hooking up an array observer.

**Comment by alexanderteinum** [comment]
Hum. Actually, I’m not sure why I wanted to observe `router.navigation`. After it has been bound, it shouldn’t change? By removing the `@computedFrom`, but keeping the property it seems to work for my current use case – which is filtering based on if the environment is dev or not.
