### ISSUE TITLE
route undefined error

### ISSUE THREAD

**Issue by chaituGS** [aurelia/binding#389]
i am trying to change route by using navigateToRoute  method but could not do that.
Can anybody help me solving that or please share a working example.
Note: i am using the typescript - navigation - skeleton & trying to change route on button click in welcome.html page
Thanks in advance.

**Comment by jdanyow** [comment]
Please ask these kinds of questions on the gitter channel: https://gitter.im/Aurelia/Discuss

There's a ton of developers in there helping people out with questions.

**Comment by chaituGS** [comment]
thanks
