### ISSUE TITLE
Component Lifecycle runs as many prop binded to it

### ISSUE THREAD

**Issue by DiegoGallegos4** [aurelia/binding#390]
Im currently building custom table element. It looks like this: 

```js
import {bindable} from "aurelia-framework"


export class CustomTable{
	@bindable header = {};
	@bindable data = [] ;

	bind() {
	  this.keys = this.getKeys(this.header);
	  this.values = this.getValues(this.header);
	  console.log(this.data);
	}

	getKeys(obj) {
		let keys = [];
		for(const key in obj){
			keys.push(key)
		}
		return keys
	}

	getValues(obj){
		let values = [];
		for(const key in obj){
			values.push(obj[key])
		}
		return values
	}
}
```

The View looks like this: 

```html
<template>
	<div class="table-responsive">
		<table class='table table-striped table-bordered'>
			<thead>
				<tr>
					<th repeat.for='value of values'>${value}</th>
				</tr>
			</thead>
			<tbody>
				<tr repeat.for='d of data'>
					<td repeat.for='key of keys'>${d[key]}</td>
				</tr>
			</tbody>
		</table>
	</div>
</template>
```

Call it like this: 
`<custom-table header.bind="header" data.bind="data"><custom-table>`

The issue is the following. Whenever I want to log `data`, it does it twice. Once as the array passed and other as an empty array. This creates a couple of inconvenienes as whenever I want to process the `data` an error returns on the second iteration. 

Should it just run the component's lifecycle once?

This is the log: 

![image](https://cloud.githubusercontent.com/assets/5933437/14938583/ae0e9194-0ee5-11e6-9768-70e7c6e9fa4f.png)

**Comment by jdanyow** [comment]
@DiegoGallegos4 could you put together a reproduction of what you're seeing using the Aurelia Gist: https://gist.run/?id=7542e061bc940cde506b

**Comment by DiegoGallegos4** [comment]
https://gist.run/?id=dd770d413c5ec7fd5b4a50cc5643ba87

I uploaded a photo of my console log. On the gist log I just see one thing getting log. I have two properties. Does the bind function runs once or twice?

**Comment by jdanyow** [comment]
@DiegoGallegos4 do you have an `if.bind` somewhere that is flipping from true to false and then back to true?

**Comment by DiegoGallegos4** [comment]
As a matter of fact. I do.
