### ISSUE TITLE
View does not render correctly after moving/dragging object from one binded array to another

### ISSUE THREAD

**Issue by maimon51** [aurelia/binding#391]
We're using sortable library to allow drag and drop of items from tool box to list and from list to another list.

The symptoms are strange, the drag and drop works well if we drag the last item on the list, but if we drag any other item, the next item is removed.

On the drop event we move the object from the source list to the destination list and after when debugging the state of the model appears correct. But for some reason the view does not show the model state.

One of my colleagues had a very similar problem with aurelia/sortable and was not able to resolve it.

We've tried changing the binding behavior and also use the signal to somehow force binding refresh, 

I have setup two areas on the the page that hold the two lists (right/left) and setup the sortable object on each.

```
initializeSortable(element) {
        new sortable(element, {
            group: 'widget',
            handle: ".draggable-control",
            ghostClass: 'control-ghost',
            onAdd: this.onControlAdded.bind(this)
        });
    }
```

Then on the drag event, we remove from one list and add to the other:
```
fieldContainer=that.fieldControlsLeft.splice(evt.oldIndex, 1);
this.fieldControlsLeft.splice(evt.newIndex, 0, fieldContainer);
```

**Comment by EisenbergEffect** [comment]
The best way to handle drag/drop with Aurelia or any front-end framework that manages the dom is to not let the drag drop library alter the dom in any way, but instead only use its events to know what was dropped and then update your data model appropriately based on this, allowing the framework to sync the dom changes.
