### ISSUE TITLE
@observable docs / example

### ISSUE THREAD

**Issue by michaelmalonenz** [aurelia/binding#392]
Can we please have some documentation and/or an example of the `@observable` decorator - searching from an input seems to be a common scenario where this is useful.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you include this in general binding docs you are working on?

**Comment by EisenbergEffect** [comment]
```
export class MyViewModel {
  @observable myProperty;

  myPropertyChanged(newValue, oldValue) {
    //do something here
  }
}
```

**Comment by michaelmalonenz** [comment]
Yes, sorry, I am raising this in response to @PWKad asking me to in the Gitter channel.  It wasn't me being unable to reverse engineer how to use it, it was knowing about it in the first place that was the missing piece - being in the docs would be a start.

**Comment by Gheoan** [comment]
Fixed by https://github.com/aurelia/framework/commit/7bdcb221127e3c78211c3931959dc2e89bdc15a2.
