### ISSUE TITLE
missing dependency 

### ISSUE THREAD

**Issue by TGMorais** [aurelia/binding#393]
Hi, 

I'm not sure is this an issue, or just my miss understanding of how npm works, but is not `aurelia-logging` missing from the "dependencies"? 
It's included in the jspm dependencies.

the current package
```javascript
  "jspm": {
    "registry": "npm",
//...
    "peerDependencies": {
      "aurelia-logging": "^1.0.0-beta.1.1.2",
//..
    },
    "dependencies": {
      "aurelia-logging": "^1.0.0-beta.1.1.2",
//...
    }, 
//...
  },
  "dependencies": {
 //should this not have "aurelia-logging" too?
    "aurelia-metadata": "^1.0.0-beta.1.1.3",
    "aurelia-pal": "^1.0.0-beta.1.1.1",
    "aurelia-task-queue": "^1.0.0-beta.1.1.0"
  },
```

I've pulled a fresh skeleton and installed `aurelia-i18n`, which has a dependency on this package, however after  I `run npm install`, If I run `npm run dev` an error is thrown:
```
RROR in ./~/aurelia-i18n/~/aurelia-binding/dist/commonjs/aurelia-binding.js
Module not found: Error: Cannot resolve module 'aurelia-logging' in /Users/../web-client/node_modules/aurelia-i18n/node_modules/aurelia-binding/dist/commonjs
 @ ./~/aurelia-i18n/~/aurelia-binding/dist/commonjs/aurelia-binding.js 34:22-48
```

This is because auelia-logging has not been installed, since it's missing from the dependencies

Thanks!

**Comment by EisenbergEffect** [comment]
I believe you are correct. We'll get a patch release out shortly.

**Comment by EisenbergEffect** [comment]
Released. Apologies!

**Comment by TGMorais** [comment]
Thanks! 👍 👍
