### ISSUE TITLE
Camel Case properties in SVG's

### ISSUE THREAD

**Issue by AStoker** [aurelia/binding#394]
I have a custom element that handles creating SVG elements. In the svg element itself, I bind the view box property and the rest to the element like so:
```
<svg viewBox="${viewBox}" x="${svgX}" y="${svgY}">...</svg>
```

Since the update (seemingly related to this particular part about camel case https://github.com/aurelia/binding/commit/315cfaa229c13da8355ee1dec201a09c7df507db) properties that are camel case in the svg (such as `viewBox`) no longer display, while other properties like `x` and `y` display fine.   
Also, to further define the problem, it appears that the binding for camel case properties breaks when using string interpolation. For example, this works:
```
<svg viewBox="0 0 48 48" x="${svgX}" y="${svgY}">...</svg>
```
while this doesn't (the `viewBox` property does not show in the element):
```
<svg viewBox="0 0 48 ${svgHeight}" x="${svgX}" y="${svgY}">...</svg>
```
  
Another use case is that dropping the `.bind` and simply using `view-box` as a property works:
```
<svg view-box="${viewBox}" x="${svgX}" y="${svgY}">...</svg>
```
This doesn't seem right, because view-box is not a valid svg property. It seems that the binding engine is taking any property that has a dash in it and converting it to camel case (could be wrong, but it appears to be the case here)

**Comment by Scapal** [comment]
I confirm `viewBox="0 0 ${size} ${size}”` doesn't work anymore, I have to do `view-box="0 0 ${size} ${size}”` now.
`stroke-width.bind=“strokeWidth”` stays `stroke-width.bind=“strokeWidth”` in the rendered web page and is not computed.

**Comment by AStoker** [comment]
Could be related to a previous story https://github.com/aurelia/binding/issues/59

**Comment by Scapal** [comment]
Not related since it was working before the update and the attributes we are using are present in binding/svg.js.

**Comment by AStoker** [comment]
Related in as far as the support for additional svg properties that have camel case. They mentioned adding attributes to a mapping, could be that the mapping was cleared with the new update?

**Comment by Scapal** [comment]
extract from `aurelia-binding/src/svg.js`:
```javascript
  svg: ['baseProfile','class','contentScriptType','contentStyleType','externalResourcesRequired','height','id','onabort','onactivate','onclick','onerror','onfocusin','onfocusout','onload','onmousedown','onmousemove','onmouseout','onmouseover','onmouseup','onresize','onscroll','onunload','onzoom','preserveAspectRatio','requiredExtensions','requiredFeatures','style','systemLanguage','version','viewBox','width','x','xml:base','xml:lang','xml:space','y','zoomAndPan'],
```
It already contains `viewBox`.

**Comment by EisenbergEffect** [comment]
@jdanyow Looks like we have a regression here with respect to SVG. Is this going to be easy to address?

**Comment by jdanyow** [comment]
@AStoker / @Scapal - there's a new build of templating-binding and templating-resources available- let me know if you run into any further issues with this release.
