### ISSUE TITLE
repeat.for does not update on pre-valueconverter object changes.

### ISSUE THREAD

**Issue by istrau3** [aurelia/binding#395]
Here is a reproduction:
https://gist.run/?id=9736b006cb3cc52a201d144c22176cb6

Basically, the issue appears when I try to repeat through some object that has a value converter applied to it:

```javascript
repeat.for="item of object | valueConverter"
```

what I am seeing is that, when I updated the object, the repeat does not re-render. I assume this is because it is watching the valueConverter's output. However, this is very counter-intuitive, as I would expect that when I change object, the repeat re-renders...

**Comment by EisenbergEffect** [comment]
@jdanyow I thought we fixed this...

**Comment by istrau3** [comment]
@EisenbergEffect Do I have the wrong version of aurelia in the gist? I am getting the same error on my machine using 

```
"aurelia-binding": "^1.0.0-beta.1.1.0"
```

**Comment by doktordirk** [comment]
@istrau3 current is 1.0.0-beta.1.3.4

**Comment by istrau3** [comment]
@doktordirk How do you keep up with the versions (i.e. become aware when new ones come out)?

**Comment by doktordirk** [comment]
it's announced on gitter, twitter, on the blog. i think an email newsletter is there as well if you want it automated

**Comment by doktordirk** [comment]
here we go newsletter http://durandal.us10.list-manage1.com/subscribe?u=dae7661a3872ee02b519f6f29&id=3de6801ccc

**Comment by istrau3** [comment]
Thanks.

**Comment by istrau3** [comment]
@jdanyow @EisenbergEffect I just updated aurelia-framework to the latest and tried again. Still seeing the same issue.

**Comment by EisenbergEffect** [comment]
@istrau3  We haven't been using the newlsetter yet. We will when we get closer to rtm. For now, the best way to keep up to date is through the Blog. We have a new initiative to post and announce release information every Tuesday. There's lot of other info on the blog as well though.

**Comment by valichek** [comment]
I confirm this issue exists in aurelia-binding 1.0.0-beta.1.3.3, here is my gist https://gist.run/?id=df3d84d1818a19c92ea3b96ba62d45f3 with latest aurelia (https://github.com/valichek/aurelia-bundle/tree/i18n-0.5.2v0.0.4/jspm_packages/npm)

**Comment by istrau3** [comment]
@valichek 
How are you producing these scripts:
```
<script src="https://cdn.rawgit.com/valichek/aurelia-bundle/i18n-0.5.2v0.0.4/jspm_packages/system.js"></script>
    <script src="https://cdn.rawgit.com/valichek/aurelia-bundle/i18n-0.5.2v0.0.4/config.js"></script>
```

**Comment by valichek** [comment]
@istrau3 check rawgit.com and https://github.com/valichek/aurelia-bundle/

**Comment by istrau3** [comment]
After looking at @valichek 's gist, and seeing this statement:
```
this.object = Object.assign({}, this.object, {key3: "value3"});
```
its clear that that the original object IS being watched. However, it isn't being watched deep which perhaps is not desired. I am not sure how this problem is supposed to be solved actually. The only way would be to either watch it in a deep way or to somehow reverse engineer the value converter to see what on the object needs to be watched.

**Comment by jdanyow** [comment]
```js
export class App {
  
  constructor() {
    this.object = {
      key1: 'value1',
      key2: 'value2'
    };
    
    window.setTimeout(() => {
      this.object.key3 = 'value3';
    }, 2000)
  }
}
```
```html
<template>
  <div repeat.for="value of object | objectValues">
    ${value}
  </div>
</template>
```

we've never supported this^^^

it cannot be done without dirty checking or object.observe

**Comment by EisenbergEffect** [comment]
Doh. I should have looked closer. I assumed we were iterating an array. Apologies if I added confusion here.

**Comment by istrau3** [comment]
@jdanyow So the solution here is just to replace the reference to object right? Something like this:

```
this.object = Object.assign({}, this.object, {key3: "value3"});
```
