### ISSUE TITLE
Multiple overrideContexts

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/binding#396]
We can call `.bind()` with a bindingContext and an overrideContext. Is it also possible to supply multiple overrideContexts?

The use case is as follows:

```
<template>
  <ak-grid>
    <ak-col repeat.for="col of columnsMetadata"  k-title="${col.title}" k-field="${col.field}">
      <ak-template>
        ${$this[col.field]}
      </ak-template>
    </ak-col>
  </ak-grid>
</template>
```

We use enhance to compile templates in `<ak-template>` and we do this for every row in the grid. I believe that there are actually three contexts here:
1. the dataItem behind the row (this is currently our bindingContext)
2. the view-model behind `<ak-col>` that contains a `col` property (if i'm right)
3. the view-model where the `<ak-grid>` is used in (this is currently our overrideContext)

Is it possible to somehow bind the template to these three contexts?

Thanks

**Comment by EisenbergEffect** [comment]
@jdanyow will show you the magical way :)

**Comment by jdanyow** [comment]
@JeroenVinke do you already have access to the override contexts for the ak-col and ak-grid?  trying to figure out where to start- it's going to be something like this:

```js
import {createOverrideContext} from 'aurelia-binding';

let rowBindingContext = .... the row data item ....;
let rowOverrideContext = createOverrideContext(rowBindingContext, colOverrideContext);
```

https://github.com/aurelia/binding/blob/master/src/scope.js#L12

**Comment by JeroenVinke** [comment]
> do you already have access to the override contexts for the ak-col and ak-grid?

I thought that it would be possible, but after trying things out I don't think I can get to the column override context. So i'll close this issue for now, thanks though :+1:

**Comment by jdanyow** [comment]
@JeroenVinke not sure if this will be useful for you but if you know that your element is within an ak-col / ak-grid you can use DI to access the element view models.  Here are some stackoverflow posts that might be helpful:
http://stackoverflow.com/a/32781324/725866
http://stackoverflow.com/a/36875154/725866

**Comment by JeroenVinke** [comment]
@jdanyow thanks for the links.
