### ISSUE TITLE
Addding binding at runtime not working on custom elements

### ISSUE THREAD

**Issue by dpinart** [aurelia/binding#397]
Hi,

I have an scenario where I need to setup a binding in a view at runtime. I'm intercepting "created" pipeline step in order to add the binding as follows (typescript):
```
public created(owningView:View, myView:View) {
     let doc = <Document>targetView['fragment'];
    let targetEditor = doc.querySelector('paper-input[name=editor]');
    if (targetEditor) {
        let bindingExpression = this._bindingEngine.createBindingExpression('value', 'model.dynamicProperty', bindingMode.twoWay);
       let binding = bindingExpression.createBinding(targetEditor);
      myView.addBinding(binding);
        }  }
```
This is working fine as long target editor is a polymer's element or any primitive html element like input, chechbox,... But it's not working if target editor is a custom aurelia element with a two way bindable property,setting a value to the bindable property within the aurelia component does not update the model's bound property.

I can workaround this issue by creating a markup string dynamically and using InlineViewStrategy... But I'd like to know if this is a bug, a design decission or I'm doing something wrong

**Comment by jdanyow** [comment]
You'll need to pass in the custom element's view-model instance to the `bindingExpression.createBinding(...)` call.  Not the DOM element.

**Comment by dpinart** [comment]
How can I get the view model's instance?

**Comment by jdanyow** [comment]
Assuming you have the DOM element, you can access the view model via `domElement.au.controller.viewModel`.  Here's an example: https://gist.run/?id=b9cf5b2ac96d6573a363464cefcc1c17

**Comment by dpinart** [comment]
It makes sense and, of course, it works as expected...

Thanks a lot

**Comment by jdanyow** [comment]
:+1:
