### ISSUE TITLE
Plugins with IOS and Cordova

### ISSUE THREAD

**Issue by Hansl001** [aurelia/binding#399]
Hi 
I cant seem to get plugins working on iOS and Cordova.
Using the ES2016 Start kit and for example the Aurelia-Dialog plugin (or i18n, or the validation plugin).
It works on Android with Cordova but on iOS I just get empty screen. Without loading any plugins (through main.js) the starter kit is working

What could be the problem?

**Comment by EisenbergEffect** [comment]
Please direct questions to our gitter chat room: gitter.im/aurelia/discuss
