### ISSUE TITLE
Slow DOM updates if using unshift on an array

### ISSUE THREAD

**Issue by lukechilds** [aurelia/binding#401]
I have a `posts` property that is an array of post objects displayed on the page. I have navigation buttons on the page that will make an api request and add multiple posts to the array, either at the start or the end of the array depending on which way they are navigating:

```javascript
// Insert results
if(page == 'prev') {
  this.posts.unshift(...response.posts);
} else {
  this.posts.push(...response.posts);
}
```

When `Array.push()` is used it looks like the new appended objects get new appended elements in the DOM, this is really fast.

Alternatively when `Array.unshift()` is used it seems new elements don't get **prepended**, instead it looks like the current elements stay the same and any extra elements are **appended** to the DOM so the count of DOM elements match the array length. The properties for each object in the DOM are then updated to be in sync. This seems much slower.

This is causing issues as I have an array observer listening for updates on the `posts` array. When it updates I need to check some stuff in the DOM. This works fine for `Array.push()` but with `Array.unshift()` rendering hasn't finished so I get incorrect DOM results.

Example:

```javascript
this.arrayObserver(this.posts).subscribe(() => {
  this.taskQueue.queueMicroTask(() => /* DOM stuff here */);
});
```

This worked in older versions of Aurelia. It would appear this is some sort of performance improvement to try and reuse elements, however it's definitely degrading performance in this use case.

Is there some sort of Aurelia event I can hook into that will fire when all Aurelia DOM stuff is finished for this array update? Or would I need to downgrade Aurelia to get this working again?

**Comment by EisenbergEffect** [comment]
@niieani I just sent you a core team invitation. Pending your agreement to join, this seems like a great issue for you to start work on 😄

**Comment by EisenbergEffect** [comment]
@martingust @jdanyow Would you assist @niieani as needed?

**Comment by lukechilds** [comment]
Just to add to this, it would be great if there was an event when rendering was done but it would also be great if you could set templating to not reuse DOM elements as that can sometimes be undesirable.

For example, when you change an image source in some browsers they will display the old image until the new image is loaded. So reusing an `img` element with a binded `src` attribute appears really laggy, you get duplicate images and then after a short delay one updates to the correct image.

Alternatively there amy be a better way of handling this scenario such as removing the `src` attribute before updating it.

**Comment by niieani** [comment]
@lukechilds I've tried recreating your issue, but so far I'm seeing that Aurelia does in fact prepend DOM when doing `.unshift(...)`. Aurelia does also have in place processing (`_inPlaceProcessItems`) for array repeats, but it is only used when both of these conditions are satisfied:
1. views don't require a lifecycle (i.e. not a component, no animation, etc.)
2. you splice the array by removing **and** adding values at the same time / very quickly in order (or recently also when you replace the array with a new instance that has some different elements)

[This is what](https://github.com/aurelia/templating/blob/master/src/view-slot.js#L146-L165) happens when you insert an element into the array - note the `insertNodesBefore` is there.
`unshift()` should behave similarly to `push()`, with the difference of the index, i.e. it adds a new view at an index provided, which is 0. What happens if you replace your `unshift` by `splice(0, 0, ...response.posts)` ?

Could you provide a more comprehensive piece of code showing this problem upon [forking this](https://gist.run/?id=7542e061bc940cde506b)?

As for your other issue, to force a View lifecycle on your `img` element you could create a simple custom attribute for just that. Take a look at the [`if` attribute](https://github.com/aurelia/templating-resources/blob/master/src/if.js). What you'd want to do is whenever the value changes you [remove the View from the ViewSlot](https://github.com/aurelia/templating-resources/blob/master/src/if.js#L70) and [add it back](https://github.com/aurelia/templating-resources/blob/master/src/if.js#L92).

**Comment by lukechilds** [comment]
@niieani Thanks for looking into this. The the elements data gets prepended eventually but the actual extra DOM nodes appear to get appended and then afterward the properties are all updated.

I've added a comprehensive example [here](https://gist.run/?id=bdb331f980350bf60cd54cccadee65a6)

I'm using an alert to halt execution so you can see what's going on at that point in time. You should see in the example that if you append items every things good but if you prepend there is duplicate data when the alert halts execution. As soon as you continue execution all the values are recalculated.

**Comment by lukechilds** [comment]
Just to clarify, the actual issue here isn't the way the templating works, it's that I don't think there's a way to reliably check the DOM after adding elements. If you remove the alert everything happens fast enough that both ways look fine.

It's just trying to check the DOM by adding cod to the task queue after the update works if you're appending but not if you're prepending. You _could_ fix this at the template level by doing some sort of deep compare on all of the objects and working out where the new elements should be inserted in the DOM but I'm guessing that would have a pretty steep performance penalty.

Ideally I'd say the templating should be left as is and there should be some sort of event added to bind to that fires when templating has finished for a property.

So instead of doing this:

```javascript
this.arrayObserver(this.posts).subscribe(() => {
  this.taskQueue.queueMicroTask(() => /* DOM stuff here */);
});
```

You could do something like this:

```javascript
this.arrayObserver(this.posts).subscribeRenderUpdate(() => /* DOM stuff here */);
```

Maybe you would have to subscribe to a view rather the actual `posts` object for this to work but you get the idea.

**Comment by lukechilds** [comment]
To answer your question above I get the issue with both `Array.splice` and `Array.unshift`.

**Comment by EisenbergEffect** [comment]
Have you tried `taskQueue.queueTask(() => /* DOM stuff here */)`?

**Comment by niieani** [comment]
@lukechilds Okay, sure. Thanks for your example. I see both the problem and room for improvement. As for a workaround, I'll send you something in a moment.

@EisenbergEffect indeed he has.

**Comment by lukechilds** [comment]
@EisenbergEffect  @niieani 

No I haven't, `queueTask()` does indeed [fix the problem](https://gist.run/?id=c2063f23fdd8ce6d00676335e42a4442).

Thank you very much!

**Comment by EisenbergEffect** [comment]
@niieani I didn't see any use queueTask, only queueMicroTask.

**Comment by EisenbergEffect** [comment]
@lukechilds But, is there still a performance issue?

**Comment by niieani** [comment]
@EisenbergEffect that's right, my mistake. As for the performance issue, we could add special a way to handle splices when there are only insertions happening and/or a way to manually force the `repeat` to enable view-lifecycle. Depending on how changes happen in the DbMonster, the first solution might slightly lower its refresh speed.

**Comment by lukechilds** [comment]
No, that's working perfectly. I mean it must be slightly slower than before the update because it's no longer rendered in time for `queueMicroTask()` but using `queueTask()` there is no visible lag.

There is a perceived performance issue when image elements are reused due to default browser behaviour mentioned above but I'll open a separate issue in the templating repo for that.

If it's not too much trouble could you briefly explain when you should use `queueTask()` over `queueMicroTask()` and vice versa? I've checked [the docs](http://aurelia.io/docs.html#/aurelia/task-queue/1.0.0-beta.1.2.0/doc/api/class/TaskQueue) but it just says it's "ASAP execution" vs "Turn-based execution". Could you expand on that?

**Comment by EisenbergEffect** [comment]
@niieani Talk with @jdanyow and @martingust about that to see what they think.

@lukechilds Micro tasks are put on to a draining queue that runs as soon as possible, before rendering. Macro tasks (or just tasks) are executed after the next "paint" or as soon after that as the browser will allow.

**Comment by niieani** [comment]
@lukechilds If you want to force the element to be added instead of appending & reusing the old ones you can make the element use a view-model implementing `attached` method. Like this: https://gist.run/?id=78e6ce914568a9b336d05eb301dc0c14
Now it works even with `queueMicroTask`.

**Comment by lukechilds** [comment]
@niieani Thanks, but the above gists were very simplified examples.

In my actual application I have a custom element that has array of objects that are child custom elements. I add multiple child custom elements in one go and this should trigger some logic on the parent custom element once per batch add.

If I understand the `attach()` method correctly, it would fire once on the parent element when it is added and once on each child element when they are added. There would be no way to use it to fire once when a single batch of children have been added would there?

**Comment by lukechilds** [comment]
I agree that manually adding to the `taskQueue` doesn't seem ideal though. If there's a better way to achieve this functionality with Aurelia I'm all ears 👍

**Comment by niieani** [comment]
@lukechilds I see. As far as I know, there isn't any event that fires after a repeat has finished re-rendering. I suppose your way is the closest to achieving that. 
However it would be trivial to add something like that to the `repeat` custom attribute to achieve the following:

```html
<div repeat.for="item of items" repeat-items-changed.bind="someMethod">
  ${item}
</div>
```

`someMethod` from the view-model would fire every time the repeater finished updating all its views. Would something like that solve your case? 
@EisenbergEffect Do you think this is something worth implementing?

**Comment by EisenbergEffect** [comment]
That's an interesting idea....the repeater could just raise a custom DOM event. @martingust @jdanyow What do you guys think?

**Comment by lukechilds** [comment]
@niieani That would be perfect!

**Comment by niieani** [comment]
@lukechilds Here's a monkey-patched implementation:
https://gist.run/?id=6d2d446e55947d564daae507800da5c4

Can you try if this works for you?

**Comment by lukechilds** [comment]
@niieani Yeah, that works well :)

**Comment by niieani** [comment]
@EisenbergEffect note that a custom DOM event doesn't really help here because its not clear on which element it should be raised. Instead the above implementation simply triggers a method from the ViewModel, similarly to a how a `matcher` definition is extracted from the bindingContext.

If @martingust and @jdanyow agree that this is something useful, I'll clean up the code, add tests and make a pull request to templating-resources.

**Comment by EisenbergEffect** [comment]
Good point. Let's see what the others say.
