### ISSUE TITLE
Nested Binding expression

### ISSUE THREAD

**Issue by rajivbala** [aurelia/binding#402]
I am trying to create a binding expressions (along with a few date converters) with i18n plugin as below, but i am not able to get it working

${'translation-key' | t:{'userName': user.name, 'day': $ {user. dateOfBirth | dayFormat}}

**Comment by jdanyow** [comment]
it's not possible to use string interpolation binding within a string interpolation binding  `${ ... ${ ... } ... }`

You'll need to simplify your binding expression or do it in steps like this:

```html
<div ref="myDiv" dob.bind="user. dateOfBirth | dayFormat">
  ${'translation-key' | t:{'userName': user.name, 'day': myDiv.dob}}
</div>
```
