### ISSUE TITLE
ObserverLocator error when trying to observe a constructor property

### ISSUE THREAD

**Issue by zakjan** [aurelia/binding#404]
I use TypeScript for model classes with polymorphism. In HTML templates I display a different template based on model type.

```
<li repeat.for="model in models">
    <dog-row if.bind="model.constructor === DogModel"></dog-row>
    <cat-row if.bind="model.constructor === CatModel"></cat-row>
</li>
```

I need to compare constructor because instanceof operator is not supported by templating library.

Sometimes I get this error message: Uncaught TypeError: observer.subscribe is not a function

After debugging I found out that ObserverLocator.getObserver returns a wrong value when called with propertyName = "constructor". I believe the fix is as simple as to replace `propertyName in observersLookup` with `observersLookup.hasOwnProperty(propertyName)`.

https://github.com/aurelia/binding/blob/31f69c8f6f3f79a09d4c78823cbbf4bb993dc15d/src/observer-locator.js#L48

**Comment by EisenbergEffect** [comment]
Generally, speaking, we don't advise this kind of approach to handling polymorphic rendering. Have you looked at the compose element? That is the preferred way.
