### ISSUE TITLE
Binding getter to attribute without `computedFrom` causes infinte loop

### ISSUE THREAD

**Issue by lukechilds** [aurelia/binding#405]
I have a custom element for media uploads that displays either the media that has already been saved or the blob url of the media about to be uploaded.

In my VM I have a getter to workout the correct url for the media:
```javascript
export class UploadField {
  @bindable field;

  fileToUrl(fileList) {
    return fileList ? URL.createObjectURL(fileList[0]) : false;
  }

  get src() {
    return this.fileToUrl(this.field.files) || this.field.src || '';
  }
}
```
and in my view I have:
```html
<video controls if.bind="field.element == 'video' && src" src.bind="src"></video>
<img if.bind="field.element == 'img' && src" src.bind="src"></img>
```

This appears to work, however on closer inspection if I add a file to the input it seems to infinite loop and repeatedly creates new blob urls and updates the src. Adding `@computedFrom` resolves the issue and everything works as expected:
```javascript
@computedFrom('field.files', 'field.src')
get src() {
  return this.fileToUrl(this.field.files) || this.field.src || '';
}
```

**Comment by lukechilds** [comment]
@EisenbergEffect is this expected behaviour?

**Comment by jdanyow** [comment]
yes, getters are observed with dirty-checking.
