### ISSUE TITLE
Creating observers on frozen objects?

### ISSUE THREAD

**Issue by MrHayato** [aurelia/binding#407]
Our Aurelia application is using Redux. We have everything hooked up and we're looking at different immutability options. The ones we can find are immutable.js and redux-freeze. With immutable.js, the API makes it really complicated for simple data objects we get from an API. Combine that with TypeScript, and it makes for a lot of extra work to just get typings to work properly as well. We love the idea of using redux-freeze, as Object.freeze will just make everything immutable, and leave it up to the developers to create new instances of their models.

The problem, however, is that we can't add observers to a frozen object, since Reflect.defineProperty will fail to add the `__observers__` property.

This isn't specifically an aurelia issue, since you can easily reproduce this with:

``` javascript
let obj = {};
Object.freeze(obj);
console.log('Added property?', Reflect.defineProperty(obj, 'test', {})); // false
```

But I was wondering if there's any way to work around this problem? Would a custom ObserverLocator that returns new instances of the object instead of mutating its properties work? We'd like to avoid immutable.js if possible.

Thanks!

**Comment by EisenbergEffect** [comment]
One solution is to replace the methods on the ObserverLocator with alternate implementations, yes. You use a WeakMap. In the future, this may be what we switch to internally as well. Since it's not universally implemented across the browsers we support, we use the hidden property.

**Comment by tomasbonco** [comment]
Hello,

Implementation with WeakMap should be default behavior with fallback using the hidden property, in my opinion. This would allow full usage of Immutable structures (that are popular these days) with Aurelia.

Tomáš

**Comment by gheoan** [comment]
I think WeakMap polyfills use the hidden property method so it is safe to switch to WeakMap assuming there are no other regressions.

**Comment by tomasbonco** [comment]
I was further thinking about the issue and I think I was wrong. There is no need for an observer in case of immutable structures in a first place (besides getting rid of warnings).

**Comment by Archelyst** [comment]
For arrays this unfortunately does not give a warning but it fails and raises an exception, because it assumes, that the property was set (but it's `undefined`)
