### ISSUE TITLE
observable decorator not working with decorators function

### ISSUE THREAD

**Issue by Gheoan** [aurelia/binding#408]
Here is a reproduction: https://gist.run/?id=db11dd4fd9e4dd1908fc88778a60aa5d.

**Comment by jdanyow** [comment]
@EisenbergEffect is this supposed to work?

**Comment by EisenbergEffect** [comment]
@jdanyow We should probably make it work in order to support pure ES6. The decorator implementation will need to be updated to account for this scenario.

**Comment by Gheoan** [comment]
Is this being worked on? I would like to develop without a transpiler.

**Comment by EisenbergEffect** [comment]
PRs are welcome.
