### ISSUE TITLE
as-element or custom elements breaks when used in tables

### ISSUE THREAD

**Issue by 4nderss** [aurelia/binding#409]
Have tried to comment in [closed issue](https://github.com/aurelia/binding/issues/305) but seems dead? 

> ViewModel

```
<tbody as-element="row-model" class="section-body" repeat.for="item of items" model.bind="item">
				
</tbody>
```

> rowmodel.html

```
<template>
<require from="somerequirement"></require>

<tr click.delegate="viewDetails = !viewDetails>
<td>${model.property1}</td>
<td>${model.property2}</td>
</tr>
<tr show.bind="viewDetails">
<td>${model.detail1}</td>
<td>${model.detail2}</td>
</tr>
</template>

```

Currently works without require in chrome but not with, does not work at all in IE. Renders without any tr or td containers. 

[See plunkr](http://plnkr.co/edit/4hjqxcXmVLv325y3gvkw?p=preview)

**Comment by jdanyow** [comment]
are you sure you want to repeat a `tbody` element?  Did you mean to use a `tr` element?

>`<tbody as-element="row-model" class="section-body" repeat.for="item of items" model.bind="item">`

**Comment by 4nderss** [comment]
Yes, this is because of our perticular setup where we have 3 identical lists with spacing inbetween (future, current and historical itemgroups). And each itemgroup contains several items(tbody) and a item(tbody) has n number of tr groups depending on the items setup. Normally there are 2 sets of tr(row details and expanded info) but depending on the amount of changes made to the item the amount of tr grows. So grouping each item inside a tbody makes it alot smoother when styling and managing the item. 

Although we are flexible if you can provide us with anoter way to have a custom element with multiple tr and repeat that custom element it would suffice :)

**Comment by EisenbergEffect** [comment]
I'm guessing that having multiple tbody elements is a problem for certain browsers.

**Comment by 4nderss** [comment]
Well as you can see in the plunkr, rendering it normally (without custom elements) and just repeating on the tbody and having all the html inside the repeated tbody. Everything will render correctly. Problem with this is that we have to copy paste all that html for each of the three sections making it really unmanageable when we change in one place.

```
<tbody class="section-body" repeat.for="item of items">
<tr click.delegate="item.viewDetails = !item.viewDetails>
<td>${model.property1}</td>
<td>${model.property2}</td>
</tr>
<tr show.bind="itemviewDetails">
<td>${model.detail1}</td>
<td>${model.detail2}</td>
</tr>
</tbody>
```

**Comment by Einarsson** [comment]
To me this looks like the classic bug with IE for example. It doesn't allow <template> elements inside table and thus screws up the rendering which would explain why it works in your last example but not when using a custom element. 

This is an issue posted with a lot of frameworks around the community but as far as I know there are no workarounds for it yet.

**Comment by MikaelPorttila** [comment]
bump, any news on this **bug**?

**Comment by EisenbergEffect** [comment]
It's an IE bug. As stated above, it's a problem that all frameworks suffer from and there isn't a way to work around it. Try taking a completely different approach.

**Comment by robharper** [comment]
@4nderss I have the same problem with `as-element` with a `<tr>`, and in Chrome. Easy work around is to move the `require` inside the first child element within the inner view.

Table:
```
<tr as-element="tr-view" cells.bind="whatever"></tr>
```

Inner view
```
<!-- tr-view -->
<template>
  <td repeat.for="cell of cells">
    <require from="../utils/value-formatter"></require>
    <!-- ... -->
  </td>
</template>
```

**Comment by istrau2** [comment]
+1 same issue @robharper solution worked. If the require tag is a direct child of the template tag, weird things happen.

**Comment by erilot** [comment]
You can also remove the `<require>` statements from the view/template and use the `@viewResources` decorator on the accompanying VM instead (assuming you have one):

```
import {viewResources} from 'aurelia-framework';

@viewResources('./path/to/something', './path/to/another/thing')
export class XYZ {
...
}
```

Aurelia documentation: http://aurelia.io/hub.html#/doc/article/aurelia/templating/latest/templating-custom-elements/7

**Comment by huochunpeng** [comment]
@robharper see 
https://github.com/aurelia/aurelia/issues/116#issuecomment-458332326 about the require out of tr thing.

**Comment by ggayowsky** [comment]
Not that this is ever getting fixed... but contrary to what has been said here., this is an aurelia problem, not an IE problem. Every other framework I has a solution to this.

Anyways, as said earlier, take a different approach as this won't work and this framework has no intention of fixing any problems or making your life easier

**Comment by bigopon** [comment]
@ggayowsky It'da been fixed long ago, if it was actionable, but maybe let's try to see how your template looks like first? There could be something missing from the framework side?

**Comment by ggayowsky** [comment]
@bigopon Here is a easily and small repro of this problem:

I will happily open another issue if that would be advised.

custom-table-component.html
```
<template>
  <require from="./custom-row-component"></require>
  <table class="table">
    <thead>
      <tr>
        <th>Header A</th>
        <th>Header B</th>
        <th>Header C</th>
      </tr>
    </thead>
    <tbody>
      <tr as-element="custom-row-component"
        repeat.for="row of fileTableRows"
      ></tr>
    </tbody>
  </table>
</template>
```

custom-row-component.html

```
<template>
  <td>
    A
  </td>
  <td>
    B
  </td>
  <td>
    C
  </td>
</template>
```

Both JS classes are just stubs.

The output in IE is (cleaned for readability):

```
<table class="table">
  <thead>
	<tr>
	  <th>Header A</th>
	  <th>Header B</th>
	  <th>Header C</th>
	</tr>
  </thead>
  <tbody>
    <!-- Weird solution to dynamically compose repeatable row: https://github.com/aurelia/binding/issues/556#issuecomment-269352204 -->
    <tr class="au-target" au-target-id="1702" as-element="custom-row-component">
      A B C
    </tr>
    <tr class="au-target" au-target-id="1702" as-element="custom-row-component">
      A B C
    </tr>
    <tr class="au-target" au-target-id="1702" as-element="custom-row-component">
      A B C
    </tr>
    <tr class="au-target" au-target-id="1702" as-element="custom-row-component">
      A B C
    </tr>
    <tr class="au-target" au-target-id="1702" as-element="custom-row-component">
      A B C
    </tr>><!--anchor-->
  </tbody>
</table>
```

As you can see the TD element are stripped from the `custom-row-component` output.

HTML Output in Chrome/ FF is as expected.

**Comment by bigopon** [comment]
@ggayowsky Is the content of `custom-row-component` missing?

**Comment by bigopon** [comment]
@ggayowsky Though, I think I can guess what the content of `custom-row-component` is, it's probably like:
```html
<template>
  <td>A</td>
  <td>B</td>
  <td>C</td>
</template>
```
If so, it's as you saw. As per following simple test:
![image](https://user-images.githubusercontent.com/9994529/93405460-6cc5a680-f8d0-11ea-97c1-1083dd5c6fed.png)

With the latest version of Aurelia templating, we have a way to overcome this, though. Instead of relying on the HTML parser to transform HTML string into HTML template, and potentially mess up the structured intended, we can do that transformation ourselves, or build the HTML template ourselves, to be precise.

An example:
```ts
function buildTemplate() {
  const template = document.createElement('template');
  const firstTd = document.createElement('td');
  firstTd.textContent = 'A';
  // ...second, third etc
  template.appendChild(firstTd);
  return template;
}

export class CustomRowComponent {
  static $view = buildTemplate()
}
```

Edit: note that this should be used for this scenario only. You don't have to go this tedious to declare the template for your component. You can just do the following, or any other ways that you have been doing:

```ts
export class CustomRowComponent {
  static $view = `<template>
    ...
  </template>`
}
```

**Comment by ggayowsky** [comment]
Yea missed a backtick in my earlier post which mucked up the formatting. It has been fixed now.

While I appreciate the work around, and it might work for the simple reproduction I provided, it isnt sufficient for actual uses. The reason being, most templates have bound values in there (much like ours does) and I dont know how I would accomplish that with your workaround.

In this case, it was just easier to use divs + table layout styling.

I believe that this issue should be reopened, instead of being dismissed as a user error, since this is a capability this framework lacks

**Comment by bigopon** [comment]
For:
> most templates have bound values in there (much like ours does)

You can achieve the same thing with the following template
```html
<template>
  <td>${someContentA}</td>
  <td>${someContentB}</td>
  <td>${someContentC}</td>
</template>
```
by the following template building code
```ts
function td(text) {
  const $td = document.createElement('td');
  $td.textContent = text;
  return $td;
}
function buildTemplate() {
  const template = document.createElement('template');
  template.appendChild(td('${someContent1}'));
  template.appendChild(td('${someContent2}'));
  template.appendChild(td('${someContent3}'));
  return template;
}
```
Basically we are building the template, to be bound with data later, not the final view of a custom element. So whatever the expression/template syntax you use, you can do the same, just have to write them in a more tedious form.

**Comment by ggayowsky** [comment]
Thanks for the workaround. I still think the issue should be reopened
