### ISSUE TITLE
Is there any way to fill a table using repeat.for

### ISSUE THREAD

**Issue by ashanvabs** [aurelia/binding#410]
I have a html structure like below. so i need to create that structure by using a array of elements.
`<tr>
  <td>aa</td>
  <td>bb</td>
  <td>bb</td>
<tr>
<tr>
  <td>aa</td>
  <td>bb</td>
  <td>bb</td>
<tr>
<tr>
  <td>aa</td>
  <td>bb</td>
  <td>bb</td>
<tr>`
I want to fill a table using same array elements. so is there any specific way to perform that.

**Comment by EisenbergEffect** [comment]
Please ask questions at gitter.im/aurelia/discuss
