### ISSUE TITLE
Enable value converters with `ref` bindings.

### ISSUE THREAD

**Issue by davismj** [aurelia/binding#412]
My particular use case is that I'm using `element.ref` to grab an SVG element, which I then pass to [snap.svg](http://snapsvg.io/) for use in my viewModel. At the moment, I can do this by wrapping the svg in the `Snap` object in the `attached()` callback, but it would be nice and make sense to create a `valueConverter`:

**snapValueConverter.js**
```
class AsSnapValueConverter {
  fromView(svg) {
    return Snap(svg);
  }
}
```

**bestViewEver.html**
```
<svg element.ref="svg | asSnap"></svg>
```

At the moment, this results in a heartbreaking error:

> aurelia-binding.js:1304 Uncaught (in promise) TypeError: Cannot read property 'valueConverters' of undefined(…)

**Comment by EisenbergEffect** [comment]
@jdanyow You broke the package.json for jspm with this commit. Please revert changes to the package.json. Thank  you :)

**Comment by EisenbergEffect** [comment]
You can keep the additions, but look at what was removed in the commit. Those things should not be removed.

**Comment by jdanyow** [comment]
Not sure how I missed that!  I had added the two new dev deps manually too...  Fixed now.
