### ISSUE TITLE
Apache cordova x.two-way binding not working in android 4.0.x

### ISSUE THREAD

**Issue by behzad888** [aurelia/binding#415]
In Android 4.0.x to 4.4.4 two-way binding not working until .bind is ok.

**Comment by jdanyow** [comment]
need more info

**Comment by behzad888** [comment]
When we use `src.two-way` instead `src.bind` in view like [this](https://github.com/au-cordova/com.auCordova.catalogue/blob/master/client/js/app/details-list/details-list.html#L11), on android 4.0.x to android 4.4.4 `.two-way` do not working, but `.bind` is ok.

**Comment by EisenbergEffect** [comment]
Two-way binding isn't going to work on an image src. Are you seeing this with form controls as well?

**Comment by behzad888** [comment]
Yes its work with controls, Thanks.
