### ISSUE TITLE
Unable to pass class context to binding engine

### ISSUE THREAD

**Issue by Furynation** [aurelia/binding#417]
I'm trying to update a property in my class via a callback passed/called from a propertyObserver subscription (in my case a SetterObserver.subscribe() callback)). In my case, "this" is undefined. Using the BindingEngine propertyObserver, it looks like only the callback is ever passed, even though there is a signature in SubscriberCollection.addSubscription which allows you to pass a context. Given this code:

```javascript
import {inject} from 'aurelia-framework';
import {EventAggregator} from 'aurelia-event-aggregator';
import {BindingEngine} from 'aurelia-binding';

@inject(EventAggregator, BindingEngine)
export class UserFundsFormCustomElement {           
    committed = 0.00;
    uncommitted = 0.00;
   
    constructor(eventAggregator, bindingEngine) {
        this.ea = eventAggregator;

        let sub = bindingEngine.propertyObserver(this, 'committed')
            .subscribe(this.committedOnChange);       
    }
	
	  committedOnChange(oldValue, newValue){
            var diff = newValue - oldValue;

		    //"this" is undefined here		
            diff < 0 ? this.uncommitted = this.uncommitted + Math.abs(diff) : this.uncommitted = this.uncommitted + diff;
    }
}
```

"this" is undefined in committedOnChange. If I change the subscribe line to "subscribe(this, this.committedOnChange) it fails as well because BindingEngine.propertyObserver only ever calls observer.subscribe(callback), it ignores the context.

Not sure if this is intended, but if not, is it possible to update class properties within an property subscriber?

**Comment by jdanyow** [comment]
the dreaded javascript `this` issue strikes again!

change: 
```js
let sub = bindingEngine.propertyObserver(this, 'committed')
            .subscribe(this.committedOnChange);
```
to 
```js
let sub = bindingEngine.propertyObserver(this, 'committed')
            .subscribe(this.committedOnChange.bind(this));
// or this:
let sub = bindingEngine.propertyObserver(this, 'committed')
            .subscribe((newValue, oldValue) => this.committedOnChange(newValue, oldValue));
```

**Comment by Furynation** [comment]
I thought I had tried every possible combination of passing this in, save for this one :) Thank you very much!
