### ISSUE TITLE
Binding a textarea's rows property to an undefined value throws exception

### ISSUE THREAD

**Issue by icanhasjonas** [aurelia/binding#418]
Firefox doesn't seem to like when assigning a undefined value to an attribute. In my case it was the `rows` attribute on a `<textbox>`

```html
<template>
   <textarea rows.bind="rows"></textarea>
</template>
```

```js
export class SomeViewModel {
  rows = 2

 activate(){ this.rows = undefined; }  // explosion triggered here
}
```

Firefox throws `IndexSizeError: Index or size is negative or greater than the allowed amount`
@ https://github.com/aurelia/binding/blob/master/src/property-observation.js#L8 (That's `propertyAccessor.setValue()`)

**Comment by jdanyow** [comment]
I think you can cause similar exceptions in Internet Explorer by setting a `td` element's `colspan` to an invalid value.  The binding system doesn't try to fixup or normalize the data.  Looks like firefox and edge throw and chrome eats the error.


```js
var t = document.createElement('textarea');
console.log(`rows is ${t.rows}`);
t.rows = undefined;
console.log(`rows is ${t.rows}`);
```

chrome:
![test](http://i.imgur.com/Z16ggrz.png)

firefox:
![test](http://i.imgur.com/hPVvQmd.png)

edge:
![test](http://i.imgur.com/QvAc9Zw.png)
