### ISSUE TITLE
Callbacks rather than string-based property lookups.

### ISSUE THREAD

**Issue by mikecann** [aurelia/binding#419]
Hi All,

Im not sure how feesable this is, I have had only a brief look through the code.

It would be great if instead of (or in addition to) doing something like:

```
binding.propertyObserver(someObject,  "myProp");
```

You could do the following:

```
binding.propertyObserver(someObject, o => o.myProp);
```

That would remove the "magic stringness" and enhance tooling support such as refactor.

Thoughts?

If you think its worth doing I may have a look at implementing it.

**Comment by jdanyow** [comment]
it already works like this- the other signature is primarily used internally to reduce memory pressure by eliminating closures.

Here's an example:  https://gist.run/?id=fea20e7760122b7292888b2aa653e202
```js
import {BindingEngine, inject} from 'aurelia-framework';

@inject(BindingEngine)
export class App {
  message = 'hello world';
  
  constructor(bindingEngine) {
    let obj = { foo: 'bar' };
    bindingEngine.propertyObserver(obj, 'foo').subscribe(newValue => alert(newValue));
    obj.foo = 'baz';
  }
}
```

**Comment by mikecann** [comment]
@jdanyow thanks but thats not strictly what I meant. 

In your example you are still referencing "foo" by name:

```
 let obj = { foo: 'bar' };
    bindingEngine.propertyObserver(obj, 'foo').subscribe(newValue => alert(newValue));
```

I would like to remove that string reference by using a callback to get the property:

```
 let obj = { foo: 'bar' };
    bindingEngine.propertyObserver(obj, o => o.foo).subscribe(newValue => alert(newValue));
```

**Comment by jdanyow** [comment]
My bad, I misunderstood.  I think that would make a nice plugin.  Here's a Gist that shows how that could be done:

https://gist.run/?id=fea20e7760122b7292888b2aa653e202

**Comment by mikecann** [comment]
Awesome! Ill have a look at writing something like that up :+1:
