### ISSUE TITLE
Index and length assignments not observed by ModifyArrayObserver

### ISSUE THREAD

**Issue by martingust** [aurelia/binding#42]
ModifyArrayObserver does not deliver change records on index and length assignments. 

Example:

```javascript
var foo = [1, 2, 3];

foo[1] = 9;
foo.length = 0;
````

**Comment by EisenbergEffect** [comment]
That's correct. It's also impossible to fix as far as I know. The only reasonable solution I can think of is to add a method to array prototype called `set` for setting array indexes that we can use to publish the change notifications for observable arrays. We'd have to do something with the length that was similar.

**Comment by martingust** [comment]
Alright. Yeah couldn't think of any way to solve it either. Hmm with that at least other browser than Chrome will have a way to handle this. Though when Array.observe arrives the pollyfill will need to be kept or code will break. Might be better to not support it anyway...

**Comment by EisenbergEffect** [comment]
Need to think about it....let's wait until someone complains and then see what we want to do.

**Comment by martingust** [comment]
Sounds good. I'm closing this.

**Comment by schnetzi** [comment]
How should it be solved in the frontend to iterate over an `ModifyArrayObserver` to render entries of the array?

```
<div repeat.for="myArray of myModifyArrayObserver">
  <span>${myArray.property}</span>
</div>
```

Because the length is 0 I don't get rendered anything at all. Or do I miss anything? Thanks in advance!

**Comment by bigopon** [comment]
@schnetzi Can you help post your question on Discourse https://discourse.aurelia.io? It will be easier to follow up there. Also would be nice if you could give some more details of what you want to achieve.
