### ISSUE TITLE
Double Two-way binding not working with custom element

### ISSUE THREAD

**Issue by Roustalski** [aurelia/binding#420]
Hi,

I have a custom component, `coolcomp`, in the following demo, that has a property `searchString`. I am referencing coolcomp from the welcome view and binding the firstName property to the referenced coolcomp's search-string property.

When I type in coolcomp and hit submit, the value I entered does not show in the popup.

Is this a known limitation, a binding bug, or did I simply not wire it together correctly?

https://github.com/Roustalski/skeleton-navigation/commit/284e4a2c6730d6a413bcb2633c4b41e57f7e5d0d

https://github.com/Roustalski/skeleton-navigation/commit/23d33ffeac2128a160a32a95d103438d7814b44b

Thanks!!

**Comment by Roustalski** [comment]
Since it is a custom component, the search-string in the example needs to have the .two-way=... attribute modifier. Herp derp.

**Comment by EisenbergEffect** [comment]
You can also define the bindable on the element as have a defaultBindingMode of two-way if you want to use .bind.

**Comment by erikvullings** [comment]
Actually, this does not work in case you don't have a view template. E.g. in my case, I've created a simple custom element (a d3 wrapper) which doesn't have a view, and although the attributes flow in, even when I explicitly specify two-way binding, they don't flow back. 

As a test, I've taken the skeleton-typescript-webpack (3 May 2017) version and created a custom element without a view. However, the custom-element 's attributes are not updated and keep their old value. Is this still a bug, or am I doing something wrong?

`custom-element.ts`
```javascript
import { bindable, customElement, autoinject, noView, bindingMode } from 'aurelia-framework';

@customElement('custom-element')
@noView
@autoinject
export class CustomElement {
  @bindable public hello = '';
  @bindable( { defaultBindingMode: bindingMode.twoWay } ) public name = '';

  constructor(private el: Element) { }

  public attached() {
    this.el.innerHTML = `<h1>${this.hello}, ${this.name}</h1>`;
    this.hello = 'My'; // I expect these to be updated in the custom-element
    this.name = 'Test';
  }

  public helloChanged(newValue: string, oldValue: string) {
    console.log(`Hello changed from ${oldValue} to ${newValue}`);
  }

  public nameChanged(newValue: string, oldValue: string) {
    console.log(`Name changed from ${oldValue} to ${newValue}`);
  }
}
```
And I use it from the `welcome.html` page
```html
  <require from="./custom-element"></require>

  <section class="au-animate">
    <custom-element name="Aurelia" hello="Hello"></custom-element>
```
