### ISSUE TITLE
getContextFor is missing in aurelia-binding.d.ts

### ISSUE THREAD

**Issue by Opiskull** [aurelia/binding#422]
Hi,

I tried the aurelia-validatejs package yesterday within a typescript project and it doesn't find the getContextFor function in the typescript definition. So adding this function to `aurelia-binding.d.ts` should fix that problem.

**Comment by jdanyow** [comment]
need to fix this in the validatejs package.  this is an internal API we don't need to expose

**Comment by jdanyow** [comment]
Issue moved to [aurelia/validatejs #76](https://github.com/aurelia/validatejs/issues/76) via [**ZenHub.io**](https://www.zenhub.io/)
