### ISSUE TITLE
Handle caret position after toView processing

### ISSUE THREAD

**Issue by qraynaud** [aurelia/binding#427]
When I use a ValueConverter to render a field like a currency, let's say it adds dots and `$` where needed, though adding a `.` or the `$` sign may disrupt the experience some, actually the current implementation makes the caret jumps after the last character every time someone types something in the input. This is even more disturbing, especially if the user wants to add digits in the middle of the number.

My use case is the following:
```html
<input value.bind="property | currency:'<some format>'" />
```

With currency (simplified):
```js
exports class CurrencyValueConverter {
  fromView(str) {
    return numbro().unformat(str);
  }

  toView(value, format) {
    return numbro(value).format(format);
  }
}
```

There is 2 solutions that I can think about:
- have the normal algorithm save/restore caret in between every matches
- have a binding behavior do this, but this seems like a bad idea because a  binding behaviour can be used on a component thus it would not work properly depending on where it is used which looks bad

**Comment by jdanyow** [comment]
It's tempting to make controls using value converters but the best way to do this is to create a custom element or attribute.  Then you'll have the ability to control the formatting *and the behavior* of the element.

**Comment by qraynaud** [comment]
I understand this pretty well. I was just pointing out that a simple input element with a ValueConverter cannot be used to do a simple formatting in the input without a very bad experience. input + format with currency is not very extraordinary but the caret always jumping at the end is bothersome.

Does it really seems appropriate to you that when I add a digit in the middle of my number, only because spaces are reordered all around thanks to formatting, my cart jumps to the end of the input? Wouldn't restoring the caret be the better user XP in most cases?

So I do a custom attribute to do this? Then I can't make more complex renderings because I can't stack them. That was the point of the ability to pipe a converter into another right? And it won't behave fine if I want to use it on another component that expects a value.

I like the way aurelia is conceived because you can always build a small bit of code that can neatly fit in everything else. I really don't see the custom attribute/element fit for this problem.

I can't even begin to fathom how I can even write a custom attribute that will do what I want without 20 times as much code as what I have now and a lot of complex edge cases.

I'm OK to try to make a PR for this if you are willing to merge it & provide some direction as to where to look in the codebase. I found the parts I read neatly written and easy to understand and I don't think it is a hard patch.

**Comment by jdanyow** [comment]
Try a binding behavior.  It's a lot like a value converter but it gives you full access to the binding, the element, etc.  Value converters can be thought of as a side-effect free / pure data pass-through.  Binding behaviors are more advanced, they allow adding behavior like cursor movement.

```js
export class CurrencyFormatBehavior {
  bind(binding, source, format) {
    binding.standardUpdateSource = binding.updateSource;
    binding.updateSource = function(newValue) {
      this.standardUpdateSource(numbro().unformat(newValue));
    };
    binding.standardUpdateTarget = binding.updateTarget;
    binding.updateTarget = function(newValue) {
      binding.standardUpdateTarget(numbro(value).format(format));
      const element = this.target;
      // mess with cursor position...
    };
  }

  unbind(binding, source) {
    binding.updateSource = binding.standardUpdateSource;
    binding.updateTarget = binding.standardUpdateTarget;
  }
}
```

https://www.danyow.net/aurelia-binding-behaviors/

**Comment by qraynaud** [comment]
I know of them and already implemented some. My issue is that you can use a ValueConverter on a custom element. If you put a binding behavior instead, it would work great on base inputs. You could even easily make it work on custom element you know of. But what of components that you are unaware of completely.

The ValueConverter thing is only an example. If I have a keypress event and modify the value in the model that is bound to the current input, the caret will also jump at the end of the input.

So let's reformulate my request: is it possible to make aurelia restore caret position each time it modifies the value of an element that has focus?

**Comment by thiagomaia971** [comment]
Hi! I'm going through the same problem. My solution was create a ValueConverter to converter toView and fromView, and create a CustomAttribute for handle the caret position behavior. But the code got crap. Has anyone made another implementation?

**Comment by gman7911** [comment]
I Have this issue when editing numeric fields as described above, with a ValueConverter, is there a solution for this without major re-coding. @thiagomaia971 did your CusomtAttribute handle the caret position correctly? Do you have an example?
