### ISSUE TITLE
support radio inputs

### ISSUE THREAD

**Issue by jdanyow** [aurelia/binding#43]
[discussion on gitter chat](https://gitter.im/Aurelia/Discuss?at=54eb3d7a22844aed1cab8b42)

**Comment by jdanyow** [comment]
# special handling for checked.bind

prior art:  http://knockoutjs.com/documentation/checked-binding.html

## scenarios

### 1)  Radio:  checked.bind="stringProperty"
``` javascript
export class Test {
  constructor() {
    this.colors = ['red', 'green', 'blue'];
    this.selectedColor = 'red';
  }
}
```
``` markup
<input type="radio" name="colors" repeat.for="color of colors"
  value.bind="color" checked.bind="$parent.selectedColor" />
```
*The binding will set the element's checked property to true when the view model's selectedColor value matches the input's value property.*

-------------------------------------------------------------------------------------

### 2)  Radio:  checked.bind="objectProperty"
``` javascript
export class Test {
  constructor() {
    this.colors = [ { name: 'red' }, { name: 'green' } , { name: 'blue'} ];
    this.selectedColor = this.colors[0];
  }
}
```
``` markup
<input type="radio" name="colors" repeat.for="color of colors"
  model.bind="color" checked.bind="$parent.selectedColor" />
```
*The binding will set the element's checked property to true when the view model's selectedColor value matches the input's model property.*

-------------------------------------------------------------------------------------

### 3)  Radio:  checked.bind="booleanProperty"
``` javascript
export class Test {
  constructor() {
    this.isAChecked = true;
    this.isBChecked = false;
  }
}
```
``` markup
<input type="radio" name="colors" value="A" checked.bind="isAChecked" />
<input type="radio" name="colors" value="B" checked.bind="isBChecked" />
```
*This scenario doesn't seem like it would be very useful.  Included for completeness.*

-------------------------------------------------------------------------------------

### 4)  Checkbox:  checked.bind="booleanProperty"
``` javascript
export class Test {
  constructor() {
    this.isChecked = true;
  }
}
```
``` markup
<input type="checkbox" checked.bind="isChecked" />
```
-------------------------------------------------------------------------------------

### 5)  Checkbox:  checked.bind="arrayOfStrings"
``` javascript
export class Test {
  constructor() {
    this.colors = ['red', 'green', 'blue'];
    this.selectedColors = ['red'];
  }
}
```
``` markup
<input type="checkbox" name="colors" repeat.for="color of colors"
  value.bind="color" checked.bind="$parent.selectedColors" />
```
*The binding will push/splice the element's value from the viewmodel's selectedColors property*

-------------------------------------------------------------------------------------

### 6)  Checkbox:  checked.bind="arrayOfObjects"
``` javascript
export class Test {
  constructor() {
    this.colors = [ { name: 'red' }, { name: 'green' } , { name: 'blue'} ];
    this.selectedColors = [ this.colors[0] ];
  }
}
```
``` markup
<input type="checkbox" name="colors" repeat.for="color of colors"
  model.bind="color" checked.bind="$parent.selectedColors" />
```
*The binding will push/splice the element's model value from the viewmodel's selectedColors property*

-------------------------------------------------------------------------------------

**Comment by EisenbergEffect** [comment]
Looks good. Let's move ahead with this. Thanks!
