### ISSUE TITLE
Lexer and ParserImplementation in typescript definition

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/binding#430]
I just noticed that `Lexer` and `ParserImplementation` aren't in the typescript definition. I would create a PR but I can't explain what `Lexer` and `ParserImplentation` does (not well atleast).

**Comment by EisenbergEffect** [comment]
For the time being, we've purposefully kept the public api small, not exposing inner details that could change. We could expose this in the future if there's a good use case for you using the Lexer/parser directly.
