### ISSUE TITLE
Two-Way binding for class attribute

### ISSUE THREAD

**Issue by MaartenThomassen** [aurelia/binding#433]
Currently, the class attribute on any element can't be two-way bounded to.

class-observer.js states the following:

```
subscribe() {
    throw new Error(`Observation of a "${this.element.nodeName}" element\'s "class" property is not supported.`);
  }
```

Is there a reason for this? If so, i would like to add this functionality. 

A use case:

Bootstrap has some javascript plugins using jquery to do some stuff like collapse a panel. This adds and removes class properties "in", "collapse" and "collapsed" to a div element wrapping the panel. I would like to two-way bind to this to observe when "in" is being added or removed so i can define a boolean property "collapsed" on my custom Control (which can also be bound to) to control whether or not the panel inside my custom Control is collapsed.

**Comment by EisenbergEffect** [comment]
I can't think of a good way to do that without using a MutationObserver. It seems pretty edge case...

**Comment by MaartenThomassen** [comment]
My current workaround is using a MutationObserver indeed. What would be the reason for not using that here?

**Comment by EisenbergEffect** [comment]
It could be done. @jdanyow would have to comment on how best to integrate two-way binding of non-input attributes going forward. This would only happen upon explicit request and wouldn't be the cheapest thing in the world probably. We can do this post, RC.

**Comment by MaartenThomassen** [comment]
Allright. I'd be willing to assist with that when the times comes. I do however lack the deeper knowledge of javascript and browsers you guys have to judge if an implementation is good or bad performance wise though.

For now, I've constructed my own workaround, but it would be nice to have this in a future version.

**Comment by atsu85** [comment]
@MaartenThomassen, could You share Your workaround here with the community? :)

**Comment by jdanyow** [comment]
You could add this capability with a binding behavior:  https://gist.run/?id=eaf7783359307513c0013808049307f1

**Comment by MaartenThomassen** [comment]
@atsu85 I've used a MutationObserver https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver on the <div> element i wanted to two-way bind the class on and whenever the class property updates i check for a certain keyword and if that keyword is present i set my "collapsed" property is true and if its not present i set it to false.

**Comment by EisenbergEffect** [comment]
Closing this since the question was answered. @jdanyow If you get a chance...this might make a really interesting addition to the binding behavior docs.
