### ISSUE TITLE
name-expression: Include target element in thrown error

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia/binding#434]
Aurelia throws an error if it can't find an `au` property on an element, defined here: https://github.com/aurelia/binding/blob/b3e48bf42aa2f545652876b69778fc254ef55c55/src/name-expression.js#L4

If this error is thrown, there's no way to detect which element caused the problem. Suggestion - add a property to the instance of the error with the problematic element to aid troubleshooting.

**Comment by jdanyow** [comment]
https://github.com/aurelia/binding/pull/429

**Comment by jdanyow** [comment]
fixed
