### ISSUE TITLE
Typings: Access{Scope/Member/Keyed} should be classes

### ISSUE THREAD

**Issue by MeirionHughes** [aurelia/binding#436]
in source you have: 
```
export class AccessScope extends Expression
export class AccessMember extends Expression
export class AccessKeyed extends Expression
```

but in the typings (1.0.0-beta.2.0.7): 
```
export declare interface AccessScope extends Expression
export declare interface AccessMember extends Expression 
export declare interface AccessKeyed extends Expression {
```

its a minor issue, but it would be nicer if these could be typed as classes and not interfaces as it would allow clean use of `instanceof` comparison. 

... these are missing the variables in the typings as well.

**Comment by jdanyow** [comment]
@MeirionHughes I'm happy to change this- quick question for you- what did you mean by:

>these are missing the variables in the typings as well

**Comment by MeirionHughes** [comment]
Cool! please. :D 

What ever you use to create the definitions isn't picking up the way you define your variables (constructor only). So in any case where you haven't declared the variable explicitly outside the constructor, you're missing that off the typings output. Makes it difficult to develop against the types (there was a lot of console.log involved. :D).

**Comment by MeirionHughes** [comment]
Alternatively; you could go the same way TypeScript has gone and have all Expressions and Access Nodes supply a `kind` value. You'd also have an enum that lists all the Kinds. You could keep with the interfaces with this approach.
