### ISSUE TITLE
@observable broken in TypeScript

### ISSUE THREAD

**Issue by jdanyow** [aurelia/binding#438]
http://www.typescriptlang.org/play/#src=function%20observable(keyOrTargetOrConfig%3A%20any%2C%20_key%3F%3A%20string%2C%20_descriptor%3F%3A%20PropertyDescriptor)%20%7B%0A%20%20let%20deco%20%3D%20function(target%2C%20key%2C%20descriptor)%20%7B%0A%20%20%20%20if%20(!key)%20%7B%0A%20%20%20%20%20%20key%20%3D%20typeof%20keyOrTargetOrConfig%20%3D%3D%3D%20'string'%20%3F%20keyOrTargetOrConfig%20%3A%20keyOrTargetOrConfig.name%3B%0A%20%20%20%20%7D%0A%20%20%20%20%2F%2F%20use%20a%20convention%20to%20compute%20the%20inner%20property%20name%20and%20the%20callback%0A%20%20%20%20%2F%2F%20function%20name.%0A%20%20%20%20let%20innerPropertyName%20%3D%20%60_%24%7Bkey%7D%60%3B%0A%20%20%20%20let%20callbackName%20%3D%20(keyOrTargetOrConfig%20%26%26%20keyOrTargetOrConfig.changeHandler)%20%7C%7C%20%60%24%7Bkey%7DChanged%60%3B%0A%0A%20%20%20%20if%20(descriptor)%20%7B%0A%20%20%20%20%20%20%2F%2F%20babel%20passes%20in%20the%20property%20descriptor%20with%20a%20method%20to%20get%20the%20initial%20value.%0A%0A%20%20%20%20%20%20%2F%2F%20set%20the%20initial%20value%20of%20the%20property%20if%20it%20is%20defined.%0A%20%20%20%20%20%20if%20(typeof%20descriptor.initializer%20%3D%3D%3D%20'function')%20%7B%0A%20%20%20%20%20%20%20%20target%5BinnerPropertyName%5D%20%3D%20descriptor.initializer()%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20descriptor%20%3D%20%7B%7D%3B%0A%20%20%20%20%20%20target%20%3D%20target.prototype%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20%2F%2F%20we're%20adding%20a%20getter%20and%20setter%20which%20means%20the%20property%20descriptor%0A%20%20%20%20%2F%2F%20cannot%20have%20a%20%22value%22%20or%20%22writable%22%20attribute%0A%20%20%20%20delete%20descriptor.writable%3B%0A%20%20%20%20delete%20descriptor.initializer%3B%0A%0A%20%20%20%20%2F%2F%20add%20the%20getter%20and%20setter%20to%20the%20property%20descriptor.%0A%20%20%20%20descriptor.get%20%3D%20function()%20%7B%20return%20this%5BinnerPropertyName%5D%3B%20%7D%3B%0A%20%20%20%20descriptor.set%20%3D%20function(newValue)%20%7B%0A%20%20%20%20%20%20let%20oldValue%20%3D%20this%5BinnerPropertyName%5D%3B%0A%20%20%20%20%20%20this%5BinnerPropertyName%5D%20%3D%20newValue%3B%0A%20%20%20%20%20%20if%20(this%5BcallbackName%5D)%20%7B%0A%20%20%20%20%20%20%20%20this%5BcallbackName%5D(newValue%2C%20oldValue)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%3B%0A%0A%20%20%20%20%2F%2F%20make%20sure%20Aurelia%20doesn't%20use%20dirty-checking%20by%20declaring%20the%20property's%0A%20%20%20%20%2F%2F%20dependencies.%20This%20is%20the%20equivalent%20of%20%22%40computedFrom(...)%22.%0A%20%20%20%20descriptor.get.dependencies%20%3D%20%5BinnerPropertyName%5D%3B%0A%0A%20%20%20%20Reflect.defineProperty(target%2C%20key%2C%20descriptor)%3B%0A%20%20%7D%3B%0A%0A%20%20if%20(_key)%20%7B%0A%20%20%20%20return%20deco(keyOrTargetOrConfig%2C%20_key%2C%20_descriptor)%3B%0A%20%20%7D%0A%0A%20%20return%20deco%3B%0A%7D%0A%0A%0Aclass%20Foo%20%7B%0A%09%40observable%20bar%3B%0A%7D%0A

**Comment by Ma3yTa** [comment]
@jdanyow I think problem is in 22 line of code https://gyazo.com/03d03c2a4a2e96c5f9bee95183c57e04. 
```

if (descriptor) {
      // babel passes in the property descriptor with a method to get the initial value.

      // set the initial value of the property if it is defined.
      if (typeof descriptor.initializer === 'function') {
        target[innerPropertyName] = descriptor.initializer();
      }
    } else {
      descriptor = {};
      //target = target.prototype; //If comment this all works
    }

```

**Comment by Ma3yTa** [comment]
I think this merge broke decorator https://github.com/aurelia/binding/commit/0b2d8b770e0a91cc40613937a44633cf40614339

**Comment by kellyethridge** [comment]
aurelia-binding@1.0.0-rc.1.0.1 still produces the same error.

`Error: TypeError: Reflect.defineProperty called on non-object
	    at deco (http://localhost:4671/jspm_packages/npm/aurelia-binding@1.0.0-rc.1.0.1/aurelia-binding.js:5325:15)
	    at observable (http://localhost:4671/jspm_packages/npm/aurelia-binding@1.0.0-rc.1.0.1/aurelia-binding.js:5329:14)
	    at __decorate (http://localhost:4671/app/viewmodels/view-model-base.js:4:110)
	    at eval (http://localhost:4671/app/viewmodels/view-model-base.js:82:9)
	    at Object.eval (http://localhost:4671/app/viewmodels/view-model-base.js:103:6)
	Error loading http://localhost:4671/app/main.js`

Is there additional information I can give you?

**Comment by Souldrinker** [comment]
Seems like I got bitten by the same bug. It crashes on the same line for me for my observable property: ```Reflect.defineProperty(target, key, descriptor);``` (5325 in aurelia-binding.js).

The target seem to be null for me here... Commenting out the line @Ma3yTa suggested seems to fix it for now...
