### ISSUE TITLE
databound input changes bound value to string

### ISSUE THREAD

**Issue by kuechlerm** [aurelia/binding#443]
With view and model (typescript):

```
// html
<template><input type="number" value.bind="val"></template>

// ts
class Foo {
  val = 5; // number

  increment() { 
    this.val += 1; 
    console.log(this.val, typeof this.val);
  }
}
```

Now calling twice increment (via button.click) results in
> 6 "number"
> 61 "string"

I expect 
> 6 "number"
> 7 "number"

Using `this.val++` works.
Using one-way binding works.

**Comment by atsu85** [comment]
You could use 2way valueconverter to convert string value from view to number

**Comment by fopsdev** [comment]
or use a custom bindingbheaviour so you are not running into:
http://stackoverflow.com/questions/37882659/force-view-to-be-updated-from-within-a-valueconverter

**Comment by kuechlerm** [comment]
I understand your solution, but this is still confusing and unexpected.
Why is there a difference between `this.val += 1` and `this.val++` ?

**Comment by fopsdev** [comment]
@kuechlerm hmm good question. well i would say that TS implies when using this.val++ that you are operating on a numeric value

**Comment by atsu85** [comment]
@kuechlerm 
> Why is there a difference between this.val += 1 and this.val++ ?

As @fopsdev wrote
> JS implies when using this.val++ that you are operating on a numeric value and therefore treats it like that internally

it is totally JS thing, that has nothing to do with Aurelia. You can verify it out on browser console as well (for example on this site, that doesn't use Aurelia)

**Comment by EisenbergEffect** [comment]
Closing this since the ValueConverter recommendation address the original issue and the following discussion expounds on the JavaScript oddity.

**Comment by MJLHThomassen** [comment]
> Closing this since the ValueConverter recommendation address the original issue and the following discussion expounds on the JavaScript oddity.

And what is this ValueConverter recommendation?

I'm having a similar issue as original poster:

`<input id="nrOfLicensesInput" class="form-control" type="number" value.two-way="nrOfLicenses" min="1" placeholder="1"/>`

Then, whever i change the input box number (either manually or trough the arrows provided by Chrome), in my VM, the nrOfLicenses field is suddenly a string instead of a number. I'm using typescript so i also cant work around it by doing a manual Number.parse(nrOfLicenses) because nrOfLicenses is already a string and I get Typescript erros.

Any suggestions?

**Comment by EisenbergEffect** [comment]
See docs here: http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-value-converters/8

**Comment by jdanyow** [comment]
also might be helpful: https://gist.run/?id=d9d8dd9df7be2dd2f59077bad3bfb399

**Comment by MJLHThomassen** [comment]
Any reason as to why we have to work around it like this?

**Comment by jdanyow** [comment]
An html input element will coerce anything assigned to it's value attribute to a string.  Number type inputs are essentially worthless without adding extra logic to get them to behave the way you want.

**Comment by MJLHThomassen** [comment]
@jdanyow Thanks for the explanation, I did not know that. A flaw of html5 in my opinion.

Anyway, many thanks for the explanation and possible solution directions!

**Comment by jdanyow** [comment]
No problem, I should have mentioned, the same thing happens with `<select>` element value and it's children, `<option>` element value.... it certainly can make things confusing.
``` js
var input = document.createElement('input')
input.type = 'number'
input.value = 55
console.log(input.value === 55); // false
console.log(input.value === '55'); // true
```

**Comment by 4nderss** [comment]
How does this workaround work with validation? Right now I get bindingerrors if I use the following example https://gist.run/?id=d9d8dd9df7be2dd2f59077bad3bfb399 and try to number-value.bind="myNumber & validate".

**Comment by nashwaan** [comment]
@jdanyow @EisenbergEffect  But why `model.bind` doesn't work with number input?
I think this issue can be solved cleanly if Aurelia can simply support this:
```js
<input type="number" model.bind="myValue" />
```
The strange thing is Aurelia already support this concept for binding `select`. In the [documentation](http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-selects/1), it even recommends using `model.bind` over `value.bind` to avoid coercing the input to string (see point #4 in the introduction) and the example given is `<option model.bind="product.id"></option>`. So why not support `model.bind` in "number" input???
Also this will make validations simpler and cleaner:
```js
<input type="number" model.bind="myValue & validate" />
```
