### ISSUE TITLE
binding selected checkboxes to array doesn't work (as documented)

### ISSUE THREAD

**Issue by atsu85** [aurelia/binding#445]
Hi,
I created a [gis.run](https://gist.run/?id=c96fbadb6e783e07e03254be0e30fefc) based on sample from Aurelia documentation "[Checkboxes with an Array](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/cheat-sheet/5)" to demonstrate the problem. 

# problem
While checkboxes are initialized based on array defined in js, the array is not updated when changing the checkbox

# expected outcome
I'd expect the favoriteColors to be `["green", "blue"]` after selecting corresponding checkboxes, not left untouched.

@jdanyow, is this a regression or am I doing smth wrong?

**Comment by jdanyow** [comment]
works for me: https://gist.run/?id=566dfb2d79815a9990e8522e504cd3fa

**Comment by atsu85** [comment]
dooh, I forgot that `${someArray}` doesn't reflect the array content. Thanks for the reply!
