### ISSUE TITLE
enhance signaler to work on html nodes as well

### ISSUE THREAD

**Issue by fopsdev** [aurelia/binding#447]
Imagine we have a view like:
```
<template>
   <div au-signal="1"> 
       <p>${val1}</p>
       <p>${val2}</p>
       <div au-signal="2">
             ${val3}
       </div>
       <div au-signal="2">
             ${val4}
       </div>
   </div>
</template>
```

and a viewmodel (pseudocode) like:

```
import {BindingSignaler} from 'aurelia-templating-resources';

@oneTime 
(Class Decorator which makes oneTime binding default for this view-viewmodel **but still calls the propertyChanged** for input .binds)
...
//some code which should result in a view update
signaler.signalNode("1");   // forces the bindings and expressions inside the elements with au-refresh="1" to be refreshed
//-> ${val1}, ${val2} would be refreshed
// or if the childs should also be refreshed:
this.signaler.signalNode("1",true);   
//-> ${val1}, ${val2}, ${val3}, ${val4} would be refreshed
this.signaler.signalNode("2");   
//-> ${val3}, ${val4} would be refreshed

```

what do you think?

**Comment by EisenbergEffect** [comment]
Isn't this the same as Signals?

**Comment by fopsdev** [comment]
no.
because by also decorating the class (see my update) the binding automatically uses oneTime behaviour everywhere.
and as you can see it's au-refresh attribute. so all the expressions within that element would be refreshed avoiding cluttering the html with signal syntax

**Comment by EisenbergEffect** [comment]
What does it mean to "refresh" an element? Can you provide the specifics of that?

**Comment by fopsdev** [comment]
Updated the inital proposal to answer this question more precisely.

**Comment by fopsdev** [comment]
Well since signaler has similar purpose i've adjusted the sample once again to make use of it.

**Comment by EisenbergEffect** [comment]
This should be possible to implement as an external plugin. I'd like to see that first.
