### ISSUE TITLE
feature request: an error message when multiple Template Controllers (repeat, if binding) are used on the same element

### ISSUE THREAD

**Issue by morioma** [aurelia/binding#448]
According to [this issue](https://github.com/aurelia/binding/issues/250), when multiple Template Controller binding are used on the same element, unexpected behaviors could happen.
It would be helpful to throwing an error message at a lint process or at run time when multiple Template Controller is used on the same element, providing better guidance.

**Comment by stsje** [comment]
Someone already beat you to it. There's a linting plugin that checks for multiple template controllers on the same element.
https://github.com/MeirionHughes/aurelia-template-lint

**Comment by EisenbergEffect** [comment]
Yep, we'll use this to track Meirion's work getting incorporated into our tooling.

**Comment by atsu85** [comment]
@EisenbergEffect, I'd close this, there is another [issue](https://github.com/aurelia/tools/issues/31) that is more appropriate for tracking Aurelia linter

**Comment by EisenbergEffect** [comment]
Will do sinde it's already tracked.
