### ISSUE TITLE
View model reference returns null 

### ISSUE THREAD

**Issue by Kukks** [aurelia/binding#449]
Are there some circumstances where a `view-model.ref` from a  custom element would return null( and the reference element actually loaded)?

I have a custom element's view model referenced and in some unknown scenarios, it does not populate.

**Comment by jdanyow** [comment]
yes there is!

If the element the `view-model.ref` were to unbind, the reference would be set to null to avoid memory leaks.  This can happen when you have a `view-model.ref` within an element that has an `if.bind`.

Example:

```html
<template>
  <div if.bind="isVisible">
    <my-element view-model.ref="vm"></my-element>
  </div>
</template>
```

*assigning `false` to `isVisible` would unbind the contents of the div, ultimately setting the `vm` property to null.*

**Comment by Kukks** [comment]
Hey, thanks for replying.

Would it stay null even after it is loaded back? I am having my custom elements on screen but the reference in the parent view model is staying null.

**Comment by jdanyow** [comment]
@Kukks if you would be willing to provide an example of what you're seeing using the aurelia gist we can provide further info:  https://gist.run/?id=7542e061bc940cde506b

**Comment by edseabolt** [comment]
I'm seeing this behavior on Chrome versions <= 53 and on any version of FF so far. Here's my Gist that illustrates it: https://gist.run/?id=7ad1dc6da1dc4f7d2120d0c2d1daa534. The difference I see is that the ref is valid in the view, but null in the view model. One other difference is that I simulate a loading of a resource after attachment.

**Comment by jdanyow** [comment]
@edseabolt the `if` binding doesn't evaluate synchronously immediately after you change the value of `isLoading`. It will happen on the next flush of the taskqueue, to ensure dom updates are batched.

https://gist.run/?id=8b3021b4a990a5961dc9d8546b87cef9

**Comment by edseabolt** [comment]
@jdanyow. Thanks. Makes better sense now.
