### ISSUE TITLE
enable two-way binding content of contenteditable="true" elements

### ISSUE THREAD

**Issue by jdanyow** [aurelia/binding#45]
https://gitter.im/Aurelia/Discuss?at=54f2f35e0cfa7291277d01e4

What do we want the binding syntax to look like: 

``` markup
<td contenteditable="true" inner-html="value.two-way: tdtext;"></td>
```

or this:

``` markup
<td contenteditable="true" value.bind="tdtext"></td>
```

Test fiddle for contenteditable element events:
http://jsfiddle.net/8j6jea6p/

**Comment by jdanyow** [comment]
@zewa666 and I were discussing this on the team gitter and were thinking we ought to support both for completeness sake and document the value.bind approach as the recommended way.

thoughts?

**Comment by jdanyow** [comment]
discussed with @EisenbergEffect  on the team gitter.  https://gitter.im/aurelia?at=54f31d2e4f9b4aa73b3dbd9f

* `<td value.bind="tdtext"></td>` will create a one-way binding
* `<td value.two-way="tdtext"></td>` will create a two-way binding.  If contenteditable is not true, it will be assigned true and a warning will be logged.

**Comment by EisenbergEffect** [comment]
Also, we need to create a basic value converter for sanitization. All examples in the docs should use this.

**Comment by jdanyow** [comment]
Maybe we should use `textContent` instead of `innerHTML` so that this is safe by default.

from MDN:

#### Differences from innerHTML

innerHTML returns the HTML as its name indicates. Quite often, in order to retrieve or write text within an element, people use innerHTML. textContent should be used instead. Because the text is not parsed as HTML, it's likely to have better performance. Moreover, this avoids an XSS attack vector.
https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent

**Comment by jdanyow** [comment]
@EisenbergEffect @zewa666 @PWKad 

Would you mind reviewing what I have so far on this one?  As I got into this I strayed a bit from what we had discussed yesterday.  Seemed like tying this to the element's `textContent` property was the thing to do (vs `innerHTML`).

Here's what the markup would look like:

``` markup
<template>
  <label>Results in two-way binding</label>
  <div style="width: 200px; height: 50px; border: solid black 1px;"
      contenteditable="true" text-content.bind="value">
  </div>

  <label>Results in one-way binding</label>
  <div style="width: 200px; height: 50px; border: solid black 1px;"
       text-content.bind="value">
  </div>

  <label>Result</label>
  ${value}
</template>
```

The Atom editor removed a bunch of spaces in the code which obfuscates the diffs a little bit.  Here are the meaningful changes:

* https://github.com/jdanyow/templating-binding/blob/binding-45/src/binding-language.js#L19
* https://github.com/jdanyow/templating-binding/blob/binding-45/src/syntax-interpreter.js#L51-L53
* https://github.com/jdanyow/binding/blob/issue-45/src/event-manager.js#L145-L147

**Changes from what we discussed:**
Was thinking a `text-content` attribute was more appropriate than using `value` since behind the scenes we're manipulating element.textContent.  Seems like it aligns with `contenteditable` better as well.

No automatic assignment of `element.contentEditable`.  Was thinking a devs would be using `contenteditable="true"` and then trying to figure out how to bind the element content to the viewmodel so all we really needed to do was come up with the least surprising way of doing that.

Thoughts?

**Comment by EisenbergEffect** [comment]
We can's use textContent. That actually doesn't do the same thing. If the developer wants to set html, that won't work.

**Comment by davismj** [comment]
For the record, `value.bind` does not work. You must use `textcontent`. This is consistent with the docs.

**Comment by schatekar** [comment]
I'm not sure if this is the right channel to ask my question. However, what I am trying to do is strongly related to the discussion on this thread. 

I am building a tiny CMS-like functionality for a page. The page starts in `contentEditable="false"` mode and I use `textContent` binding to bind the contents of header, list and span elements. Users then can click an edit button to enable the edit mode. Internally this just sets the `contentEditable` attribute to `true`. 

The way `textContent` binding is implemented, when the binding happened initially, it is sent to `ONE_WAY`. How can I change that to `TWO_WAY` after I changed the value of `contentEditable` to `true` based on user action? I was thinking I can initiate binding workflow again but not sure how.

**Comment by jdanyow** [comment]
@schatekar - be explicit about the binding mode: `<div contenteditable="false" textcontent.two-way="foo">`

**Comment by schatekar** [comment]
@jdanyow Thanks. That works like a charm.

**Comment by obedm503** [comment]
`.bind` doesn't work but `.two-way` does
