### ISSUE TITLE
radio button two way binding not working

### ISSUE THREAD

**Issue by stefan505** [aurelia/binding#454]
**I'm submitting a bug report**

* **aurelia-binding version:**
1.0.0-rc.1.0.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v5.10.1

* **NPM Version:**
3.8.3

* **JSPM OR Webpack AND Version**
JSPM 0.17.0-beta.16

* **Browser:**
all

* **Language:**
TypeScript 1.8.x

**Current behavior:**
Radio button bound from view model is not reflected in view.

**Expected/desired behavior:**
Radio button bound from view model should reflect in view.

https://gist.run/?id=c5fbe9d4af981e0b0f403b2c51df6e61

**Comment by stefan505** [comment]
managed to figure it out, gist updated to show it working.

**Comment by EisenbergEffect** [comment]
@stefan505 Can this be closed?
