### ISSUE TITLE
Move Unparser to aurelia-testing

### ISSUE THREAD

**Issue by Gheoan** [aurelia/binding#457]
**I'm submitting a feature request**

**Current behavior:**
`Unparser` exists in `aurelia-binding` and is used internally only to test `aurelia-binding`.

**Expected/desired behavior:**

* **What is the expected behavior?**
`Unparser` should exist in `aurelia-testing`.

* **What is the motivation / use case for changing the behavior?**
Reducing `aurelia-binding` size.

**Comment by EisenbergEffect** [comment]
@jdanyow This is an interesting idea. Could we move this before v1 next week? It would be great if that would reduce size a bit. It's probably technically a breaking change, but I doubt anyone is using that. Let me know your thoughts.

**Comment by jdanyow** [comment]
this would break `toString` on the AST nodes.  Is that OK?

https://github.com/aurelia/binding/blob/master/src/ast.js#L18-L20

**Comment by jdanyow** [comment]
closing for now- @EisenbergEffect please re-open if you want me to remove AST toString feature

**Comment by EisenbergEffect** [comment]
@jdanyow Could we do something where....the toString generates a placeholder result by default, but then when the Unparser is plugged in via the testing library it registers itself so that the toString implementation of the AST can pick it up and use it.

**Comment by jdanyow** [comment]
@EisenbergEffect you pick- I'm still on the fence. It's a savings of 902 gzipped bytes.
`toString` pre-dates any tests. I think it's a nice utility in the library. For example, it's used [here](https://gist.run/?id=c2394c5748d27f3dc77acabc7b8f2752).

If we're aggressively removing bytes maybe we should also move the svg stuff (3370 gzipped bytes) to a plugin.

**Comment by EisenbergEffect** [comment]
I think we can just leave it for now.
