### ISSUE TITLE
Event Bubbling

### ISSUE THREAD

**Issue by AshleyGrant** [aurelia/binding#460]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-rc.1.0.3

**Current behavior:**
A click event handler on an inner element will stop an outer element's click handler from being fired. This is not how standard HTML events work.

Standard HTML gist: https://gist.run/?id=b1f5359d6e1f6870aec16c592041fdf7
Open the console and then click on the text to test.

Aurelia delegate gist: https://gist.run/?id=8871e9720d0a2ece3ae60e36922196e7
Click inside and outside the green box

Aurelia trigger gist: https://gist.run/?id=30a31a9249c2370365f6df97f1d827fd
Click inside and outside the green box

**Expected/desired behavior:**
I'm not sure if this is the desired behavior or this is a bug. The code in question is here: https://github.com/aurelia/binding/blob/master/src/event-manager.js#L8-L25 this stops looking for callbacks after it finds one, and thus bubbling doesn't occur. 

So, is this a bug or expected behavior?

**Comment by jdanyow** [comment]
https://github.com/aurelia/binding/issues/138#issuecomment-183492983
