### ISSUE TITLE
Suggestion: Binding behaviour scope / container

### ISSUE THREAD

**Issue by jods4** [aurelia/binding#461]
I was building a validation component today and got frustrated by the fact that you can't grab an enclosing custom element viewModel from a binding behavior.

Imagine you have this setup:
```html
<my-form>
  <my-input value.bind="x & validate" my-attr />
</my-form>
```

Inside `MyInputCustomElement` or `MyAttrCustomAttribute`, I can ask the DI for a `MyFormCustomElement` and get the enclosing `<my-form>` view model.

Not so in `ValidateBindingBehavior`. First thing is that binding behaviors are singleton, so you can't DI anything that is binding-specific inside the ctor. But let that not stop us! When you use a behavior, the following method is called: `bind(binding, scope)`. Both `binding` and `scope` grant you access to a `container`, although those containers seem to be higher in the hierarchy (at the main view level) and as such they do not give you access to enclosing view models.

Do you think this is something that could/should be possible? Why isn't `binding.container` at the binding level?

**Comment by EisenbergEffect** [comment]
There aren't containers associated with every element that has a binding. I'm not sure it's possible or a good idea exactly. We'd need to think about it.

**Comment by jods4** [comment]
> There aren't containers associated with every element that has a binding.

No, of course. But there is one for each custom element right?

It doesn't seem right that a custom element or attribute "executes" inside the container of its parents in DOM, but the binding do not.

Or maybe there is something I'm understanding incorrectly.

**Comment by jdanyow** [comment]
does this give you what you need:

```js
// in your binding behavior...
bind(binding, source) {
  let viewModel = source.bindingContext;
  ...
}
```

**Comment by jdanyow** [comment]
disregard my last post- it's not what you're looking for.

---

*foo.html*
```html
<template>
  <my-form>
    <my-input value.bind="x & validate" my-attr />
  </my-form>
</template>
```

The bindings are owned by the view they appear on, in this case, *foo.html*.  Consider something like an `if.bind`.  The element the `if.bind` appears on cannot own the `if.bind` because it might not even exist depending on the state of the `if` condition.

**Comment by jods4** [comment]
@jdanyow I am not sure I fully understand. How are custom attributes different?

In the example above, I could inject `MyFormCustomElement` into `MyAttrCustomAttribute` constructor and get the enclosing view model. How does this work? Why can't the same thing work for the binding?
