### ISSUE TITLE
Binding ignores input from safari autofill

### ISSUE THREAD

**Issue by wichert** [aurelia/binding#462]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.0.1 

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11 / 
* **Node Version:**
6.3.0

* **NPM Version:**
3.10.5

* **JSPM OR Webpack AND Version**
Webpack 2.1.0-beta.20
* **Browser:**
Safari 9.1.2

* **Language:**
ESNext

**Current behavior:**

I made a very simple login form. For demonstration purposes the trimmed down version looks like this:

```javascript
export class Login {
    email    = '';
    password = '';

    login() {
    }
}
```

and the template:

```html
<template>
  <section class="au-animate">
    <h2>${heading}</h2>
    <form role="form" submit.delegate="login()">
      <div class="form-group">
        <label for="email">Email address</label>
        <input id="email" type="email" value.bind="email" class="form-control" placeholder="Email address">
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input id="password" type="password" value.bind="password" class="form-control" placeholder="Your password">
      </div>
      <button type="submit" class="btn btn-default">Login</button>

      <code>${email}</code>
    </form>
  </section>
</template>
```

Safari will try to autofill the inputs when you start typing for this form. For example when I enter `wichert@` in the email input it will offer to autocomplete that to my full email address. When I do that the full email address it put in the input field, but aurelia never picks up on the never data, and any bound variables are not incomplete. The HTML template shows this directly: the `<code>..</code>` element will not match the input. Here is a screenshot of the result where I used autofill after entering `wichert@`:

![image](https://cloud.githubusercontent.com/assets/199657/17050284/49a9a678-4ff2-11e6-9364-65a07cbe282e.png)

**Expected/desired behavior:**

Autofill-generated values for inputs are picked up correctly in bindings.

* **What is the motivation / use case for changing the behavior?**

The current behaviour is extremely confusing for users: the data they see on a form does not match what aurelia sees, causing invalid data being send to backends for forms.

**Comment by wichert** [comment]
Autocomplete works correctly in Chrome 51.

**Comment by jdanyow** [comment]
please give this a try and let me know if it resolves the issue:  
`value.bind="email & updateTrigger:'change':'input':'blur'"`

The standard logic listens for 'change' and 'input', i'm wondering if 'blur' will resolve the issue.

If you google for `safari autofill change event` the results are not promising...
