### ISSUE TITLE
 Array binding seems to have changed in Release Candidate

### ISSUE THREAD

**Issue by akircher** [aurelia/binding#464]
**I'm submitting a bug report**

Array binding seems to have changed in 
aurelia-framework@^1.0.0-rc.1.0.4, 
aurelia-binding@^1.0.0-rc.1.0.3

* **Operating System:**
OSX 10.10.5

* **Browser:**
Chrome 52.0.2743.82

* **Language:**
ESNext (Babel)

**Current behavior:**
View model
```
this.test = []
    setInterval(_ => {
      this.test.splice(0, 1, ! this.test[0])
    }, 1000)
```
View
```
${ test[0] }
```

I would expect the view to alternate displaying true and false, however, it always displays false.  Putting a console.log statement in setInterval confirms that the array value is alternating however. Aurelia is just not observing the change and updating the view.

* **What is the expected behavior?**
This used to work in Beta.  In fact this more intuitive version used to work in Beta as well:
```
this.test = []
    setInterval(_ => {
      this.test[0] = ! this.test[0]
    }, 1000)
```

**Comment by EisenbergEffect** [comment]
The second version only worked in Chrome. It never worked anywhere else and that was only possible because of Object.observe, which is no longer a standard and isn't available.

As to the first version, using `splice` that should work. @jdanyow Can you take a look at this really quickly?

**Comment by akircher** [comment]
Thanks for looking into it.  That makes sense for the 2nd part since I have only been using chrome.

**Comment by jdanyow** [comment]
works for me:  https://gist.run/?id=37689747e357376e73903a2ff44b10c0

**Comment by EisenbergEffect** [comment]
If you write it like @jdanyow has, it will work. But if you write it like the sample above, it won't because we don't detect changes on individual indexes. If you need something like that, you may want to consider using a signal.

**Comment by akircher** [comment]
I will use a signal.  However, I believe this is a unexpected behavior.  A developer would very rarely interpolate a full array as `${ test }` in a view as the gist shows.  A developer would just use a simple property, not an array.  I think using array methods in situations like these should update the entire array and trigger a change in the view without needing to use a signal.

**Comment by jdanyow** [comment]
My bad- I missed the indexer.  Misunderstood the question
