### ISSUE TITLE
Binding uses dirty checking even with signal behavior

### ISSUE THREAD

**Issue by mohsenasfia** [aurelia/binding#466]
**I'm submitting a bug report**
- **Library Version:**
  1.0.0-rc.1.0.3
- **Browser:**
  Chrome | Firefox | IE 11
- **Language:**
  TypeScript 1.8

**Current behavior:**
The `foo` getter is invoked repeatedly, i.e. using dirty checking.

View:
`${foo & signal: 'some-signal' }`

ViewModel:

``` typescript
export class Foo
{
    public get foo(): string
    {
        return Date.now();
    }
}
```

**Expected/desired behavior:**
We expected the `foo` getter to be invoked _only_ when `some-signal` is published.

If we bind to a method instead, like below, it does work as expected:

View:
`${foo() & signal: 'some-signal' }`

ViewModel:

``` typescript
export class Foo
{
    public foo(): string
    {
        return Date.now();
    }
}
```

**Comment by jdanyow** [comment]
The way it currently works is the signal is an additional way to get the binding to update. You'd like it to be the *only* way, which I think is a logical way of looking at it. Unfortunately this would be a breaking change for folks that rely on the current behavior so we'll need to discuss... @EisenbergEffect thoughts?

**Comment by EisenbergEffect** [comment]
No breaking changes. But could it be extended to allow a developer to opt into that behavior?

**Comment by jdanyow** [comment]
possibly- @mohsenasfia another option would be to use `oneTime` in conjunction with `signal`:

```html
<h1>${message & oneTime & signal:'test'}</h1>
```
https://gist.run/?id=3f0bf0beb303f9db9ed61c5daf0888bf

**Comment by mohsenasfia** [comment]
Thanks a lot for your answers and tips. 

That does make sense to use one-time binding behavior with a signal, however what really surprised me was that the expected behavior works fine with a method instead of a getter! I was just wondering why there's a discrepancy with this behavior?!

**Comment by jdanyow** [comment]
The binding system doesn't dirty check method-call expressions- that's why it works as you'd expect with those types of expressions.

**Comment by obedm503** [comment]
did this change ever happen? 
because I'm one of those `folks that rely on the current behavior `. and I've been facing an inconsistent bug where a binding with a signal _only_ updates when the signal happens, and not like normal. problem is that I still don't know if the bug comes from my code or aurelia

**Comment by bigopon** [comment]
How does your binding look like ? This behavior is still there as signal is still just another way to update binding like Jeremy stated

**Comment by obedm503** [comment]
after some more research it seems signals weren't the cause
