### ISSUE TITLE
stopPropagation is not respected

### ISSUE THREAD

**Issue by michaelmalonenz** [aurelia/binding#467]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
5.11.1

* **NPM Version:**
3.9.5

* **JSPM OR Webpack AND Version**
JSPM 0.16.39

* **Browser:**
all 

* **Language:**
all

**Current behavior:**
I have some nested div elements, which each have click delegates.  If I call `event.stopPropagation` when in the inner-most element, the event delegate on the parent is called.

**Expected/desired behavior:**  
I would expect the event to _not_ bubble to the parent if `stopPropagation` was called on the event.  The behaviour was changed in [this commit](https://github.com/aurelia/binding/commit/2c08d058e0f152378965fee781014d877ac2abc5) to start bubbling events like a browser would.  

Please find an example gist [here](https://gist.run/?id=e3e136983e5d4e467b59fd8ab21e89ba)  When clicking the inner element, I would expect that only it changes colour, not both.

* **What is the expected behavior?**    
Essentially, that the event manager respects the `stopPropagation` behaviour like any browser would.

After looking at the problem, I feel there is an obvious, if slightly awkward solution, and I wanted to get feedback prior to submitting a pull request:

```javascript
function handleDelegatedEvent(event) {
  let originalStopPropagationFn = event.stopPropagation;
  let propagationStopped = false;
  event.stopPropagation = () => { 
    propagationStopped = true; 
    originalStopPropagationFn.call(event);
  }
  let target = findOriginalEventTarget(event);

  while (target && !propagationStopped) {
    if (target.delegatedCallbacks) {
      let callback = target.delegatedCallbacks[event.type];
      if (callback) {
        callback(event);
      }
    }

    target = target.parentNode;
  }
}
```
* **What is the motivation / use case for changing the behavior?**

So I can have delegates instead of triggers (the problem goes away if I use a trigger on both) except that I have a large number of "inner" elements (hundreds / thousands), so wanted to keep the improved performance promised by delegation (which was possible prior to the bubbling change mentioned earlier).

**Comment by jdanyow** [comment]
I think this is a good change. We actually discussed this when we were researching the event manager fix.

Couple performance suggestions:

What if we lazily overrode stopPropagation, deferring the override work until we knew we were about to invoke a callback?

What do you think about refactoring the override to eliminate closures?

Here's some examples:

```js
function interceptStopPropagation(event) {
  event.standardStopPropagation = event.stopPropagation;
  event.stopPropagation = function() {
    this.propagationStopped  = true;
    this.standardStopPropagation();
  }
}

function handleDelegatedEvent(event) {
  let interceptInstalled = false;
  event.propagationStopped = false;
  while (target && !event.propagationStopped) {
    if (target.delegatedCallbacks) {
      let callback = target.delegatedCallbacks[event.type];
      if (callback) {
        if (!interceptInstalled) {
           interceptStopPropagation(event);
        }
        callback(event);
      }
    }

    target = target.parentNode;
  }
}
```

**Comment by michaelmalonenz** [comment]
Sounds good - I've amended the Pull Request with the updated code

**Comment by CasiOo** [comment]
Just a quick note about the implementation: Instead of polluting the event object with more methods, how about keeping the `stopPropagation` local to `interceptStopPropagation`?

**Comment by CasiOo** [comment]
@michaelmalonenz I see what you mean with only adding the interceptor if it's needed. That way we don't interfere with DOM events outside Aurelia :+1: .

For good measure, this is what I originally had in mind.
```
function handleDelegatedEvent(event) {
  let propagationStopped = false;
  let target = findOriginalEventTarget(event);
  interceptStopPropagation(event);

  while (target && !propagationStopped) {
    if (target.delegatedCallbacks) {
      let callback = target.delegatedCallbacks[event.type];
      if (callback) {
        callback(event);
      }
    }

    target = target.parentNode;
  }
  
  function interceptStopPropagation(event) {
    let standardStopPropagation = event.stopPropagation;
    
    event.stopPropagation = function() {
      propagationStopped = true;
      standardStopPropagation.call(this);
    };
  }
}
```
