### ISSUE TITLE
Problem with input validation attribute binding (minlength, maxlength and pattern)

### ISSUE THREAD

**Issue by tolemac** [aurelia/binding#473]
**I'm submitting a bug report**

* **Library Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
5.1.0

* **NPM Version:**
3.5.0

* **JSPM OR Webpack AND Version**
none, I'm using AureliaCLI

* **Browser:**
Chrome 51

* **Language:**
TypeScript 1.9

**Current behavior:**
`pattern` attribute binding not work fine. If value is undefined aurelia sets `pattern="undefined"` and input is always invalid.
`minlength` and `maxlength` attribute binding sets `0` if binding source is null or undefiend.

**Expected/desired behavior:**
You can see a demo here: http://plnkr.co/edit/pLIM83?p=preview

* **What is the expected behavior?**
If source of pattern binding is undefined, aurelia shouldn't set pattern attribute, like `required`.
The same for minlength and maxlength.

* **What is the motivation / use case for changing the behavior?**
You can build custom inputs elements and enable to set or not validations attributes.

**Comment by jdanyow** [comment]
Issue moved to [aurelia/validatejs #115](https://github.com/aurelia/validatejs/issues/115) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tolemac** [comment]
I think it isn't related with validations, I don't use validatejs ...
I thought it was related with the `binding` or `template-binding` but never with `validatejs`.

Ok, thanks anyway.
