### ISSUE TITLE
Observer on decorated property doesn't work

### ISSUE THREAD

**Issue by ccantill** [aurelia/binding#476]
**I'm submitting a bug report**

* **Library Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
Linux Elementary Loki

* **Node Version:**
4.4.7

* **JSPM OR Webpack AND Version**
JSPM 0.16.39

* **Browser:**
Chrome 52

* **Language:**
ESNext

**Current behavior:**
Observing a property that is decorated results in "Cannot observe property 'xxx' of object" warning. Changes are not being responded to. Adding a decorator on a property will result in that property being added (regardless of the decorator's function). The createPropertyObserver will return a SetterObserver for that property, but SetterObserver calls Reflect.defineProperty for that property, which will fail as the property already is defined.

**Expected/desired behavior:**

* **What is the expected behavior?**
It should probably fall back to a DirtyCheckProperty.

* **What is the motivation / use case for changing the behavior?**

**Comment by ccantill** [comment]
Proposed fix: https://github.com/aurelia/binding/pull/477

**Comment by jdanyow** [comment]
https://github.com/aurelia/binding/issues/406

**Comment by jdanyow** [comment]
this is more of a babel issue- same thing doesn't occur when using TypeScript transpilation.

**Comment by RWOverdijk** [comment]
@jdanyow We tried solving this with babel, [and they didn't accept it](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy/pull/44) with reason. Meanwhile, this is still an issue.

Do you have any suggestions on how to move forward?
