### ISSUE TITLE
one-time binding and non-bindable properties

### ISSUE THREAD

**Issue by StrahilKazlachev** [aurelia/binding#480]
**I'm submitting a feature request**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.32

* **Browser:**
all

* **Language:**
all

**Current behavior:**
Changes done in the `bind` callback to non-bindable properties are not reflected if the properties are bound with one-time/oneTime. This is not the case if the property is bindable.

**Expected/desired behavior:**

* **What is the expected behavior?**
I expected the behavior of one-time/oneTime binding to be the same for both bindable and non-bindable properties - changes will not be applied after the `bind` callback has been called.

* **What is the motivation / use case for changing the behavior?**
In my custom elements I have non-bindable flag properties that are set in the `bind` callback based on a bindable(bindingMode.oneTime) property.

**Comment by jdanyow** [comment]
hi @StrahilKazlachev, please put together a gist that demonstrates the scenario: https://gist.run/?id=7542e061bc940cde506b

**Comment by StrahilKazlachev** [comment]
I'm closing it since I can not reproduce it in gist - both bindable and non-bindable properties can not be changed from `.bind()` when used in one-time binding. I'll look where in our application I tried this and **thought** it gave different result. Sorry for the noise.
