### ISSUE TITLE
Weird Issue with repeater inside repeater

### ISSUE THREAD

**Issue by ppn2** [aurelia/binding#484]
**I'm submitting a bug report**
- **Library Version:**
  1.0.1

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  4.4.6
  
  
- **NPM Version:**
  3.10.6
  
  
- **JSPM OR Webpack AND Version**
  JSPM 0.16.45
- **Browser:**
  Chrome 52.0.2743.116 m
- **Language:**
  ESNext

**Current behavior:**
I created a grid component. It has child grid-column components which are inserted through the slot. The grid is bound to an array. the grid.html first renders column headers by looping through columns. Then it renders individual rows by looping through items and then looping through columns. Here is the code. 

```
    <div>
        <label repeat.for="column of columns">
            ${column.title}
        </label>
    </div>
    <div repeat.for="item of items">
        <label repeat.for="column of columns">
            ${item[column.field]}
        </label>
    </div>
```

The problem is that if I comment out the code which renders the header, nothing is displayed.
**Expected/desired behavior:**
The Grid should works in both cases when the header rendering code is commented or not.
The code to reproduce the behaviour is attached. 
[repeater-issue.zip](https://github.com/aurelia/binding/files/435393/repeater-issue.zip)

Please run
npm install
jspm install
npm start
- **What is the expected behavior?**
  Same as above.
- **What is the motivation / use case for changing the behavior?**

**Comment by jdanyow** [comment]
hi @ppn2 please use the gist mentioned in the issue template to create a reproduction: https://gist.run/?id=7542e061bc940cde506b

**Comment by ppn2** [comment]
@jdanyow I tried this in the gist [https://gist.run/?id=3a13dc67f549b257ed30c455ace6fadc](https://gist.run/?id=3a13dc67f549b257ed30c455ace6fadc).

Unfortunately the issue does not reproduce there. On my machine I tried both systemjs and requirejs and I can reproduce the issue consistently. I have double checked that I got the latest version of all the packages. any advice?

**Comment by ppn2** [comment]
@jdanyow After you updated the gist, I tried my code again but I could not reproduce the issue. However I hosted all the **latest aurelia packages** at my own web site and referred the gist to those instead of yours. I sure can reproduce the problem. Here is the link to gist.
[https://gist.run/?id=3a13dc67f549b257ed30c455ace6fadc](https://gist.run/?id=3a13dc67f549b257ed30c455ace6fadc).

To summarize the problem again, I am creating a grid which has custom column components. The columns are defined through children attribute and they are being projected through slot. grid.html repeats for each dataitem and within that it repeats through each columns. Here is the code for the grid.html
```
<template>
    <div>First Block: Rendering Cells - before rendering header (but nothing get rendered)</div>
    <div repeat.for="item of items">
        <label repeat.for="column of columns">
            ${item[column.field]}
        </label>
    </div>
    <div>Rendering Header</div>
    <div>
        <label repeat.for="column of columns">
            ${column.title}
        </label>
    </div>
    <div>Second Block: Rendering Cells - after rendering header</div>
    <div repeat.for="item of items">
        <label repeat.for="column of columns">
            ${item[column.field]}
        </label>
    </div>
    <slot></slot>
</template>
```
In this example I am rendering the cells two times. One before I render the header (First Block) and one after I render the header (Second block). The Second block renders fine but the first block renders nothing at all.

**Comment by ppn2** [comment]
hi @jdanyow  did u get a chance to look at it?

**Comment by Alexander-Taran** [comment]
stale since 2016

**Comment by Alexander-Taran** [comment]
@ppn2 if it renders with prebuilt Aurelia libraries then it looks like your setup did not work correctly in 2016

I hope you solved it

Maybe can be closed and reopened if need arises

**Comment by EisenbergEffect** [comment]
Closing since it appears to be fixed and no response from OP.
