### ISSUE TITLE
typescript compilation error TS1110 in aurelia-binding.d.ts

### ISSUE THREAD

**Issue by activebiz** [aurelia/binding#487]
**I'm submitting a bug report**

* **Library Version:**
1.0.3

**Please tell us about your environment:**
* **Operating System:**
Windows [7|8|8.1|10]

* **Node Version:**
6.4.0

* **NPM Version:**
3.10.3

* **Language:**
TypeScript 1.5

**Current behavior:**

```
/node_modules/aurelia-binding/dist/aurelia-binding.d.ts(414,10): error TS1110: Type expected
/node_modules/aurelia-binding/dist/aurelia-binding.d.ts(415,22): error TS1110: Type expected.
```
Getting above compilation error when doing typescript compilation. Its to do with the following in aurelia-binding.d.ts

```
/**
 * A literal primitive (null, undefined, number, boolean).
 */
export declare class LiteralPrimitive extends Expression {
  value: null|undefined|number|boolean;
  constructor(value: null|undefined|number|boolean);
}
```

Shouldn't it be ?

```
/**
 * A literal primitive (null, undefined, number, boolean).
 */
export declare class LiteralPrimitive extends Expression {
  value: any;
  constructor(value: any);
}
```

Thanks

**Comment by RomkeVdMeulen** [comment]
`number|boolean` would be okay, but null and undefined as types are [part of typescript 2.0](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#typescript-20) which hasn't been released yet.

**Comment by jdanyow** [comment]
fixed in upcoming release

**Comment by activebiz** [comment]
Thanks chaps
