### ISSUE TITLE
Error with children attributes

### ISSUE THREAD

**Issue by ggrimbert** [aurelia/binding#493]
Hi,
I'm submitting a bug report

* **Library Version:**
1.0.3

* **Operating System:**
Fedora 19

* **Node Version:**
5

* **NPM Version:**
3.9.6

* **JSPM  Version**
0.16.39 

* **Browser:**
Chrome

* **Language:**
ESNext

**Current behavior:**
I have created a custom element that takes params defined as children(@children). 
If I define 3 children, I should have 3 elements displayed, but I have 6 elements, the 3 "normals" and 3 "undefined".

I made a gist https://gist.run/?id=49a6e0ac84c6266b2e3614e9191da0e0, but it doesn't reproduce the problem as the versions of libraries are too old.

The code I use is in the gist, I removed the part with the progress bar and the list underneath, but this changes nothing to reproduce the bug.
Classes : 
 - tracker -> the component
 - tracker-item -> definition of component's children
 - app -> call to the component

Here's what I have with aurelia-binding 1.0.1 : 
![image](https://cloud.githubusercontent.com/assets/15869188/18205861/8a2e0f24-7124-11e6-855f-120bbe5758b1.png)

And here's what i have with version 1.0.3 : 
![image](https://cloud.githubusercontent.com/assets/15869188/18205956/f957e190-7124-11e6-895f-13f5d5ea8020.png)

The only thing that changed between the screenshots is the aurelia-binding version (from 1.0.1 to 1.0.3)

**Comment by jdanyow** [comment]
hi @ggrimbert - here's a link to the current gist: https://gist.run/?id=7542e061bc940cde506b

It's also in the issue template

**Comment by ggrimbert** [comment]
Hi, 

I created a new one with your link, but of course, the problem doesn't occur...

https://gist.run/?id=dc81f196be8ddd4b176646bb90a81d5a

Does it use aurelia-binding 1.0.3 ? I cannot see the versions it loads. 
If it is the good version, do you have any idea of what can happen ?

**Comment by jdanyow** [comment]
@ggrimbert can this be closed? Have you updated to the latest aurelia repos?

**Comment by ggrimbert** [comment]
I need to try with a new version of the dependency. I'll let you know when it's done.

**Comment by ggrimbert** [comment]
I tried with 1.0.9 and it works. I don't know what happened but there is no problem now. I close this issue.
