### ISSUE TITLE
LiteralPrimitive declaration invalid in TSD?

### ISSUE THREAD

**Issue by JoshMcCullough** [aurelia/binding#494]
**I'm submitting a bug report**

* **Library Version:**
https://github.com/aurelia/binding/commit/2eae96e964a0cb3152219fe4853f3e147568353d

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
5.10.1

* **NPM Version:**
3.8.3

* **JSPM OR Webpack AND Version**
JSPM 0.16.15

* **Browser:**
N/A

* **Language:**
TypeScript 1.7.5

**Current behavior:**
`typings install aurelia-binding` gives me a TSD which raises build errors as follows:

```
"C:/Projects/Avvro/GDS-Web/typings/modules/aurelia-binding/index.d.ts(417,10): The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type."
"C:/Projects/Avvro/GDS-Web/typings/modules/aurelia-binding/index.d.ts(417,15): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type."
"C:/Projects/Avvro/GDS-Web/typings/modules/aurelia-binding/index.d.ts(417,25): Cannot find name 'number'."
"C:/Projects/Avvro/GDS-Web/typings/modules/aurelia-binding/index.d.ts(417,32): Cannot find name 'boolean'."
"C:/Projects/Avvro/GDS-Web/typings/modules/aurelia-binding/index.d.ts(418,15): A parameter initializer is only allowed in a function or constructor implementation."
```

See here, I don't think `null|undefined|` should be emitted: https://github.com/aurelia/binding/search?l=typescript&q=literalprimitive&utf8=%E2%9C%93

**Expected/desired behavior:**
TSD should build without raising errors.

**Comment by Gheoan** [comment]
#485

**Comment by JoshMcCullough** [comment]
Thanks.
