### ISSUE TITLE
bindable valueChanged callback is fired even after component unbind

### ISSUE THREAD

**Issue by huochunpeng** [aurelia/binding#496]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
6.5.0

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
NA (aurelia-cli)

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
bindable valueChanged callback is fired even after component unbind. This should be a bug.
It is related with repeater as far as I can tell.

**Expected/desired behavior:**
To reproduce it: click the button twice in this gist run.
https://gist.run/?id=052bbfdb6bdc260d030d44ee07aa4f72

child component was created by repeater, child has an id reference.
The first click will create one child component with id:A, second click will replace the child component with another one with id:new.
But a mutation on old model can still reach child:A valueChanged callback after child:A unbind.

id:A bind
id:A unbind
id:new bind
id:A value changed to 2

* **What is the expected behavior?**
all valueChanged callback should be unwired during unbind.

* **What is the motivation / use case for changing the behavior?**
I had this issue in a bigger app which surprised me with unwanted side-effect. I was able to bypass this problem by setting/unsetting a flag in bind() and unbind() callback.
I think this is a bug to be fixed.
Thanks.

Chunpeng

**Comment by jdanyow** [comment]
@EisenbergEffect what do you think about adding something like this to the BehaviorPropertyObserver (would require adding `flushing: boolean` to the TaskQueue):

https://github.com/aurelia/templating/blob/master/src/behavior-property-observer.js#L44

```diff
  setValue(newValue: any): void {
    let oldValue = this.currentValue;

    if (oldValue !== newValue) {
      if (this.publishing && this.notqueued) {
        this.notqueued = false;
+        if (this.taskQueue.flushing) {
+          this.call();
+        } else {
          this.taskQueue.queueMicroTask(this);
+        }
      }

      this.oldValue = oldValue;
      this.currentValue = newValue;
    }
  }
```

I think it would solve this issue, along with https://github.com/aurelia/templating/issues/363 and possibly a few others.

**Comment by jdanyow** [comment]
https://github.com/aurelia/binding/issues/479

**Comment by EisenbergEffect** [comment]
@jdanyow That works for me, especially if you think you can use that to resolve those other issues. It's a non breaking change (bump minor) but we would need to make sure to update the version dependencies between templating and task queue.

If you feel good about it solving all these issues, please proceed.

**Comment by bondib** [comment]
@jdanyow  - just so you know, I applied the fix you wrote 4 days ago in my code, and bugs https://github.com/aurelia/templating-resources/issues/252 and https://github.com/aurelia/binding/issues/496 still occur. FYI...

**Comment by jdanyow** [comment]
@bondib thanks for testing this out. Can you confirm you applied the task-queue PR that goes along with the templating PR?

Here's a fork of the gist in https://github.com/aurelia/templating-resources/issues/252 with the fixes applied:

https://gist.run/?id=72490bd928925d0a0bcfe67511ce0125
