### ISSUE TITLE
Add support for `this` binding to reference the current view model

### ISSUE THREAD

**Issue by MrHayato** [aurelia/binding#50]
Currently there's no way to reference the view-model itself from the view, and can currently only reference its properties. A way to reference the VM as a whole would be great. Currently the only way to do this is to create a property on the view model to reference itself.

Eg:

```JavaScript
export class EntityTreeView {
    constructor(modelFactory) {
        this.treeRoot = this;
    }

    doSomethingWithNode(node) {
        something(node);
    }
}
```

```HTML
<component model.bind="{ node: nodes, root: treeRoot }"></component>
```

Use case:

Trying to build out a tree, so we recursively build out each node. When the node gets clicked it needs to call a function at the root level of the tree. Don't want to have to use EventAggregator to do so.

**Comment by EisenbergEffect** [comment]
@jdanyow After we fix up the binding engine, when we add more integrated support for $parent and a few other things, we should also look at supporting $this. I think all these changes will be in the AccessScope AST class when we are ready to make them.
