### ISSUE TITLE
@observable is not a proper decorator

### ISSUE THREAD

**Issue by jods4** [aurelia/binding#501]
https://github.com/aurelia/binding/blob/master/src/decorator-observable.js#L45
The code of `observable` decorator ends with 
`Reflect.defineProperty(target, key, descriptor);`
What it should do is:
`return descriptor;`
The property will be installed by the system, according to the decorators specs.

Why does it matter?
Because installing the property yourself prevents chaining decorators.

For instance, `observable` creates a non-enumerable property with no way to change this.
So I tried to do this:
```ts
@enumerable
@observable
x = 0;
```
Where `@enumerable` simple sets `descriptor.enumerable = true`.

With the way `observable` is coded this doesn't works (`descriptor` is `undefined`).
With my suggestion, it works.

_Aside:_ unlike the property observer, `@observable` really messes up the object on which it is applied (for example if you try to convert it to JSON later). 
Two points specifically:
- Aurelia property observer installs a property that is enumerable (or not) according to the original field/property. Would be nice if `@observable` did the same.
- `observable` installs a backing field simply with convention `_fieldName`. This has side-effects, notably it is serialized in JSON. I understand that this attribute works per class rather than per instance, which makes it more tricky (property observation stores it inside a capture in the getter function, won't work here). At least I think that putting it in a non-enumerable field would be nice. Using a (native) `WeakMap` where available is probably even better.

**Comment by jdanyow** [comment]
@jods4 I agree with everything you wrote, minus the WeakMap part.

Any chance you'd be willing to contribute a PR with the necessary changes?

The trick is getting things to work in both TypeScript and Babel which work slightly differently when applying property decorators. This is maddening, and makes the already complex code even more complex. I put together a little chart, which may need to be updated: https://github.com/aurelia/binding/blob/master/src/decorator-observable.js#L55-L66

**Comment by jods4** [comment]
@jdanyow see PR #503 for the chainable aspect (trivial change to `return decorator`)

About that table, is it still right? 
If I understand it correctly, it implies TS omits the `descriptor` parameter but when I look at the code generated by current TS compiler, it seems to be there.

I think this might have been fixed and TS follows the current standard proposal?

**Comment by jods4** [comment]
@jdanyow I see what you meant now. The table is not obvious ;)
The trick is that _for simple fields_ (not accessors), there is no specs at the moment.
Which means the following code is kind of undefined:
```ts
class C {
  @observable x;
}
```
In this specific case, TS does no pass a descriptor, while Babel passes a descriptor with some defaults (enumerable: true, notably).

Note that the comment above means that when I complained that the accessor was non-enumerable and hence hidden from JSON serialization, etc. _it was only true when compiling with TS_.

**Comment by jods4** [comment]
I updated the PR #503 
The only remaining issue is how to hide the backing `_name` field. 

This is actually quite tricky because Aurelia may want to observe it.
To hide the field from plain sight, we need to assign its value with `Object.defineProperty(instance, '_name', { writable: true, value: 42 })` instead of `x._name = 42`.
But then, if Aurelia observes `_name`, it will convert it to a pair of accessors, at which point the previous trick won't work anymore.

I can see 2 solutions here, but they require a bit more work: 
- we add a `getObserver()` method on the installed `get` accessor, which uses the already done getter to implement observation. This way, Aurelia doesn't need to be aware of the backing field at all.
- or we probe the descriptor at each write. If there are accessors (after observation), direct access is fine, otherwise we should use `defineProperty()` as described above.

**Comment by bmcdaniels** [comment]
I'd like to point out that this is still an issue for me, even after the change to return the descriptor in the decorator.
