### ISSUE TITLE
FYI: Aurelia Hub Binding Documentation Errors

### ISSUE THREAD

**Issue by waynepennington** [aurelia/binding#504]
See - http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-value-converters/4

**I'm submitting a bug report**
- **Library Version:** - whatever you're using on the documentation hub
- *\* Windows 10, Chrome Version 52.0.2743.116 m
  **Current behavior:**
  Unhandled rejection TypeError: numeral is not a function
  at NumberFormatValueConverter.toView

**Comment by EisenbergEffect** [comment]
@jdanyow I think you have access to the Hub. Can you take a look at what is going on here?

**Comment by tragiclifestories** [comment]
There is a similar error complaining that moment is missing.

**Comment by ErikSchierboom** [comment]
I can also confirm that there is indeed a problem:

![image](https://cloud.githubusercontent.com/assets/135246/19598755/d946af50-979c-11e6-9158-585535b78d55.png)
