### ISSUE TITLE
observable decorator creates backing field that shouldn't be enumerable

### ISSUE THREAD

**Issue by jdanyow** [aurelia/binding#505]
This issue was split off from https://github.com/aurelia/binding/issues/501

cc @jods4

**Comment by Gheoan** [comment]
Even if the backing property is converted to accesors, it can still be nonenumerable.

**Comment by jods4** [comment]
The problem with the backing property is that it must be observable by Aurelia's regular observer.
So it must be a regular property or we need a custom observation strategy (e.g. add `getObserver` on the getter) on the property decorated with `@observable`.
If it is a regular property, it can still be non-enumerable, but then you have to use `Object.defineProperty('_name', { writable: true, enumerable: false, value: 42 })` _each time you set its value_.
And after Aurelia `SetterObserver` has transformed this plain property into accessors to be able to observe it, the call above won't work anymore.

**Comment by EisenbergEffect** [comment]
@jdanyow Where are we at with this?

**Comment by jdanyow** [comment]
The PR is still in review
