### ISSUE TITLE
feature request: ArrayObserver to react on array[index] = newItem

### ISSUE THREAD

**Issue by huochunpeng** [aurelia/binding#509]
**I'm submitting a feature request**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12

* **Node Version:**
6.6.0

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
NA

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
ArrayObservation doesn't react on array[index] = newItem

**Expected/desired behavior:**
https://gist.run/?id=93437c5e48cfb9434dea2278fa898ed8

Aurelia array observation doesn't react on array[index] = newItem.

This is confirmed when I read the spec https://github.com/aurelia/binding/blob/master/test/array-observation.spec.js

The array observation only reacts on methods pop/push/reverse/shift/sort/splice/unshift. Replacing the whole array works too.

* **What is the expected behavior?**
Is it possible to support observing array[index] = newItem?

* **What is the motivation / use case for changing the behavior?**
Right now, need to avoid using` array[index] = newItem` to mutate any observable array.

Support this in ArrayObserver will make it totally transparent to programmers using Aurelia binding.

**Comment by jdanyow** [comment]
Unfortunately this would require dirty-checking. Some background here:

- https://github.com/aurelia/binding/commit/7d01567a00f5b0bb334b48614300273f7a99caed
- https://github.com/aurelia/binding/issues/289

Workaround is to use splice in place of indexed assignment. For example `myArray[i] = 'foo'` would become `myArray.splice(i, 1, 'foo')`.

**Comment by huochunpeng** [comment]
Thx, I had the feeling this might be really hard. I did use splice to work around.
