### ISSUE TITLE
custom element bindable changed not called if newValue is empty

### ISSUE THREAD

**Issue by sspilleman** [aurelia/binding#516]
Hi,

Ik have the following issue. I created a slideshow custom element. That element has a bindable property "images". I want the slideshow to start when the images (array) is changed. That images array is populated when I click a picture (first image of an array) on the page that hosts the custom element, that basically populates the slideshow array which is bound to the custom element.

```html
<slideshow images.bind="slideshow" stopfn.bind="stopSlideshow"></slideshow>
```
```javascript
startSlideshow(images) {
	console.log('startSlideshow', images);
	this.slideshow = images;
}
```

In the custom element class i have defined a method:

```javascript
imagesChanged(images) {
	console.log('SlideshowElement', images);
	if (images) {
		window.addEventListener('keydown', this.keyboardHandler, false);
		this.started = true;
		this.image = this.urlprefix + this.images[this.currentImage].original;
		this.startRenderTimer();
	}
}
```

So far so good. It works... Unless I want to start the same slideshow again... Which makes sense as the slideshow array isn't changed. I resolved this by putting a stopSlideshow method in the host class that empties the slideshow array:

```javascript
stopSlideshow() {
	console.log('stopped!');
	this.slideshow = [];
}
```

Calling stopSlideshow does NOT fire the imagesChanged propertyCallback...

My expectation is 1) That when stopSlideshow is called the imagesChanged is fired with an empty array (hence I put in the if (images) clause)).... and 2) that if I click the same image again (which again calls the startSlideshow fn)... that the imagesChanged propertyCallback refires....

Bug? Or am I doing something wrong?

Sander

**Comment by jdanyow** [comment]
Set a breakpoint or add the `debugger;` statement to your `stopSlideshow` method. At the breakpoint, examine the value of `this`. Is it what you expect it to be?

Typically when passing function references around via data-binding the `.call` binding command is used: `stopfn.call="stopSlideshow()"`

More info in the binding docs- basics section.

**Comment by sspilleman** [comment]
You're right! Good catch! That was it! Thanks again
