### ISSUE TITLE
Ordering issue with repeater

### ISSUE THREAD

**Issue by ppn2** [aurelia/binding#517]
**I'm submitting a bug report**
- **Library Version:**
  1.0.5

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  6.2.0
  
  
- **NPM Version:**
  3.8.9
  
  
- **JSPM OR Webpack AND Version**
  JSPM 0.16.45
  
  
- **Browser:**
  Chrome 52.0.2743.116 m
- **Language:**
  all

**Current behavior:**
I created a grid with three columns, which has capability to show/hide columns. If I hide columns Num 2 and then show it, column Num 2 renders after column number Num 3.

**Expected/desired behavior:**
The rendering order of the column should not change.
[https://gist.run/?id=4b65aa99aed5066b18a44b7e11b262a5](https://gist.run/?id=4b65aa99aed5066b18a44b7e11b262a5)
In this example the grid has three columns. Id, Name and State. Initially all the columns are shown. When you click on the "Hide Name" button, the Name column would disappear. Click on the button again to show Name Column. You would notice that column headers are in the correct order, however the cell order has messed up.

**Comment by EisenbergEffect** [comment]
We are going to need more information here, such as details for how you are hiding/showing the columns.

**Comment by ppn2** [comment]
@EisenbergEffect 

This is an oversimplified example of the grid custom control we are attempting. In this example the user has option to define custom columns, with the following syntax. (My apologies for long explanation as this bug is tricky to reproduce.)

```
    <grid items.bind="customers" grid.ref="customerGrid">
        <grid-column field="id" title="ID"></grid-column>
        <grid-column field="name" title="NAME"></grid-column>
        <grid-column field="state" title="STATE"></grid-column>
    </grid>
```
grid-columns are projected into the grid view model using @children property. The grid-column has two properties "field" and "title". title is used to render the header and field is used to calculate the value at run time. In the grid-column constructor, we create the viewfactory as follows.
```
let innerHtml = `$\{$$item.${fieldName}}`;
let template = `<template><label>${innerHtml}</label></template>`;
this.viewFactory = viewCompiler.compile(template, viewResources);
```
And finally we define a grid-column-renderer component, which renders the value of the cell. It is used in the grid as follows.

```
    <div repeat.for="item of items">
        <label as-element="column-renderer" repeat.for="column of columns" $$item.bind="item" column.bind="column"></label>
    </div>
```
In the renderer component we pass the grid-column component and the data item component. This component extract the viewFactory from the column, creates the view from the view factory, bind the view and attaches to the viewSlot as follows.
```
        let context = this.column.bindingContext;
        this.view = this.column.viewFactory.create(this.container);
        this.view.bind(this, context);
        let index = this.column.grid.columns.indexOf(this.column);
        this.viewSlot.add(this.view);
        this.viewSlot.attached();
```
So far it works fine. 

To add the show/hide functionality (which brings to the crux of the question), we define a property called "show" in the grid-column vm and also define an new columns array called "internalColumns" in the grid vm. Initially the property internalColumns is populated with the copy of original columns. We also listen to the "show" property and if this changes we filter the columns by show property and we repopulate the interalColumns. and finally we changed the grid.html to follows.
```
<div repeat.for="item of items">
        <label as-element="column-renderer" repeat.for="column of internalColumns" $$item.bind="item" column.bind="column"></label>
    </div>
```
Please not the repeat.for="column of columns" has been changed to "column of internalColumns". The idea is that when the show property changes, internalColumns will change and in turn will retrigger the repeat. This is where the problem occurs and the order of the columns get out of whack.

Please let me know if you need more information.

**Comment by ppn2** [comment]
Guys I will appreciate if someone can help me out here.

**Comment by EisenbergEffect** [comment]
We will really need a simplest-possible reproduction of the problem that we can run and debug on our own.

**Comment by ppn2** [comment]
@EisenbergEffect  this is the simplest I could use to reproduce. There are total of 5-6 files here in which 4-5 are the boilerplate code. I don't know what to say.

**Comment by EisenbergEffect** [comment]
Oops. Sorry. I didn't see the original gist.

**Comment by jdanyow** [comment]
gist doesn't seem to run. I tried updating it to the current version of the aurelia libs, errors in the console:
https://gist.run/?id=80c4bdcb6e48d34c494560adc9f8cd9a
