### ISSUE TITLE
Element observation styling not accepting number datatype

### ISSUE THREAD

**Issue by CasiOo** [aurelia/binding#518]
**I'm submitting a bug report**

* **Library Version:**
1.0.6

* **Browser:**
all

* **Language:**
all

**Current behavior:**
@khenderick https://github.com/aurelia/templating-resources/issues/251#issuecomment-250991098
Numbers aren't supported in style binding.

The following code
`css.bind="{opacity: !output.inUse ? 0.65 : 1}"`

Results in the error
`TypeError: value.indexOf is not a function`

**Expected/desired behavior:**
Styling should support numbers as well as strings.
The specified opacity number should be applied to the element.

**Comment by EisenbergEffect** [comment]
Technically, all values in the current CSSOM are strings, I believe. @jdanyow Can you check on this?

**Comment by jdanyow** [comment]
@z-brooks I think this might be a quick fix here: https://github.com/aurelia/binding/blob/master/src/element-observation.js#L66

**Comment by stsje** [comment]
@jdanyow There's already an open pull request.

**Comment by Vheissu** [comment]
Heads up, this merged PR doesn't actually always fix the problem. I encountered this same issue and for null/undefined values, this will fail as `indexOf` does not exist. The better way seems to check if the value exists and then do the check.

**Comment by EisenbergEffect** [comment]
Can you PR the fix? Ping @jdanyow so he can review and we can get a patch release out.
