### ISSUE TITLE
@Child decorated property is not being populated in the dynamically created element.

### ISSUE THREAD

**Issue by ppn2** [aurelia/binding#520]
**I'm submitting a bug report**

* **Library Version:**
1.0.5

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.32

* **Browser:**
Chrome 52.0.2743.116 m

* **Language:**
all

**Current behavior:**
If a custom component uses slot and catches the projected element through the @child decorated variable, the variable is populated as expected if the component is statically used. If the same component is used dynamically (e.g. define the html is defined as string and compiled into viewfactory and manually bound and attached to the slot), the @child decorated variable is not populated.

**Expected/desired behavior:**

The child decorated variable should be populated regardless of the use of the component. You can reproduce the problem at the following gist.
[https://gist.run/?id=0a64de7c329a40154f5bcf888bea8026](https://gist.run/?id=0a64de7c329a40154f5bcf888bea8026)
Please note: I have redirected the log statements to the div at the bottom of the screen for convenience.

**Comment by ppn2** [comment]
I did some more digging around this issue and found that the child property indeed get populated but it is not available at the time attached is fired (during dynamic use. During static use the property is populated when attach event is fired.). Not sure if this is the right behavior.

**Comment by EisenbergEffect** [comment]
We have this tracked elsewhere. For now, if you are doing dynamic things like this I recommend that you use the change callback for the child so you can know exactly when it becomes available.
