### ISSUE TITLE
Select bound to a sub-property does not update properly when changing the parent property

### ISSUE THREAD

**Issue by geleto** [aurelia/binding#521]
**I'm submitting a bug report**
- **Library Version:**
  1.0.6
- **Browser:**
  Chrome, Edge

I have a Select element which is bound to a sub-property: 
`<select value.bind="selectedCar.selectedModel">`
- The initially displayed value (as set in the constructor) is correct.
- If I change the value of `selectedCar` - the select always displays the first option, no matter what the value of `selectedCar.selectedModel` is. A string interpolation next to the select displays the correct value.
- If I change only the value of the subproperty : `selectedCar.selectedModel` - the select displays the correct option.

See this gist that reproduces the problem: https://gist.run/?id=9537cfd05a9c8c3666be8646343248b8

**Comment by StrahilKazlachev** [comment]
@geleto Is this still an issue, since the gist seems to work as expected?

**Comment by StrahilKazlachev** [comment]
My mistake, where was I looking.

**Comment by bigopon** [comment]
@geleto a fix for this is at https://github.com/aurelia/binding/pull/677
