### ISSUE TITLE
Binding style object works only on single worded css properties [1.0.9]

### ISSUE THREAD

**Issue by GabrielMancik** [aurelia/binding#523]
I have an element with css.bind="style".
In Viewmodel I have:
```
	get style() {
		return {
			backgroundColor: blabla,
			color: blabla,
			padding: blabla,
			fontFamily: blabla,
			fontWeight: blabla,
			fontStyle: blabla,
			fontSize: blabla,
			textAlign: blabla
		};
	}
```

But only color and padding gets binded. I just assume its because other properties are not single words.
Previously I used version 1.0.4 and everything worked fine.

**Comment by jdanyow** [comment]
@z-brooks / @GabrielMancik this is strange- looking at the 1.0.4 code, I can see how it would work the way @GabrielMancik describes. On the other hand, the [1.0.4 tests](https://github.com/aurelia/binding/blob/1.0.4/test/element-observation.spec.js#L202-L212) are using hyphenated property names.

@GabrielMancik, change the code to the following and it should work:

```js
    get style() {
        return {
            'background-color': blabla,
            'color': blabla,
            'padding': blabla,
            'font-family': blabla,
            'font-weight': blabla,
            'font-style': blabla,
            'font-size': blabla,
            'text-align': blabla
        };
    }
```

**Comment by GabrielMancik** [comment]
Suggested code change works. Thanks

**Comment by BenDTU** [comment]
It'd be good to get this one fixed - we just had a bunch of stuff break because we were using the Typescript CSSStyleDeclaration to generate our styles, which uses camelCasing.
