### ISSUE TITLE
repeat.for generates too many entries

### ISSUE THREAD

**Issue by khenderick** [aurelia/binding#525]
**I'm submitting a bug report**

* **Library Version:**
aurelia-binding 1.0.9

**Please tell us about your environment:**
* **Operating System:**
ArchLinux

* **Node Version:**
6.7.0

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.22

* **Browser:**
Chrome 55.0.2873.0 dev

* **Language:**
ESNext

**Current behavior:**

Assume some class where the constructor creates a list

```
this.entries = [];
```

Some method, called every x seconds, will call an API, and add/remove/update objects inside ```this.entries```. Something like ```this.entries.push(new Entry());```.

In the HTML, I loop over these objects to print a given property

```
<span repeat.for="entry of entries">
    Name: <span>${entry.name}</span><br />
</span>
```

When there are let's say 4 entries in the list, I get the following:

```
Name: one
Name: two
Name: three
Name: four
Name:
Name:
Name:
Name:
```

When I include ```<span>${entries.length}</span>``` in my html, it reports (correctly) four. If I do a ```console.log(this.entries)``` in my javascript, it prints a list with 4 entries (and some observing logic).

E.g.

```
[Entry, Entry, Entry, Entry, __array_observer__: ModifyArrayObserver, __observers__: Object]
```

**Expected/desired behavior:**

I would expect only this:

```
Name: one
Name: two
Name: three
Name: four
```

However, I cannot simply reproduce it as simple as explained above (then it seems to work fine), but the behavior was introduced in the last week or so (updated yesterday, and then the reported behavior started).

A workaround I'm currently using is adding a getter:

```
@computedFrom('entries')
get workingEntries() {
    let entries = [];
    for (entry of this.entries) {
        entires.push(entry);
    }
    return entries;
}
```

and updating the repeat.for like this: ```<span repeat.for="entry of workingEntries">```

Any recent change that could explain this?

**Comment by jdanyow** [comment]
@khenderick please provide a reproduction using the aurelia gist and we'll look into this:

https://gist.run/?id=7542e061bc940cde506b

**Comment by khenderick** [comment]
Apparently an ```rm -rf node_modules``` and then ```npm install``` did the trick, even though I ran ```npm update``` before.
