### ISSUE TITLE
different behaviour on valueChanged() callback when bind() callback is defined.

### ISSUE THREAD

**Issue by huochunpeng** [aurelia/binding#526]
**I'm submitting a bug report**

* **Library Version:**
1.0.9

* **Operating System:**
OSX 10.x

* **Node Version:**
NA

* **NPM Version:**
NA

* **JSPM OR Webpack AND Version**
NA

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
When `bind()` callback is defined, initial `valueChanged` callback is not fired.

When no `bind()` callback was defined,  initial `valueChanged` callback is fired.

**Expected/desired behavior:**
https://gist.run/?id=54c4c0ce81f49de3327549677adb21dd

Just try to turn on/off `line.js` `bind()` callback to see the different log in console.

* **What is the expected behavior?**
The behaviour should be same with or without `bind()` callback defined.

* **What is the motivation / use case for changing the behavior?**
To be consistent.

**Comment by huochunpeng** [comment]
This is a side issue of what I found when I try to reproduce another bug.

The original bug I am working on is related with computedFrom property, which briefly got wrong result (during transition, part of dependencies still use old model, part of dependencies use new model). An empty `binding()` callback magically solves that issue. So far I was not able to simplify my code enough to find the exact minimum to reproduce that bug.

Somehow, `bind()` callback behave like a barrier which makes sure all dependencies in computedFrom are "synchronised". This is the behaviour I would like to keep when `bind()` callback is undefined.

Hopefully the future fix for this one will solve my original bug I was unable to reproduce in gist.

**Comment by EisenbergEffect** [comment]
Yes. If you define a `bind` callback, the change callbacks are not called the first time. Instead you get a single call to `bind` after all properties are set.

**Comment by EisenbergEffect** [comment]
@AshleyGrant Do we have this in the docs on custom elements? If not would you be willing to PR that to the appropriate place?

**Comment by AshleyGrant** [comment]
I'll add notes for it.

**Comment by huochunpeng** [comment]
Thx. I will try to get a gist working for the computed property bug I mentioned.
