### ISSUE TITLE
Interpolation in event binding

### ISSUE THREAD

**Issue by ldrews1** [aurelia/binding#528]
Does interpolation work in event binding?

I tried the following:

 <button type="button" click.delegate="${action}()">${action}</button>

action is a VM variable containing the name of a function as a string: Add, Edit, Delete
The name appears properly as the label of the button but does not appear in the event binding.

**Comment by jdanyow** [comment]
Would this work for you:

```html
<button type="button" click.delegate="$this[action]()">${action}</button>
```

**Comment by ldrews1** [comment]
On Fri, 2016-10-28 at 09:15 -0700, Jeremy Danyow wrote:
> Would this work for you:
> 
> <button type="button" click.delegate="$this[action]()">${action}</button>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
Did not work.  Received error msg: 

vendor-bundle.js:10581 Uncaught Error: $this[action] is not a function(…
)evaluate @ vendor-bundle.js:10581callSource @
vendor-bundle.js:13939(anonymous function) @
vendor-bundle.js:13963handleDelegatedEvent @ vendor-bundle.js:12142

Using Chrome Version 54.0.2840.71 (64-bit)
LinuxMint

**Comment by jdanyow** [comment]
here's an example: https://gist.run/?id=14b65a8f9e3f8484ae466f73f43801a1

**Comment by rquast** [comment]
How do you use this in a repeat.for? https://gist.run/?id=7ffea129f996c1514bdeafdf1f9925d1

**Comment by rquast** [comment]
nevermind.. it's $parent[action] if used in a repeat.for - https://gist.run/?id=fb97fc865a1fb6cb9790c237dfc0b126
