### ISSUE TITLE
Idea: "Merge" binding (of objects)

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/binding#529]
This idea is a consequence of some discussion I had with a person on Gitter.

The problem is that if someone builds a custom-element and that custom-element needs a fair amount of data, it can be tedious to expose all of that data as separate bindables. Tedious, but it works of course. It makes sense to encapsulate that data into an object, like this:

```
<customer-details customer.bind="customerObject"></customer-details>
```

and the view-model class is something like:

```
export class CustomerDetails
{
    @bindable det = { name: null, address: null }; // placeholders
}
```

Inside the customer-details template one would ideally like to bind to individual properties of "customerObject" as held by the view-model, eg:

```
<template>
    Name: ${det.name}
    Address: ${det.address}
</template>
```

and so forth.

The binding won't work in practice because Aurelia will be looking for "customerObject" to change, and when it does change, the original bindings inside the template will now be targeting the wrong properties (ie. of the old object). In other words, Aurelia has replaced the entire "det" object.

So the idea was to have a different bind primitive such as:

```
<customer-details customer.merge="customerObject"></customer-details>
```

such that when Aurelia detects that "customerObject" has changed, it merges the properties from the changed "customerObject" into the view-model property object "det", rather than simply assigning "det" with a new value.

I guess in practice the process would need to be recursive, and I'm not sure what "merge" would mean in the context of arrays. In fact, merge may be the wrong term altogether - "update" might be a better term.

**Comment by jdanyow** [comment]
The binding would work in practice: 
https://gist.run/?id=08d941418d33b81b31e193435948591b

**Comment by kevmeister68** [comment]
When I look at the code I didn't think it was a representative Gist of what I had explained, so I changed the Gist to replace the complete customerObject with an entirely new object. The bindings continued to work. 

Wow. I'm impressed. I was unaware Aurelia did that (and I'm bummed because I told someone the wrong thing).

Does that mean that Aurelia maintains a directed graph (or similar) of binding dependencies? For example, the binding of "det.name" is somehow a dependent of "customerObject", so if customerObject is changed then det.name is rebound?

It's the only way I can think of that would allow this to work?

If that's all true, my suggestion is in fact pointless and you can close this issue.

**Comment by jdanyow** [comment]
Nice! Glad your scenario is supported out of the box. The binding system parses the binding expression text, producing an abstract syntax tree (AST). Each node in the tree knows how to monitor it's part of the expression for changes. You can read more about how this all works here:
http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-how-it-works
