### ISSUE TITLE
String interpolation binding doesn't observe inner array when expression uses value converter

### ISSUE THREAD

**Issue by wc-matteo** [aurelia/binding#531]
**I'm submitting a bug report**

* **Library Version:**
1.0.9 (aurelia-binding)

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.3.0

* **NPM Version:**
3.10.3

* **Browser:**
Chrome 54

* **Language:**
ESNext

Here is a gist.run: https://gist.run/?id=38b5fcb8fda8329876546c41d7137ef5

It does work when modifying the original collection: https://gist.run/?id=5b52c518e48be73b602292aec1af20e0

Or when inside the repeater: https://gist.run/?id=44695b110c8fcfa98d3d9e9f1ac8e94a

**Comment by jdanyow** [comment]
The question is:

*Given the following template:*
```html
<template>
  <h1>${messages | filter}</h1>
</template>
```
*Why doesn't the binding update when the array referenced by the `messages` property is mutated?*

**Comment by wc-matteo** [comment]
The same behaviour may be observed when using a bindable property on a custom element:

```html
<conditions conditions.bind="conditions | conditionFilter:category.types"></conditions>
```

`conditionFilter` creates a new array; removing the value converter makes the changes to `conditions` update the binding

**Comment by EisenbergEffect** [comment]
@jdanyow Is this a bug?

**Comment by rayalan** [comment]
I came across this today (see a similar scenario here with buttons and value converters). https://gist.run/?id=5a9308b2788c0e4330b7135f74328ea7

This feels like a bug; it certainly wasn't what I expected from the documentation.

@jdanyow @EisenbergEffect Is there any chance of an update or a quick look on this issue? It makes arrays surprisingly hard to work with in many circumstances.

**Comment by rayalan** [comment]
I forgot to mention; I hit this with aurelia-binding 1.1.0, so the last release didn't fix this.

**Comment by jdanyow** [comment]
This isn't a bug, it's just something that is not currently supported. Typically the only thing that observes array mutation is the `repeat.for`. Early in the alpha we made a change to observe array mutation in simle string interpolation expressions like `${myArray}`.
