### ISSUE TITLE
Missing interface for simple ValueConverter (TypeScript)

### ISSUE THREAD

**Issue by fracz** [aurelia/binding#533]
There are no interfaces (or I am unable to find them) for the [Simple ValueConverters described in the docs](http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-value-converters/2), i.e. classes that implement either `toView` or `fromView` methods.

My suggestions:

```ts
interface ToViewValueConverter {
  toView(modelValue: any): any;
}

interface FromViewValueConverter {
  fromView(viewValue: any): any;
}
```

**Comment by EisenbergEffect** [comment]
Should we add something like this f? We have them for navigation, for example. (Not something I would use since the runtime is duck typed and no APIs receive an instance of value converter, I don't think.) @fracz Can you describe your use case more?

**Comment by fracz** [comment]
Such interfaces could be used in the same way as for example the [`ComponentAttached`](https://github.com/aurelia/templating/blob/master/dist/aurelia-templating.d.ts#L190) interface. The functionality of the `attached()` is also supported by duck typing. Using an interface in TS adds a benefit of immediate API changes detection when upgrading. Also, when using an interface, IDE (WebStorm) does not complain that the method is unused :-)

**Comment by StrahilKazlachev** [comment]
We did add the `Component...` and `RoutableComponent...` interfaces, but some quick thoughts:
* in this case if you have additional parameters you would have to override the interface methods definitions
* then there is also the same problem/question as with `Component...` do we make `ValueConverterToView` and `ValueConverterFromView` or one `ValueConverter`.
```
// sample definition
interface ValueConverter<TSource, TView> {
  toView(value: TSource): TView;
  fromView(value: TView): TSource;
}
```
* if this is added won't a definition for a behavior also be expected? Although I found it counterproductive typing the `.bind` binding parameter different from `any` - too many `as any` when substituting `.updateSource`, ...

**Comment by Alexander-Taran** [comment]
stale from 2016

**Comment by EisenbergEffect** [comment]
The framework doesn't need these, so we'll punt for now. Any consumer is happy to create their own interfaces to facilitate their own App-specific scenarios.
