### ISSUE TITLE
Binding to checkbox

### ISSUE THREAD

**Issue by pragmaproducts** [aurelia/binding#534]
With the current version of aurelia, there is a binding issue with checkboxes and property setters.

I have a property setter for a property isReadOnly that uses bitmasks.

```
    set isReadOnly(isReadOnly: boolean) {
        if (this.isRequired && isReadOnly) {
            return;
        }

        this.setOption(isReadOnly, SCREEN_ITEM_OPTIONS.ReadOnly);
    }
```

if is Required is true then the isReadOnly bit must not be set.
This works fine in code.
When binding to a checkbox you can pick up problems.
If isRequired is true and you click on the isReadOnly checkbox it stays checked even though isReadOnly is still false.

binding on the checkbox works like:
`checked.bind="screenItem.isReadOnly"`

**Comment by jdanyow** [comment]
hi @pragmaproducts, if you'd like to put together a minimal reproduction using the Aurelia gist we can look into this for you.
https://gist.run/?id=7542e061bc940cde506b

**Comment by EisenbergEffect** [comment]
No feedback from the OP for over two weeks so we assume they worked it out
