### ISSUE TITLE
.keys() function is not defined

### ISSUE THREAD

**Issue by code-chris** [aurelia/binding#535]
**I'm submitting a bug report**

* **Library Version:**
aurelia-binding 1.0.9
aurelia-polyfills 1.1.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.0.0

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
webpack 1.13.3

* **Browser:**
IE 11

* **Language:**
TypeScript 2.0

**Current behavior:**
On app startup I always get this error in Internet Explorer:
`Das Objekt unterstützt die Eigenschaft oder Methode "keys" nicht`. This points to the following line in aurelia-binding: `var keys = bindings.keys()` inside the `flush` function. I tested the following to isolate the issue:
- The codeblock in aurelia-polyfills where the Map Polyfill is applied, is executed correct (before this error happens)
- If I execute `bindings.keys` during debugging I received `undefined`.
- If I execute `new Map().keys` during debugging I received the `sharedKeys` function from the polyfill.
- If I execute `bindings.constructor.name` during debugging I received `Map`.

It seems, that some bindings are not correct handled after this issue appears.

**Comment by code-chris** [comment]
aurelia/polyfills#33

**Comment by EisenbergEffect** [comment]
@jdanyow Can you look into this?

**Comment by jdanyow** [comment]
@code-chris I wasn't able to reproduce this using the [typescript+webpack skeleton](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript-webpack) in IE11 on windows 10.

**Comment by Thanood** [comment]
I'm also not getting any errors with the skeleton.
However, the skeleton uses `webpack 2.1.0-beta.25` and @code-chris mentioned `webpack 1.13.3`. Maybe there is a difference. I couldn't find any, though (not a webpack pro),

**Comment by jdanyow** [comment]
I'm not a webpack expert either- @code-chris, can you try upgrading webpack or dropping your code into the webpack skeleton?

**Comment by code-chris** [comment]
@jdanyow I'm creating a skeleton with this error at the moment.

**Comment by code-chris** [comment]
@jdanyow I created a repository with the skeleton: https://github.com/code-chris/aurelia-binding-issue-535

I figured out, that if I remove the interpolation binding in `App.html` the error does not occur anymore...

**Comment by jdanyow** [comment]
thanks @code-chris! can you tell us a little bit about this repo- is it the webpack skeleton with some code changes in the src folder or is it a completely custom setup?

**Comment by code-chris** [comment]
It's a completely custom setup. But there is not much code in it.

**Comment by jdanyow** [comment]
ok maybe @niieani will be able to help you out- he's our webpack expert and put together the webpack skeletons in such a way that the polyfills loaded ahead of everything else so these types of issues don't occur.

**Comment by Thanood** [comment]
@niieani uses a [bootstrap entry/bundle](https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-typescript-webpack/webpack.config.ts#L35-L39) which he declares as first chunk in [`CommonsChunkPlugin`](https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-typescript-webpack/webpack.config.ts#L106).

I tried to change @code-chris's repo to include that but failed.

**Comment by niieani** [comment]
Not sure what's going on here, perhaps you could try putting 'aurelia-polyfills' as listed in the first chunk.

**Comment by code-chris** [comment]
@niieani I modified my webpack config (https://github.com/code-chris/aurelia-binding-issue-535/commit/90a81b7f727f42811923664bd626152fc9e0c970) but I get always a 404 when "0.bundle.js" is requested...

**Comment by niieani** [comment]
@code-chris how about without CommonsChunkPlugin?

**Comment by code-chris** [comment]
@niieani I tried it. Then I get the following error:
```
Unhandled rejection TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (http://localhost:8080/assets/aurelia.js:51:29)
    at http://localhost:8080/assets/aurelia.js:20023:25
    at Promise.then._this2.modulesBeingLoaded.(anonymous function) (http://localhost:8080/assets/aurelia.js:20025:11)
    at WebpackLoader._import (http://localhost:8080/assets/aurelia.js:20008:19)
    at WebpackLoader.loadModule (http://localhost:8080/assets/aurelia.js:20066:18)
    at http://localhost:8080/assets/aurelia.js:18521:13
From previous event:
    at run (http://localhost:8080/assets/aurelia.js:18518:25)
    at Object.<anonymous> (http://localhost:8080/assets/aurelia.js:18543:2)
    at Object.<anonymous> (http://localhost:8080/assets/aurelia.js:18544:31)
    at __webpack_require__ (http://localhost:8080/assets/aurelia.js:51:30)
    at Object.<anonymous> (http://localhost:8080/assets/aurelia.js:101:2)
    at __webpack_require__ (http://localhost:8080/assets/aurelia.js:51:30)
    at http://localhost:8080/assets/aurelia.js:94:18
    at http://localhost:8080/assets/aurelia.js:97:10
```

The original error seems to be away at the moment.

**Comment by niieani** [comment]
You're hitting the webpack-plugin bug of missing modules, it's a pain, I know. Do you have all the necessary build resources listed in your package.json file?

Fortunately a better solution is coming soon: https://github.com/aurelia/skeleton-navigation/pull/714

**Comment by code-chris** [comment]
@niieani I simplified my webpack config. For the moment I don't use the CommonsChunkPlugin and don't create a own vendor bundle, so all is in one file. This works good for now. Looking forward to your great solution ;).

**Comment by Gheoan** [comment]
This might have been fixed by https://github.com/aurelia/binding/commit/d676d63d31cccab5d0492ef273c920a372b58b0e.

**Comment by code-chris** [comment]
This is fixed by the commit mentioned above. I applied the unreleased change to my app and it worked.

**Comment by jdanyow** [comment]
thanks for the update @code-chris - closing this
