### ISSUE TITLE
value.bind on select removes ability to default to a disabled option

### ISSUE THREAD

**Issue by DanCardin** [aurelia/binding#540]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Linux (Ubuntu)

* **Node Version:**
4.4.7

* **NPM Version:**
3.10.9

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.25

* **Browser:**
all

* **Language:**
TypeScript 2.1

**Current behavior:**
```
<select value.bind="selected">
  <option disabled model.bind="{}">Select</option>
  <option repeat.for="item of arr" model.bind="item">${item.label}</option>
</select>
```
Won't let the first item default to being selected, and won't allow the item to *get* selected either if I try to manually set the value to the first option. This includes when the empty option is part of the `repeat.bind`, or if I try to do something like `<option disabled.bind="$first" repeat.for....>`

**Expected/desired behavior:**
It should work the same way it would without any javascript, which is allowing the `select` to default to the disabled option (or be selected programmatically), while the `disabled` attribute keeps the user from selecting the option.

* **What is the motivation / use case for changing the behavior?**
I couldn't find where its handled, but this almost seems like it was done on purpose. If that's true, then I feel like there are ways to achieve that effect manually with the current binding capabilities, while the current behavior is different from vanilla html, confusing, and difficult or not possible to exactly reproduce as-is.

**Comment by jdanyow** [comment]
https://gist.run/?id=fa360ebc31cab8d0d93732cf92324f21

**Comment by CasiOo** [comment]
@jdanyow Your example gist doesn't select the first option 'Select' on my machine (Chrome 54).

Here's a working example on my machine https://gist.run/?id=1c6aabd5197e3051b80aa7de31d2c880

**Comment by jdanyow** [comment]
My gist is demonstrating that it does not work when the model value for the first item is null and the first item is disabled.

**Comment by RWOverdijk** [comment]
Is this issue getting any love? @jdanyow Anyone you can poke about this? Or maybe provide some information so we can perhaps help solve this?

**Comment by jdanyow** [comment]
fix:

https://gist.run/?id=f5a581ebd6c1f8052598f6085293e3e7

```js
import {SelectValueObserver} from 'aurelia-binding';

SelectValueObserver.prototype.synchronizeOptions = function() {
  let value = this.value;
  let isArray;

  if (Array.isArray(value)) {
    isArray = true;
  }

  let options = this.element.options;
  let i = options.length;
  let matcher = this.element.matcher || ((a, b) => a === b);
  while (i--) {
    let option = options.item(i);
    let optionValue = option.hasOwnProperty('model') ? option.model : option.value;
    if (isArray) {
      option.selected = value.findIndex(item => !!matcher(optionValue, item)) !== -1; // eslint-disable-line no-loop-func
      continue;
    }
    option.selected = !!matcher(optionValue, value);
  }
}
```

**Comment by itkfm** [comment]
Any idea how to get this working with TypeScript?
> `Property 'synchronizeOptions' does not exist on type 'SelectValueObserver'.ts(2339)`

**Comment by bigopon** [comment]
@itkfm Did you still get unexpected behavior with the latest version?

**Comment by itkfm** [comment]
> ```
> src/app.ts(493,31): error TS2339: Property 'synchronizeOptions' does not exist on type 'SelectValueObserver'.
> TypeScript: 1 semantic error
> TypeScript: emit succeeded (with errors)
> [10:50:35] gulp-notify: [Error running Gulp] Error: TypeScript: Compilation failed
> ```


##### package-lock.json
> `"aurelia-binding": { "version": "2.5.0"`

**Comment by itkfm** [comment]
Updated dependencies

> `INFO [Bundler] Auto tracing package: 2.5.2      aurelia-binding`

still the same, though:

> ```
> src/app.ts(493,31): error TS2339: Property 'synchronizeOptions' does not exist on type 'SelectValueObserver'.
> TypeScript: 1 semantic error
> TypeScript: emit succeeded (with errors)
> [10:53:45] gulp-notify: [Error running Gulp] Error: TypeScript: Compilation failed
> ```

**Comment by bigopon** [comment]
@itkfm with version 2.5, you dont need to copy paste the above code block in your app anymore. Can you try remove itand see if your app works as expected?

**Comment by itkfm** [comment]
Unfortunately it does not. That's why I even started googling this and came to this issue.

I did just retry and it always selects the first non-disabled `<option>`.

**Comment by itkfm** [comment]
My code:

##### time-slot.html
```html
<template>
    <require from="./simple-time-picker"></require>
    <select as-element="simple-time-picker" placeholder="from" value.two-way="a" required></select>
    <select as-element="simple-time-picker" placeholder="to" value.two-way="b" required></select>
</template>
```


##### simple-time-picker.ts
```ts
import { bindable } from 'aurelia-framework';

export class SimpleTimePicker
{
    @bindable placeholder: string;
}
```
##### simple-time-picker.html
```html
<template>
    <option disabled selected value="">${placeholder}</option>
    <option>00:30</option>
    <option>00:00</option>
    <option>01:00</option>
    <option>01:30</option>
    <option>02:00</option>
    <option>02:30</option>
    […]
</template>
```

**Comment by itkfm** [comment]
Any ideas?

**Comment by RWOverdijk** [comment]
@itkfm This is a closed issue, I doubt anyone is going to respond to it.

**Comment by bigopon** [comment]
Oops, sorry I forgot this. let me try to reproduce it

**Comment by bigopon** [comment]
@itkfm I just had a look at this and was able to figure out why it doesn't seem to be working as you expected.
The timing sequence is like this:
1. Aurelia syncs view model -> view, so the `<select/>` would have value `undefined`
2. `<option/>` gets added by `repeat`, triggering a mutation event
3.1. Aurelia tries to sync the value from view model to view one more time, and thus un-select all the `<option/>` element, because none matches the value in the view model (`undefined`)
3.2. Aurelia tries to sync the value of `<select/>` back to the view model, which is the first non-disabled `<option/>`, because that's how `<select/>` works in HTML.

So, in order to make work, you need to ensure the step 3.1 is done correctly by giving proper initial view model value, which in this case, an empty string. You can see the a working example here:
 https://codesandbox.io/s/httpsgithubcomaureliabindingissues540-w2qun

**Comment by itkfm** [comment]
neat :ok_hand:
Got it working now (by setting `a` and `b` to `''` instead of `null`). Thank you very much.

(Maybe this should make it's way into the documentation if it's not there already.)
