### ISSUE TITLE
Support anonymous functions in binding parser

### ISSUE THREAD

**Issue by zakjan** [aurelia/binding#541]
**I'm submitting a feature request**

```
<template>
    <div title.bind="entities.map((x) => x.name).join(', ')"></div>
</template>
```

Now it throws ```Uncaught Error: Parser Error: Unexpected token > at column 19 in [entities.map((x) => x.name).join(', ')]```

**Comment by EisenbergEffect** [comment]
@jdanyow This would be nice to have for the future. I'm not sure just how complicated it would be to do with the parser right now. There are more important bugs we want to fix first though.

**Comment by Alexander-Taran** [comment]
Stale since 2016

**Comment by EisenbergEffect** [comment]
Not planning to add this. We don't want to encourage putting too much code into a binding expression.
