### ISSUE TITLE
Checked observer of an array could create a new array instead of mutating

### ISSUE THREAD

**Issue by zakjan** [aurelia/binding#542]
**I'm submitting a feature request**
Currently `checked.bind="entities"` edit the array in-place. If a parent component wants to listen to its changes, it needs to create `bindingEngine.collectionObserver`, and dispose it when no longer needed. It would be more bug-proof and more intuitive for users if such array is considered as immutable, and updating it creates a new array instead. Then it would be possible to listen to its changes with regular `entitiesChanged` method in VM.

**Comment by jdanyow** [comment]
Hi @zakjan, thanks for the feature suggestion. This would be a breaking change for a lot of people and cause quite a bit of confusion for folks who expect their array instance to remain the same.

I think you could create a custom attribute or `& immutableArray` binding behavior that achieves the result you're looking for, potentially releasing as a plugin or perhaps we could incorporate into the core if it's something that would work in similar applications like a select element with the multiple attribute.

**Comment by zakjan** [comment]
Sounds good, I'll write a binding behavior for this. Thanks.
