### ISSUE TITLE
$this contextual property is not exactly the same object as VM

### ISSUE THREAD

**Issue by zakjan** [aurelia/binding#543]
**I'm submitting a bug report**

* **Library Version:**
latest in the gist bundle https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.6

* **Browser:**
Chrome 55

* **Language:**
JS

**Current behavior:**
Binding a method to `$this` doesn't allow its body to access VM in `this`. Example, use case: https://gist.run/?id=8f1021e1b276a2c7ecab8722a0799c49

**Expected/desired behavior:**
Binding a method to `$this` should allow its body to access VM in `this`. In the example, `matcher.bind="matcher.bind($this)"` column should behave similar as `matcher.bind="matcher.bind(this2)"` column.

**Comment by jdanyow** [comment]
In the repeat, use `$parent` to access the outer view-model scope.

Or declare the method in a way that will preserve the `this` binding no matter how it's invoked:

```diff
export class App {
  ...  

-  matcher(item1, item2) {
+  matcher = (item1, item2) => {
    console.log(this);
    return this && this.itemUtils && this.itemUtils.itemsAreEqual(item1, item2);
  }

  ...
}
```

**Comment by zakjan** [comment]
`matcher.bind="matcher.bind($parent)"` throws `Error: Parser Error: Unexpected token ) at column 21 in [matcher.bind($parent)]`

All right, `$this` in the repeat can't be the same object as VM, but could it extend the VM?

Using an arrow function in the VM has a disadvantage that it needs to be declared before any other its usage. I'd like to keep using just one style for all methods. But it is probably the best solution for now.

**Comment by jdanyow** [comment]
oops- the parser error is a bug. I've pushed a fix so it will be fixed in the next release.
