### ISSUE TITLE
valueChanged() acts like valueWasSet()

### ISSUE THREAD

**Issue by nicolasdejong** [aurelia/binding#544]
**I'm submitting a bug report**

* **Library Version:**
gist

**Please tell us about your environment:**
* **Operating System:**
gist

* **Node Version:**
gist

* **NPM Version:**
gist

* **JSPM OR Webpack AND Version**
gist

* **Browser:**
all

* **Language:**
all

**Current behavior:**
valueChanged() is called when value is not changed. I came here expecting this only to happen when value is NaN (as it is on the 1.0 we are running -- apparently different from the gist version).

**Expected/desired behavior:**
When valueChanged(newValue, oldValue) is called, newValue should be different from oldValue.

See: https://gist.run/?id=87f66654eac57861d5eaeb5d06056d09

Then look in the console. Value is set to 123 twice. The valueChanged() is called three(!) times.

If the if(oldValue === newValue) statement is removed, the page will crash.

**Comment by EisenbergEffect** [comment]
@jdanyow Ping.
