### ISSUE TITLE
show.bind does not work in IE11 after jspm update on sceleton-typescript 1.1.2

### ISSUE THREAD

**Issue by nndevstudio** [aurelia/binding#551]
Hi,
sceleton-typescript 1.1.2 works fine after initial npm/jspm installation.
But after jspm update:
![ts-skeleton112-jspm-update](https://cloud.githubusercontent.com/assets/22050968/21261175/1bb16a92-c38a-11e6-8051-cdfdfd6b693b.png)

show.bind does not work in IE11 with error:
 
 stack: "Error: Error invoking Show. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: Object.getPrototypeOf: 'this' is not an Object
Inner Error Stack:
TypeError: Object.getPrototypeOf: 'this' is not an Object
   at get (eval code:46:7)
   at get (eval code:600:9)
   at elementContainerGet (eval code:2098:5)
   at get (eval code:86:9)
   at get (eval code:590:9)
   at elementContainerGet (eval code:2098:5)
   at invoke (eval code:451:7)
   at invoke (eval code:410:7)
   at invoke (eval code:670:9)
   at get (eval code:2043:7)
End Inner Error Stack

In users.ts we have property 
`showu:boolean= true; `
and in users.html we have  `<div show.bind = "showu">DDD</div>`

We have noticed this after update of Aurelia in our real project.

We can do something like `css="display: ${!showu ? 'none' : ''}"` now but it would be nicer to do `show.bind = "showu"`

**Comment by StrahilKazlachev** [comment]
Check this aurelia/templating-resources#267
It seems to be related to the aurelia-dependency-injection@1.2.1.

**Comment by nndevstudio** [comment]
Thank you. After downgrading aurelia-dependency-injection@1.2.0 it works in IE again.
