### ISSUE TITLE
as-element not rending bound attributes

### ISSUE THREAD

**Issue by djedi** [aurelia/binding#556]
**I'm submitting a bug report**

* **Library Version:**
1.0.6

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
5.12.0

* **NPM Version:**
3.8.6

* **JSPM OR Webpack AND Version**
JSPM 0.16.48

* **Browser:**
all 

* **Language:**
ESNext

**Current behavior:**
If I create a custom component and set `this.cls` in the constructor, I can't use that attribute in the custom componet if I render that component `as-element`

**Expected/desired behavior:**
 I would expect to use that in the custom element `as-element` as I would without the `as-element`. But it doesn't recognize `this.cls`

Plunker example:  https://plnkr.co/edit/BIhLjfyUN9I3v7comQKx?p=preview

* **What is the motivation / use case for changing the behavior?**
I need to set styles on certain  table cells used a computed property, but it is just not rendering.

**Comment by cottrellio** [comment]
I'm running into the same problem. Trying to add a class to an <li> tag that is using `as-element` attr.

**Comment by EisenbergEffect** [comment]
I think you may be confusing the scope of the element's properties. Those are only "visible" inside the view of the element, not outside it.

**Comment by djedi** [comment]
For those who may run into a similar situation I figured it out. it was a combination of using `as-element`, `@containerless`, and putting my html `<require>` statements at the bottom of my template.

actual code...

calling my data-cell element
```
                    <tbody>
                        <tr repeat.for="record of data" class="row-status" click.trigger="rowClick(record)">
                            <td as-element="data-cell"
                                repeat.for="col of columns"
                                col.bind="col"
                                record.bind="record"
                                prop.bind="record[col.key]">
                            </td>
                        </tr>
                    </tbody>
```

data-cell.js
```
import {bindable, containerless, computedFrom} from 'aurelia-framework';


@containerless
export class DataCell {
    @bindable col;
    @bindable record;
    @bindable prop;

    @computedFrom('record', 'prop')
    get cls() {
        const record = this.record;
        if (!this.col.getClass) {
            return '';
        }

        return this.col.getClass(record);
    }
}
```

data-cell.html
```
<template>
    <td if.bind="col.isVisible" data-th.bind="col.label" get-class.call="col.getClass(record)" class.bind="cls">
        <compose if.bind="col.view" view.bind="col.view" view-model.bind="col.viewModel" model.bind="{record: record}"></compose>
        <record-value if.bind="!col.view" prop.bind="record[col.key]" record.bind="record" get-value.call="col.getValue(record)"></record-value>
    </td>

    <require from="resources/data-table/record-value"></require>
</template>

```
