### ISSUE TITLE
computedFrom a Map does not work

### ISSUE THREAD

**Issue by Tarpsvo** [aurelia/binding#558]
**I'm submitting a bug report**

* **Library Version:**
1.1.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
4.X

* **NPM Version:**
3.X

* **JSPM OR Webpack AND Version**
Webpack 2 RC3

* **Browser:**
Any

* **Language:**
ESNext

**Current behavior:**
```shell
map = new Map();
@computedFrom('map')
get mapSize() { return this.map.size; } 
```

Does not work when using `.set()` on the map.

**Expected/desired behavior:**
I would've expected it to work, since I'm changing the object.

See this gist:
https://gist.run/?id=caa652ef4fbc54e16df2e853784ffa4b

**Comment by jdanyow** [comment]
That usage (observing the map/set/array for mutation) is not supported. Use `@computedFrom('map.size')` instead.
