### ISSUE TITLE
When checked.bind causes the checkbox to become disabled, change.trigger isn't called in Firefox

### ISSUE THREAD

**Issue by Mario050** [aurelia/binding#560]
**I'm submitting a bug report**

* **Library Version:**
1.1.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.2

* **Node Version:**
7.2.1

* **NPM Version:**
3.10.9

* **JSPM Version**
JSPM 0.16.29

* **Browser:**
Firefox 50.1.0 

* **Language:**
all

**Current behavior:**
When checked.bind causes the checkbox to become disabled, change.trigger isn't called in Firefox. In Chrome, IE 11, Edge and Safari it is called.

See: https://gist.run/?id=a2d46d1dd07b63e945b98bb40ec7d514

**Expected/desired behavior:**

Call change.trigger in firefox if checked.bind causes the checkbox to become disabled, like the other browsers.

**Comment by johan-v-r** [comment]
I have a similar issue which might be related with `checked.bind` not working along with `ref` & `disabled.bind`. More detail [here](http://stackoverflow.com/questions/41861010/aurelia-array-binding-with-checkbox-selection-and-element-reference-disable).

Also see examples:
- [With checked.bind](https://gist.run/?id=0c64a1602738774bb7658cf28db726ee)
- [Without checked.bind](https://gist.run/?id=670c62155647e16d8be5f8a79772ff34)

**Comment by jdanyow** [comment]
Seems to be a browser quirk.  Take a look at the console output of this gist: https://gist.run/?id=dcf92e0854a0d6658c6a0d7200269213

Chrome:
```
change... disabling
second change
```

FireFox:
```
input... disabling
second input
```

In chrome, the change event fires first, and disabling the input during the change event prevents the input event from firing.

In firefox, the input event fires first, and disabling the input during the input event prevents the change event from firing (which is the issue you're seeing).

Try disabling the input in a setTimeout or using the microtaskqueue.
