### ISSUE TITLE
Pause and restore dirty checking using page visibility API

### ISSUE THREAD

**Issue by jdanyow** [aurelia/binding#562]
*this issue originated in https://github.com/aurelia/framework/issues/386#issuecomment-202844643*

Use the [page visibility api](https://www.w3.org/TR/page-visibility/) and the window's focus and blur events to pause and restore dirty checking?

> ## Page Visibility (Second Edition)
> 
> This specification defines a means for site developers to programmatically determine the current visibility state of the page in order to develop power and CPU efficient web applications.

http://caniuse.com/#feat=pagevisibility

http://stackoverflow.com/questions/1060008/is-there-a-way-to-detect-if-a-browser-window-is-not-currently-active

**Comment by Alexander-Taran** [comment]
Should stay on the radar for mobile
Saving batteries is every developers responsibility

**Comment by Alexander-Taran** [comment]
@EisenbergEffect added to vNext candidates list.
Maybe can be closed
