### ISSUE TITLE
img usemap binding not working

### ISSUE THREAD

**Issue by pndewit** [aurelia/binding#564]
**I'm submitting a bug report**

**Please tell us about your environment:**
* **Operating System:**
OSX 10

* **JSPM OR Webpack AND Version**
webpack 2.2.0-rc.3

* **Browser:**
Chrome 55

* **Language:**
TypeScript 2.1

**Current behavior:**
The `usemap` attribute is not being added to the DOM when I use: `usemap.bind="'#something'"`. If relevant, I am using the `usemap` attribute in combination with a `map` element that has the `name` attribute set to (in this case) `something`.

**Expected/desired behavior:**
I expect to get a `usemap="#something"` attribute on my element.

**Workaround:**
If anyone is interested in a workaround. I now dynamically set the `usemap` attribute by referencing to the element using the Aurelia `ref` binding:

HTML:
```
<template>
    <img ref="image" />
</template>
```

JS:
```
public image;

someFunction() {
    this.image.setAttribute('usemap', '#something');
}
```

**Comment by jdanyow** [comment]
workaround: `<img usemap.bind="'something' & attr" ...>`

**Comment by pndewit** [comment]
@jdanyow Thanks, that workaround is even better! 👍
