### ISSUE TITLE
.call binding does not assign function reference to bindable property on <compose> element.

### ISSUE THREAD

**Issue by davismj** [aurelia/binding#566]
**I'm submitting a bug report**

* **Library Version:**
1.1.1

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
6.4.0

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
JSPM 0.16.48

* **Browser:**
Chrome

* **Language:**
ESNext

**Current behavior:**
Using `.call` binding on `<compose>` custom element does not pass the function reference to the `@bindable` property.

**Expected/desired behavior:**
In the following example, the `do` function in `compose.js` should be defined and equal to the `doIt` function in `app.js`
https://gist.run/?id=a721c2ebcefd0fa4e8c9258cd53edf2b

**Comment by StrahilKazlachev** [comment]
I was under the impression that `compose` has its own bindable properties and does not proxy to the user VM. Has proxying ever worked?

**Comment by jdanyow** [comment]
right- compose does dynamic composition and has it's own bindable properties. This kind of usage isn't supported.
