### ISSUE TITLE
@children array contains duplicate entries

### ISSUE THREAD

**Issue by Mario050** [aurelia/binding#568]
**I'm submitting a bug report**

* **Library Version:**
1.1.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.3

* **Node Version:**
7.2.1

* **NPM Version:**
3.10.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.29

* **Browser:**
all
* **Language:**
all

**Current behavior:**

When a component has a property decorated with @children and both one of the projected children and the component itself have an `if.bind`, the @children array accumulates duplicate entries when the following events occur: 
 * `if.bind` on one of the children becomes `false`.
 * `if.bind` on the component becomes `false`. 
 * `if.bind` on the child and component become `true` again. 

Now the @children array contains two entries pointing to the same child. 

See the following gist: https://gist.run/?id=bfd7218832bada43e27293094d3cf8fc

**Expected/desired behavior:**

@children array should only contain the children currently present.

**Comment by bigopon** [comment]
This has been fixed in templating. Demo at https://codesandbox.io/s/8lj0k0xln0

@EisenbergEffect can be closed.

**Comment by bigopon** [comment]
@Mario050 the bundle used in the gist ins't the latest version of Aurelia, so it still reflect the bug, but it has been fixed. Thank you for reporting this bug.
