### ISSUE TITLE
multi-select valueChanged callback function not called on changes

### ISSUE THREAD

**Issue by gerbendekker** [aurelia/binding#570]
I'm trying to get notified when the selected value has changed for a multi select.
Here a modified sample from the docs [Multiple Select Objects](http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-selects/8):
```javascript
export class App {
  products = [
    { id: 0, name: 'Motherboard' },
    { id: 1, name: 'CPU' },
    { id: 2, name: 'Memory' },
  ];

  @bindable() selectedProducts = [];

  selectedProductsChanged(newValue, oldValue) {
    console.info('selectedProductsChanged ' + newValue);
  }
}
```
```html
  <label>
    Select products:
    <select multiple value.bind="selectedProducts">
      <option repeat.for="product of products"
              model.bind="product">
        ${product.id} - ${product.name}
      </option>
    </select>
  </label>
```
**Current behavior:**
The notify isn't called and I think it's determined here:
[https://github.com/aurelia/binding/blob/master/src/select-value-observer.js#L118](https://github.com/aurelia/binding/blob/master/src/select-value-observer.js#L118)

**Expected/desired behavior:**
It would be nice to be notified of a change.

**Comment by jdanyow** [comment]
The binding system makes a distinction between property changes and collection mutation. The `selectedProducts` property never changes, it remains the same array instance (although the contents of the array change). This is why the `selectedProductsChanged` property changed handler is never called.

Try subscribing to the select element's change DOM event:  `<select ... change.delegate="selectedProductsChanged()" ... >`

**Comment by gerbendekker** [comment]
Sound logical, thanks for the explanation and pointing me into the right direction!
