### ISSUE TITLE
Binding to 'checked' doesn't get updated for radio button

### ISSUE THREAD

**Issue by nashwaan** [aurelia/binding#572]
Here is a simple test html:
```html
<input type="radio" ref="ref1" name="mygroup" checked />
<input type="radio" ref="ref2" name="mygroup" />
<input type="radio" ref="ref3" name="mygroup" />

<div>${ref1.checked}</div>
<div>${ref2.checked}</div>
<div>${ref3.checked}</div>
```

Initially I get the following on the renedered html:
◉
○
○
true
false
false

But when I click the second radio button, the rendered html becomes:
○
◉
○
**true**
true
false

You see, the first `${ref1.checked}` remains `true` instead of getting updated to `false`!
Why `${ref1.checked}` doesn't get reevaluated and updated?

**Comment by jdanyow** [comment]
the binding system is listening to the ref1 input's `change` and `input` events and will update the `${ref1.checked}` binding when one of those events fire. 

*ref1 fires neither event when you click on the ref2 or ref3 inputs so the binding system doesn't know it changed.*  We'd have to start dirty-checking this prop to make this use-case work..

Try doing something like this:

```html
<template>
  <input type="radio" name="asdf" value="red"   checked.bind="color" />
  <input type="radio" name="asdf" value="green" checked.bind="color" />
  <input type="radio" name="asdf" value="blue"  checked.bind="color" />
  
  <div>${color}</div>
</template>
```

```js
export class App {
  color = 'green';
}
```

https://gist.run/?id=4f7ba62963bcf799680837412bda740f

**Comment by nashwaan** [comment]
@jdanyow  Thanks for the clarification & the gist. This helped me a lot.
