### ISSUE TITLE
Radio with model=undefined and checked=undefined should be checked by default

### ISSUE THREAD

**Issue by zakjan** [aurelia/binding#574]
**I'm submitting a bug report**

* **Library Version:**
latest in gist

**Please tell us about your environment:**
* **Browser:**
all

* **Language:**
all

**Current behavior:**
If input type="radio" has model.bind="undefined" and checked.bind="value" where value=undefined, it is not checked.
https://gist.run/?id=5c2d55c58bb270bfab2f41026898cd23

**Expected/desired behavior:**
It should be checked by default, similar to when it is clicked.

**Comment by jdanyow** [comment]
Thanks for reporting this.

https://github.com/aurelia/binding/blob/b2d68c85d1e02775300a083746880de03990d034/src/checked-observer.js#L19
