### ISSUE TITLE
It is not possible to use values from value converters in expressions

### ISSUE THREAD

**Issue by fracz** [aurelia/binding#578]
**I'm submitting a feature request**
* **What is the expected behavior?**
It should be possible to use converted values just like any other value in expressions.
 
* **What is the motivation / use case for changing the behavior?**
Please find below some self-explanatory (I hope) examples that are possible with Angular filters. In Aurelia, all of them throw `Parser Error`.

1. `${ (myEntity.children | activeOnly).length }`
1. `${ (myEntity | isEntityActive) ? 'ACTIVE' : 'INACTIVE' }`
1. `<span if.bind="!(myEntity | isActive)"`>`
1. `${ (myEntity.title | inCurrentLanguage) || 'No title' }`

**Comment by fabioluz** [comment]
In the mean time, you could use some trickery, like:

```
<p ref="myP" is-active="${myEntity | isEntityActive}">
   ${ myP.isActive ? 'ACTIVE' : 'INACTIVE' }
</p>
```

**Comment by EisenbergEffect** [comment]
I don't see us making this change to the parser any time soon. The solution from @fabioluz (and other similar ideas) is our recommendation currently.  We've talked about adding a `let` attribute to the templating language to make this a bit easier at some point in the future.
