### ISSUE TITLE
Binding maxlength with undefined value

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/binding#579]
This problem was formerly reported as #473, got moved around a bit but was never answered.

As far as I can tell, there's currently no good way of binding an `<input>`'s `maxlength` attribute to a variable that may or may not be `undefined`. If a number is passed in, the maxlength is set and all works as expected. However, if undefined is passed in, it is interpreted as `0`, meaning nothing can be enter in the input field. The expected behaviour would be for no maxlength to be set at all in this case.

This isn't necessarily Aurelia's problem: when passing `null` or `undefined` directly into the `maxLength` DOM property, the result is the same. However, as there is currently no way to define a binding which removes the attribute entirely in case of `undefined`, it is hard to work around the problem.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-maxlength), it should be possible to set the `maxlength` attribute to a negative number to get the intended behaviour: no maximum input length. However, passing a negative number into the DOM property results in an error in most browsers: see [Mozilla Bug 536891](https://bugzilla.mozilla.org/show_bug.cgi?id=536891).

Currently the only way I see around this is manipulating the DOM directly from the ViewModel or using a rather cumbersome construction in the template:

```
<input if.bind="maxlength !== undefined"
    maxlength.bind="maxlength"
    [other attributes] />

<input if.bind="maxlength === undefined"
    [other attributes] />
```

I'd like to avoid either one and use a more elegant solution. Is there any way around this?

**Comment by RomkeVdMeulen** [comment]
On further examination of Mozilla Bug 536891 I've found that this should work:

```js
inputElement.setAttribute("maxLength", -1);
```

Verified this as giving the epexected behaviour in Chrome 55 and FF 51.

Would it be possible to use `setAttribute` in [SetterObserver](https://github.com/aurelia/binding/blob/1d6e826dbbc401ca21ad0deaf7acca498cd71c8b/src/property-observation.js#L50)?

**Comment by jdanyow** [comment]
You can instruct the binding system to use `getAttribute`/`setAttribute` instead of assigning the dom property with the `attr` binding behavior.

```html
<input maxlength.bind="-1 & attr">
```

https://gist.run/?id=654e24398c579d2b40bc443885c8a8c0

**Comment by RomkeVdMeulen** [comment]
Nice! Thanks for pointing that out.
