### ISSUE TITLE
Question: How to programmatically add binding behaviours to view model

### ISSUE THREAD

**Issue by anthonyborell** [aurelia/binding#583]
I'm submitting a question.

**Library Version:**
0.26.1

**Operating System:**
Windows 10

**Node Version:**
6.10.0

**NPM Version:**
3.10.8

**Browser:**
all

**Language:**
all

I have a created custom element which is going to be used multiple times, on one occasion the custom element's click event needs to be throttled by 1 second. How would I go about doing this outside of the view? 

Can't seem to find any documentation. Everything I've read says I'd need to add ` & throttle:1000` to the custom element's `click.delegate` attribute, but obviously I want this to be dynamic and set via the view-model.

Thanks!

**Comment by EisenbergEffect** [comment]
You can always write a simple throttle function in JS. Please ask questions on Gitter or SO.

**Comment by anthonyborell** [comment]
@EisenbergEffect Fair enough for closing, but was just hoping that it would be exposed in your API/documentation. Would rather do it the aurelia way, considering you've already written it.
