### ISSUE TITLE
<select> construct doesn't work in IE10 

### ISSUE THREAD

**Issue by nashwaan** [aurelia/binding#584]
**I'm submitting a bug report**

* **Library Version:**
2.1.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.5.0

* **NPM Version:**
4.1.2

* **JSPM OR Webpack AND Version**
webpack 2.2.1

* **Browser:**
IE 10 and below **only**

* **Language:**
ESNext

**Current behavior:**
`<select>` and `<option>` construct doen't work in IE 10.
Browser console shows this error: `ERROR [app-router] TypeError: Object doesn't support this action`

**Expected/desired behavior:**
`<select>` and `<option>` construct should work in IE 10.

**Reproduction of the case**
(Because I don't know how to create any gist example that can work on IE, I am showing here the minimal steps to reproduce it based on [super-minimal-aurelia repo](nathanchase/super-minimal-aurelia)).

1) Download and `npm install` [super-minimal-aurelia repo](nathanchase/super-minimal-aurelia) which has minimal setup that works on all browsers including IE 11 - 9.

2) Make the following simple changes to `page-hello` (based on 'Binding: Selects' in Aurelia docs by @jdanyow)

`page-hello.js`:

```js
export class PageHelloViewModel {
    products = ['Motherboard', 'CPU', 'Memory'];
    selectedProduct = '';
}
```

`page-hello.html`:
```html
<template>
  Select product:<br/>
  <select value.bind="selectedProduct">
    <option repeat.for="product of products" value.bind="product">${product}</option>
  </select>
  Selected product: ${selectedProduct}
</template>
```

This thing works for all browsers except for IE10-9.
The error in the console is obscure:
`ERROR [app-router] TypeError: Object doesn't support this action`

Any idea why `<select>` construct fails in IE10?

-------
By the way, if I use radio buttons construct, it works in IE 11-9:
```html
<template>
  <label repeat.for="product of products">
    <input type="radio" name="group1" value.bind="product" checked.bind="selectedProduct">
    ${product}
  </label>
  Selected product: ${selectedProduct}
</template>
```

**Comment by Gheoan** [comment]
Similar issue: https://github.com/aurelia/framework/issues/753. Is Mutation Observer polyfilled?

**Comment by nashwaan** [comment]
@Gheoan Yes, Mutation Observer is polyfilled.
If you download and `npm install` [super-minimal-aurelia](https://github.com/aurelia/binding/issues/nathanchase/super-minimal-aurelia), you will get everything working for all browsers including IE 11 - 9. As I mentioned in my issue, there seems to be an issue with `<select>` binding. There is no issue if I use `<input type="radio">` for achieving similar logic.

**Comment by jdanyow** [comment]
what's the call stack for the error

**Comment by nashwaan** [comment]
Sorry, I don't know how to get call stack for the error or any error in IE. In fact, I wish I could setup a debugger properly as this would have saved lots of my time.

Did you try to reproduce the error at your end?

**Comment by nashwaan** [comment]
Hi @jdanyow,

Sorry to bother you, but did you manage to reproduce this issue? Is this a bug?

**Comment by Gheoan** [comment]
I managed to reproduce this and fixed it by adding a polyfill for `Mutation Observer`.

**Comment by nashwaan** [comment]
Hi @Gheoan ,

Can you explain how did you polyfill `MutationObserver` exactly? The documentation in [Aurelia Hub about polyfilling MutationObserver](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/app-configuration-and-startup/3) seems to be outdated.

Did you get the polyfill from [webcomponentsjs](https://github.com/webcomponents/webcomponentsjs)? If so, then how did you `import 'MutationObserver';` exactly?

**Comment by Gheoan** [comment]
I add the following to `index.html`:
```html
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=MutationObserver"></script>
```

You could also use https://github.com/megawac/MutationObserver.js.

**Comment by nashwaan** [comment]
Yes, this has worked!

I installed MutationObserver:
```
npm install --save mutationobserver-shim
```

and added this line to `ie9-polyfill.js`:
```js
import 'mutationobserver-shim/MutationObserver'; // IE10 MutationObserver polyfill
import 'raf/polyfill'; // IE9 requestAnimationFrame polyfill
```

And now `<select>` construct works as expected in IE10-9.

Thanks @Gheoan .
