### ISSUE TITLE
Binding to undefined property using `.bind` should not result in `attr="undefined"`

### ISSUE THREAD

**Issue by thomas-darling** [aurelia/binding#589]
**I'm submitting a bug report**

* **Library Version:**
aurelia-binding@1.2.1
aurelia-templating-binding@1.3.0

* **Browser:**
all

**Current behavior:**

Doing this in a template, where `url` is a view model property with the value `undefined`.
```html
<a href.bind="url">
```
Produces this in the DOM:
```html
<a href.bind="url" href="undefined">
```

**Expected/desired behavior:**

* **What is the expected behavior?**

  When the value of the property is `undefined` or `null`, I would not expect the `href` attribute to be present in the DOM.

  In this case, it's a problem, as there's a difference between a link with and without an `href` - one is clickable, the other is not. In this case, I end up with a link to `http://example.com/undefined`, where
I expected the link to be non-clickable.

  Another common case where this is a problem is the `<img>` element, where `src.bind` results in `src="undefined"`, thus triggering an HTTP request to download an image named `undefined`.

**Comment by jdanyow** [comment]
is there a scenario where you'd want a data-bound image or anchor element to be present in the DOM when the url the element is bound to is null or undefined?

**Comment by thomas-darling** [comment]
Yeah, there is, actually :-)

Normally we could work around it with an `if.bind`, but in my particular case that won't work.

We have a `card` custom element, which has a template along the lines of this:
```html
<template>
    <a href.bind="href">
        <slot></slot>
    </a>
</template>
```
Now, this `card` can be used with or without an href, depending on whether we want it to be a link or not. When no href is set, we don't want that `href` attribute on the anchor, as it makes the browser think is is a link, meaning that users can e.g. right-click and open in a new tab - which won't do what they expect.

However, in this case we can't put an `if.bind` on the anchor, as that won't work with the `slot` inside of it.
Only way to make it work, is to manually observe the `href` property and add/remove the the attribute as needed. That workaround does work, but its cumbersome, and I think the proposed behavior is closer to what would be expected - i.e. _if we don't know what value an attribute should have, then it shouldn't be there_. That behavior would also make the very common use cases with e.g. images safe by default - i.e. no more requests for images named `undefined`.

Makes sense?

**Comment by jdanyow** [comment]
Thanks for the additional info. I think I understand your position. I don't think it's semantically correct to use an anchor without an href. You'd at least need to set it to `#` wouldn't you? Otherwise button would be the appropriate element to use.

In the image scenario, the `if` template controller would solve the problem. The image element shouldn't be present without a src.

That said, you could still make this work the way you want want by creating a binding behavior.

```js
export class UrlAttrBindingBehavior {
  bind(binding, source) {
    binding.targetObserver = new UrlAttributeObserver(binding.target, binding.targetProperty);
  }

  unbind(binding, source) {}
}

class UrlAttributeObserver {
  constructor(element, propertyName) {
    this.element = element;
    this.propertyName = propertyName;
  }

  getValue() {
    return this.element.getAttribute(this.propertyName);
  }

  setValue(newValue) {
    if (newValue === null || newValue === undefined || newValue === '') {
      this.element.removeAttribute(this.propertyName);
    }
    return this.element.setAttribute(this.propertyName, newValue);
  }

  subscribe() {
    throw new Error(`Observation of a "${this.element.nodeName}" element\'s "${this.propertyName}" property is not supported.`);
  }
}
```

```html
<a href.bind="mightBeNull & urlAttr">Click Me</a>
```

Thoughts?

**Comment by gheoan** [comment]
Related: https://github.com/aurelia/templating/issues/76, https://github.com/aurelia/framework/issues/599.

**Comment by thomas-darling** [comment]
Actually, an anchor without an href is valid, as of HTML5 ;-)
https://html.spec.whatwg.org/multipage/semantics.html#the-a-element

You're absolutely right that we could generalize this into a binding behavior - would definitely make it less cumbersome to deal with. That said though, I'd still argue the proposed behavior of removing the attribute is a much better default - I don't think there's _any_ scenario where you would ever want the values `null` or `undefined` to be present in a DOM attribute.

Now, the underlying property value is a different story. I fully agree that `.bind` should never attempt to coerce the actual value in any way, as suggested in https://github.com/aurelia/framework/issues/599, but that's not what this is about - this is only a question of how the property value is reflected to the DOM attribute.

This is actually kinda related to https://github.com/aurelia/binding/issues/347#issuecomment-242106920, which is about boolean properties and how they are reflected to the DOM. I'd argue, that while doing a `toString()` and using that as the attribute value is generally the right approach, some special cases, specifically the values `null`, `undefined`, `true` and `false`, need to be handled differently when reflecting the value to the attribute in the DOM.

In the vast majority of cases, things "just works" when working with Aurelia, but this is one case where we _constantly_ have to work our way around the default behavior, and constantly have to track down where e.g. requests for images named 'undefined' come from - and let me tell you, that can be _really_ hard to figure out, especially if it was only `undefined` for a few milliseconds, before the URL became known. It's just a lot of friction that could be avoided by simply changing the default behavior.

I really think this is worth considering...
Can you think of any arguments for _not_ going with the behavior proposed here? :-)

**Comment by gheoan** [comment]
If https://github.com/aurelia/templating/issues/76#issue-76535290 would be supported writing `<a href.bind="url" href.if="url">` would result in `<a href.bind="url">` when `url` is `undefined`, `null` or empty string.

**Comment by jdanyow** [comment]
@EisenbergEffect - thoughts on changing the behavior for a.href and img.src? Breaking change but low impact?

**Comment by EisenbergEffect** [comment]
@jdanyow This seems like a harmless change and one that would result in a more correct behavior. What do you think? How difficult would it be to address this?

**Comment by Eagle94T** [comment]
Since this issue is still open, I wanted to give another scenario.
I have a form where a Date-Field can be disabled. In this case the Input-Field is not validated but since it's value is bind to an model with a date-format-converter, the value is saved as `undefined`, which is for me the expectet behaviour since the field is empty.
If this form is now reopened with the values from the model (where datefield-value is `undefined`), my date-format-converter is trying to convert the value, and ends up in: `value = Invalid Date {}` which I need to cache in my converter.

It would be nice if it could be possible to bind a value and value-converter normal to an input field, and also have a `value.if="date"` so the converter is just used, when there will be a value.

At the moment my input-field looks like this:
`<input value.bind="date | dateFormat: 'DD.MM.YYYY'" disabled.bind="isDisabled">`

Maybe it would be a better approach to just disable converters on disabled input field. But then, you can't use the field in case you want to show only non-editable information to the user.

**Comment by bigopon** [comment]
@EisenbergEffect This one is an easy fix, we currently have this direction of binding:

if it's something related to input, use special observer via `this.getObserver`
if it's a known svg attribute we want to intercept, use `dataAttributeAccessor`
the rest just simple set/get on the dom element itself.

Proposal fix:

Check if property is special via `if (propertyName in obj)`, if true, we use simple get / set
other wise, we intercept it by converting undefined to null, which will not cause `href=undefined`.

[Gist with full fix](https://gist.run/?id=1cc68d08b9d2c966911b63f79853ac6c)

You can see even though binding to undefined property, anchor `href` and img `url` are ok.

I also opened a pull

**Comment by nashwaan** [comment]
@jdanyow , Thank you for providing another new complete code example about custom binding behavior (which is really scarce to find). I noticed this time, you use `binding.targetObserver`. Most of the other examples I found is based on `binding.updateSource` or `binding.updateTarget`.

I tried your code and I believe `return` is missing from this line of code to make it work correctly:
```js
this.element.removeAttribute(this.propertyName);
```

However, both `this.element.removeAttribute()` and `this.element.setAttribute` return `undefined`. So, `setValue()` should not return anything.

The code should probably look like this:
```js
class RemovableObserver {
    constructor(element, propertyName) {
        this.element = element;
        this.propertyName = propertyName;
    }
    getValue() {
        return this.element.getAttribute(this.propertyName);
    }
    setValue(newValue) {
        if (newValue === null || newValue === undefined || newValue === false || newValue === '') {
            this.element.removeAttribute(this.propertyName);
        } else {
            this.element.setAttribute(this.propertyName, newValue);
        }
    }
    subscribe() {
        throw new Error(`Observation of a "${this.element.nodeName}" element\'s "${this.propertyName}" property is not supported.`);
    }
}
```

And it can be used like you showed: `<a href.bind="mightBeNull & removable">Click Me</a>`
