### ISSUE TITLE
Rendering too slow on model change

### ISSUE THREAD

**Issue by AxXxel001** [aurelia/binding#591]
**I'm submitting a bug report**

* **Library Version:**
aurelia-api@3.1.1
aurelia-framework@1.1.2

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.6

* **Node Version:**
7.8.0

* **NPM Version:**
4.2.0

* **Browser:**
Chrome Version 57.0.2987.133 (64-bit)

* **Language:**
ES6

**The situation:**
In my app I periodically fetch JSON data from my server and store this object as an attribute in the fetching class (I call it DynamicData). This is just a class to fetch data and grant access to it.
In my viewmodel I inject the DynamicData object and store it as attribute so that the view template can access the data.
The data contains arrays ob objects which I want to render as rows in a table, so I split the HTML code in templates which I then compose together.
The goal is to have kind of a real time overview about the fetched data in my view.

**Current behavior:**
When new data is fetched and the view is rerendered, there is strong flickering in the rows. They disappear for a very short time and get repainted. Anyway this is... pretty ugly. Sometimes (maybe every 10 seconds) the process works just fine and no flickering appears.

**Expected/desired behavior:**
The rendering process should work fine.

**Comment by EisenbergEffect** [comment]
We'll need more information to help you.

**Comment by AxXxel001** [comment]
Hi, thanks for the quick reply. I found a solution, I just don't understand why it works better. When I got the flickering on screen I worked with <compose> to generate the page based on templates. Now I replaced the <compose> tag with custom elements and it works fine.
Is this maybe a problem you are familiar with? If not I can give you an example more spicific.

Thank you

**Comment by StrahilKazlachev** [comment]
Could you provide the example?

**Comment by jdanyow** [comment]
I'd like to see this too- if you have a chance to provide a quick reproduction we can look into it. Here's a gist you can use: https://gist.run/?id=7542e061bc940cde506b 

One of the scenarios we work hard to optimize is grid repaints where the backing data is completely replaced. This is essentially the "dbmonster" scenario: http://mathieuancelin.github.io/js-repaint-perfs/

**Comment by jdanyow** [comment]
no response, closing
