### ISSUE TITLE
@observable and @bindable properties are not serialized with JSON.stringify

### ISSUE THREAD

**Issue by geleto** [aurelia/binding#592]
aurelia-binding 1.2.1
Windows 10
Chrome 58.0.3029.81

@observable and @bindable properties are not serialized with JSON.stringify
Observe this gist:
https://gist.run/?id=8dc8b100453b6da12072b8c33683a896&sha=58f369d752ca4d19ff7a7f06ff3292e6c45010e1

The output is:
`{"p3":"Property 3"}`
and the expected output is:
`{"p1":"Property 1","p2":"Property 2","p3":"Property 3"}`

Strangely in my TypeScript app which uses the latest aurelia-binding, @bindable works properly, while @observable still does not and the output is:
`{"p2":"Property 2","p3":"Property 3"}`

This worked properly in previous versions

**Comment by gheoan** [comment]
Seems to be a problem with the transpiler not with the decorators. For example when using Aurelia to decorate the class the output is as expected: https://gist.run/?id=8dc8b100453b6da12072b8c33683a896.
