### ISSUE TITLE
String interpolation in <style> element no longer works.

### ISSUE THREAD

**Issue by DarienFord** [aurelia/binding#593]
**I'm submitting a bug report**

* **Library Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.3.0

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
Aurelia CLI

* **Browser:**
Chrome 

* **Language:**
ESNext

**Current behavior:**
When including string interpolation in a <style> tag, the string is not translated.
It did work in a prior version (unknown version)

**Expected/desired behavior:**
The expected behavior is that the string interpolation correctly translates the value.

https://gist.run/?id=c2df443d83a08cc677df966e7e322b28

This gist is an example, but I believe is not using 1.2.1 since it works, but when trying the same exact thing locally by starting a new project with au new, it does not.

* **What is the motivation / use case for changing the behavior?**
This has broken an app I have which I would like to update

**Comment by DarienFord** [comment]
@jdanyow just showed me that this is not an issue with 1.2.1.
That does not change the issue though that it does not work locally in a brand new environment using `au new` for me.

**Comment by jdanyow** [comment]
@EisenbergEffect he's saying it's an issue with `au new`

**Comment by EisenbergEffect** [comment]
@jdanyow Thanks! For some reason that went right past me.
@DarienFord Try turning off the HTML minification. I bet that's the problem.

**Comment by DarienFord** [comment]
@EisenbergEffect unfortunately it happens with the dev environment with minification disabled.
`"options": {
      "minify": "stage & prod",
      "sourcemaps": "dev & stage"
    },`

**Comment by EisenbergEffect** [comment]
@JeroenVinke Any ideas what in the CLI might be related to this?

**Comment by JeroenVinke** [comment]
I believe it's related to https://github.com/aurelia/cli/issues/619. @EisenbergEffect what do you think about this issue? The same problem has been reported to aurelia-bundler: https://github.com/aurelia/bundler/issues/159

**Comment by EisenbergEffect** [comment]
@JeroenVinke I thought that might be the case but @DarienFord is saying that he's having this error without minification. I wonder if the html minification is happening no matter what and not keying on configuration.

**Comment by JeroenVinke** [comment]
Yep, if you choose for html minification in `au new` then it will always minify HTML.: https://github.com/aurelia/cli/blob/master/lib/resources/tasks/process-markup-minify-min.js#L10-L15,  This is something we could change. Adding [this line](https://github.com/JeroenVinke/cli/commit/860bedee01dee66a183c54b200f831099fa30692#diff-67b223207feed0a4fe6155b8c200651dR23) will instruct the minifier to ignore interpolation expressions and should be the fix for @DarienFord's problem.

**Comment by thomas-darling** [comment]
@JeroenVinke, @EisenbergEffect That won't work - please see aurelia/bundler#163

**Comment by jdanyow** [comment]
closing this because it's tracked in aurelia/bundler#163
