### ISSUE TITLE
Assigning `undefined`  to @observable field doesn't propagate through bindings in some cases

### ISSUE THREAD

**Issue by gronostajo** [aurelia/binding#594]
**I'm submitting a bug report**

* **Library Version:**
aurelia-binding 1.2.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
5.7.1

* **NPM Version:**
3.6.0

* **JSPM OR Webpack AND Version**
JSPM 0.16.48

* **Browser:**
Chrome 58, Firefox 53, possibly more

* **Language:**
TypeScript 2.1, ESNext

**Current behavior + expected behavior:**
MSVE with description: https://gist.run/?id=2cac8c024cac4c9b921bcbe7b9e0b115

**Comment by bigopon** [comment]
@EisenbergEffect @jdanyow Observable `valueChanged` is executed immediately when setting the value, hence the bug (or desired behavior ?).

**Comment by Alexander-Taran** [comment]
looks stale @bigopon
