### ISSUE TITLE
Unable to two-way bind via custom element

### ISSUE THREAD

**Issue by lyptt** [aurelia/binding#596]
**I'm submitting a bug report**

* **Library Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
webpack 2.2.0

* **Browser:**
IE 10 / IE 11

* **Language:**
ESNext

**Current behavior:**
I've created a basic custom element with an @bindable property:
```javascript
export class MyElement {
  @bindable someVariable = []
}
```

At some point in time, the array gets updated not by direct user interaction. The arrays' contents change successfully and the DOM internal to the element successfully updates to represent the new data.

The issue is, if I then try to bind this someVariable property in a parent ViewModel, the ViewModel binding doesn't work whatsoever - no data gets into the element, and no data gets out.

I'm attempting to bind like so:

```html
<my-element someVariable.two-way="institutionTypes"></my-element>
```

**Expected/desired behavior:**

**Comment by swalters** [comment]
someVariable.two-way should be some-variable.two-way

**Comment by lyptt** [comment]
Hi @swalters, yeah this issue was posted in error. I found my mistake but it looks like Github went and submitted it anyway. Sorry to waste your time!
