### ISSUE TITLE
DefaultBinding  BindingMode.OneTime is not working correctly

### ISSUE THREAD

**Issue by ne0guille** [aurelia/binding#598]
**I'm submitting a bug report**
* **Operating System:** Windows 7 |10
* **Node Version:** 6.9.0 | 8.0.0
* **NPM Version:** 3.10.10 | 4.0.0
* **JSPM OR Webpack AND Version** webpack 2.3.1
* **Browser:** all
* **Language:** JS || TypeScript 2.3.2

**Current behavior:**

@bindable({ defaultBindingMode: bindingMode.oneTime }) text

if i set the bindingMode to onetime, and use **text.bind** in the HTML, it doesnt work as a onetime binding, but if i use **text.one-time** in the HTML it does work as expected

Here is the gist, if you change the text.bind to text.one-time in the HTML it work as expected.

https://gist.run/?id=5f7b001f9ffefe47d0f06c71a71474e9
**Expected/desired behavior:**

Setting the bindindable defaultBindingMode: bindingMode.oneTime on the VM and using the property.bind in the View should work.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you take a look into this?

**Comment by bigopon** [comment]
@EisenbergEffect @jdanyow 

This bug is caused by [line 69 in syntax interpreter](https://github.com/aurelia/templating-binding/blob/master/src/syntax-interpreter.js#L69)

```js
info.defaultBindingMode || this.determineDefaultBindingMode(element, info.attrName, context),
```

The cause is `info.defaultBindingMode = 0` when specified inside `bindable`, thus will be resolved to `bindingMode.oneWay`

There are 3 ways to fix this though:

```js
info.defaultBindingMode !== null && info.defaultBindingMode !== void 0 ? info.defaultBindingMode : this.determineDefaultBindingMode(element, info.attrName, context),

// or
typeof info.defaultBindingMode === 'number' ? info.defaultBindingMode || determine(...)

// or increase number in bindingMode in binding by 1
bindingMode.oneTime = 1
bindingMode.oneWay = 2 ...
```
