### ISSUE TITLE
value.bind issue when using optgroup in a a select

### ISSUE THREAD

**Issue by Aaike** [aurelia/binding#60]
I am having issues with binding a value to the select when using optgroups
```
<select value.bind="selectedTheme">
    <optgroup repeat.for="theme of themes" label.bind="theme.name" >
        <option repeat.for="skin of theme.skins" value.bind="skin">
          ${skin}
        </option>
    </optgroup>
  </select>
```

I am trying to load the array from a json from the backend.
So in the VM the themes property is null at first . then i do a http.get , and only then is the array assigned to the themes , when i do that the items appear in the select just fine , but the current selected item won't work.

It does work if i assign an array in the view model itself without loading it from the server.

tested with version 0.4.1

**Comment by jdanyow** [comment]
thanks @Aaike - will take a look asap

**Comment by Aaike** [comment]
I might have another issue related to this.
When using optgroups the value of the options are not necessarily unique.
So i would need interpolation in the value of the option, something like 
`value.bind="${theme.name}-${skin}"` , but interpolation does not work with using bind.
if i try `value="${theme.name}-${skin}` , then i cannot access the skin property because it's not inside the for loop yet.

**Comment by Aaike** [comment]
this actually works:
```
<template repeat.for="skin of theme.skins">
        <option value="${theme.name}-${skin}">
          ${$parent.theme.name}-${skin}
        </option>
</template>
```
but not the best solution i suppose ;)

**Comment by jdanyow** [comment]
how about this:

``` html
<select value.bind="selectedTheme">
  <optgroup repeat.for="theme of themes" label.bind="theme.name" >
    <option repeat.for="skin of theme.skins" value.bind="$parent.name + '-' + skin">
      ${skin}
    </option>
  </optgroup>
</select>
```

**Comment by Aaike** [comment]
that works great :smile: scratch additional issue :wink:

**Comment by Aaike** [comment]
oops, didnt mean to close

**Comment by jdanyow** [comment]
@Aaike any chance you could throw together a fork of the skelly that reproduces this issue?

Just fixed https://github.com/aurelia/framework/issues/83 might be related.

**Comment by jdanyow** [comment]
@Aaike provided a [plnkr](http://plnkr.co/edit/rw3WII1XlB8ZaWQsH00q?p=preview)- thanks @Aaike !

description:

>it doesnt set the initial selectedTheme in that example

**Comment by jdanyow** [comment]
@Aaike I did some digging, the select element binding works if I copy the markup in `select-theme.html` and paste it in `app.html`.

The problem seems to be specific to behavior-property binding.  The framework is not calling `targetProperty.setValue` (line 90 below) which means the target property (a `SelectValueObserver` instance) has no way of knowing which option to select initially.

https://github.com/aurelia/binding/blob/master/src/binding-expression.js#L68
![debug](http://i.imgur.com/2bqmdH7.png)

I'll do some more digging...

**Comment by jdanyow** [comment]
figured this out- the issue was the view model's selectedTheme value was never assigned to the custom element's selectedTheme property because the wrong attribute name was used in the markup.

this:

``` html
<select-theme selectedTheme.bind="selectedTheme" themes.bind="themes"></select-theme>
```

should be:

``` html
<select-theme selected-theme.bind="selectedTheme" themes.bind="themes"></select-theme>
```

**Comment by Aaike** [comment]
Thank you for looking into this @jdanyow , glad it turned out to be not a bug ;)
