### ISSUE TITLE
Update typescript definition file

### ISSUE THREAD

**Issue by tdamir** [aurelia/binding#601]
**I'm submitting a bug report**

* **Library Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.1

* **NPM Version:**
4.5.0

* **Browser:**
all

* **Language:**
TypeScript 2.4.1

**Current behavior:**
Typescript definition file is not in sync with the code (some missing types: CallScope, Listener).

**Comment by MaximBalaganskiy** [comment]
`bindingMode` is also outdated

**Comment by Alexander-Taran** [comment]
Would you like to provide a pull request for it @tdamir ?
Does one actually need those types?

**Comment by Alexander-Taran** [comment]
Maybe can be closed

**Comment by Alexander-Taran** [comment]
@tdamir there is tooling you are right. And the build process for js based libs of aurelia uses that tooling.
It's that there got to be annotations and classes / properties should be part of public API surface to get to be part of d.ts

That takes time to write. Like everything else. And time is a precious resource shared between tasks like this and others. Like closing bugs and implementing features.
If it is not obvious, this one is really low priority. As you are the only one who wanted it. 
If the team would find this useful, I'm sure you PR will come through.
It might be that team will not consider documenting this API then your PR would go to waste.

**Comment by Alexander-Taran** [comment]
@tdamir you are right it is a manual labor for this specific repo.
So it won't be the case of just adding those comments
like in the router for example
https://github.com/aurelia/router/blob/master/src/router.js

@jdanyow & @EisenbergEffect is it feasible to change the building of this one to build d.ts from annotations or it's not worth the time?

**Comment by tdamir** [comment]
@Alexander-Taran I just replaced aurelia-binding/tasks/build.js with the one from router project and was able to generate some sort of d.ts with errors and without comments. I suppose the next step would be to annotate the code and hopefully errors will disappear.

**Comment by Alexander-Taran** [comment]
@tdamir feel free to play around while we wait an answer from main contributors to the repo

**Comment by EisenbergEffect** [comment]
Some time back we made the move to have a hand-authored d.ts file for the binding repo. I can't remember the details around that. At the time there were some special reasons. @jdanyow may be able to comment. In the future, we're going to move the entire binding engine to TypeScript, which will form the single truth source for type definitions.

I'm going to close this issue in favor of issues/PRs to address any specific issues with the current d.ts file.
