### ISSUE TITLE
toView binding not working after NativeScript v3.0 upgrade

### ISSUE THREAD

**Issue by nudiref** [aurelia/binding#603]
**I'm submitting a bug report**

**Please tell us about your environment:**
* **Operating System:**
Windows [7]

* **Node Version:**
6.9.1

* **NPM Version:**
3.10.8

**Current behavior:**
i have a valueconverter, using toView. this is then defined as an applicationresource. 

before NativeScript v3.0, code for all this was like:

var view = require("ui/core/view");

var listOptionsConverter = {
    toView: function (value, options) {
        //custom code            
    }
};

appModule.resources["listOptionsConverter"] = listOptionsConverter;

and when called in a control during binding, it produced the desired results.

with NativeScript v3.0 upgrades, both valueconverter and application resources were changed. currently, the code above does not work. when the control using listOptionsConverter is loaded, following error is generated:

JS: Cannot find function or filter: listOptionsConverter

and the control does not work properly.

**Comment by EisenbergEffect** [comment]
Do you have the correct framework? I'm not entirely sure what you are talking about here.

**Comment by nudiref** [comment]
all my components seems to be up to date

nativescript 3.1.2
tns-core-modules 3.1.0
tns-android 3.1.0
npm 3.10.8
node 6.9.1

let me ask a more specific question. in "NativeScript v3.0 Breaking Changes" page (https://github.com/NativeScript/NativeScript/blob/v3.0.0/Modules30Changes.md) it says: 

application.resources was removed, use get/set methods:

    application.getResources(): any
    application.setResources(res: any)

How do i call setResources method? more specifically, how does the following line that i had previously change:

appModule.resources["listOptionsConverter"] = listOptionsConverter;

where listOptionsConverter is:

var listOptionsConverter = {
toView: function (value, options) {
//custom code
}
};

**Comment by EisenbergEffect** [comment]
Why are you asking this here? What does it have to do with Aurelia?
