### ISSUE TITLE
[Proposal] Adjust `EventManager` and `Listener` classes

### ISSUE THREAD

**Issue by bigopon** [aurelia/binding#604]
**I'm submitting a proposal**

* **Library Version:**
1.2.1

**Current behavior:**
Whenever Listener `bind` is called, it creates a new function `event => this.callSource(event)`, which will be use as `callback` inside `DefaultEventStrategy`.

This `callback` is then assigned to either `delegatedCallbacks` or `capturedCallbacks` properties on the element listening to the event. The disadvantage of this approach is the higher memory allocation for creating lambda in `Listener`, and only one listener allowed per event type per element. While the memory maybe negligible, the latter disadvantage sometimes makes it hard to consume an element. 

For example:

```html
<!-- my-comp.html -->
<template bindable="message" click.delegate="say(message)">
  <!-- ... -->
</template>

<!-- my-comp-consumer.html -->
<template>
  <require from="./my-comp.html" ></require>
  <my-comp message="hello" click.delegate="doExtraWorkWhenClick(someReference)"></my-comp>
  <!-- ... -->
</template>
```

We will either lose `say(message)` or `doExtraWorkWhenClick(someReference)` due to the current way of how event is registered on an element.

# **Proposal**

Lets start with `EventManager` `addEventListener` method:

**CURRENT**
```js
addEventListener(target, targetEvent, callback, delegate)
```

**PROPOSAL**
```js
// Could be named `addListener` to avoid breaking change ?
addEventListener(target, targetEvent, listener /* instance of class listener */, delegate)
```

Changes required in `Listener` class: **NOT breaking (requires test changes)**

```js
  bind(source) {
    if (this.isBound) {
      if (this.source === source) {
        return;
      }
      this.unbind();
    }
    this.isBound = true;
    this.source = source;

    if (this.sourceExpression.bind) {
      this.sourceExpression.bind(this, source, this.lookupFunctions);
    }
    // this._disposeListener = this.eventManager.addEventListener(
    //  this.target,
    //  this.targetEvent,
    //  event => this.callSource(event),
    //  this.delegationStrategy);

    this._disposeListener = this.eventManager.addListener(
      this.target,
      this.targetEvent,
      this,
      this.delegationStrategy
    );
  }
  
  // new extra class method to handle event, leveraging EventTargetInterface
  // This help avoid creating lambda inside each listener (Great win, in my pov for memory)
  handleEvent(event) {
    this.callSource(event);
  }
```

Changes required in `DefaultEventStrategy` **(Breaking, need to duplicate to avoid)**

```js
  // old signature:
  // subscribe(target, targetEvent, callback, strategy) {
  
  // new signature
  subscribe(target, targetEvent, listener, strategy) {
    let delegatedHandlers;
    let capturedHandlers;
    let handlerEntry;

    if (strategy === delegationStrategy.bubbling) {
      delegatedHandlers = this.delegatedHandlers;
      handlerEntry = delegatedHandlers[targetEvent] || (delegatedHandlers[targetEvent] = new DelegateHandlerEntry(targetEvent));
      let delegatedCallbacks = target.delegatedCallbacks || (target.delegatedCallbacks = {});

      handlerEntry.increment();
      
      // We remove the following line, as it restrict only one listener for 1 event.
      // delegatedCallbacks[targetEvent] = callback;
      
      // Instead, we use an array      
      delegatedCallbacks[targetEvent] = delegatedCallbacks[targetEvent] || (delegatedCallbacks[targetEvent] = []);

      // We replace the following implementation 
      return function() {
        handlerEntry.decrement();
        delegatedCallbacks[targetEvent] = null;
      };

      // By
      return function() {
        handlerEntry.decrement();
        var idx = delegatedCallbacks[targetEvent].indexOf(listener);
        if (idx !== -1) {
          delegatedCallbacks[targetEvent].splice(idx, 1);
        }
      };
    }
    if (strategy === delegationStrategy.capturing) {
      // Similar to bubbling delegation strategy ...
    }

    target.addEventListener(targetEvent, listener, false);

    return function() {
      target.removeEventListener(targetEvent, listener);
    };
  }
```

And finally, changes required in `handleDelegatedEvent`: **(Breaking, need to duplicate to avoid)**

```js
function handleDelegatedEvent(event) {
  let interceptInstalled = false;
  event.propagationStopped = false;
  let target = findOriginalEventTarget(event);

  while (target && !event.propagationStopped) {
    if (target.delegatedCallbacks) {
      // we replace following implementation
      // let callback = target.delegatedCallbacks[event.type];
      // if (callback) {
      //  if (!interceptInstalled) {
      //    interceptStopPropagation(event);
      //    interceptInstalled = true;
      //  }
      //  callback(event);
      // }

      // With following one
      let listeners = target.delegatedCallbacks[event.type];
      if (listeners) {
        for (let i = 0, ii = listeners.length; ii > i; ++i) {
          let listener = listeners[i];
          if (!interceptInstalled) {
            interceptStopPropagation(event);
            interceptInstalled = true;
          }
          listener.handleEvent(event);
        }
      }
    }

    target = target.parentNode;
  }
}
```

**Summary:**

* Pros: Less memory consumption, allow multiple listeners for each event type
* Cons: May introduce breaking change

cc @EisenbergEffect @jdanyow

**Comment by EisenbergEffect** [comment]
Please no breaking changes at this point. Can we find a way to handle this in a backwards compatible way? @jdanyow Can you review these ideas?

**Comment by bigopon** [comment]
The breaking change can be avoid if we

* Add new method to `EventManager`: `addListener`
* Dupplicate the code of `DefaultEventStrategy`, `handleDelegatedEvent` and `handleCapturedEvent`, which consist around 170 LOC in total.

**Comment by bigopon** [comment]
@EisenbergEffect I have updated some part to show which requires breaking changes, which doesn't in the proposal.

**Comment by bigopon** [comment]
@EisenbergEffect @jdanyow I have prepared a [draft implementation at this gist](https://gist.run/?id=4d2758b3d9223cdacd358ffaf79f39d2)

You can see that breaking changes can be totally avoided, with the cost of 100+ LOC

**Comment by stoffeastrom** [comment]
Since the native [spec](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) handles both cases why not support both? Or maybe your draft does that @bigopon ?

**Comment by bigopon** [comment]
@stoffeastrom It can be that way, but with some extra check when adding the listeners. So it's all up to @EisenbergEffect @jdanyow

**Comment by bigopon** [comment]
Some thought:

- Using `handleEvent` will help us keep reference to the `Listener` class instance, so we can easily intercept it to support ability to do event with count. For example:

```js
class Listener {
  count = -1 // by default it trigger idefinitely

  handleEvent(e) {
    this.callSource(e);
    if (--this.count === 0) {
      this.eventManager.removeListener(this);
    }
  }
}
```

Then we can have small & specific binding behavior to alter the count of each `Listener` binding:

```html
<input blur.trigger='lostFocus() & eventCount:5' />
```

```js
class EventCountBindingBehavior {
  bind(binding: Listener, scope, count) {
    binding.count = count;
  }
}
```

@EisenbergEffect what do you think ?

**Comment by bigopon** [comment]
In this test: [http://www.stefankrause.net/js-frameworks-benchmark6/webdriver-ts-results/table.html](http://www.stefankrause.net/js-frameworks-benchmark6/webdriver-ts-results/table.html), Aurelia has quite low score in memory consumption, when the number of items is very big.

This change should drastically improve this aspect.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you review this? It looks like a good improvement. Can we find a way to do this so that the API supports both inputs, allowing us to avoid a breaking change?
