### ISSUE TITLE
IE11 repeat for with if bind doesn't work

### ISSUE THREAD

**Issue by bmarotta** [aurelia/binding#605]
**I'm submitting a bug report**

* **Library Version:**
1.2.1

* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
N/A

* **Browser:**
IE11

* **Language:**
all

**Current behavior:**
The if.bind inside of a repeat.for doesn't work on IE11. No item is displayed. The show.bind works.

The first problem I could reproduce on the below plunker:
http://plnkr.co/edit/UmwpxwrwXbASFwBkNSfs?p=preview

This works on Firefox, Chrome but not IE11 nor Edge.

**Expected/desired behavior:**
repeat.for with if.bind should work on IE as it works on the other browsers

**Comment by StrahilKazlachev** [comment]
Both attributes are *template controllers*. Using more than one template controller on an element is not supported. The order of processing of attributes is not the same in all browsers. Thus it may have unexpected results.

**Comment by atsu85** [comment]
Right, that inpredictability is due to the order that browser parses the attributes. If you had used https://github.com/MeirionHughes/aurelia-template-lint it would have told you about the problem. Try it out, it will save you soon a lot of time that you'll otherwise spend on debugging different problems.

**Comment by bmarotta** [comment]
tks. Do you know anyway to integrate Aurelia template lint with  Aurelia cli?

⁣Bruno Marotta​

**Comment by atsu85** [comment]
Last time I tried CLI, it used gulp tasks internally, so you could add a gulp task using https://github.com/MeirionHughes/gulp-aurelia-template-lint. I've added the task also to the watch task, so it runs whenever I change scripts or templates that can contain bugs discoverable by linter.

**Comment by bmarotta** [comment]
Hi atsu85,

The gulp task works. The linter for aurelia didn't find the fact that I was using if.bind and repeat.for in the same element... I know it is working because it found some duplicate ids.

Any thoughts?

Rgds
