### ISSUE TITLE
Using replaceable parts on repeated items causes duplication in Edge/IE

### ISSUE THREAD

**Issue by AStoker** [aurelia/binding#606]
**I'm submitting a bug report**

* **Library Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.11.0

* **NPM Version:**
3.10.10
* **Yarn Version:**
0.24.6

* **Browser:**
Edge 40.15063.0.0 | IE 11.413.15063.0

* **Language:**
ESNext

**Current behavior:**
Gist (IE/Edge can't use gist.run, download gist and run in browser): https://gist.github.com/AStoker/39b571d960bc9d8a0e38bd4688a3a0d4

When you use `replaceable` on a repeated element, where that repeated element is the actual repeater (i.e. contains the `repeat.for` attribute), on Edge/IE, you get duplicate elements for each item in the array.  
Given the code:
```html
<ul>
  <li replaceable part="item" repeat.for="item of items">${item}</li>
</ul>
```
When I attempt to replace `item`, for each item in the list of items, I get a duplicate entry.  
So with this as my replacement:
```html
<custom-element items.bind="items">
    <template replace-part="item">
      <li repeat.for="item of items">Foo: ${item}</li>
    </template>
</custom-element>
```
And with a list of 3 items, this is the compiled output:
```html
<ul>
  <li>Foo: 1</li>
  <li>Foo: 2</li>
  <li>Foo: 3</li>

  <li>Foo: 1</li>
  <li>Foo: 2</li>
  <li>Foo: 3</li>

  <li>Foo: 1</li>
  <li>Foo: 2</li>
  <li>Foo: 3</li>
</ul>
```
If my list would have only 2 items in it, then I would have a repeated list of `Foo: 1` and `Foo: 2` twice.
This behavior only appears in Edge and IE, not any of the other browsers.

**Expected/desired behavior:**

Expected behavior is that I would not have a duplicated list, and that Edge/IE would behave in the same manner as other browsers. I know, asking Edge/IE to be... consistent? Crazy talk! ;)

**Comment by EisenbergEffect** [comment]
Try removing "replaceable" and just have "part". See if that makes a difference.

**Comment by AStoker** [comment]
Removing `replaceable` and just having `part` actually makes it consistently behave incorrectly across browsers.
Thanks to Niieani, I have a reproducible site to show the issue on Edge easily. 
https://codesandbox.io/s/Kr6EoYjYJ

**Comment by AStoker** [comment]
Also, not quite sure it lies under the 'question' tag. Appears to be more of a bug since it is a behavioral difference between browsers and Edge/IE.

**Comment by StrahilKazlachev** [comment]
One thing that's been bugging me about the repro - why do you have `repeat.for` twice? Once in the custom element and again where you use that custom element. If you remove the `repeat` in  `app`, don't you get the result you are after or am I misunderstanding something?
```html
    <template replace-part="item">
      <li> <!-- removed repeat.for="item of items2" -->
        <label>${item.text}</label>
      </li>
    </template>
```
Also this does not run in IE. Edge is OK.

**Comment by EisenbergEffect** [comment]
@StrahilKazlachev Is correct. The repeat should be removed since this is a replacement for the template used by the repeater.

**Comment by EisenbergEffect** [comment]
@StrahilKazlachev Are you saying that there's still a bug in IE after that?

**Comment by StrahilKazlachev** [comment]
@EisenbergEffect Sorry, meant that the sample does not run in IE for me. I get:
```
SCRIPT1003: Expected ':'
2.e66f976f56c69c764193.chunk.js (152,22)
```

**Comment by EisenbergEffect** [comment]
I wonder if that's a separate issue unrelated to template parts. Maybe something to do with the codesandbox setup?

**Comment by StrahilKazlachev** [comment]
Yes, it seems so.

**Comment by AStoker** [comment]
The case is that I have a repeatable element in a custom element that is used for 3/4 cases. But there are some cases where I need to replace that repeated element completely. Thus, that repeated element needs to get replaced. And since I'm replacing the actual element that previously contained the `repeat.for`, I need to add a `repeat.for` back into my replaced element, otherwise I'll only have one `<li>`

**Comment by EisenbergEffect** [comment]
You need to have a part that wraps the repeater.

**Comment by AStoker** [comment]
Okay, if that's how it needs to be done, that's fine. Just seems strange that this works currently _in all the other browsers_.
So if I have a `<ul>` with a heck-ton of configuration done to it, and a repeated `<li>` inside I want to replace, I need to replace the whole `<ul>`? Is there a way to wrap the `<li>` without replacing the overall container? There are multiple cases where that becomes very inconvenient.

**Comment by EisenbergEffect** [comment]
It's because of the unpredictable order of attributes in different browsers.

**Comment by StrahilKazlachev** [comment]
The *thing* that you mark with `part` and `replaceable` will be replaced later on, not its parent/container.
The element you place a `repeat` on gets an implicit `replaceable` added, so it just needs `part` so that you can swap the template.

**Comment by AStoker** [comment]
@StrahilKazlachev 👍 
😮 💥 
Learning a few new things here I didn't understand in the repeater. Got it straightened out, thanks guys. 
The reason that didn't work earlier (just using part) was because I still had the repeater on the replaced portion. Now I understand how all those parts are communicating.
