### ISSUE TITLE
@bindable({ defaultBindingMode: bindingMode.oneTime }) not working

### ISSUE THREAD

**Issue by Ralimist** [aurelia/binding#609]
@bindable({ defaultBindingMode: bindingMode.oneTime }) attribute; doesn't set the defaultBindingMode to oneTime; the attributeChanged(newValue) function is still being called after attached() was invoked.
Setting the binding mode manually using attribute.one-time="stuff" works

**Comment by jdanyow** [comment]
please include a reproduction using the aurelia gist: https://gist.run/?id=7542e061bc940cde506b

**Comment by Teoxoy** [comment]
https://gist.run/?id=432af3293d446c6f0cc4c80a345782b6
But I think I should submit this issue in the templating repo.

**Comment by bigopon** [comment]
@EisenbergEffect the fix for this was already merged, it can be closed
