### ISSUE TITLE
Value converter `fromView` method never called for multi-selects

### ISSUE THREAD

**Issue by glen-84** [aurelia/binding#611]
https://gist.run/?id=285933c1cb0e2ff4b7fe67879db946ae

I don't understand why the `fromView` method is never called – is this a bug or am I misunderstanding something?

Update: This only applies to selects with the `multiple` attribute, and also affects binding behaviors, where `updateSource` is not called.

**Comment by jdanyow** [comment]
A value converter's fromView method is called when the binding expression is updating the value of the view model property. In a multiple select binding, changing the selected items doesn't change the value of the property, it remains the same array instance. This is why you don't see `fromView` invoked when you change the selection.

**Comment by glen-84** [comment]
@jdanyow Is it the same for binding behaviors?

What I wanted to do was to convert the array of strings `["1", "2", "3"]` to an array of integers `[1, 2, 3]`. I ended up creating a custom attribute, but it seems a bit like overkill.

**Comment by jadrake75** [comment]
@jdanyow thanks for your comment.  This was exactly what was happening for me with a multiple-select picker in which I need to convert the values in an array into a bitwise number.  A technique I have done is the tickle approach.  ie. if you have a two-way bound "value" in your custom element you can 
```
onSelect(dataItem) {
   let originalValue = this.value;
   originalValue.push(dataItem);
   this.value = []; // tickle it
   _.defer(() => { // you could use a setTimeout without lodash
      this.value = originalValue;
   });
}
```
