### ISSUE TITLE
Setting select options and value at the same time

### ISSUE THREAD

**Issue by glen-84** [aurelia/binding#614]
Gist: https://gist.run/?id=285933c1cb0e2ff4b7fe67879db946ae

Would this be considered a bug, or is it impossible to accomplish in this way?

It seems like a simple case. Is there an alternative?

---
Edit: I managed to work around the issue with something like this:

```ts
const matchGame = { /* the data from an API call */ };

// Assign this data first, so that the select options can be bound before the value.
this.matchGame.opponent1 = matchGame.opponent1;
this.matchGame.opponent2 = matchGame.opponent2;

this.matchGame = matchGame;
```

**Comment by bigopon** [comment]
@glen-84 fix for this is at https://github.com/aurelia/binding/pull/677

**Comment by glen-84** [comment]
Thank you! 🙂
