### ISSUE TITLE
determine what (if anything) we need to do to support <datalist>

### ISSUE THREAD

**Issue by jdanyow** [aurelia/binding#62]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

``` html
<div>Choose a browser from this list:</div>
<input list="browsers" />
<datalist id="browsers">
  <option value="Chrome">
  <option value="Firefox">
  <option value="Internet Explorer">
  <option value="Opera">
  <option value="Safari">
</datalist>
```

Question came up in the gitter around binding an input's value to an object when using `<datalist>`.  Each option in the datalist was using `model.bind`.

**Comment by flieks** [comment]
Could use this for creating your my own autocomplete custom element.. :)

**Comment by EisenbergEffect** [comment]
@jdanyow Do we need to do anything for this?

**Comment by jdanyow** [comment]
I think the original question was around using an input combined with a datalist to in a `<select>` element like fashion in that the input's value binding would handle objects like we do in the select.  This would be a good candidate to explore in an external plugin and then perhaps merge into the core if a good solution is found.

**Comment by chris-dickson** [comment]
Came up on an issue when trying to support this (specifically for autocomplete) in our app.  

We have a form that contains multiple input fields, which are associated with their own datalist.  When trying to bind the input list attribute to the datalist id, we receive the following error:

`ERROR [app-router] TypeError: Cannot assign to read only property 'list' of object '#<HTMLInputElement>'(…)`

My question is, how do we support having multiple datalists in the same document if we cannot dynamically assign unique list values for each input element?

**Comment by jdanyow** [comment]
Apparently the input element's list property is read-only... strange it's not documented as such:

![image](https://cloud.githubusercontent.com/assets/1306747/17524250/d7d328ec-5e2b-11e6-812e-0023b2bfc47d.png)
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement

You'll need to set the `list` HTML attribute (eg `setAttribute('list', myId)`) instead of attempting to assign the input element's `list` DOM property.

Here's an example that uses a binding behavior to make it easier:

https://gist.run/?id=40fbbb1ba7c43b1df5f078f0093c11e3

**Comment by chris-dickson** [comment]
Worked like a charm!  Thanks Jeremy.
