### ISSUE TITLE
Changed property handling doesn't work anymore

### ISSUE THREAD

**Issue by mreiche** [aurelia/binding#628]
**I'm submitting a bug report**

I'm facing a strange bug after upgrading my complete aurelia framework to the newest stable version. Code that worked before, is not working anymore. Especially binded properties.

* **Library Version:**
1.3, maybe earlier, maybe not in this library.

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.6

* **NPM Version:**
3.10.10

* **Browser:**
Chrome 61.0.3163.100

* **Language:**
ESNext

**Current behavior:**

When binding an item to my component like
```html
<item item.bind="currentItem">
</item>
```

The ``bind`` method is called:

```javascript
bind() {
	console.log('bind',this.item.title);
	//this.__rebuildBreadcrumb();
}
```
console output:
```
bind Products
bind About
etc...
```

But the view doesn\'t update and the ``valueChanged()`` method is not called.
```javascript
itemChanged() {
	console.log('item changed',this.item.title);
	//this.__rebuildBreadcrumb();
}
```

When the item was once rendered with "Products", it doesn't receive any updates. Even if I bind another item and the bind method tells ``bind Foo`` the view still shows "Products".

**Expected/desired behavior:**

The view needs to be updated and the ``valueChanged()`` should be called.

**Comment by bigopon** [comment]
Possibly related: aurelia/templating-resources#315

**Comment by mreiche** [comment]
I can confirm, that this only happens (or not happens) when the element is conditionally present in the DOM. This bug occurs because of:

```html
<div if.bind="currentItem!==null">
    <item item.bind="currentItem">
    </item>
</div>
```

**Comment by nenadvicentic** [comment]
Same problem here.
After template is hidden and shown again, `delegate` binding on some items does not work any more.

```
<template if.bind="...">
    <button if.bind="..." click.delegate="doSomething()"></button>
</template>
```

**Comment by mreiche** [comment]
https://github.com/aurelia/templating-resources/issues/317
