### ISSUE TITLE
IE11 value binding doesn't update when clearing input with ESC key

### ISSUE THREAD

**Issue by arnederuwe** [aurelia/binding#632]
**I'm submitting a bug report**

* **Library Version:**
1.3.0

**Please tell us about your environment:**
* **Operating System:**
Windows

* **Browser:**
IE 11, possibly 9 and 10 (didn't test)

* **Language:**
all

**Current behavior:**
When value binding a standard input element, the value isn't updated on the VM when clearing the input with the ESC key. Resulting in a UI that doesn't reflect the VM's state.
Clearing inputs with ESC is an IE 'Feature', so this is the only browser where this issue is present, the 'x' symbol IE renders in each input field works as expected.

**Expected/desired behavior:**

* **What is the expected behavior?**
The VM bound field is updated when pressing the ESC key.

* **What is the motivation / use case for changing the behavior?**
A consistent binding experience across all supported browsers.

As this is mainly an issue about IE not complying to the HTML standard, I understand if this would not be fixed. I just need some advice on how one would:
- (dirty) fix this in a project
- prevent the ESC functionality from triggering in the first place

**Comment by arnederuwe** [comment]
Relevant MS connect issue:
https://connect.microsoft.com/IE/feedback/details/881670/ie11-esc-key-changes-value-of-input-type-text-but-does-not-fire-input-event

**Comment by jdanyow** [comment]
oh IE 💓 🔫 

here's a workaround to disable the esc funtionality: https://plnkr.co/edit/AMh5BwhaAV6fgihsxFh2?p=preview

**Comment by arnederuwe** [comment]
Thanks, I will try to educate the customer not to use the ESC 'functionality' the hard way...
Next year the current Silverlight app will be rewritten in Aurelia, then we can finally ditch IE...

**Comment by jdanyow** [comment]
sounds good- closing this
