### ISSUE TITLE
Inheritance of @observable

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [aurelia/binding#634]
This is a feature request. I need inheritance of @observable. 

Inheritance of @bindable is available in a recent release. Although there are some limitations, it is very useful.

How about @observable?  Very difficult?

**Comment by bigopon** [comment]
Can you describe your scenario and why its not working for you ? From what I see, `@observable` is inheritable

**Comment by HIRANO-Satoshi** [comment]
Thanks. Seems working.

**Comment by bigopon** [comment]
@EisenbergEffect I think this can be closed.
