### ISSUE TITLE
Click handler prevents <a href> actions inside

### ISSUE THREAD

**Issue by zakjan** [aurelia/binding#636]
**I'm submitting a bug report**

* **Library Version:**
1.3.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Browser:**
Chrome 62.0.3202.29

**Current behavior:**
```
  <div click.delegate="click()">
    <a href="#/aaa">Click me!</a>
  </div>

  click() {}
```

Clicking on the link doesn't update `window.location.hash`. It requires explicit `return true` in the event handler to not prevent it.

See gist https://gist.run/?id=5c2d55c58bb270bfab2f41026898cd23

**Expected/desired behavior:**

* **What is the expected behavior?**
Href action is not prevented.
#/aaa appears after clicking the link in the gist.

* **What is the motivation / use case for changing the behavior?**
Consistency with browser native behavior. `return true` should be assumed by default.

**Comment by bigopon** [comment]
You are using Aurelia implementation of event delegation via `delegate` binding command, with the trade off you noticed. The other way you can do it is to drop delegation and use browser native behavior via `trigger` binding command:

```html
<div click.trigger='click()'>
  <a href='#/aaa'>Click me!</a>
</div>
```

**Comment by zakjan** [comment]
The same happens with trigger.

**Comment by bigopon** [comment]
Right, I typed before checking with the code [Listener](https://github.com/aurelia/binding/blob/master/src/listener-expression.js#L40-L42), Sorry for that false info.

About the behavior, @jdanyow @EisenbergEffect maybe we can opt in a flag to let it ignore the `return true` behavior. Or even better, config based on `delegationStrategy`. Something like this:

```js
Listener.preventDefaultForDelegationStrategy({
  capturing: true,
  bubbling: true,
  none: false
});
```

And then allow this to be configurable from `FrameworkConfiguration` ?

**Comment by jdanyow** [comment]
This is working as-designed.

**Comment by zakjan** [comment]
@jdanyow Is it documented anywhere? Why is it different from browser's native behavior?

**Comment by jdanyow** [comment]
It’s in the docs:
http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-basics/3

**Comment by prakash12** [comment]
Hello,
I am also facing same issue with aurelia <a> tab. I need to reload the page when user clicked on <a> link but it's not reloading. So I need to use event aggregator to refresh other part of my web page but click event is not working. Please suggest
