### ISSUE TITLE
else binding breaks value.bind for inputs and textareas

### ISSUE THREAD

**Issue by thinkOfaNumber** [aurelia/binding#639]
**I'm submitting a bug report**

* **Library Version:**
aurelia-binding 1.3.0

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
v8.6.0

* **NPM Version:**
5.4.2

* **JSPM OR Webpack AND Version**
webpack 2.5.0

* **Browser:**
Chrome 61.0.3163.100

* **Language:**
TypeScript 2.2 & JS

**Current behavior:**
If I use `else` on an `<input>` or `<textarea>` element, then the value.bind doesn't work.

gist.run here: https://gist.run/?id=e8bb52d515be789f1e4da4efeb3c079c

**Expected/desired behavior:**

* **What is the expected behavior?**
I would expect that the `else` doesn't stop me from using `value.bind` on an element.

As a workaround I can use `if.bind="test"` and `if.bind="!test"` on respective elements, but this defeats the purpose of having `else`.

* **What is the motivation / use case for changing the behavior?**
To make it consistent with the behaviour before `else` was available, i.e. the same as using `if.bind`.

Edit: updated incorrect gist url. This one shows the issue.

**Comment by jods4** [comment]
I'll have a look, whoever has control over this repo can assign to me.

**Comment by jods4** [comment]
@thinkOfaNumber your issue looks like a duplicate of aurelia/templating-resources#322 (that's where `if` and `else` actually are).
It was fixed but your repro uses a previous version.

Please try with `aurelia-templating-resources@1.5.4`. If it still doesn't work I'll have a closer look.

**Comment by thinkOfaNumber** [comment]
Yep that seems to have done it, awesome, thanks! Sorry I thought we were on the latest version of everything. Time for an audit!
