### ISSUE TITLE
Assigning an Array value by index does not notify subscribers.

### ISSUE THREAD

**Issue by davismj** [aurelia/binding#64]
**viewModel**
`array = ['foo']`

**view**
`<div>${array[0]}</div>`

The above will output foo, as expected. However, if you index-assign a new value, e.g. `array[0] = 'bar'`, the output is not updated.

**Comment by EisenbergEffect** [comment]
We can't fix this. It's impossible with native Array.observe. It's the one flaw in the binding system. The only way to get around it is to create a helper method on array that would notify the changes and use that instead of the indexer when you want to change something. You can always use splice as well. But, JS provides no way to override the indexer (at least no way that isn't insane and non-scalable).

**Comment by davismj** [comment]
What about employing dirty checking in these scenarios? Is there any way to
communicate to the developer at runtime that he shouldn't expect it to
work?

**Comment by EisenbergEffect** [comment]
Basically, use dirty checking on array indexes...hmmm. That could work.

On Tue, Apr 7, 2015 at 11:18 PM, Matthew James Davis <
notifications@github.com> wrote:

> What about employing dirty checking in these scenarios? Is there any way to
> communicate to the developer at runtime that he shouldn't expect it to
> work?
> On Apr 7, 2015 10:27 PM, "Rob Eisenberg" <notifications@github.com> wrote:
>
> > We can't fix this. It's impossible with native Array.observe. It's the
> one
> > flaw in the binding system. The only way to get around it is to create a
> > helper method on array that would notify the changes and use that instead
> > of the indexer when you want to change something. You can always use
> splice
> > as well. But, JS provides no way to override the indexer (at least no way
> > that isn't insane and non-scalable).
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/aurelia/binding/issues/64#issuecomment-90783799>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/binding/issues/64#issuecomment-90792191>.
>



-- 
Rob Eisenberg,
President - Blue Spire
www.durandaljs.com

**Comment by EisenbergEffect** [comment]
Not sure if we should do anything about this or not just yet.

**Comment by nexbit** [comment]
Does https://github.com/aurelia/binding/issues/76 covers an expression like `data[0].property` ?
It seems my binding doesn't get notified when `property` changes, even if it is defined as an ES property..

**Comment by pasky** [comment]
This is one of the top google results for Aurelia not reacting to array element changes.  In my view, it's no big deal if Aurelia doesn't support this implicitly, but it'd be great to mention a precise recipe to work the issue around and force the update manually.  For example, I have found the suggestion to replace ```this.samples_loaded[i] = true;``` with ```this.samples_loaded.splice(i, 1, true);``` but that doesn't help...

**Comment by EisenbergEffect** [comment]
@jdanyow Since you are working on the binding docs currently, can you be sure to include this information and recommendation in that. (Along with any other common scenarios you've seen over the last months.)

**Comment by MeirionHughes** [comment]
taking suggestions on how/when to warn about this issue: https://github.com/MeirionHughes/aurelia-template-lint/issues/82#issuecomment-250273617

**Comment by MeirionHughes** [comment]
Anyone having issues with this; check out this example: https://gist.run/?id=c3d618546a0fef10a266109465eed94c

by using splice and the property indexer (string) you can get the binding working.

**Comment by gbreeze** [comment]
What is with polyfills, is there a workaround? 

Example: 
```
if (!Array.prototype.swap) {
    Array.prototype.swap = function (newIndex: number, oldIndex: number) {
        let temp = this[newIndex];
        this[newIndex] = this[oldIndex];
        this[oldIndex] = temp;
        return this
    }
}
```

this does not reflect on a 'repeat.for' binding :-|

**Comment by jdanyow** [comment]
@gbreeze aurelia does not observe array mutation via indexed assignment (eg `arr[x] = y`) because it would require dirty-checking now that Object.observe is discontinued. Use `splice` instead:

```js
if (!Array.prototype.swap) {
    Array.prototype.swap = function (newIndex: number, oldIndex: number) {
        const temp = this[newIndex];
        this.splice(newIndex, 1, this[oldIndex]);
        this.splice(oldIndex, 1, temp);
        return this;
    }
}
```
