### ISSUE TITLE
Observing Map doesn't work, possible regression

### ISSUE THREAD

**Issue by davismj** [aurelia/binding#642]
**I'm submitting a bug report**

* **Library Version:**
1.5.0

**Current behavior:**
No observation of map.get

**Expected/desired behavior:**
Observe map.get

* **What is the expected behavior?**
https://gist.run/?id=97468444c5aea6042dfbdd3ccf6c7b2c

* **What is the motivation / use case for changing the behavior?**
Observe maps

**Comment by bigopon** [comment]
The first case has never been supported. Same for second case as they are both bound to function call result. So if the map never changed, It won't call the binding to update those text node.

I think it's intentional, since we don't support function call result. Aurelia cannot differentiate between a map get and a normal function call.

**Comment by davismj** [comment]
I had some code that was using this and I seem to remember it working before.

Since map.get, for example, is not just a normal function, but a function whose result is explicitly tied to a map mutation, such as map.set, I'm thinking it would be possible, maybe reasonable, to observe these mutations.

**Comment by bigopon** [comment]
I dont know the full history so you could be right, then support for it was dropped. Maybe @jdanyow left those out for performance optimization ?

**Comment by jdanyow** [comment]
Never was supported. Mr Davis here has a history of requesting method call observation. 😉

**Comment by jdanyow** [comment]
https://github.com/aurelia/binding/issues/147

**Comment by davismj** [comment]
Haha okay, maybe I found a workaround for it like iterating over the map elements and then testing to see if it was equal to the one I actually wanted.

However, I don't think this is an unreasonable thing to observe. These aren't arbitrary methods, and in fact Map.get is quite similar to Array[i] as we know Map.get will be updated by Map.set just like we know Array[i] will be updated by Array methods including splice. 

I think this Array use case--in an issue also opened by yours truly--was eventually added: https://github.com/aurelia/binding/issues/64

**Comment by davismj** [comment]
@jdanyow @bigopon I'm looking at the map-observation code here: https://github.com/aurelia/binding/blob/master/src/map-observation.js#L42

So basically, this works on a repeat but not on a `.get()` call. In the case of Map, however, I think more often than not you will want to get specific values rather than iterating over the entire Map.

Wouldn't there be a way to extend the get function to add it as a subscriber to the map's subscriber collection?
