### ISSUE TITLE
vanilla web components biding does not work

### ISSUE THREAD

**Issue by pragmaproducts** [aurelia/binding#644]
I'm submitting a bug report
Library Version:
aurelia-binding@1.2.1

binding does not work on vanilla web components.

Usage
```html
<template>
    <link rel="import" href="./metal/greeting.html" async>

    <div>${message}</div>
    <greeting-test message="hello world"></greeting-test>
    <greeting-test message.bind="message"></greeting-test>
    <greeting-test message.two-way="message"></greeting-test>
</template>
```

if i use ```<greeting-test message="hello world"></greeting-test>``` everything works fine using binding it does not

The actual HTML does not show that this was even set.

html result
```html
<router-view class="au-target" au-target-id="128">
    <link rel="import" href="./metal/greeting.html" async="">

    <div>Johan Rabie</div>
    <greeting-test message="hello world" role="list">
    <div id="content"></div>
</greeting-test>
    <greeting-test message.bind="message" class="au-target" au-target-id="137" role="list">
    <div id="content">Greeting</div>
</greeting-test>
    <greeting-test message.two-way="message" class="au-target" au-target-id="138" role="list">
    <div id="content">Greeting</div>
</greeting-test>
</router-view>
```

The custom element observes the attribute 
```js
static get observedAttributes() {return ['message']; }
```
and attributeChangedCallback fires when you just assign the property as seen in the hello world example. It does not fire when binding is done and looking at the html result it looks like the message attribute is never set in the binding.

This is a huge issue for us and any support on how to resolve this would be greatly appreciated.

**Comment by bigopon** [comment]
@pragmaproducts  Here is a base Gist you can fiddle with, with all base test CE, https://gist.run/?id=4d2758b3d9223cdacd358ffaf79f39d2

It's working fine for me. So maybe you are experiencing something different. If you can describe clearer in the Gist or here, maybe it can help to debug.

**Comment by bigopon** [comment]
Please note that Aurelia binding system works with props, not attributes, so when doing `message.bind="message"`, the message is never automatically reflected to the attribute. If needed, there should be a setter at `message` to reflect it to the attribute.

**Comment by jdanyow** [comment]
could try `message.attr="message"` or `message.bind="message & attr"`
