### ISSUE TITLE
Feature: Support spread operator in view

### ISSUE THREAD

**Issue by davismj** [aurelia/binding#645]
**I'm submitting a feature request**

**Current behavior:**
> Error: Parser Error: Unexpected token . at column 19 in [computePathString(...points)]

**Expected/desired behavior:**
Spreads the points array, as if you had passed `computePathString(points[0], points[1], points[2])`, which also observes these variables.

* **What is the motivation / use case for changing the behavior?**
To observe the items in the array when computing a value.

**Comment by Alexander-Taran** [comment]
https://github.com/aurelia/binding/pull/647#issuecomment-350692094
>For what its worth, I was mostly trying to get a discussion going to see if this was a good idea in the first place. I think the discussion here has mostly proved that it isn't.

@davismj ?
