### ISSUE TITLE
Missing DirtyCheckProperty in d.ts

### ISSUE THREAD

**Issue by gama410** [aurelia/binding#648]
**I'm submitting a bug report**

* **Library Version:**
1.2.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.11.0

* **NPM Version:**
5.2.0

* **JSPM OR Webpack AND Version**
webpack ??

* **Browser:**
Chrome XX | Firefox XX 

* **Language:**
TypeScript 2.6.1

**Current behavior:**
I'm trying to import DirtyCheckProperty from aurelia-binding using the following line:
_import {DirtyCheckProperty} from 'aurelia-binding';_

but tsc transpilation throws the following error: 
_Error: src\main.ts(9,9): error TS2305: Module '"..../node_modules/aurelia-binding/dist/aurelia-binding"' has no exported member 'DirtyCheckProperty'._

Although it works well at runtime (it is just a typescript error because it can't find it in the d.ts but the feature is available in aurelia-binding.js)

**Expected/desired behavior:**

* **What is the expected behavior?**

I expected to be able to import this but it doesn't appear in aurelia-binding.d.ts anymore (it was before). 

* **What is the motivation / use case for changing the behavior?**
I'm not sure a change is necessary : Maybe this feature is expected to be removed or accessible from elsewhere? Otherwise, the d.ts would probably need to be regenerated to include this class...

**Comment by gama410** [comment]
@jdanyow @EisenbergEffect @bryanrsmith  any ideas?

**Comment by jdanyow** [comment]
@gama410 this will be available in the next release of aurelia-binding

**Comment by gama410** [comment]
great! Thanks for the fix!
