### ISSUE TITLE
Maximum call stack size exceeded at MouseEvent.stopPropagation

### ISSUE THREAD

**Issue by AquilaSands** [aurelia/binding#649]
**I'm submitting a bug report**

* **Library Version:**
1.5.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
9.0.0

* **NPM Version:**
5.5.1

* **JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Browser:**
Chrome 62 | Firefox 57 | (assuming all)

* **Language:**
all

**Current behavior:**
Outer div with click.capture binding, inner div with click.delegate binding and an <a> tag. Inner div click function checks if the target was the <a> tag and if so calls stopPropagation() and returns true to allow the default action of navigating to the link URL. This causes an uncaught 'Maximum call stack size exceeded' exception. Strangely the navigation still occurs and no other ill effects are observed.

**Expected/desired behavior:**

https://gist.run/?id=fc46b21d09cb9e188e87999f5660bda3

Click on the google link in the inner content div to trigger the stack exception.

* **What is the expected behavior?**
No exception occurs.

* **What is the motivation / use case for changing the behavior?**
Getting rid of the exception.

**Additional Info**
 As a workaround in the actual project I'm working on I have used the click.trigger binding on the outer div. Debugging the code seems to point to some kind of infinite recursion in the stopPropagation function in aurelia-binding.js as the call to this.standardStopPropagation(); is executed continuously and the following line this.propagationStopped = true; is never reached.

I may have just done a stupid thing here by using both capturing and bubbling events, apologies if so. :)

**Comment by jdanyow** [comment]
https://gist.run/?id=e85d11d7d7098c641162c3362ff15bbb
