### ISSUE TITLE
Documentation: Binding | Value Converter | Signalable demo broken

### ISSUE THREAD

**Issue by rockResolve** [aurelia/binding#650]
**I'm submitting a bug report**

The "Flight Dashboard with Signalable Value Converter Demo" at the bottom of the page looks quite broken. I see nothing below "Flights", no flight information at all.

http://aurelia.io/docs/binding/value-converters#signalable-value-converters

**Comment by bigopon** [comment]
It's fixed in this [commit](https://github.com/aurelia/binding/commit/4fa99d5c187c29fc8c14dcd94c7cd39e03cce5f9), waiting for @EisenbergEffect to update doc

**Comment by EisenbergEffect** [comment]
I'm making a note. The releasing those binding demos requires some extra work that isn't part of the normal docs release flow. I'll get it with the next release.

**Comment by Alexander-Taran** [comment]
@EisenbergEffect looks like you did
can be closed
