### ISSUE TITLE
Missing TypeScript Interface: ICollectionObserverSplice

### ISSUE THREAD

**Issue by jonathaneckman** [aurelia/binding#652]
I have to add this interface to all of my projects. It would be nice if the framework exported it for us. 

```
interface ICollectionObserverSplice {
    addedCount: number;
    index: number;
    removed: Array<any>;
}
```

This would be used in `BindingEngine.collectionObserver(splices: ICollectionObserverSplice)`

**Comment by jdanyow** [comment]
@jonathaneckman would you be willing to PR these changes [here](https://github.com/aurelia/binding/blob/master/src/aurelia-binding.d.ts)?

**Comment by jonathaneckman** [comment]
@jdanyow yes I can take this. Ill get it in this weekend.
