### ISSUE TITLE
Aurelia-binding typings build issue after latest commit

### ISSUE THREAD

**Issue by dhanapalschandran** [aurelia/binding#663]
HI Team,
The recent change is throwing error in type definition during compile.
typings/modules/aurelia-binding/index.d.ts
Could you resolve it ASAP>
export interface CollectionObserver {
  /**
   * Subscribe to collection mutation events.
   */
  subscribe(callback: (changeRecords: Array<IArrayObserverSplice> | Array<IMapObserverSplice> | Array<ISetObserverSplice>) => void): Disposable;
}

**Comment by StrahilKazlachev** [comment]
OK, there is an issue template for, reasons.
1. Which version of `aurelia-binding` is giving you the issue?
2. What is your tooling? Basically now I'm guessing that you are referencing the master branch in git somehow, and not a specific tag or preferably a npm package. The merged PR you commented first has not been released yet.
3. Please provide the related compiler errors. I can't seem to find `callback: (changeRecords: Array | Array | Array` in the code.

**Comment by dhanapalschandran** [comment]
Hi,

 Please find the below screen shot of the gulp build issue we are facing with Aurelia typings file.

![typings issue](https://user-images.githubusercontent.com/9696305/35849145-9af27832-0b46-11e8-9883-967dc0cf1c80.png)

 And regarding the version, our build server will take the latest Aurelia binding version. 
Regards,
Dhanapal Chandran

**Comment by bigopon** [comment]
From the look of the error report, I think you have typescript version less than 2.3 as the new typings use Default generic type.

@EisenbergEffect @jdanyow @StrahilKazlachev What should we do about this ?

**Comment by bigopon** [comment]
Also notice that the distribution typings doesn't match typings in src, could be an issue.

**Comment by StrahilKazlachev** [comment]
@bigopon about the typings in the `dist`, isn't is normal, since there has not been a release?

**Comment by Alexander-Taran** [comment]
@dhanapalschandran have you resolved your issue?

**Comment by Alexander-Taran** [comment]
```
async triageQuestion(id) =>{
 respondSameDay()
 let response = await getResponseFromOP( { timeout : longEnough} )
 if(!response) {
    closeQuestion(id,randomReason())
 }
}
```

can be closed

**Comment by EisenbergEffect** [comment]
Closing because:
* This is likely an issue with the OPs TS version.
* No response from OP in 10 days.
