### ISSUE TITLE
Typings conflict with aurelia/validation while transpiling typescript

### ISSUE THREAD

**Issue by stravinskij** [aurelia/binding#664]
**I'm submitting a bug report**

* **Library Version:**
?? aurelia-binding 1.6.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.9.4

* **NPM Version:**
5.6.0

* **JSPM OR Webpack AND Version**
JSPM 0.17.0-beta.47

* **Browser:**
N/A during transpile

* **Language:**
all | TypeScript X.X | ESNext

**Current behavior:**
```
typings\modules\aurelia-binding\index.d.ts(42,17): error TS2451: Cannot redeclare block-scoped variable 'getContextFor'.
[00:28:28] gulp-notify: [Error running Gulp] Error: typings\modules\aurelia-binding\index.d.ts(42,17): error TS2451: Cannot redeclare block-scoped variable 'getContextFor'.
typings\modules\aurelia-validation\index.d.ts(48,11): error TS2451: Cannot redeclare block-scoped variable 'getContextFor'.
[00:28:28] gulp-notify: [Error running Gulp] Error: typings\modules\aurelia-validation\index.d.ts(48,11): error TS2451: Cannot redeclare block-scoped variable 'getContextFor'.
```

** Reproduce **
use [aurelia-skeleton-navigation-typescript](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript)
install node modules `npm install`
install jspm modules `jspm install`
run typings `typings install`
run gulp watch `gulp-watch`

**Expected/desired behavior:**

* **What is the expected behavior?**
no typescript errors

* Errata 
I believe it was caused by the following commit
[https://github.com/aurelia/binding/commit/49f46ceddd72250350ac541c196a70ccb9a9bd9f](https://github.com/aurelia/binding/commit/49f46ceddd72250350ac541c196a70ccb9a9bd9f)

which conflicts with this file over in aurelia/validation
[dist/amd/property-info.d.ts](https://github.com/aurelia/validation/blob/master/dist/amd/property-info.d.ts)

I'm not sure if it needs to be corrected here or in aurelia/validation or if i'm way of track. It appears to be that typings just grabs from the master branch.

**Comment by bigopon** [comment]
The typing to fix this has been updated, waiting for release. so we can remove the declare block above.

@EisenbergEffect @jdanyow

**Comment by wpearson4** [comment]
Is there any update on when this fix will be released?  I am experiencing the same issues and it is causing issues with other modules not be bundled correctly after the error.

**Comment by TylerJPresley** [comment]
This is still an issue with the latest releases of each. 

```
    "aurelia-binding": "^1.7.0",
    "aurelia-validation": "^1.1.2",
```
Shouldn't the entry be removed from the validation lib?

**/Users/tjpresley/Projects/strengthen_webapp/node_modules/aurelia-validation/dist/commonjs/property-info.d.ts(**
```
import { Expression, Scope } from 'aurelia-binding';
declare module 'aurelia-binding' {
    const getContextFor: any;
}
/**
 * Retrieves the object and property name for the specified expression.
 * @param expression The expression
 * @param source The scope
 */
export declare function getPropertyInfo(expression: Expression, source: Scope): {
    object: object;
    propertyName: string;
} | null;
```

**Comment by Alexander-Taran** [comment]
updated validation is out
can be closed
