### ISSUE TITLE
Debounce is not updating input correctly if value has been re-typed

### ISSUE THREAD

**Issue by GabrielMancik** [aurelia/binding#666]
I'm submitting a bug report

Library Version:
1.6.0

NPM Version:
5.3.0

JSPM Version:
0.16.48

Browser:
Chrome 60.0.3112.113 (Official Build) (64-bit)

Language:
TypeScript 2.3.4

Current behavior:
Steps to reproduce:
Please use your own demo for testing (http://aurelia.io/docs/binding/binding-behaviors)

1. Enter "qwe" as first name
2. Quickly type "qwe" as value again
3. only "qw" remains in input (for a short time input correctly showed "qwe" but then "e" was removed)

I have also tested master branch whether **https://github.com/aurelia/templating-resources/pull/336** this has not fixed the problem, but it seems it did not.

Expected behaviour:
"qwe" typed in input

**Comment by bigopon** [comment]
@EisenbergEffect @jdanyow Can you move this to `templating-resources` ?

**Comment by EisenbergEffect** [comment]
Issue moved to [aurelia/templating-resources #341](https://github.com/aurelia/templating-resources/issues/341) via [**ZenHub**](https://www.zenhub.com/)
