### ISSUE TITLE
Property of argument object is 'undefined' in call binding

### ISSUE THREAD

**Issue by petronellius** [aurelia/binding#667]
**I'm submitting a bug report / a feature request ?**

* **Library Version:**
aurelia-binding 1.6.0

**Please tell us about your environment:**

* **Browser:**
Chrome 64

* **Language:**
TypeScript 2.5

**Current behavior:**
If property of EventArgs class is declared as public variable and set to some value, the property has value also in callback function.
In case the property is defined through getter syntax, the property value is undefined in callback function.

**Expected/desired behavior:**

* **What is the expected behavior?**
Property of argument object has value in callback method.

* **What is the motivation / use case for changing the behavior?**
Better encapsulation.

**Comment by Alexander-Taran** [comment]
Could you please provide more context.
With a gist probably.
It is not that clear what you are trying to do.
And where does it fail you.

**Comment by petronellius** [comment]
Please, see sample code here.
http://next.plnkr.co/edit/xWQSFyLxJ9MFSUG8?preview

Click on any of items. In console you will see 'undefined' from callback function.
The problem is in EventArgsWrapper. Property eventArgs is defined as public getter that backed private variable. When I change it to public readonly variable everything is working as expected. 
http://next.plnkr.co/edit/0BMEO4KEgVqZMfz4

Probably, simple Object.assign() is used in aurelia-binding plugin that doesn't copy getter definition. Anyway, this is not big issue.

**Comment by Alexander-Taran** [comment]
Interesting observation.
Indeed there is Object.assign() hidden somwhere in the chain to call the callback.

On other hand if you just pass the reference outside it could lead to memory leaks.
Would it satisfy your needs to pass a POJO clone of your object to the callback? It is a DTO isn't it? 
If so, you could JSON.parse(JSON.stringify(EventArgsWrapper)) to deep the values.

**Comment by Alexander-Taran** [comment]
@petronellius can you live with workaround that I provided?

@EisenbergEffect should we consider this?

**Comment by EisenbergEffect** [comment]
Try this:

```
<template>
    <require from="./list"></require>
  <h1>${message}</h1>
  <list before-selected-item-changed.call="beforeItemChanged($event)"></list>
</template>
```

**Comment by petronellius** [comment]
@Alexander-Taran I need the reference on eventArgs object in parent component. I react there on selection changed event with dialog confirming selection. If user cancel selection eventArgs.cancel is set to true in beforeItemChanged callback and list component clear selection.

@EisenbergEffect Your solution is working perfectly even with getter defined in BeforeSelectedItemChangedEventArgs class. I don't even need EventArgsWrapper to pass reference to parent component now.
Only strange thing is that [in my sample code](http://next.plnkr.co/edit/CBHCouzP8jGVi3By?preview) BeforeSelectedItemChangedEventArgs object is not release after callback is called. However, this doesn't happen in production code even though it's same situation. I checked it through Chrome heap snapshots comparison. 
Anyway, I am  really happy with your solution :thumbsup:

**Comment by EisenbergEffect** [comment]
I'm fairly certain that you won't have a memory issue with this. What you observed is likely a result of having the dev tools open or a delay in the browser GC. You should be good :)
