### ISSUE TITLE
Collection observer is not working properly

### ISSUE THREAD

**Issue by mariaantony-gnanasekaran** [aurelia/binding#670]
**I'm submitting a bug report**

* **Library Version:**
1.1.2

* **Operating System:**
Windows 10

* **Node Version:**
8.7.0

* **NPM Version:**
4.6.1

* **Webpack Version**
 webpack 3.6.0

* **Browser:**
all 

* **Language:**
all

**Current behavior:**

I am using collection observer to observe the changes in Array type dataSource. This triggers changeHandler callback , whenever I do changes in array by using push,pop,splice method.

But when I change an array with index like the below code snippet

```
let arr = [ {a:1}];
arr[0].a =2;

```
changeHandler callback function is not getting triggered. but view is getting updated.

Refer the below gist sample

https://gist.run/?id=437548a49d87f665ea6c1eb0ca725510

**Expected behavior:**

whenever the property gets changed, we expect callback method to get triggered for notifying the change.

**Comment by Alexander-Taran** [comment]
As I said in gitter this has nothing to do with the framework. 
vuejs got the same "problem"
there is no way apart from dirty checking to know that you assigned a new value to array element.
nothing observes it.

But guidance around this should be improved.
solution to your case is to use splice method of array

arr.spilce(indexOfElementToReplace,1, newValue)

**Comment by StrahilKazlachev** [comment]
Another way is to clone the current array, modify the clone and then assign the clone to the property.
```js
const clone = this.myArrProp.slice(0);
clone[0] = clone[0]+ '4';
this.myArrProp = clone;
```

**Comment by Alexander-Taran** [comment]
@mariaantony-gnanasekaran here is your gist modified to your needs
https://gist.run/?id=3f9e4c4013f1110597fff7599b8db048

**Comment by Alexander-Taran** [comment]
can be closed
