### ISSUE TITLE
Bug - Automatic bindable properties work but explicitly doesn't?

### ISSUE THREAD

**Issue by diegohb** [aurelia/binding#672]
* **Library Version:**
aurelia-binding: 1.6.0
aurelia-cli: 0.32.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
9.4.0

* **Yarn Version:**
1.3.2

* **systemjs version**
0.20.18

* **Browser:**
all

* **Language:**
TypeScript 2.6.2

**Current behavior:**
When i place attribute for bindable() and/or computedFrom on my "chosenZipCodes" property, it no longer gets called or the getter doesn't execute at all.. it show undefined at runtime in browser console.
Removing the attribute(s), fixes the problem.

**Expected/desired behavior:**
Should work the same with or without the exdplicit attrributes.

```

class myVM {
....
    constructor(private readonly _geoSvc: GeographyService) {
        this.zipOptions = new Array<ListItem<string>>();
        this.selectedZipOptions = new Array<ListItem<string>>();
    }

    public zipOptions: Array<ListItem<string>>;

    public selectedZipOptions: Array<ListItem<string>>;

    @bindable({ defaultBindingMode: bindingMode.toView })
    @computedFrom("selectedZipOptions")
    public get chosenZipCodes(): ReadonlyArray<PostalCode> {
        return this.selectedZipOptions.map(pItem => pItem.metadata as PostalCode);
    }
...
}
```

**Comment by Alexander-Taran** [comment]
Why do you want to decorate a readonly property with bindable toView?
It is the default for almost everything..except input values? those are two-way by default

Looks like overengineering

**Comment by bigopon** [comment]
`@bindable` will rewrite (not intercept) the property, thus washes away your getter. That's why your getter does not get called. @jdanyow @EisenbergEffect @Alexander-Taran  This could be a good target for `<let />` element, where one can do:

#### element declaration

```html
<!-- zip code.html -->
<template>
  <let chosen-zip-codes.bind='selectedZipOptions | metadataOnly'></let>

  <div repeat.for='zipCode of chosenZipCodes'>${zipCode}</div>
</template>
```

```js
class myVM {
....
    public selectedZipOptions: Array<ListItem<string>>;

    @bindable({ defaultBindingMode: bindingMode.toView })
    public chosenZipCodes(): ReadonlyArray<PostalCode> {
        return this.selectedZipOptions.map(pItem => pItem.metadata as PostalCode);
    }
...
}
```

#### element usage

```html
<!-- app.html -->
<template>
  <require from='zip-code' ></require>
  <zip-code chosen-zip-codes.bind='initChosenZipCodes' ></zip-code>
</template>
```

So it can be a `@bindable`, to take initial data passed from element that consumes it in template, while still reacts automatically to internal changes

**Comment by bigopon** [comment]
Actually it can be doned simply via `@observable` as well, `<let/>` could help in case there are many declaration, and binding dependencies, but the above could be done via:

```js
class myVM {
....
    @observable()
    public selectedZipOptions: Array<ListItem<string>>;

    @bindable({ defaultBindingMode: bindingMode.toView })
    public chosenZipCodes(): ReadonlyArray<PostalCode>;

    public selectedZipOptionsChanged(selectedZipOptions: Array<ListItem<string>>) {
        this.chosenZipCodes = selectedZipOptions.map(pItem => pItem.metadata as PostalCode);
    }
...
}
```

**Comment by Alexander-Taran** [comment]
@bigopon don't think I like having logic in markup even for convenience reasons. 
declaring a variable in markup that you are going to use in view-model..

**Comment by bigopon** [comment]
It helps define how to compute the value of a property in view model based on an expression, just to clarify. But I see your point.

**Comment by Alexander-Taran** [comment]
can be closed

maybe add a note to `@bindable` on the use case for that. what it does and why we need one on vm

**Comment by diegohb** [comment]
@Alexander-Taran - thanks for your response..

To answer your question, the primary reason is to be explicit with the code and minimize auto-magic that newbies to aurelia may not immediately understand or recognize. Though I'm not sure I understand the answer.. I'm saying that if I don't use any property attibutes it DOES execute my custom getter.. are you saying this is not by design? not supported even though it seems to work (for now)? 

Second reason I guess was for my understanding on how things work - i wouldn't imagine that you all would make a choice in design that wires up some default behavior that isn't available programmatically/explicitly also.. just out of curiosity, I would still like to know how to replicate a read-only bindable property explicitly..

@bigopon - thanks for the suggestion and response. I mainly wanted to know if I could avoid the extra step of assigning the property. maybe i'm misunderstanding how computed properties work.

thanks!

**Comment by Alexander-Taran** [comment]
well aurelia is about conventions that make sense
it is about auto-magic (-:
about not writing boilerplate code

I'm saying that you don't have to decorate your getter with `@bindable`
it only defines a getter.. and that's enough for it to be read-only AFAIK

and `@bindable` is for passing parameters inside a vm.
and by default most of binding is done one-way.
input values..(what user can modify) are two-way by default.

what you are trying to do looks like fighting the framework for no reason (-:

**Comment by diegohb** [comment]
Thanks for the clarification. To be (more) clear, i cannot reproduce the default auto-magic behavior? and does this mean every property/field defined in a viewmodel object is automatically wired up to observe changes? that doesn't sound right.. maybe I'm still confused. I appreciate your patience.

**Comment by Alexander-Taran** [comment]
>i cannot reproduce the default auto-magic behavior?

depends on weather you are a magician (-:
from what I get - `@bindable` has different reason to be. It is meta.

>does this mean every property/field defined in a viewmodel object is automatically wired up to observe changes?

only those that need observation

**Comment by StrahilKazlachev** [comment]
`@bindable` marks, and configures, the properties to be the `public` *declarative* API of a custom `attribute`/`element`. Using it just to get some of the *behaviors* it introduces will lead to issues at some point, as with everything else when used inappropriately.
Properties marked with `@computed` should not be part of the `public` API - [Computed Properties](http://aurelia.io/docs/binding/computed-properties#introduction) usage.
If you just need the `somePropertyChanged` behavior on properties from the non-publick API use `@observable` as suggested by @bigopon

**Comment by Alexander-Taran** [comment]
can be closed
discussion can continue.
better yet move it to [discourse](https://discourse.aurelia.io/)

**Comment by EisenbergEffect** [comment]
Closing this since it's more of a question that can be talked through on discourse.
