### ISSUE TITLE
Orchestration between a Property Observer subscription, and the value changes.

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/binding#682]
This is not so much an issue as me requesting some information with a problem I have encountered and seeing where people's opinion's sit.

If you create a property observer using the BindingEngine, the following will not work as you expect:

this.observer = this.myBindingEngine.createPropertyObserver( myobj, "someProperty" )
this.subscription = this.observer.subscribe( myChangeHandler );

Sometime later I want to "unhook" from seeing a change:

this.subscription.dispose( ); // I don't want to see notifications for the next change
myobj.someProperty = null;
this.subscription = this.observer.subscribe( myChangeHandler ); // start watching again

In hindsight, this code doesn't work because the *set of subscribers* is not captured at the point when a value change occurs. Instead, when a value change occurs, the change notification is published to whatever set of subscribers exists at the time the change handler is invoked on the micro-task queue.

The question is probably fairly anal, but it basically revolves around whether a subscriber should see a change if it has occurred temporally before the subscription was made.

In my case it came about simply because the obvious pattern of unsubscribe, change, subscribe does not produce the expected outcome because the "publish" portion of the change notification uses the set of subscribers at the time of execution, not at the time of the value having changed.

Thanks for your thoughts.

**Comment by fkleuver** [comment]
It boils down to this:

```js
var obj = {};

Object.defineProperty(obj, "fooDirect", { set: () => {
  if (obj.listen) console.log("set fooDirect");
}})

Object.defineProperty(obj, "fooDelayed", { set: () => {
  setTimeout(() => { if (obj.listen) console.log("set fooDelayed")}); 
  // this is not how queueMicroTask works but it's OK for illustrating the point
}});

obj.listen = false;
obj.fooDirect = null; // no console output (expected)
// console.log called here
obj.listen = true;

obj.listen = false;
obj.fooDelayed = null; // console output: "set fooDelayed" (unexpected)
obj.listen = true;
// console.log called here
```

If you look at it in isolation, it doesn't make much sense. But consider that bindings are there to synchronize between code and the DOM, which itself operates in a similar fashion, via event loops. You gain flexibility in scheduling different units of work - a sort of necessary evil to keep UI's responsive while work is being done. 

Now you need to consider that temporally a change does not occur directly when you assign a value, but rather at the next flush of the task queue. So you put your logic temporally after a change by tapping into the same api:

```
this.subscription.dispose(); 
myobj.someProperty = null;
this.tq.queueMicroTask(() => this.subscription = this.observer.subscribe(myChangeHandler)
```

Again, in isolation, it should work how you're suggesting it. But you're using an API that is designed to work in the context of a UI layer. Delayed/scheduled change handling is just an inherent aspect of that.

**Comment by Alexander-Taran** [comment]
@kevmeister68 can you close this one?

**Comment by fkleuver** [comment]
@kevmeister68 Could you close this one if your question is answered? Thanks :)
