### ISSUE TITLE
Help Required: Best Way to Ignore Your Own Changes to an Observed Property

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/binding#684]
I'm hoping someone can offer some guidance. It is about making use of the Aurelia Observers in the best possible manner.

The example is a made-up example to illustrate the perceived problem.

Let's say I have three number properties: hours, mins, secs aka H, M, S and I wish to build an object that monitors H, M, S and each time any of these three changes, it produces a property T which is string that looks like a duration eg. "hh:mm:ss" using the H, M, S properties with appropriate zero padding etc.

Conversely, the property T is bound to in the user interface and therefore if the user modifies T (eg. via an input field), I need to decompose the pieces of T into their H, M, S components and push the individual values back into the H, M, S properties.

It should not be lost upon anyone that this behaviour is remarkably similar to the Aurelia value converter behaviour in terms of "toView" and "fromView" behaviour, *except* that we are dealing with 3 properties on 1 side, and 1 property on the other side.

Implementation-wise, I can use the BindingEngine or ObserverLocator to create observers on the H, M, S and T properties, and subscribe to those change notifications. Easy peasy for that bit.

My question is ultimately this:

When H changes, that will trigger a recompute of T, therefore I will write a new value to T. 

Changing T will trigger a change notification for T, whose handler will then decompose the value of T and write new values back to H, M, S.

Writing back to H, M, S triggers another change notification to produce a new T, and so forth.

It seems self-evident that it is - at the very least - DESIRABLE that when my "converter" object writes to the H, M, S, T properties then it should _prepare itself_ in some way to _ignore the change notification that it expects will be forthcoming_ as a consequence. 

However, saying it and doing it are two different things.

My question is -- is it really necessary at all? If it is desirable, how do I go about doing it in the easiest manner possible. The impediments to doing it are as follows:

- There must be a real change to a value to produce a change notification, so you need to know in advance whether you are "expecting" to receive one.
- The much more difficult issue is that the change notifications are issued via the Aurelia "synthetic" micro-task queue, so you are very much unaware when you will receive that micro-task call.

So, is there a good solution to this problem? Does anyone actually worry about this, or do they simply rely on Point 1 producing a self-limiting outcome? That is, there might be a couple of cycles of change notifications but the process will eventually acquiesce?

**Comment by fkleuver** [comment]
I'd be happy to clear this up for you. However, purely implementation questions like this are better off on StackOverflow where the answer will help much more people in the future. Here on github it will eventually disappear into the closed issue list and it will generally be longer before you get an answer. Would you mind taking it there instead?

**Comment by Alexander-Taran** [comment]
can be closed

**Comment by fkleuver** [comment]
@kevmeister68 Could you close this one if your question is answered? Thanks :)
