### ISSUE TITLE
collectionObserver typings do not accept Set

### ISSUE THREAD

**Issue by Mobe91** [aurelia/binding#687]
The Aurelia documentation states that collection observers work for Array , Map , and Set types.

However, the signature of `collectionObserver` is currently specified as
```ts
collectionObserver(collection: Array<any> | Map<any, any>): CollectionObserver;
```
This currently prevents the invocation of with a `Set<any>`.

**Comment by Alexander-Taran** [comment]
Would you like to provide a pull request for it @Mobe91 ?
