### ISSUE TITLE
ParseError: conditional value converter in data bind 

### ISSUE THREAD

**Issue by asahui** [aurelia/binding#694]
**I'm submitting a bug report**

* **Library Version:**
1.7.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.11.2

* **NPM Version:**
5.6.0

* **JSPM OR Webpack AND Version**
webpack 4.8.3

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
TypeScript 2.8.3

**Current behavior:**
Attempt to bind value with value converter conditionally, but expression is not parsed.

For example, I am creating a custom element `Field`
```ts
// Field.ts
import { bindable, customElement } from 'aurelia-framework';

@customElement('p-field')
export class Field {
    @bindable private value;
}
```
```html
<!-- Field.html -->
<template>
    <p>Value is ${value}</p>
</template>
```
Use it in another template
```html
<!-- Welcome.html -->
<template>
  <require from="./dateFormat"></require>
      <p-field
        value.bind="val1 === val2 ? (val3 | dateFormat) : val3"
      ></p-field>
</template>
```
```ts
export class Welcome {
  @bindable private val1 = 1;
  @bindable private val2 = 1;
  @bindable private val3 = new Date();
}
```

dateFormat is a converter copied from aurelia doc
```ts
import * as moment from 'moment';

export class DateFormatValueConverter {
  toView(value) {
    return moment(value).format('M/D/YYYY h:mm:ss a');
  }
}
```
I got this error
`Parser Error: Missing expected ) at column 23 in [val1 === val2 ? (val3 | dateFormat) : val3]`

If i change the expression to `value.bind="val1 === val2 ? val3 | dateFormat : val3"`
got error
`Parser Error: Conditional expression val1 === val2 ? val3  requires all 3 expressions at column 22 in [val1 === val2 ? val3 | dateFormat : val3]`

I read src code `parser.js`
```js
parseConditional() {
    let start = this.peek.index;
    let result = this.parseLogicalOr();

    if (this.optional('?')) {
      let yes = this.parseExpression();
....
```
`parseConditional` calls `praseExpression` which parse the second expression and it does not consider this expression might be a value converter expression, therefore no `parseValueConverter` is called again.

If the expression is `value.bind="val3 | dateFormat"`, it is fine.

**Expected/desired behavior:**

* **What is the expected behavior?**
Expression is corrected parse

* **What is the motivation / use case for changing the behavior?**
Apply value converter conditionally to an value and bind it

**Comment by Alexander-Taran** [comment]
I doubt that this is possible at the moment to have a conditionally applied valueConverter
```
<p-field if.bind="val1 === val2 " value.bind="val3 | dateFormat"></p-field>
<p-field else value.bind="val3"></p-field>
```

**Comment by fkleuver** [comment]
The limitation here is that a valueConverter, just like a bindingBehavior, must come at the end of an expression. You can read about that [here](https://github.com/aurelia/binding/blob/master/doc/article/en-US/binding-basics.md#user-content-binding-behaviors-and-value-converters).

So the places where you are writing a `|`, the valueConverter is simply not considered an option and instead it "expects" something else (as the errors indicate - albeit in a non-obvious way).

We have actually had some internal discussions about whether or not to support valueConverters inside an expression as there are no direct technical limitations making this impossible. The counter-argument is that people might want the ability to use `|` as a Bitwise OR instead. Currently the `|` operator is not at all recognized inside an expression, so we could go either way.

@EisenbergEffect What do you think? We *could* support this. Do we want to?

**Comment by EisenbergEffect** [comment]
I'd prefer not to bring in value converters in other positions now. I think that would be confusing. We also don't want to encourage putting too much logic in a binding expression, as that leads to unmaintainable projects or unexpected outcomes. I'm more of the opinion that we should support computed properties better so that it's easier to move more advanced logic and conversion to the view model, where it's easier to find and test. I'd love to hear thoughts on that. I've got improvements for computed props in the experiment repo that should be able to be back-ported to vCurrent pretty easily if we want to.

**Comment by fkleuver** [comment]
That got me to realize, it's actually possible with the latest version to achieve something very similar via tagged template literals:

```
<template>
    <p-field value.bind="val1 === val2 ? (dateFormat`${val3}`) : val3">
    </p-field>
</template>
```

```
export class Welcome {
  @bindable private val1 = 1;
  @bindable private val2 = 1;
  @bindable private val3 = new Date();
  dateFormat(cooked, expr1) {
    return moment(expr1).format('M/D/YYYY h:mm:ss a');
  }
}
```

The main drawback of course is that you need to have the function in your viewModel. You could declare it somewhere as a standalone function and simply import+assign it.

Not quite as clean as a value converter but it it's a viable option in some cases I guess :)

**Comment by fkleuver** [comment]
@asahui Have you tried tagged templates?

**Comment by asahui** [comment]
@fkleuver I am really sorry that I am so busy recently that I forget this stuff. I tried your tagged templates and it works like a charm. As you say, we prefer value converter which is in line with other code. Introducing a tagged function can just be a viable option in some cases. 

Anyway, thanks for your help.😊

**Comment by fkleuver** [comment]
@asahui Thanks for the feedback, glad to know it works well!

@EisenbergEffect Seems this one can be closed
