### ISSUE TITLE
Escape binary operators in property path expressions

### ISSUE THREAD

**Issue by Mobe91** [aurelia/binding#695]
My backend delivers generic attributes for an article in a JSON structure like:
```json
{
  "attributeValues": {
    "0aaf8418-9c5c-0000-0000-000000000000": "val",
    "a229bde9-9c5b-0000-0000-000000000000": "val",
    "e0b77a97-6b7c-0000-0000-000000000000": "val"
  }
}
```
I want to observe changes to this structure using Aurelia's binding engine like so:
```typescript
for (const attributeId in article.attributeValues) {
  const observer = this.bindingEngine.expressionObserver(article, 'attributeValues.' + attributeId);
  observer.subscribe(...);
}
```
However, the Aurelia expression parser produces Binary expression nodes for the input string 'attributeValues.e0b77a97-6b7c-0000-0000-000000000000'. Is there any way to wrap or escape the string to make the parser treat the path parts as property names?
I do not want to modify the attribute ids since I am later using the same structure for saving the attribute values.

**Comment by bigopon** [comment]
From the look of your object,

```js
this.bindingEngine.expressionObserver(article, attributeId)
```

should work as expected. Also you will need to store references to those observers to dispose them later.

**Comment by Mobe91** [comment]
@bigopon my bad, I have edited my original question to reflect the actual article object structure. But the point is that `-` is treated as binary arithmetic operator and not as party of the property name.

**Comment by fkleuver** [comment]
The parser only accepts valid JS expressions, and effectively what you're trying to parse is this:

```
attributeValues.0aaf8418-9c5c-0000-0000-000000000000
```

Which is not valid JS.

Here's what would work:

```
attributeValues['0aaf8418-9c5c-0000-0000-000000000000']
```

Changing your code to this (taking the liberty of turning it into a template string, but that's up to you):

```js
for (const attributeId in article.attributeValues) {
  const observer = this.bindingEngine.expressionObserver(article, `attributeValues['${attributeId}']`);
  observer.subscribe(...);
}
```

**Comment by Mobe91** [comment]
@fkleuver Thank you, `attributeValues['0aaf8418-9c5c-0000-0000-000000000000']` works.
