### ISSUE TITLE
Latest version (2.1.0) does not work in IE 10

### ISSUE THREAD

**Issue by pkozul** [aurelia/binding#697]
After creating a new app using `aurelia-cli` and then updating `aurelia-binding` to the latest version (2.1.0), the app fails to run on IE 10. The error is shown below:

![image](https://user-images.githubusercontent.com/2073827/41752687-63f9f93c-760c-11e8-9d2b-1f9029797ef5.png)

Looks like some calls to `Array.find()` were added in the latest version, but `aurelia-polyfills` does not contain a polyfill for this function.

**Comment by fkleuver** [comment]
Thanks for reporting this!

@EisenbergEffect  this is fixed by https://github.com/aurelia/binding/pull/698

**Comment by EisenbergEffect** [comment]
Release coming in just a few minutes.
