### ISSUE TITLE
Add protection agains double registration on Array.prototype.*

### ISSUE THREAD

**Issue by rmja** [aurelia/binding#699]
**I'm submitting a feature request**

* **Library Version:**
1.* and 2.*

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
9.2.1

* **NPM Version:**
6.1.0

* **JSPM OR Webpack AND Version**
webpack 3.12.0

* **Browser:**
all

* **Language:**
all

**Current behavior:**
Aurelia binding is [current being included in the dependency graph in two versions](https://github.com/aurelia/templating-router/issues/80). The binding library adds functionality with side effects on e.g. `Array.prototype.splice`, and when included in two versions, it gets added twice, causing all sorts of subtle bugs as change tracking events are recorded twice.

**Expected/desired behavior:**

* **What is the expected behavior?**
A clear error in the browser console telling that something is very wrong because side effect functionality is being double registered.

* **What is the motivation / use case for changing the behavior?**
An error like this would have saved me some hours of debugging inside aurelia itself.

**Comment by Alexander-Taran** [comment]
The double version should be fixed by now.
All dependencies have been updated to use ^2.x version

**Comment by fkleuver** [comment]
I suppose we could add a simple global object thing as a patch to both `v1` and `v2`, and throw an error or log a warning. The double version was "fixed" multiple times but I'm sure it will keep popping up now and then for various reasons. This is an unfortunate thing in the way webpack bundles modules..
@bigopon any thoughts?
