### ISSUE TITLE
`bind`ing to `click` should throw a warning or error

### ISSUE THREAD

**Issue by PWKad** [aurelia/binding#70]
It is easy for a dev to accidentally `click.bind=""` on accident.  Let's let them know when they make easy mistakes.

**Comment by EisenbergEffect** [comment]
So, specifically, if there's a binding command with an empty string? We should be able to do that. Any other scenarios?

**Comment by PWKad** [comment]
Actually the main issue would be accidentally using the bind on click so I should have said 

`click.bind="doSomething()"` since it doesn't do what most think it would on first glance.

**Comment by EisenbergEffect** [comment]
ah...I didn't catch that. Not sure if we can help with that though. `click` could be a property on a web component, for example.

**Comment by EisenbergEffect** [comment]
Not much we can do. Closing.
