### ISSUE TITLE
Array.prototype.__au_patched__ should not be enumerable

### ISSUE THREAD

**Issue by zakjan** [aurelia/binding#706]
**I'm submitting a bug report**

* **Library Version:**
1.7.2, 2.1.3

**Please tell us about your environment:**
* **Node Version:**
9.11.1

* **NPM Version:**
6.3.0

* **JSPM OR Webpack AND Version**
webpack 4.16.4

* **Browser:**
Chrome 68

* **Language:**
TypeScript 2.9.2

**Current behavior:**
`Array.prototype.__au_patched__` is enumerable, `for (var i in array)` iterates over it

**Expected/desired behavior:**
* **What is the expected behavior?**
`Array.prototype.__au_patched__` should not be enumerable

* **What is the motivation / use case for changing the behavior?**
fix breaking change caused by #704

**Comment by bigopon** [comment]
@zakjan my rookie mistake. Thanks for this issue.

**Comment by zakjan** [comment]
Thanks for the fast fix!
