### ISSUE TITLE
One-Way adds 'undefined' property value on object with no properties

### ISSUE THREAD

**Issue by jmzagorski** [aurelia/binding#713]
**I'm submitting a bug report**
Although I am sure this is the expected behavior and my scenario might be an edge case.

* **Library Version:**
1.6.0 (aurelia-framework 1.2)

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v8.9.4

* **NPM Version:**
6.3.0

* **JSPM OR Webpack AND Version**
webpack 3.12.0

* **Browser:**
all

* **Language:**
all

**Current behavior:**
When using `one-way` binding on an objects property in a view, that property is added to the object with a value an `undefined` when that object is created without any properties, which makes it feel like the view is updating my model (aka `two-way`).  See https://stackblitz.com/edit/aurelia-javascript-qekbtf?embed=1&file=src/app.js for an example.

The `undefined` value gets added [here](https://github.com/aurelia/binding/blob/a680c7203e850ea37b4e1147365d2c0a07e94968/src/property-observation.js#L97) 

**Expected/desired behavior:**

* **What is the expected behavior?**
No property is added the object if it does not exist and the value is undefined

* **What is the motivation / use case for changing the behavior?**
Using the example I provided: When `canDeactivate` runs I compare the initial `foo` to the current `foo` so I can warn users of any unsaved changes before navigating away. I not only compare property values, but property count too (i am using lodash.isequal). However, when a user goes to a view model and does nothing, then tries to navigate away, they receive my warning because the properties in the view have been added to my empty object. There are many ways I can work around this, and I have done that in my app. However, in my example I am using redux so i am expecting all state mutations to come from my reducer. There might not be a solution, but I wanted to address this before I moved on since it bothered me that something outside of my reducer was changing my object and that the change originated from the view in `one-way` binding.

**Comment by bigopon** [comment]
The behavior you see is because that's how Aurelia observation works. Property interceptors need to be installed upfront in order to detect changes so it can work when you do `this.foo.bar = 'random message'`.

**Comment by jmzagorski** [comment]
Thanks for the reply, and from debugging the code I could tell this was the expected behavior of the binding system. Maybe this is more of a documentation item since it can be the source of bugs in a state driven application that expects all changes to come from one function. Especially since Aurelia has the aurelia-store plugin, which includes documentation on the Redux DevTools. Using the Redux DevTools tools was my original source of confusion because it always showed an empty object since my state was being changed from the outside. I only figured it out by having a logging middleware log out all the actions in my system.

**Comment by bigopon** [comment]
The documentation part could always use some help. At the moment, `how it works` section (https://aurelia.io/docs/binding/how-it-works) covers high level perspective and is lacking part like this. Would be nice if you could help add some more 😉

**Comment by jmzagorski** [comment]
Absolutely, I will work on that. Anything to help out.
