### ISSUE TITLE
File input - clearing the variable and re-selecting the same file doesn't update variable

### ISSUE THREAD

**Issue by edwardridge** [aurelia/binding#719]
**I'm submitting a bug report**

* **Library Version:**
1.6.0

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
8.9.4

* **NPM Version:**
4.0.5

* **Browser:**
Chrome Version 67.0.3396.99
* **Language:**
TypeScript 2.2.1

**Current behavior:**
When using .bind on an input of type "file", setting the bound variable to null isn't reflected within the input. Re-selecting the same file doesn't update the variable.

**Expected/desired behavior:**
Steps:
1) Open the gist in Chrome. Select a file from the input at the top.
2) Click "Clear Document". This sets the backing variable to "null", but you can still see the name of file next to the "input"
3) Select the same file again. You can see that the length of the backing variable doesn't change. If you select a different file, it works as expected.

Gist: https://gist.run/?id=1bb475638441b00bcbbf8fd92974ab33

**Comment by Alexander-Taran** [comment]
You can't change selected file via javascript. It would be a security breach.
And since there is no real change in file input - it does not raise the change event.
Working as expected.

**Comment by edwardridge** [comment]
The issue isn't changing the file via javascript- it's about clearing the bound variable then re-selecting the same file. If you do that, the bound variable is still set to null (whereas it should be reset to the same file). Is there a workaround for this?

**Comment by Alexander-Taran** [comment]
yes. there is a workaround: do not use binding to files
https://github.com/aurelia/binding/issues/314#issuecomment-379259291

**Comment by Alexander-Taran** [comment]
@bigopon can be closed

@edwardridge sorry for not being explicit the last time. By not being able to change selected file via javascript I meant that framework can't replicate your setting a bound property to the file property of input control.
