### ISSUE TITLE
Using the value binding on an input can produce 'undefined' in the input

### ISSUE THREAD

**Issue by Magrangs** [aurelia/binding#73]
When using a text input, If you use the value binding on an object that does not have the property on it, 'undefined' gets added into the input. Should this just be an empty string or throw an error?

e.g. model:

````
this.myModel = {
    name: ""
}
````

html:

````
<input  value.bind="myModel.name"  />

<input value.bind="myModel.doesNotExist" />
````

**Comment by jdanyow** [comment]
The current behavior has a few things going for it:  

* Doesn't require any custom code to handle "throw on undefined prop in input value binding"
* You can see the property is undefined without having to look at the console
* People can override the standard behavior with a value converter if they want to coalesce the model value
* There will be a way to configure the Aurelia binding system to throw when binding to undefined properties:  https://github.com/aurelia/binding/issues/30

**Comment by Magrangs** [comment]
Yes, I have to agree with your points, it used to annoy me in knockout when the binding failed, it threw an error then failed to bind anything else. One downside to this approach is for large forms when binding to a large model. When creating something new, you would have to specify each and every property to be an empty string on your model for example or add a converter to every field. This could add some verbosity to the code and it's another thing to maintain. I think the plus points you described above however out weigh this negative impact.
