### ISSUE TITLE
Checkbox event arguments in repeaters not binding correctly

### ISSUE THREAD

**Issue by hamez99** [aurelia/binding#738]
**I'm submitting a bug report**

* **Library Version:**
v1.0.0-beta.13

**Please tell us about your environment:**
* **Operating System:**
OSX 10.13.6

* **Node Version:**
11.9
=

* **NPM Version:**
6.5.0
Firefox

**Current behavior:**

I have a checkbox input in a table with a repeater.
i.e. 
```
<tr repeat.for="item of dataList" click.delegate="rowClicked(item, $event, false)">
<td>
      <input id="isFeatured" type="checkbox" checked.bind="item.featured"
                                change.delegate="isFeaturedChanged(item, $event)"></input>
</td>
```
...

Whenever isFeatureChanged is fired, "item" is always the first element in the collection.  If i put the event handler on any other element, it works fine.  I also tested the click event and the trigger binding.  I also tested it by passing in $index.  It's always 0.  It should be the index of the item it's on.  checked.bind binds as expected.  Putting ${item.id} outside of the input element displays the id of the item correctly.  However in the event handlers for the checkbox, it's always the first element in the array. If I change the input type to "submit", then i get correct behavior.  Something wierd about how checkboxes are binding, or i'm missing something about how checkbox event binding is supposed to occur but i cant find any documentation on it.

**Comment by bigopon** [comment]
@hamez99 I'm not seeing the behavior you described. Can you help recreate the issue via this code sandbox https://codesandbox.io/s/2o9wo3485y

**Comment by hamez99** [comment]
Thank you for this.  I see what I did wrong now.  It’s a combination of a CSS template that hides the checkbox control and replaces it with a custom symbol using a label tag and non-unique IDs.  Since the IDs are the same on all checkboxes, only the first checkbox’s event gets fired.

**Comment by bigopon** [comment]
@hamez99 Thanks for confirming. I'll be closing this issue. If you have any other questions, please leverage Discourse forum, it's better for this purpose. It's at https;//discourse.aurelia.io

**Comment by bigopon** [comment]
@EisenbergEffect I forgot I can't close issue in this repo, can you or @hamez99  close this 😆

**Comment by hamez99** [comment]
Thanks again!
