### ISSUE TITLE
click.delegate bindings stop working

### ISSUE THREAD

**Issue by gavinaiken** [aurelia/binding#747]
**I'm submitting a bug report**

* **Library Version:**
2.2.1 and above

**Please tell us about your environment:**
* **Operating System:**
OSX 10.14 | Linux (CentOS)

* **Node Version:**
10.15.2

* **NPM Version:**
6.4.1

* **JSPM OR Webpack AND Version**
JSPM 0.16.54

* **Browser:**
Tested in: Chrome 73 | Firefox 66

* **Language:**
ESNext

**Current behavior:**
With version 2.2.1 or 2.3.0 of aurelia-binding, all our `click.delegate` bindings stop working after navigating to a few different routes in our aurelia application. There is no console error, they simply stop working silently - the function call never happens.

We can load the app on a particular route/VM and the `click.delegate` bindings work fine. Then we navigate to a different route, come back to the original one, and they have stopped working.

**Expected/desired behavior:**
With version 2.2.0 of aurelia-binding, no problems occur - the `click.delegate` bindings continue to work after navigation.

**Comment by bigopon** [comment]
@gavinaiken There is no change related to click handling between two versions. Could you give a simple repro? 

Beside this, what else did you upgrade while upgrading binding to 2.3? Also please note that `click.delegate` works with bubbling, so if there's something stopping the propagation of event before it reaches the document, click delegate won't be able to work

**Comment by gavinaiken** [comment]
I will see if I can make a simple repro but so far I have only been able to see it with our large aurelia application so I don't know if that will be possible. Will report back.

I'm sure it is something in this library because I updated all our aurelia dependencies at once (essentially all the core aurelia modules), observed the issue, then tested rolling them back one by one until the issue was resolved. I was able to upgrade everything else again so the situation we have now is that all the aurelia modules in our app are on the latest released versions except for aurelia-binding.

Looking at the diffs between 2.2.0 and 2.2.1 my suspicion falls on this commit: https://github.com/aurelia/binding/commit/56ba36daa0429f1164fb78208c3d082147f7f6bb but I'm not sure how I can test 2.2.0 plus that change to see if that exhibits the issue. Will look into that today.

**Comment by gavinaiken** [comment]
Hmm. Is the README out of date for how to build the module? I did the following:
```
git clone git@github.com:aurelia/binding.git
cd binding
git checkout 2.2.0
npm i
gulp build
```

and got the following error:
```
n$ gulp build
internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/Users/gavin/repos/aurelia/binding/node_modules/natives/index.js:137:5)
    at require (/Users/gavin/repos/aurelia/binding/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/Users/gavin/repos/aurelia/binding/node_modules/natives/index.js:137:5)
    at require (/Users/gavin/repos/aurelia/binding/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/Users/gavin/repos/aurelia/binding/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/Users/gavin/repos/aurelia/binding/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/Users/gavin/repos/aurelia/binding/node_modules/graceful-fs/fs.js:1:99)
```

**Comment by gavinaiken** [comment]
`gulp build` works in master branch, but if I check out `2.2.0` I get the above. What am I doing wrong!?

**Comment by gavinaiken** [comment]
The commit which breaks our app is this one: https://github.com/aurelia/binding/commit/a5d2b330d68b104ebd3503d97d52027bb4d9bc83

I tracked it down by checking out the master branch of `aurelia-binding`, symlinking the dist/amd file into my jspm folder, and reverting single commits from the diffs between 2.2.0 and 2.2.1 https://github.com/aurelia/binding/compare/2.2.0...2.2.1 until our app worked ok. To be sure it was just that commit I then went back to master again, and reverted just that single commit, and verified that it works ok.

**Comment by bigopon** [comment]
It feels like you are hitting this https://github.com/nodejs/node/issues/25132

But i'm not sure why. I don't hit that.

**Comment by gavinaiken** [comment]
I managed not to get derailed by the `internalBinding` error by working from the master branch, where `gulp build` works fine for me. I tracked down the commit which breaks my app, as per the above https://github.com/aurelia/binding/issues/747#issuecomment-481216664. Trying to dig further into why that is causing problems now.

**Comment by bigopon** [comment]
@gavinaiken Cool, nice that you figured that out. Could you help with a repro?

**Comment by gavinaiken** [comment]
Haha yeah the repro seems the hardest bit. If i can understand why that commit breaks my app I might be able to put a repro together...

**Comment by gavinaiken** [comment]
Better than a repro, I have a PR with a fix: https://github.com/aurelia/binding/pull/748

**Comment by gavinaiken** [comment]
Updated PR: https://github.com/aurelia/binding/pull/749

**Comment by Alexander-Taran** [comment]
@gavinaiken sorry to have caused you that trouble.
(-:
And now I stepped into it as well..

**Comment by gavinaiken** [comment]
Ha no worries, when you write software, sometimes things go wrong :)

**Comment by Alexander-Taran** [comment]
well I obviously copy pasted w/o adding a significant test
which I intend to write now (-:
