### ISSUE TITLE
Infinite loop in aurelia-bindingd.ts OverrideContext

### ISSUE THREAD

**Issue by michaelw85** [aurelia/binding#756]
**I'm submitting a bug report**

* **Library Version:**
"version": "2.3.0"

**Current behavior:**
```ts
export declare interface OverrideContext {
  parentOverrideContext: OverrideContext;
  bindingContext: any;
}
```

parentOverrideContext type makes an infinite loop.

**Expected/desired behavior:**
parentOverrideContext should be optional, while debugging an actual binding the value is null.

`parentOverrideContext?: OverrideContext;`

* **What is the expected behavior?**
Expecting properly generated typings

* **What is the motivation / use case for changing the behavior?**
This typing files makes it impossible to properly mock a binding. I now am forced to locally overwrite the typings.

**Work around**:
Add a local aurelia-binding.d.ts with the following content:
```ts
export * from 'aurelia-binding';

declare module 'aurelia-binding' {
    export declare interface OverrideContext {
        parentOverrideContext?: OverrideContext;
        bindingContext: any;
    }
}
```

**Comment by bigopon** [comment]
I think this is an ok change, though it may impact the folks with strict TS on.
But this can be treated like a bug, so let's ping @EisenbergEffect

**Comment by michaelw85** [comment]
I'm running in a very strict setup, the current typings make it impossible to create a mock binding object 🤣 if this would go from optional to required I can imagine this would cause issues but going from strict to optional should not impact existing code.

**Comment by StrahilKazlachev** [comment]
It would impact existing code *if no* checks were done on it - `type 'undefined' is not assignable to ...`.
Still, if this is going to change isn't it more correct to be `parentOverrideContext: OverrideContext | null`?

**Comment by michaelw85** [comment]
Existing code already gets a null value so it would already be broken if no checks are done.

I would personally avoid using `null`, I'm using the following ts lint rule in my own code base but that's personal preference: https://palantir.github.io/tslint/rules/no-null-keyword/

**Comment by StrahilKazlachev** [comment]
As you've seen from debugging, it is already being set to `null`. So for me it is just matter of correctness, of the typings.

**Comment by michaelw85** [comment]
@StrahilKazlachev `null` !== `undefined` 
If consuming code is using strict type checking and somewhere in the far from strict Aurelia code someone decides to create an object without explicitly defining `null` as a value this would break consuming code, I find this a bigger risk than making the key optional since the consuming code would implement a different check based on the typing.

**Comment by StrahilKazlachev** [comment]
If currently some is doing so, skipping `parentOverrideContext` in strict setup, he should be getting an error about the *missing* member(if not hacking with `any`).
Still, the call is not mine. And there is always `parentOverrideContext?: OverrideContext | null`.

**Comment by michaelw85** [comment]
@StrahilKazlachev I was referring to a potential future pitfall not current code. My point is Aurelia code is not strict, it's not written in Typescript but JS without type checking (as far as I am aware). The typings are manually maintained, this makes it very easy for the two to diverge and breaking consuming code in the process. A strict type of `null` has a higher probability of breaking consuming code in my opinion. 

But you are right the decision is not up to us, I have a preference but I'm fine with either options. Fixing the loop in the typing is more important.

**Comment by EisenbergEffect** [comment]
@michaelw85 I’d be willing to go with your proposal to make this optional. Can you submit a PR to fix this? The binding repo is one of our only JS repos with an explicit hand created d.ts file, so it should be easy to make the adjustment.

**Comment by michaelw85** [comment]
@EisenbergEffect PR has been created!

> The binding repo is one of our only JS repos with an explicit hand created d.ts file, so it should be easy to make the adjustment.

Bit offtopic but vnext is written in TS, will this replace all of the current (non ts) repos? CLI might be the exception I guess. Should all the Aurelia repo's become TS eventually? What is your take on this?

**Comment by EisenbergEffect** [comment]
All the vNext work is happening in a new monorepo. For vNext, we’ll be publishing the packages under the npm `@aurelia` organization, so it will be a difference set of packages. There isn’t a one-to-one mapping between the actual packages, since we made some architectural changes under the hood.  For example, the core of the binding engine now lives in `@aurelia/runtime`. HTML-specific parts live in other packages, since we refactored to separate the core binding and rendering from HTML (allowing other renderers). For the CLI, we’re evolving that as well. There’s an RFC open in which @3cp  explains the approach we’re planning on taking there. All things related to vNext can be found here: https://github.com/aurelia/aurelia

**Comment by EisenbergEffect** [comment]
I should note that while package names have changes and things have moved around, that doesn’t change the way you write your Aurelia app itself. Same binding and templating language, same decorators, same conventions, some concepts, etc.

**Comment by michaelw85** [comment]
Thanks for the info!
