### ISSUE TITLE
getContextFor() doesn't handle a non-object bindingContext

### ISSUE THREAD

**Issue by searus** [aurelia/binding#768]
I have a situation where `getContextFor()` is called where the bindingContext is a string.  In this scenario, I get an error because the 'in' operator cannot be used on a string on this line:
https://github.com/aurelia/binding/blob/a680c7203e850ea37b4e1147365d2c0a07e94968/src/scope.js#L35

Here's a demo of the problem: https://codesandbox.io/s/red-paper-s269f
If you click on any of the items in the list, you'll see an error in the dev tools console.

As the `in` operator can only be used on an object, would this be a better check:
```
  while (oc && !(name in oc) && !(typeof oc.bindingContext === 'object' && name in oc.bindingContext)) {
    oc = oc.parentOverrideContext;
  }
```
I'm happy to raise a pull request if I'm on the right track with this.

**Comment by bigopon** [comment]
@searus what was the scenario that led to this issue?
I'm not keen on chucking **any** check into this, as it's a pretty hot call in our binding system
cc @EisenbergEffect @fkleuver @jdanyow

**Comment by searus** [comment]
The issue seems to be when combining a `repeat.for`, `with.bind` and `click.delegate` on the same element.
I have actually solved my issue by moving the `with.bind` onto a new child template element.
So, replace this:
```
    <li
      repeat.for="item of items"
      click.delegate="select(item)"
      with.bind="item"
    >
      <template replaceable part="content">placeholder</template>
    </li>
```
with this:
```
    <li
      repeat.for="item of items"
      click.delegate="select(item)"
    >
      <template with.bind="item">
        <template replaceable part="content">placeholder</template>
      </template>
    </li>
```

**Comment by EisenbergEffect** [comment]
@searus Thanks for the update on the fix. Technically, we don't support with and repeat on the same element (only one template controller per element). We've fixed this issue in vNext but need to make this clearer in the documentation for vCurrent. Apologies for the confusion around that.
