### ISSUE TITLE
SetterObserver keeps old value retained

### ISSUE THREAD

**Issue by ccantill** [aurelia/binding#771]
**I'm submitting a bug report**

* **Library Version:**
2.2.0

* **Browser:**
all

**Current behavior:**
SetterObserver keeps a reference to the old value of a property, and doesn't release it until the property is changed a subsequent time. This can cause objects to retained much longer than needed.

**Expected/desired behavior:**
SetterObserver releases the old value as soon as it's done with it.

**Comment by bigopon** [comment]
@ccantill the value of a `SetterObserver` is the value of the property of the object that it belongs to. In that sense, we cant really release it, as it will make the object value invalid. The setter, and its value, will be released when the owner object is released. Can you check if you are keeping the reference to your object accidentally?

**Comment by ccantill** [comment]
I'm not worried about the current value being retained, it's the old value that shouldn't be retained. In our case we're binding to some properties of the `currentInstruction` on the Router. What happens as a result is that indirectly the entire viewModel of the _previous_ page is retained in `oldValue` in the SetterObserver.
