### ISSUE TITLE
show and if do not bind correctly with table TDs

### ISSUE THREAD

**Issue by jadrake75** [aurelia/binding#86]
If you have a table in which some columns are shown based on some condition, both the show.bind and if.bind fail to behave properly on TD cells in particular and they also behave differently.

The following code case shows this:

http://plnkr.co/edit/NSgsbS?p=preview

Some examples where this is of value include:
Table view configurations
Toggling columns on or off based on a condition or the data type
Hiding columns based on available real estate (adaptive column models)

**Comment by jadrake75** [comment]
I added to the test (but since I had frozen it I had to fork) with a simple DIV table using display styles for table, table-row and table-cell.  I am seeing the same behavior

http://plnkr.co/edit/4dIZkZ?p=preview

**Comment by pszybiak** [comment]
Maby you should use **$parent.** in repeaters?
`<td if.bind="$parent.enhanced">${model.issue}</td>`
`<td show.bind="$parent.enhanced">${model.issue}</t`d>

**Comment by jadrake75** [comment]
yes you are correct.  updating the TD tag only in the body (where there was a repeater) fixes the issue.

bit by $parent again evidently.  Hopefully for the last time.
