### ISSUE TITLE
Make ref bindings work with API properties.

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/binding#87]
If an element has multiple custom attributes on it and a ref, there should be a way to get access to any of the custom attribute class instances. Allow `ref.attribute-name`="someIdentifier" to be used.

**Comment by EisenbergEffect** [comment]
Or, should we reverse this altogther? `attribute-name.ref="someIdentifier"` To catch the view model for an element `this.ref="someIdentifier" and to catch the HTML instance itself `element.ref="someIdentifier"`. Thoughts?

**Comment by jdanyow** [comment]
Will `ref` by itself mean the same as `element.ref`? if not, can/should it?

**Comment by EisenbergEffect** [comment]
@jdanyow That's a good question. I was going to remove that and turn it into something purely implemented as a binding command. What do you think? We could keep support for plain `ref` and make it do the same thing as `element.ref`.

**Comment by jdanyow** [comment]
I think it would be nice if the original `ref` behavior was preserved- if it's not too much trouble.  I love the simplicity of ref for the common use case.

Question about the `[attribute name].ref` case- imagine a custom attribute for the [bootstrap tooltip](http://getbootstrap.com/javascript/#tooltips).  The attribute doesn't need to be assigned a value to work properly:

```html
<div tooltip title="bootstrap uses this for the tooltip content">
  ...
</div>
```

Would/should ref-ing a custom attribute check for the existence of the custom attribute and either apply it or throw?  

For example, is this valid:

```html
<div carousel.ref="carousel">
  ...
</div> 
```

Or would you need to do this:

```html
<div carousel carousel.ref="carousel">
  ...
</div> 
```

**Comment by EisenbergEffect** [comment]
I imagine it should throw if there wasn't one present.
