### ISSUE TITLE
two way binding not working on noView custom elements

### ISSUE THREAD

**Issue by caperaven** [aurelia/binding#88]
I want to write a modular system so that designers can build stuff with out having to write code. To do this I created a non visual custom element that calls a service to fetch work orders. internally it has a @bindable property called workorders.

using the control in a view that also has a bindable property called workorders, the work orders are fetched but the value does not bubble up to the view.

```html
<get-workorders workorders.two-way="workorders" auto.bind="true"></get-workorders>
```

what I want to be able to do is this.

```html
<get-workorders workorders.two-way="workorders" />
<show-workorders workorders.bind="workorders" />
```

when I make get-workorders a visual control by adding a template and removing the noView decorator, then the two way binding works as expected.

Summary:
Two way binding should work with a custom element that is noView

**Comment by jdanyow** [comment]
Try removing `@bindable` from the `workorders` property in your `GetWorkorders` element.  The property isn't really being bound to some data, it's surfacing data from your back-end and other properties are being bound to it.

```html
<get-workorders ref="thedata"></get-workorders>
<show-workorders workorders.bind="thedata.workorders"></show-workorders>
```

You could also use a custom attribute for the "get workorders" task that would fetch the work-orders and assign a "workorders" property:

```html
<show-workorders get-workorders workorders.bind="workorders"></show-workorders>
```

**Comment by caperaven** [comment]
Thank you very much for you reply, it is really much appreciated.
What I am trying to do is create a system where a designer can create screens that utilises two aspects
1. Non visual components responsible for fetching data but can be complex objects as to includes things like filters and criteria
2. Visual components that knows how to render data in a particular way.

What would be great is if the design is of such a manner that you can do most of what you need to do in the markup with out having to write additional code. This also includes things like binding a refresh property to a component action so that if you click the refresh button it calls the get data components get method.

<button click.bind=“element.method” />

So in a way element binding as you may find in technologies like xaml to some or other degree.

Binding in these scenarios are very important because it is the glue that makes things happen.
Any suggestions you may have?

One of the possible solutions I thought of is to use pubsub instead of binding.
Button has attribute that you set and when you click it it fires a pubsub request and the get element responds to.
When the get element gets the data then it raises a pubs event that the show elements subscribes to.

that way you don’t need to bind the stuff up and you still get the same effect.

Having said that, what is the suggested way the aurelia architects prescribe for something like this?

**Comment by EisenbergEffect** [comment]
I believe we already support what you want. Have a look in the docs at the `ref` binding. (syntax is going to change slightly in the next release, but have a look)

**Comment by caperaven** [comment]
That is fantastic news, thank you very much

**Comment by jdanyow** [comment]
@caperaven did `ref` binding solve this for you?  Can this issue be closed?

**Comment by caperaven** [comment]
Yes, you can close it, thanks
