### ISSUE TITLE
Observerlocator cannot observe @bindable properties unless they are 'resolved' first

### ISSUE THREAD

**Issue by janvanderhaegen** [aurelia/binding#89]
It's not possible to get an observerlocator on an @bindable property:
``` javascript
@inject(ObserverLocator)
export class Welcome{
  heading = 'Welcome to the Aurelia Navigation App!';
  @bindable firstName = 'John';
  lastName = 'Doe';

  constructor(observerLocator)
  {     
    //var me = this['firstName']; 
    var a = observerLocator.getObserver(this, 'firstName');
    var d = a.subscribe(()=>{});
    debugger;
  }
```
This throws
heckProperty.getValue (http://localhost:9000/jspm_packages/github/aurelia/binding@0.6.1/dirty-checking.js:77:26) {innerError: RangeError: Maximum call stack size exceeded, stack: (...), message: "Error instantiating Welcome.↵---------------------…ub/aurelia/binding@0.6.1/dirty-checking.js:77:26)"}innerError: RangeError: Maximum call stack size exceededmessage: "Error instantiating Welcome.↵------------------------------------------------↵inner error: RangeError: Maximum call stack size exceeded↵    at Welcome.execute.BindableProperty.configureDescriptor.descriptor.get [as firstName] (http://localhost:9000/jspm_packages/github/aurelia/templating@0.11.2/bindable-property.js:74:37)↵    at DirtyCheckProperty.getValue (http://localhost:9000/jspm_packages/github/aurelia/binding@0.6.1/dirty-checking.js:77:26)↵    at Welcome.execute.BindableProperty.configureDescriptor.descriptor.get [as firstName] (http://localhost:9000/jspm_packages/github/aurelia/templating@0.11.2/bindable-property.js:75:54)↵    at DirtyCheckProperty.getValue (http://localhost:9000/jspm_packages/github/aurelia/binding@0.6.1/dirty-checking.js:77:26)↵   ...

If I 'resolve' the property before gettting the observer, by uncommenting the line
``` javascript
var me = this['firstName']; 
```
Then everything works as expected.

**Comment by jdanyow** [comment]
I think aurelia rewrites `@bindable` props to use getter/setter functions.  Observing these with the ObserverLocator would require dirty-checking.  Would you be able to add a `firstNameChanged` method to the class instead?

**Comment by EisenbergEffect** [comment]
We should be able to fix this. It requires a bit of coordination between the binding system and the templating engine. I'll take a look and see what is needed.

**Comment by janvanderhaegen** [comment]
Do you mean: add a firstNameChanged method to be notified of changes instead of using an ObserverLocator to monitor changes?

In that case I'm not 100% sure, the observerlocator is instantiated and used from within the validation plugin, so people would have to add firstNameChanged methods and manually tell the validation plugin that the value has changed for any @bindable property. Feels like a lot of work to set it up.  Also the thing is, in the validation library I was able to patch this by first doing subject.[bindingpath] before calling observerLocator.getObserver(subject, bindingPath). Just doing that, 'resolves' the property, and then I can add an observerlocator without getting the stackoverflow :S Not sure if this causes performance issues or not.
Anyways, the problem seems to be that observerLocator.getObserver has a stackoverflow when accessing the generated getter/setter methods. Probably, those are only generated first time you actually access the object?

Whoops @EisenbergEffect  just commented too :) So here's some additional information :)

**Comment by mttmccb** [comment]
It's probably not new information but resolving it doesn't appear to solve the problem as the next time the property is access, in my case I have

```
user {
    username: null
}
``

To validate username it attaches the validator ok but I guess the binding is kicking in and destroying the validator.

**Comment by EisenbergEffect** [comment]
@jdanyow I'll be adding a fix for this tomorrow. The plan is to enable the observer locator to look for a getObserver function attached to the getter function of a descriptor. If that is present it will call that, passing the instance to get the function for. This would allow any custom getter a mechanism to provide its own observer. The templating engine will then take advantage of this hook by configuring its bindable property getters with this function. Let me know if that sounds good to you.

**Comment by jdanyow** [comment]
Nice!  This will enable some interesting scenarios and really fine-grained control over the process.

**Comment by EisenbergEffect** [comment]
This is fexed by f09451cefb79a85f14b47c89bf6e2c1fa0ac008e and the corresponding templating fix. It will go out in the next release, this week.

**Comment by mttmccb** [comment]
:+1:

**Comment by krostkowski** [comment]
I couldn't find information about observing arrays. In https://www.danyow.net/aurelia-property-observation/ I only found 'Note: the following doesn't cover Aurelia's strategies for observing Arrays. That's a subject for another post' :)

In my scenario i have a form with validation-errors binded to 'feedback' array:
```
  <form validation-errors.bind="feedback"...
```
Then feedback is binded to my custom element:
```
 <feedback data.bind="feedback" ...
```
In the custom element I need to watch for changes in feedback array:
```
@autoinject()
export class Feedback {
    @bindable() data;

    constructor(private observer:ObserverLocator, private bindingEngine:BindingEngine) {
        let subscription = this.observer
            .getObserver(this, 'data')
            .subscribe(this.onChange);

        let subscription2 = bindingEngine.expressionObserver(this, 'data.length')
            .subscribe(this.onChange);
    }

    public attached() {
        let subscription3 = this.bindingEngine.collectionObserver(this.data)
            .subscribe((splices) => alert('changed'));
    }

    dataChanged(newValue, oldValue) {
       alert('dataChanged')
    }

    onChange(newValue, oldValue) {
        alert(`bar changed from ${oldValue} to ${newValue}`);
    }
```
In that use case, subscription2 is working most properly. subscription and dataChanged are invoked on reference change, not length. subscription3 is invoked too many times, even when length doesn't change. Maybe it helps somebody or maybe I'm doing it wrong:)

**Comment by jdanyow** [comment]
@krostkowski 

```js
@autoinject
export class Feedback {
  @bindable data: { target: Element, error: ValidationError }[];
  
  constructor(private bindingEngine: BindingEngine) {
  }

  unsubscribe() {
    if (this.subscription) {
      this.subscription.dispose();
      this.subscription = null;
    }
  }

  dataMutated(splices) {
    console.log('the contents of the array instance changed.');
  }

  dataChanged(newValue, oldValue) {
    console.log(`the array instance changed.  unsubscribing from the old array's mutation events and subscribing to the new array's mutation events.`);
    this.unsubscribe();
    if (this.data) {
      this.subscription = this.bindingEngine.collectionObserver(this.data)
        .subscribe(splices => this.dataMutated(splices));   
    }
  }

  unbind() {
    this.unsubscribe();
  }
} 
```

**Comment by krostkowski** [comment]
Thank you @jdanyow . I think it should be added to the docs or at least your blog :)
