### ISSUE TITLE
writing unittest against a class containing @bindable

### ISSUE THREAD

**Issue by ashley-taylor** [aurelia/binding#90]
I'm trying to unit test a class that contains @bindable and whenever that variable is set I get the following error
```
Cannot read property 'getObserversLookup' of undefined
```
Is there some setup or initializations that needs to be performed for this to work.

basic example

```javascript
import { bindable } from 'aurelia-framework';

class Example {
  @bindable example;

  constructor() {
  }

  test() {
    this.example = "something";
  }
}


describe('the Example module', () => {
  var example;

  beforeEach(() => {
    example = new Example();
  });


  it('demonstrate failure', () => {
    example.test();
  });
});
```

Cheers,
Ashley

**Comment by jdanyow** [comment]
@stevies we're looking into [this](https://gitter.im/Aurelia/Discuss?at=55579dcdbb71b5b229860a78)
