### ISSUE TITLE
Problem with click.trigger

### ISSUE THREAD

**Issue by luboid** [aurelia/binding#92]
I`am trying to use click.trigger on button element which resides in div element which has click.event.stopPropagation, when I remove click.event.stopPropagation all is working well, but when it is present click.trigger do not work

Example

```html
<template>
<div click.delegate="delegateMethod($event)">
  <h1>test .... CCC</h1>
  <input type="text" value.bind="stringValue"/>
  <button type="button" click.trigger="callMethod()">callMethod...</button>
</div>
</template>
```

```javascript
export class Cc {
    stringValue:string='Init value...';

    delegateMethod($event) {
      $event.stopPropagation();
      alert('delegateMethod:' + this.stringValue);
    }
    callMethod() {
      alert('callMethod:' + this.stringValue);
    }
}
```

**Comment by shanonvl** [comment]
What is the purpose of `delegateMethod` here vs. `callMethod` ?   Why not just do the `$event.stopPropagation()` in the callMethod?   Your events seem to be fighting w each other.

**Comment by luboid** [comment]
Hi, this is only for test purpose, to show problem, I have jQuery dialog plugin into which I trying to load and open this, all is going well, but plugin at some point catch click event and stop it propagation

**Comment by shanonvl** [comment]
Can you post an example on jsfiddle or something?   This isn't a framework issue, this is just a problem with your code.

**Comment by luboid** [comment]
http://plnkr.co/edit/YmJoMvBSGHALXb7Gj9Sq?p=info

**Comment by shanonvl** [comment]
thanks -- i see what you mean now.   the click should definitely fire before the delegate.

**Comment by jdanyow** [comment]
I bet this is resolved by https://github.com/aurelia/binding/pull/97
