### ISSUE TITLE
Select model.bind with server-side options

### ISSUE THREAD

**Issue by heruan** [aurelia/binding#94]
When the selected value of a `<select>` is bound to a property of a server-side fetched model, and the available options are fetched with another API call, Aurelia binding cannot know which is the selected option since it comes from a separate request and it's not a reference from the options array.

Is there a best practice to handle this? 

Use case HTML:
````html
<select value.bind="job.assignee">
    <option repeat.for="employee of employees" model.bind="employee">${employee.name}</option>
</select>
````
and JavaScript:
````javascript
import {HttpClient} from 'aurelia-http-client';

export class Job {
    constructor() {
        this.http = new HttpClient();
    }
    activate(params) {
        return Promise.all([
            this.http.get('/api/jobs/' + params.id).then(http => {
                this.job = JSON.parse(http.response);
            }),
            this.http.get('/api/employees').then(http => {
                this.employees = JSON.parse(http.response);
            })
         ]);
     }
}
````
where the API request `/api/jobs/:id` returns:
````json
{
    "id": 1234,
    "assignee": {
       "name": "Jack",
       "age": 20
    }
}
````
and the `/api/employees` returns:
````json
[
   {
       "name": "John",
       "age": 28
    }, {
       "name": "Jack",
       "age": 20
    }
]
````
In this case the `<select>` initial value would be the first option `John` instead of the correct option `Jack`.

**Comment by jdanyow** [comment]
Great question- here's a few options:

### brute force

```javascript
import {HttpClient} from 'aurelia-http-client';
import {employeeComparer} from './employees';

export class Job {
    constructor() {
        this.http = new HttpClient();
    }
    activate(params) {
        return Promise.all([
            this.http.get('/api/jobs/' + params.id).then(http => {
                this.job = JSON.parse(http.response);
            }),
            this.http.get('/api/employees').then(http => {
                this.employees = JSON.parse(http.response);
            })
         ]).then(() => {
             var assignee = this.job.assignee;
             if (assignee) {
                 this.job.assignee = this.employees.filter(employee => employeeComparer(employee, assignee))[0];
             }
         });
     }
}
```

### converter

```javascript
export class EmployeeToIDConverter {
  toView(employee, employees) {
    return employee ? employee.id : null;
  }
  fromView(id, employees) {
     return id ? employees.filter(e => e.id === id)[0] : null;
  }
}
```
```html
<select value.bind="job.assignee | employeeToID:employees">
    <option repeat.for="employee of employees" model.bind="employee | employeeToID:$parent.employees">${employee.name}</option>
</select>
```

### enhance Aurelia's select binding logic

Maybe we should add support for an `equality-comparer` attribute that would be used like this:

```html
<select value.bind="job.assignee" equality-comparer.bind="employeeComparer">
    <option repeat.for="employee of employees" model.bind="employee">${employee.name}</option>
</select>
```

What do you think?

**Comment by shanonvl** [comment]
@heruan I'd recommend adding `id` to your `employee` model, if at all possible.   

Then something like this would work:

```
<select value.bind="${job.assignee.id}">
   <option repeat.for="employee of employees" value.bind="employee.id">${employee.name}</option>
</select>
```

**Comment by heruan** [comment]
Thank @jdanyow for your suggestions! After further investigation, I'm tempted to use the `JSON.parse()` optional argument [`reviver`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#Example:_Using_the_reviver_parameter) to return the same instance whenever the same object is parsed. That would require a map of retrieved objects (trivial) and a well-written `reviver` function to handle seamlessly (nested) arrays and nested objects (definitely non-trivial).

**Comment by heruan** [comment]
I came up to this `reviver`:
````javascript
var map = new Map();
var reviver = function(k, v) {
    if (v === null || Array.isArray(v)) return v;
    if (typeof v !== 'object') return v;
    var key = JSON.stringify(v); // this is a simplified strategy to object equality
    if (map.has(key)) {
        return map.get(key);
    }
    map.set(key, v);
    return v;
};
````
applied to the former use case:
````javascript
import {HttpClient} from 'aurelia-http-client';

export class Job {
    constructor() {
        this.http = new HttpClient();
        this.map = new Map();
        this.reviver = function(k, v) {
            if (v === null || Array.isArray(v)) return v;
            if (typeof v !== 'object') return v;
            var key = JSON.stringify(v);
            if (map.has(key)) {
                return map.get(key);
            };
            map.set(key, v);
            return v;
        };
    }
    activate(params) {
        return Promise.all([
            this.http.get('/api/jobs/' + params.id).then(http => {
                this.job = JSON.parse(http.response, this.reviver);
            }),
            this.http.get('/api/employees').then(http => {
                this.employees = JSON.parse(http.response, this.reviver);
            })
         ]);
     }
}
````
and the binding works like a charm.
See this [gist](https://gist.github.com/heruan/e42e05e1f52dd0fed9b9) for a test in NodeJS.

Obviously here I'm guessing object identity based on its string representation, but one can use other methods e.g. key attributes; also, JSON schema may help identifying the type of each property.

**Comment by jdanyow** [comment]
Cool stuff!  One question about the reviver- why not use `k` as the key instead of stringifying `v` to produce the key?

**Comment by PWKad** [comment]
@jdanyow I'm for adding the third option you listed but with an easier name like matcher :)  Even a simple object is having problems matching up.

**Comment by jdanyow** [comment]
re-opening- @PWKad i like `matcher`

**Comment by heruan** [comment]
I'm using this as a Reviver now, with slight modifications from the previous one:
- I pass a `pk` argument which is the /primary key/ (it must be a UUID, unique among collection of different objects);
- I use `Object.assign()` to update the current instance of the object.
````javascript
export class Reviver {
    constructor() {
        this.map = new Map();
    }
    revive(json, pk) {
        var self = this;
        return JSON.parse(json, function(k, v) {
            if (v === null || Array.isArray(v)) return v;
            if (typeof v !== 'object') return v;
            var key = v[pk];
            if (!self.map.has(key)) {
                self.map.set(key, v);
                return v;
            };
            return Object.assign(self.map.get(key), v);
        });
    }
}
````

**Comment by PWKad** [comment]
@heruan The reviver in the http-client is definitely configurable, you can set a shared reviver using `.reviver(revfunc)` during configuration or per request using `.withReviver()`

**Comment by 32graham** [comment]
I really like the `matcher` idea. This scenario happens on nearly every page I write for our line-of-business app.

**Comment by jdanyow** [comment]
http://stackoverflow.com/questions/33920610/binding-a-select-to-an-array-of-objects-in-aurelia
