### ISSUE TITLE
scrollTop / scrollLeft binding

### ISSUE THREAD

**Issue by jdanyow** [aurelia/binding#98]
Investigate support for two-way [scrollTop](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop) / [scrollLeft](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollLeft) binding using the [scroll](https://developer.mozilla.org/en-US/docs/Web/Events/scroll) event.

**Comment by EisenbergEffect** [comment]
Let's hold off on this until after the perf work. If you don't have anything else that's really important, then we need to start on benchmarking the binding engine immediately so we can start to work on the improvements ASAP. Let me know.

**Comment by jdanyow** [comment]
I've already implemented this- it's a basic attributeMap, EventManager.registerElementConfig

**Comment by EisenbergEffect** [comment]
Cool :)

On Sun, May 31, 2015 at 8:51 PM, Jeremy Danyow <notifications@github.com>
wrote:

> I've already implemented this- it's a basic attributeMap,
> EventManager.registerElementConfig
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/binding/issues/98#issuecomment-107271001>.
>



-- 
Rob Eisenberg,
President - Blue Spire
www.durandaljs.com

**Comment by jdanyow** [comment]
PRs in binding + templating-binding ready for review.
